#!/usr/bin/env python3
# Author: Claude Opus 5.5 (Bubba)
# Date: 23-September-2026
# PURPOSE: Round five of the FEP-style trace analysis, asked by OpenMind in #arc-3 (19:45 ET):
#   run "EBUL trained to predict" and "hand-built plus the clicked thing's colour" IN PARALLEL and
#   evaluate that combination, WITHOUT retraining the net. Round four did not save the head weights,
#   so the round-four "dm" heads (seeds 0 and 1, both splits, both folds) are regenerated by calling
#   round4._head with the identical job tuple: es_search is seeded, the data and PCA are
#   deterministic, so this reproduces the same weights. That is checked, not assumed: every
#   regenerated head's train/val diagnostics must equal round4/heads.json exactly, otherwise the
#   script stops. The heads are then pickled (round5/heads_dm.pkl) so later rounds can load them.
#   Parallel combinations scored (same held-out folds, back-off prior, event outcomes as round four):
#     joint-sN  - one context = (handcolour context, EBUL code): the two perceptions' keys together
#     mix-sN    - two separate count models side by side, prediction = 50/50 average of the two
#     bma-sN    - the same two models, weighted online by how well each has predicted this play so
#                 far (Bayesian model averaging: weight proportional to its running predictive
#                 likelihood; the "which model has more evidence" rule from the book)
#   plus the references flat, handcolour, ebul-dm-sN. Within one play only (no carry across plays),
#   because a scored Kaggle run plays each game once. Reports nats/step, gain vs flat and vs
#   handcolour with paired bootstrap CIs, per game type, for the pass and game splits.
# SRP/DRY check: Pass -- traces, event outcomes, features, folds, heads, perceptions, scorer and
#   bootstrap all come from round4.py / heldout_yardstick.py / agency_contexts.py / ebul_predictive.py;
#   this file adds only the joint perception, the two-model mixture scorer and the head check.
"""Round five: parallel EBUL-predictive + hand-built colour, no retraining."""
from __future__ import annotations

import argparse
import json
import math
import multiprocessing as mp
import pickle
import sys
import time
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import ebul_perception as ep  # noqa: E402
import heldout_yardstick as hy  # noqa: E402
import object_events as oe  # noqa: E402
import round4 as r4  # noqa: E402

OUT = Path(__file__).parent / "results/efe_trace_analysis/round5"
R4 = Path(__file__).parent / "results/efe_trace_analysis/round4"
SEEDS = (0, 1)


class JointPerception:
    """Context = (context of perception A, context of perception B)."""

    def __init__(self, name, a, b):
        self.name, self.a, self.b = name, a, b

    def reset(self):
        self.a.reset()
        self.b.reset()

    def begin(self, trace):
        for p in (self.a, self.b):
            if hasattr(p, "begin"):
                p.begin(trace)

    def context(self, step):
        return (self.a.context(step), self.b.context(step))

    def observe(self, step):
        self.a.observe(step)
        self.b.observe(step)


def score_pair(tests, pa, pb, support, open_vocab, mode):
    """Two count models side by side, fresh per play. mode 'mix' = 50/50, 'bma' = weights by running
    predictive likelihood within the play. Returns [{"trace", "nats", "steps"}]."""
    sset = set(support)
    vocab = [s for s in support if s not in hy.efe.BASE_OUTCOMES and not (open_vocab and s == hy.NOVEL)]
    out = []
    for t in tests:
        ba, bb = hy.TypePriorBeliefs(vocab, hy.efe.BACKOFF_BETA), hy.TypePriorBeliefs(vocab, hy.efe.BACKOFF_BETA)
        for p in (pa, pb):
            p.reset()
            if hasattr(p, "begin"):
                p.begin(t)
        la = lb = 0.0                         # running log evidence of each model in this play
        nats = n = 0
        for s in t.steps:
            if s.reset:
                continue
            ca, cb = pa.context(s), pb.context(s)
            o = hy._map(s.label, sset, open_vocab)
            qa, qb = ba.p(ca, o), bb.p(cb, o)
            if mode == "mix":
                wa = 0.5
            else:
                m = max(la, lb)
                wa = math.exp(la - m) / (math.exp(la - m) + math.exp(lb - m))
            nats += -math.log(wa * qa + (1 - wa) * qb)
            n += 1
            la += math.log(qa)
            lb += math.log(qb)
            ba.update(ca, o)
            bb.update(cb, o)
            pa.observe(s)
            pb.observe(s)
        out.append({"trace": t, "nats": nats, "steps": n})
    return out


def _score(job):
    split, fold, arm = job
    t0 = time.time()
    fd = r4.G["folds"][split][fold]
    if arm.split("-")[0] in ("joint", "mix", "bma"):
        kind, seed = arm.split("-")
        a = r4.make_perception("handcolour", split, fold)
        b = r4.make_perception(f"ebul-dm-{seed}", split, fold)
        if kind == "joint":
            res = hy.score(fd["test"], JointPerception(arm, a, b), fd["support"], open_vocab=fd["open"])
        else:
            res = score_pair(fd["test"], a, b, fd["support"], fd["open"], kind)
    else:
        res = hy.score(fd["test"], r4.make_perception(arm, split, fold), fd["support"], open_vocab=fd["open"])
    return job, [{"path": r["trace"].path, "nats": r["nats"], "steps": r["steps"]} for r in res], time.time() - t0


def balanced_game_folds(traces):
    """Game split for an arbitrary trace set: whole games per fold, balanced by game type and trace
    count (greedy, largest games first). Round four's fixed GAME_FOLD0 only covers its eleven games."""
    by_game = {}
    for t in traces:
        by_game.setdefault(t.nick, []).append(t)
    load = {(f, gt): 0 for f in (0, 1) for gt in ("click", "button", "mixed")}
    tot = [0, 0]
    fold_of = {}
    for g, ts in sorted(by_game.items(), key=lambda kv: (-len(kv[1]), kv[0])):
        gt = ts[0].gtype
        f = min((0, 1), key=lambda k: (load[k, gt], tot[k]))
        fold_of[g] = f
        load[f, gt] += len(ts)
        tot[f] += len(ts)
    return [([t for t in traces if fold_of[t.nick] != f], [t for t in traces if fold_of[t.nick] == f])
            for f in (0, 1)], fold_of


def main():
    global OUT
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--n", type=int, default=53, help="first n traces (ebul_perception.trace_paths order)")
    ap.add_argument("--retrain", action="store_true", help="train fresh dm heads instead of reproducing round four")
    ap.add_argument("--out", default=str(OUT))
    ap.add_argument("--workers", type=int, default=8)
    args = ap.parse_args()
    OUT = Path(args.out)
    OUT.mkdir(parents=True, exist_ok=True)
    T = {}
    t_all = time.time()
    ctx = mp.get_context("fork")
    workers = min(args.workers, 12)

    t0 = time.time()
    traces, _ = oe.load_all(ep.trace_paths(args.n), workers)
    r4.G["traces"] = traces
    r4.G["iters"] = r4.epr.ITERS
    with ctx.Pool(workers) as pool:
        r4.G["feats"] = {path: f for path, f, _ in pool.imap_unordered(r4._features, range(len(traces)))}
    r4.G["folds"] = {}
    game_folds, fold_of = balanced_game_folds(traces) if args.retrain else (None, None)
    if fold_of:
        print("game folds:", json.dumps(fold_of), flush=True)
    for split in r4.SPLITS:
        r4.G["folds"][split] = []
        pairs = game_folds if (split == "game" and game_folds) else hy.folds(traces, split)
        for train, test in pairs:
            support = hy.support_of(train)
            sset = set(support)
            r4.G["folds"][split].append({"train": train, "test": test, "support": support, "support_set": sset,
                                         "open": split == "game"})
    T["load_features_folds_s"] = round(time.time() - t0, 1)
    print(f"{len(traces)} traces; setup {T['load_features_folds_s']} s", flush=True)

    # regenerate the round-four dm heads and prove they are the same heads
    t0 = time.time()
    ref = None if args.retrain else json.loads((R4 / "heads.json").read_text())
    jobs = [(s, f, seed, "dm") for s in r4.SPLITS for f in (0, 1) for seed in SEEDS]
    r4.G["heads"] = {}
    with ctx.Pool(workers) as pool:
        for job, head, info in pool.imap_unordered(r4._head, jobs):
            key = "/".join(map(str, job))
            print(f"head {key}: {info.get('seconds')} s, val {info.get('val_diag')}", flush=True)
            for d in (("train_diag", "val_diag", "best_iter") if ref else ()):
                if json.dumps(info.get(d), sort_keys=True) != json.dumps(ref[key].get(d), sort_keys=True):
                    sys.exit(f"head {key} does not reproduce round four ({d}): {info.get(d)} vs {ref[key].get(d)}")
            r4.G["heads"][job] = head
    T["regenerate_heads_s"] = round(time.time() - t0, 1)
    with open(OUT / "heads_dm.pkl", "wb") as fh:
        pickle.dump({"/".join(map(str, k)): v for k, v in r4.G["heads"].items()}, fh)
    print(f"{len(jobs)} dm heads {'trained' if args.retrain else 'regenerated'} in {T['regenerate_heads_s']} s"
          + ("" if args.retrain else "; all match round4/heads.json"), flush=True)

    arms = ["flat", "handcolour"] + [f"{k}-s{s}" for k in ("ebul-dm",) for s in SEEDS]
    arms = ["flat", "handcolour"] + [f"ebul-dm-s{s}" for s in SEEDS] + \
           [f"{k}-s{s}" for k in ("joint", "mix", "bma") for s in SEEDS]
    t0 = time.time()
    per = {sp: {a: {} for a in arms} for sp in r4.SPLITS}
    with ctx.Pool(workers) as pool:
        for (split, fold, arm), rows, _ in pool.imap_unordered(
                _score, [(sp, f, a) for sp in r4.SPLITS for f in (0, 1) for a in arms]):
            for r in rows:
                per[split][arm][r["path"]] = (r["nats"], r["steps"])
    T["scoring_s"] = round(time.time() - t0, 1)

    lines, res = [], {}
    for split in r4.SPLITS:
        tab_flat = r4.boot_table(per[split], traces, ref="flat")
        tab_hc = r4.boot_table(per[split], traces, ref="handcolour")
        steps = sum(v[1] for v in per[split]["flat"].values())
        lines.append(f"\n## split {split} (within one play, back-off prior, event outcomes)")
        lines.append("| arm | nats/step | gain vs flat | gain vs handcolour | click | button | mixed (vs handcolour) |")
        lines.append("|---|---|---|---|---|---|---|")
        res[split] = {}
        for a in arms:
            nps = sum(v[0] for v in per[split][a].values()) / steps
            f, h = tab_flat[a], tab_hc[a]
            res[split][a] = {"nats_per_step": nps, "vs_flat": f["all"], "vs_handcolour": h["all"],
                             "types_vs_handcolour": {g: h[g] for g in ("click", "button", "mixed") if g in h}}
            ty = " | ".join(f"{h[g]['gain']:+.3f}" if g in h else "-" for g in ("click", "button", "mixed"))
            lines.append(f"| {a} | {nps:.3f} | {r4.fmt_ci(f['all']['gain'], f['all']['gain_ci'])} | "
                         f"{r4.fmt_ci(h['all']['gain'], h['all']['gain_ci'])} | {ty} |")
    T["total_s"] = round(time.time() - t_all, 1)
    lines.insert(0, f"{len(traces)} traces, {len({t.nick for t in traces})} games; "
                    f"{'retrained' if args.retrain else 'round-four'} dm heads")
    lines.append(f"\ntimings: {json.dumps(T)}")
    text = "\n".join(lines)
    print(text, flush=True)
    (OUT / "table.md").write_text(text + "\n")
    (OUT / "results.json").write_text(json.dumps({"results": res, "timings": T}, indent=1, default=str))


if __name__ == "__main__":
    main()
