"""Generate metadata and visual artifacts for research Batch 15."""
import hashlib,importlib.util,json
from PIL import Image,ImageDraw
from arcengine import ActionInput,GameAction
from build_research_batch06_metadata import ROOT,SESSION,PAL
CFG={
"q020":("Crowd Current","social-inference","diagnosed-local-crowd-rule",["alignment-avoidance-attraction","collective-reshaping"],["assumes alignment","intervenes before diagnosing","tracks one pedestrian instead of density"],[1,2,3,5,6],"Orange crowd columns redistribute under a probed social rule in a pale plaza."),
"q030":("Antidote Network","causal-intervention","neighbor-suppression-distance-two-strengthening",["network-inference","nonlocal-treatment-effect"],["treats the sickest node greedily","forgets distance-two strengthening","repeats a locally successful intervention"],[1,3,4,5,6],"Red illness bars change across a cyan clinical network after local treatment."),
"q040":("Mass Shadow","conservation-law-induction","orientation-invariant-hidden-mass",["projection-reconciliation","platform-balance"],["balances silhouette area","treats rotation as mass change","groups identical shadows together"],[1,3,4,5,6],"Blue objects cast shape-changing gray shadows above violet balance platforms."),
"q050":("Compression Cabinet","epistemic-resource-allocation","capacity-limited-reusable-pattern-basis",["abstraction-selection","xor-composition"],["stores every observed pattern","keeps redundant tiles","selects frequent rather than generative parts"],[3,4,5,6],"Cyan tiles fill a green cabinet whose stored basis explains blue query cards."),
"q060":("Clockwork Tool","tool-construction","assembled-autonomous-temporal-program",["cam-sequencing","delay-composition"],["matches outputs without cam identity","runs an incomplete program","confuses a delay with silence"],[1,2,3,4,5,6],"Colored cams and gray delays form a self-running mechanism on a blue bench."),
"q070":("Triangulation","distributed-partial-observability","three-sensor-relative-distance-location",["geometric-view-integration","hidden-target-localization"],["uses one distance as a coordinate","ignores the third sensor","selects a symmetric false intersection"],[1,2,3,4,5,6],"Three orange sensors report violet distance bars over a pale green survey field."),
"q080":("Regime Cart","nonstationary-rule-revision","transported-radius-of-physical-law",["moving-rule-field","regime-composition"],["applies the law globally","forgets the cart radius","moves state instead of the regime"],[1,3,4,5,6],"An orange cart carries green or red transformation law across blue track cells."),
"q090":("Lineage Garden","persistent-identity","inherited-trait-lineage-pruning",["ancestry-memory","selective-preservation"],["prunes by leaf appearance","forgets inspected ancestry","removes the only desired lineage"],[1,3,4,5,6],"Hidden leaves reveal green or red inherited traits along an orange branching garden."),
"q100":("Recursive Gate","hierarchical-goal-discovery","nested-parameterized-self-similar-gates",["recursive-unwinding","cross-level-parameter"],["solves only the outer gate","reuses one parameter at every depth","unwinds before reaching the base case"],[1,2,5,6],"Concentric orange and cyan gates expose progressively smaller parameter instances."),
"q106":("Local Gravity Wells","multi-scale-reference-frames","region-relative-gravity-transition",["boundary-frame-change","fall-prediction"],["uses global down everywhere","updates gravity before crossing","forgets the destination region's frame"],[1,2,3,4],"A blue body crosses pink gravity regions toward a green goal while leaving a cyan trail.")}
def load(c):
 p=ROOT/"docs"/"static"/"games"/"src"/f"{c}-v1"/f"{c}.py";s=importlib.util.spec_from_file_location(c,p);m=importlib.util.module_from_spec(s);s.loader.exec_module(m);return p,m
def main():
 games=[];out=ROOT/"research"/"games"
 for c,v in CFG.items():
  title,axis,primary,secondary,failures,actions,sil=v;p,m=load(c);h=hashlib.sha256(p.read_bytes()).hexdigest();rel=p.relative_to(ROOT).as_posix();names=[x["name"] for x in m.LEVELS]
  meta={"schema_version":1,"game_id":c,"version":"v1","internal_title":title,"public_title":None,"author_partition":"gpt","authorship":{"model_family":"OpenAI GPT-5","model_snapshot":"current Codex task model; exact deployment id not exposed to task","session_id":SESSION,"created_at":"2026-08-30T00:00:00Z","source_lineage":[f"research/gpt-ideas-v2.tsv:{c}"],"source_commit":None},"mechanics":{"primary":primary,"secondary":secondary,"novelty_claim":names[-1],"closest_prior_art":["research/coverage-gap-study-v1.md","research/flash-game-mechanics-survey.md"]},"failure_modes":failures,"interface":{"actions":actions,"observation":"64x64x16","deterministic":True,"seeded_stochasticity":False},"progression":[{"level":i+1,"role":["orient","discriminate","plan","compose","inhibit","synthesize"][i],"new_demand":n,"composes":list(range(1,i+1))} for i,n in enumerate(names)],"visual_identity":{"dominant_palette":[],"silhouette_grammar":sil,"spatial_grammar":sil,"motion_grammar":primary.replace("-"," "),"hud_grammar":"Persistent colored state markers expose the mechanic without text.","nearest_visual_games":[]},"evaluation":{"allowed_development_models":["deterministic-solvers","random-fuzzer","Qwen3.8 diagnostic only"],"held_out_evaluator":"anthropic","human_baseline_status":"not_started","held_out_status":"sealed"},"artifacts":{"source":rel,"metadata":f"research/games/{c}-v1.json","win_recording":f"research/recordings/{c}-v1-win.json","loss_recording":f"research/recordings/{c}-v1-loss.json","thumbnail":f"docs/static/img/games/{c}-v1.png","source_sha256":h},"status":"prototype"}
  (out/f"{c}-v1.json").write_text(json.dumps(meta,indent=2)+"\n");g=getattr(m,c.upper())();a=g.perform_action(ActionInput(id=GameAction.RESET),raw=True).frame[-1];im=Image.new("RGB",(64,64));im.putdata([PAL[int(x)] for row in a for x in row]);im.save(ROOT/"docs"/"static"/"img"/"games"/f"{c}-v1.png",optimize=True);games.append({"game_id":c,"title":title,"axis":axis,"levels":6,"source_sha256":h})
 path=ROOT/"research"/"gpt-batch15-v1.json";path.write_text(json.dumps({"schema_version":1,"batch_id":"gpt-batch15-v1","created_at":"2026-08-30T00:00:00Z","design":"Nine tenth-pass games closing the first axis group plus one sixth-pass reference-frame game, each with six progressive levels and a distinct colorful environment.","games":games},indent=2)+"\n")
 sheet=Image.new("RGB",(800,352),(242,242,246));d=ImageDraw.Draw(sheet)
 for i,c in enumerate(CFG):im=Image.open(ROOT/"docs"/"static"/"img"/"games"/f"{c}-v1.png").resize((128,128),Image.Resampling.NEAREST);x,y=(i%5)*160+16,(i//5)*176+12;sheet.paste(im,(x,y));d.text((x,y+136),c,fill=(28,28,36))
 sheet.save(ROOT/".cache"/"batch15-contact.png",optimize=True);print("10 metadata records",path)
if __name__=="__main__":main()
