"""Generate metadata, thumbnails, and the batch manifest for research Batch 02."""

from __future__ import annotations
import hashlib
import importlib.util
import json
from pathlib import Path

from PIL import Image, ImageDraw
from arcengine import ActionInput, GameAction

ROOT = Path(__file__).resolve().parents[1]
SESSION = "01a02a2e-aaf5-7e90-a559-46437ace2edb"
PALETTE = [
    (255, 255, 255), (204, 204, 204), (153, 153, 153), (102, 102, 102),
    (51, 51, 51), (0, 0, 0), (229, 58, 163), (255, 123, 204),
    (249, 60, 49), (30, 147, 255), (136, 216, 241), (255, 220, 0),
    (255, 133, 27), (146, 18, 49), (79, 204, 48), (163, 86, 214),
]
ROLES = ["orient", "discriminate", "plan", "compose", "inhibit", "synthesize"]

CONFIG = {
    "q101": {"title": "Carousel Coordinates", "axis": "multi-scale-reference-frames", "primary": "rotating-local-action-frame", "secondary": ["frame-composition", "dynamic-orientation", "obstacle-navigation"], "failures": ["treats controls as world-relative", "forgets rotation after acting", "fails to compose motion around walls"], "actions": [1, 2, 3, 4], "palette": [0, 6, 8, 9, 10, 12, 13, 14], "silhouette": "A white five-by-five carousel inset with a magenta rider, green socket, and blue compass bead.", "spatial": "An orange fairground surround frames a rotating cyan local board.", "motion": "Local directional inputs rotate into world motion and later turn the control frame after every step.", "hud": "A physical compass and blue action tickets externalize orientation and capacity.", "progress": ["Translate one quarter-turned control.", "Navigate an inverted frame.", "Update orientation after every step.", "Compose rotation with blocking walls.", "Reverse the carousel's turn direction.", "Plan a winding route while the local frame advances continuously."]},
    "q111": {"title": "Silent Tutor", "axis": "policy-learning-from-demonstration", "primary": "transformed-policy-imitation", "secondary": ["rotation-transfer", "reflection-transfer", "sequence-abstraction"], "failures": ["copies surface directions", "ignores the stage transform", "forgets long demonstrated routines"], "actions": [1, 2, 3, 4], "palette": [0, 7, 8, 9, 11, 13, 14], "silhouette": "Paired rows of chunky gesture arrows representing tutor and student performances.", "spatial": "Two burgundy theater stages float on a yellow rehearsal hall.", "motion": "The upper policy is transformed through visible mirror and rotation cues before reproduction below.", "hud": "White transform markers and green completed gestures expose transfer progress.", "progress": ["Copy a two-step gesture.", "Rotate a demonstrated policy.", "Reflect a policy across the stage.", "Transfer a longer rotated routine.", "Compose reflection and rotation.", "Maintain a six-action policy through a compound frame transform."]},
    "q121": {"title": "Habit Hunter", "axis": "adaptive-adversary", "primary": "recent-mode-prediction", "secondary": ["habit-breaking", "adversary-state-tracking", "route-diversification"], "failures": ["repeats a successful direction", "ignores the visible memory window", "treats prediction as random pursuit"], "actions": [1, 2, 3, 4], "palette": [0, 7, 8, 9, 12, 13, 14, 15], "silhouette": "A blue runner, green hollow goal, and red prediction marker on a clean white arena.", "spatial": "A pink arcade cabinet surrounds a violet-walled six-by-six pursuit board.", "motion": "The hunter blocks whichever direction dominates the player's recent visible action history.", "hud": "Orange and red memory chips show the action window currently driving prediction.", "progress": ["Break a two-action directional habit.", "Alternate intent around one obstruction.", "Track a three-action predictive window.", "Diversify movement through a learned corridor.", "Manage a five-action history across a long route.", "Compose prediction avoidance with a dense obstacle field."]},
    "q131": {"title": "Pulse Language", "axis": "compositional-communication", "primary": "grounded-pulse-composition", "secondary": ["separator-syntax", "ordered-messaging", "novel-command-composition"], "failures": ["matches pulse count only", "ignores separator scope", "reverses command order"], "actions": [1, 2, 3, 4, 5], "palette": [0, 3, 7, 8, 9, 10, 11, 12, 14, 15], "silhouette": "Vertical short and long pulse bars beneath a colored object-direction command card.", "spatial": "A white message sheet is suspended in a saturated blue signal studio.", "motion": "Primitive pulses and separators accumulate into a single committed spatial instruction.", "hud": "Gray token slots expose message length without revealing content.", "progress": ["Ground one short pulse.", "Compose short and long pulses.", "Introduce a separator between meanings.", "Preserve order across a four-symbol phrase.", "Build a nested two-clause command.", "Emit a seven-symbol command with two separators."]},
    "q141": {"title": "Branch Ledger", "axis": "counterfactual-planning", "primary": "persistent-sandbox-outcomes", "secondary": ["branch-comparison", "irreversible-commitment", "probe-allocation"], "failures": ["forgets reset outcomes", "commits before matching the target", "spends probes without comparison"], "actions": [3, 4, 5, 6], "palette": [1, 3, 7, 8, 10, 11, 14, 15], "silhouette": "Tabbed branch cards mirrored by a permanent row of colored ledger entries.", "spatial": "A cyan notebook page sits on a pale archival desk.", "motion": "Sandbox probes reset the branch while preserving its terminal color in the lower ledger.", "hud": "Violet ink bars count remaining counterfactual trials.", "progress": ["Compare two future outcomes.", "Preserve evidence across three branches.", "Match a target among four alternatives.", "Allocate sparse probes across five branches.", "Delay commitment until a late alternative is tested.", "Resolve six irreversible futures through the persistent ledger."]},
    "q151": {"title": "Pipes to Roads", "axis": "structural-analogy", "primary": "cross-embodiment-graph-transfer", "secondary": ["topology-matching", "role-invariance", "distractor-geometry"], "failures": ["copies coordinates instead of structure", "follows appearance-matched nodes", "loses branch roles under rearrangement"], "actions": [6], "palette": [0, 3, 6, 8, 9, 10, 11, 12, 14], "silhouette": "A highlighted water-pipe route above a sparse road network with differently placed junctions.", "spatial": "Blue waterworks and orange desert roads share one cyan outer atlas.", "motion": "The player reconstructs a solved topological path in a visually unrelated embedding.", "hud": "A magenta traveler marks progress while a green terminal anchors the road goal.", "progress": ["Transfer a straight chain.", "Choose the corresponding diamond branch.", "Match a node by structural role.", "Transfer a four-node bent route.", "Ignore geometric crossings while preserving topology.", "Reconstruct a five-node path through a seven-node analogy."]},
    "q161": {"title": "Wager Gate", "axis": "confidence-calibration", "primary": "evidence-triggered-stopping", "secondary": ["hypothesis-elimination", "probe-cost", "claim-timing"], "failures": ["claims from insufficient evidence", "continues probing after certainty", "confuses eliminated and surviving hypotheses"], "actions": [3, 4, 5, 6], "palette": [1, 7, 8, 9, 11, 13, 14, 15], "silhouette": "Tall hypothesis cards on a yellow gaming table with physical violet evidence chips.", "spatial": "A gold wager table glows inside a burgundy game-show chamber.", "motion": "Each paid probe crosses out inconsistent cards until the player chooses when to claim.", "hud": "Pale budget tiles and evidence chips make exploration cost and confidence visible.", "progress": ["Claim after one decisive clue.", "Intersect two overlapping clues.", "Eliminate across four hypotheses.", "Recognize certainty before all clues are spent.", "Calibrate a six-way wager.", "Stop a five-clue sequence exactly when one hypothesis survives."]},
    "q171": {"title": "Elastic Balance", "axis": "continuous-quantity-reasoning", "primary": "coupled-tension-redistribution", "secondary": ["equilibrium-matching", "neighbor-coupling", "locked-boundaries"], "failures": ["treats anchors independently", "matches height without tension transfer", "pushes against locked pegs"], "actions": [1, 2, 3, 4], "palette": [0, 3, 6, 8, 9, 11, 14, 15], "silhouette": "A continuous pink elastic band joins blue anchors against green target menisci.", "spatial": "A bright white tension canvas floats in a violet materials lab.", "motion": "Moving one anchor later redistributes neighboring tension in the opposite direction.", "hud": "Blue capsules count remaining adjustments and a pink coupling bar announces shared tension.", "progress": ["Stretch one independent anchor.", "Balance three independent heights.", "Respect a locked peg.", "Discover neighbor redistribution.", "Compose successive coupled adjustments.", "Solve a five-anchor coupled equilibrium."]},
    "q181": {"title": "Affordance Debt", "axis": "long-horizon-credit-assignment", "primary": "shortcut-created-future-obstacles", "secondary": ["delayed-consequence", "cross-room-planning", "shape-debt"], "failures": ["optimizes only the current route", "forgets which shortcut was used", "underestimates multi-cell future damage"], "actions": [1, 2, 3, 4], "palette": [0, 3, 6, 8, 9, 10, 12, 13, 14], "silhouette": "A green present room and blue future room joined by orange shortcut and red debt marks.", "spatial": "Two compact routes are stacked inside a magenta time ledger.", "motion": "Crossing an orange shortcut stamps an identically authored obstacle into the later room.", "hud": "Cyan action strips span both rooms, emphasizing one shared long-horizon budget.", "progress": ["Reject one tempting shortcut to preserve a future corridor.", "Compare present distance against a future detour.", "Avoid two independent debts.", "Account for a multi-cell debt shape.", "Choose which future corridor may safely carry a scar.", "Plan two rooms with competing shortcut-shaped consequences."]},
    "q191": {"title": "Event Compression", "axis": "temporal-abstraction", "primary": "event-boundary-intervention", "secondary": ["cycle-chunking", "direction-reversal", "variable-duration-invariance"], "failures": ["counts raw frames", "acts between causal boundaries", "forgets reversal after an event"], "actions": [5, 6], "palette": [1, 4, 8, 11, 13, 14, 15], "silhouette": "A violet actor crosses a gray cinema screen and flashes green at causal boundaries.", "spatial": "A compact animation theater is surrounded by a vivid red editing bay.", "motion": "Wait advances deterministic frames; capture is valid only at the next causal event, with later routines reversing.", "hud": "A pale frame strip and yellow capture badges separate raw time from compressed events.", "progress": ["Capture one causal boundary.", "Recognize two events in one cycle.", "Ignore uneven frame distances.", "Reverse temporal direction after a capture.", "Track three events through alternating direction.", "Compress a twelve-frame routine into four causal interventions."]},
}


def load_module(code):
    source = ROOT / "docs" / "static" / "games" / "src" / f"{code}-v1" / f"{code}.py"; spec = importlib.util.spec_from_file_location(f"{code}_metadata", source); module = importlib.util.module_from_spec(spec); assert spec.loader is not None; spec.loader.exec_module(module); return source, module


def render_thumbnail(code, module):
    game = getattr(module, code.upper())(); result = game.perform_action(ActionInput(id=GameAction.RESET), raw=True); grid = result.frame[-1]; image = Image.new("RGB", (64, 64)); image.putdata([PALETTE[int(value)] for row in grid for value in row]); out = ROOT / "docs" / "static" / "img" / "games" / f"{code}-v1.png"; out.parent.mkdir(parents=True, exist_ok=True); image.save(out, optimize=True)


def render_contact_sheet(codes):
    sheet = Image.new("RGB", (800, 352), (242, 242, 246)); draw = ImageDraw.Draw(sheet)
    for index, code in enumerate(codes):
        thumb = Image.open(ROOT / "docs" / "static" / "img" / "games" / f"{code}-v1.png").convert("RGB").resize((128, 128), Image.Resampling.NEAREST); x, y = (index % 5) * 160 + 16, (index // 5) * 176 + 12; sheet.paste(thumb, (x, y)); draw.text((x, y + 136), code, fill=(28, 28, 36))
    out = ROOT / ".cache" / "batch02-contact.png"; out.parent.mkdir(parents=True, exist_ok=True); sheet.save(out, optimize=True)


def main():
    out_dir = ROOT / "research" / "games"; out_dir.mkdir(parents=True, exist_ok=True); batch = []
    for code, cfg in CONFIG.items():
        source, module = load_module(code); source_rel = source.relative_to(ROOT).as_posix(); digest = hashlib.sha256(source.read_bytes()).hexdigest(); levels = module.LEVELS
        metadata = {
            "schema_version": 1, "game_id": code, "version": "v1", "internal_title": cfg["title"], "public_title": None, "author_partition": "gpt",
            "authorship": {"model_family": "OpenAI GPT-5", "model_snapshot": "current Codex task model; exact deployment id not exposed to task", "session_id": SESSION, "created_at": "2026-08-30T00:00:00Z", "source_lineage": [f"research/gpt-ideas-v1.tsv:{code}"], "source_commit": None},
            "mechanics": {"primary": cfg["primary"], "secondary": cfg["secondary"], "novelty_claim": cfg["progress"][-1], "closest_prior_art": ["research/coverage-gap-study-v1.md", "research/flash-game-mechanics-survey.md"]},
            "failure_modes": cfg["failures"], "interface": {"actions": cfg["actions"], "observation": "64x64x16", "deterministic": True, "seeded_stochasticity": False},
            "progression": [{"level": index + 1, "role": ROLES[index], "new_demand": demand, "composes": list(range(1, index + 1))} for index, demand in enumerate(cfg["progress"])],
            "visual_identity": {"dominant_palette": cfg["palette"], "silhouette_grammar": cfg["silhouette"], "spatial_grammar": cfg["spatial"], "motion_grammar": cfg["motion"], "hud_grammar": cfg["hud"], "nearest_visual_games": []},
            "evaluation": {"allowed_development_models": ["deterministic-solvers", "random-fuzzer", "Qwen3.8 diagnostic only"], "held_out_evaluator": "anthropic", "human_baseline_status": "not_started", "held_out_status": "sealed"},
            "artifacts": {"source": source_rel, "metadata": f"research/games/{code}-v1.json", "win_recording": f"research/recordings/{code}-v1-win.json", "loss_recording": f"research/recordings/{code}-v1-loss.json", "thumbnail": f"docs/static/img/games/{code}-v1.png", "source_sha256": digest}, "status": "prototype",
        }
        (out_dir / f"{code}-v1.json").write_text(json.dumps(metadata, indent=2) + "\n", encoding="utf-8"); render_thumbnail(code, module); batch.append({"game_id": code, "title": cfg["title"], "axis": cfg["axis"], "levels": len(levels), "source_sha256": digest})
    manifest = {"schema_version": 1, "batch_id": "gpt-batch02-v1", "created_at": "2026-08-30T00:00:00Z", "design": "Ten cross-mechanic games spanning the second ten research axes; each has six causal-progression levels and a distinct colorful environment.", "games": batch}; path = ROOT / "research" / "gpt-batch02-v1.json"; path.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8"); render_contact_sheet(CONFIG); print(f"{len(batch)} metadata records -> {out_dir}"); print(path)


if __name__ == "__main__": main()
