"""Generate metadata, thumbnails, and the contact sheet for research Batch 69."""
import hashlib,importlib.util,json
from PIL import Image,ImageDraw
from arcengine import ActionInput,GameAction
from build_research_batch06_metadata import ROOT,SESSION,PAL
CFG={
"q515":("Waystation Frame","multi-scale-reference-frames","local-caravan-motion-composes-with-shifting-dune-frames-and-a-two-policy-repetition-counter","A white caravan map layers three dune corridors above frame, recent-policy, and lock rails."),
"q545":("Waystation Lesson","policy-learning-from-demonstration","conditional-caravan-policy-is-inferred-through-context-switches-empty-gestures-and-recent-demo-memory","A silver lesson tent places guide demonstrations above context, rival, gesture, and policy strips."),
"q575":("Waystation Counter","adaptive-adversary","a-three-tactic-caravan-rival-is-shaped-by-the-last-two-treatments-and-corridor-shifts","A gray dune arena aligns a supply path above three tactic chambers and two recent-policy tiles."),
"q605":("Waystation Grammar","compositional-communication","paired-caravan-glyphs-compose-through-shifting-relays-whose-output-depends-on-recent-groups","A stone relay tent layers colored glyph pairs above relay, group, shift, and decoded-result rails."),
"q644":("Tessera Sandbox","counterfactual-planning","two-folding-mosaic-copies-reset-physical-tiles-while-their-intervention-evidence-persists","A charcoal mosaic laboratory places twin nine-tile panels above seam, evidence, reset, and commitment strips."),
"q665":("Waystation Analogy","structural-analogy","a-cyclic-dune-route-transfers-to-walkers-after-repetition-sensitive-rotation-and-reflection","A black relation caravan places route and walker panes above shift, history, surface, and transfer rails."),
"q695":("Waystation Evidence","confidence-calibration","unequal-dune-samples-support-safe-stopping-while-threefold-policy-repetition-inverts-evidence","A pink evidence camp aligns sample slots above result tiles, recent policies, and a signed margin."),
"q725":("Waystation Gradient","continuous-quantity-reasoning","conserved-caravan-mass-crosses-capacity-limited-dunes-where-repeated-routes-incur-smaller-transfers","A rose distribution camp holds three supply bins above target, phase, recent-policy, and commitment strips."),
"q755":("Waystation Obligation","long-horizon-credit-assignment","cargo-debts-remain-attached-to-helper-identities-while-repeated-borrowing-adds-delayed-tolls","A blue creditor tent places two helper panes above cargo, debt, swap, toll, and recent-policy tracks."),
"q785":("Waystation Rhythm","temporal-abstraction","caravan-macros-change-period-and-repeated-policies-shift-the-state-defined-interruption-window","A cyan timing camp places twelve track nodes above period, recent-macro, counter, and window rails.")}
def load(c):
 p=ROOT/"docs"/"static"/"games"/"src"/f"{c}-v1"/f"{c}.py";s=importlib.util.spec_from_file_location(c,p);m=importlib.util.module_from_spec(s);s.loader.exec_module(m);return p,m
def main():
 games=[];out=ROOT/"research"/"games";out.mkdir(parents=True,exist_ok=True)
 for c,(title,axis,primary,silhouette) in CFG.items():
  p,m=load(c);h=hashlib.sha256(p.read_bytes()).hexdigest();rel=p.relative_to(ROOT).as_posix();names=[x["name"] for x in m.LEVELS];g=getattr(m,c.upper())();frame=g.perform_action(ActionInput(id=GameAction.RESET),raw=True).frame[-1];palette=sorted({int(v) for row in frame for v in row})
  meta={"schema_version":1,"game_id":c,"version":"v1","internal_title":title,"public_title":None,"author_partition":"gpt","authorship":{"model_family":"OpenAI GPT-5","model_snapshot":"current Codex task model; exact deployment id not exposed to task","session_id":SESSION,"created_at":"2026-08-31T00:00:00Z","source_lineage":[f"research/gpt-ideas-v2.tsv:{c}"],"source_commit":None},"mechanics":{"primary":primary,"secondary":[axis,"underrepresented-capability-expansion"],"novelty_claim":names[-1],"closest_prior_art":["research/coverage-gap-study-v1.md","research/flash-game-mechanics-survey.md"]},"failure_modes":["tracks only the current corridor and ignores how the previous two policies update the visible counter","repeats a locally useful treatment until its predictable toll or inversion makes it globally harmful","resets persistent evidence or assigns delayed cargo debt to a visible position instead of causal identity"],"interface":{"actions":[1,2,3,4,5,6],"observation":"64x64x16","deterministic":True,"seeded_stochasticity":False},"progression":[{"level":i+1,"role":["orient","discriminate","plan","compose","inhibit","synthesize"][i],"new_demand":n,"composes":list(range(1,i+1))} for i,n in enumerate(names)],"visual_identity":{"dominant_palette":palette,"silhouette_grammar":silhouette,"spatial_grammar":silhouette,"motion_grammar":primary.replace("-"," "),"hud_grammar":"Dune corridors, supply walkers, policy tiles, tactic chambers, glyph relays, mosaic copies, sample slots, conserved bins, helper panes, and interruption windows expose state without text.","nearest_visual_games":[]},"evaluation":{"allowed_development_models":["deterministic-solvers","random-fuzzer","Qwen3.8 diagnostic only"],"held_out_evaluator":"anthropic","human_baseline_status":"not_started","held_out_status":"sealed"},"artifacts":{"source":rel,"metadata":f"research/games/{c}-v1.json","win_recording":f"research/recordings/{c}-v1-win.json","loss_recording":f"research/recordings/{c}-v1-loss.json","thumbnail":f"docs/static/img/games/{c}-v1.png","source_sha256":h},"status":"prototype"}
  (out/f"{c}-v1.json").write_text(json.dumps(meta,indent=2)+"\n");im=Image.new("RGB",(64,64));im.putdata([PAL[int(v)] for row in frame for v in row]);im.save(ROOT/"docs"/"static"/"img"/"games"/f"{c}-v1.png",optimize=True);games.append({"game_id":c,"title":title,"axis":axis,"levels":6,"source_sha256":h})
 path=ROOT/"research"/"gpt-batch69-v1.json";path.write_text(json.dumps({"schema_version":1,"batch_id":"gpt-batch69-v1","created_at":"2026-08-31T00:00:00Z","design":"Nine warm caravan environments make the last two visible policies causally important across moving frames, lessons, rivals, messages, analogies, evidence, conserved flow, obligations, and macro-time; a folding mosaic laboratory adds reset-persistent counterfactual evidence.","games":games},indent=2)+"\n")
 sheet=Image.new("RGB",(800,352),(242,242,246));d=ImageDraw.Draw(sheet)
 for i,c in enumerate(CFG):
  im=Image.open(ROOT/"docs"/"static"/"img"/"games"/f"{c}-v1.png").resize((128,128),Image.Resampling.NEAREST);x,y=(i%5)*160+16,(i//5)*176+12;sheet.paste(im,(x,y));d.text((x,y+136),c,fill=(28,28,36))
 (ROOT/".cache").mkdir(exist_ok=True);sheet.save(ROOT/".cache"/"batch69-contact.png",optimize=True);print("10 metadata records",path)
if __name__=="__main__":main()
