"""Generate metadata, thumbnails, and a contact sheet for the nine-game Batch 80 boundary set."""
import hashlib,importlib.util,json
from PIL import Image,ImageDraw
from arcengine import ActionInput,GameAction
from build_research_batch06_metadata import ROOT,SESSION,PAL
CFG={
"q704":("Tessera Evidence","confidence-calibration","unequally-reliable-seam-samples-support-stopping-only-after-a-fold-macro-is-interrupted-at-the-visible-window","A pale folding mosaic arrays nine tesserae above weighted samples, seam phase, and a signed margin."),
"q708":("Escapement Evidence","confidence-calibration","exclusive-clock-interventions-separate-candidate-faults-before-reliability-weighted-stopping","A blue clock tower suspends three weights above intervention outcomes, nested phase, and evidence bars."),
"q709":("Monsoon Evidence","confidence-calibration","storm-samples-have-phase-dependent-reliability-under-unequal-fast-and-slow-weather-cycles","A slate weather garden arranges eight storm cells above weighted samples and unequal clock rails."),
"q732":("Semaphore Gradient","continuous-quantity-reasoning","conserved-signal-mass-crosses-capacity-limited-relays-before-tested-policy-commitment","A lilac cliff yard stacks three signal reservoirs above capacity beams, phase, and miniature outcomes."),
"q735":("Vivarium Gradient","continuous-quantity-reasoning","conserved-fauna-mass-crosses-thermal-capacities-whose-routing-depends-on-reciprocal-trust","A green stacked vivarium places three fauna reservoirs above heat capacities and a trust margin."),
"q764":("Tessera Obligation","long-horizon-credit-assignment","mosaic-debt-remains-attached-to-causal-identity-through-seam-swaps-and-a-macro-interruption-window","A teal mosaic tracks three tessera identities above debt, seam, and macro-window rails."),
"q765":("Vivarium Obligation","long-horizon-credit-assignment","fauna-debt-follows-causal-identity-through-temperature-strata-swaps-and-reciprocal-policy-updates","A rose terrarium tracks three fauna identities above thermal strata, debt, and trust state."),
"q770":("Workbench Obligation","long-horizon-credit-assignment","tool-debt-remains-attached-to-helper-identity-after-fixtures-and-visible-tool-positions-reconfigure","A cream mobile workshop tracks three helpers above tool pedestals, fixture state, and debt rails."),
"q797":("Spectrum Rhythm","temporal-abstraction","a-prism-packet-macro-is-interrupted-at-an-inferred-relational-event-in-unequal-fast-and-slow-cycles","A peach prism gallery arrays eight packet panes above relation samples and two clock rails.")}
def load(c):
 p=ROOT/"docs"/"static"/"games"/"src"/f"{c}-v1"/f"{c}.py";s=importlib.util.spec_from_file_location(c,p);m=importlib.util.module_from_spec(s);s.loader.exec_module(m);return p,m
def main():
 games=[];out=ROOT/"research"/"games";out.mkdir(parents=True,exist_ok=True)
 for c,(title,axis,primary,silhouette) in CFG.items():
  p,m=load(c);h=hashlib.sha256(p.read_bytes()).hexdigest();rel=p.relative_to(ROOT).as_posix();names=[x["name"] for x in m.LEVELS];g=getattr(m,c.upper())();frame=g.perform_action(ActionInput(id=GameAction.RESET),raw=True).frame[-1];palette=sorted({int(v) for row in frame for v in row})
  meta={"schema_version":1,"game_id":c,"version":"v1","internal_title":title,"public_title":None,"author_partition":"gpt","authorship":{"model_family":"OpenAI GPT-5","model_snapshot":"current Codex task model; exact deployment id not exposed to task","session_id":SESSION,"created_at":"2026-08-31T00:00:00Z","source_lineage":[f"research/gpt-ideas-v2.tsv:{c}"],"source_commit":None},"mechanics":{"primary":primary,"secondary":[axis,"underrepresented-capability-expansion"],"novelty_claim":names[-1],"closest_prior_art":["research/coverage-gap-study-v1.md","research/flash-game-mechanics-survey.md"]},"failure_modes":["uses screen position while ignoring seam, gear, storm, relay, temperature, fixture, identity, reliability, or phase state","stops, commits, interrupts, or repays from one surface cue without integrating retained evidence and causal history","loses conserved mass or identity-bound debt when objects exchange visible positions"],"interface":{"actions":[1,2,3,4,5,6],"observation":"64x64x16","deterministic":True,"seeded_stochasticity":False},"progression":[{"level":i+1,"role":["orient","discriminate","plan","compose","inhibit","synthesize"][i],"new_demand":n,"composes":list(range(1,i+1))} for i,n in enumerate(names)],"visual_identity":{"dominant_palette":palette,"silhouette_grammar":silhouette,"spatial_grammar":silhouette,"motion_grammar":primary.replace("-"," "),"hud_grammar":"Mosaic seams, gear probes, storm samples, signal and fauna reservoirs, identity ledgers, tool fixtures, prism relations, signed margins, and unequal clocks expose latent state without text.","nearest_visual_games":[]},"evaluation":{"allowed_development_models":["deterministic-solvers","random-fuzzer","Qwen3.8 diagnostic only"],"held_out_evaluator":"anthropic","human_baseline_status":"not_started","held_out_status":"sealed"},"artifacts":{"source":rel,"metadata":f"research/games/{c}-v1.json","win_recording":f"research/recordings/{c}-v1-win.json","loss_recording":f"research/recordings/{c}-v1-loss.json","thumbnail":f"docs/static/img/games/{c}-v1.png","source_sha256":h},"status":"prototype"}
  (out/f"{c}-v1.json").write_text(json.dumps(meta,indent=2)+"\n");im=Image.new("RGB",(64,64));im.putdata([PAL[int(v)] for row in frame for v in row]);im.save(ROOT/"docs"/"static"/"img"/"games"/f"{c}-v1.png",optimize=True);games.append({"game_id":c,"title":title,"axis":axis,"levels":6,"source_sha256":h})
 path=ROOT/"research"/"gpt-batch80-v1.json";path.write_text(json.dumps({"schema_version":1,"batch_id":"gpt-batch80-v1","created_at":"2026-08-31T00:00:00Z","design":"The nine-game ledger boundary completes all 800 q concepts with calibrated mosaic, clock, and weather evidence; conserved signal and fauna gradients; identity-bound mosaic, vivarium, and workshop obligations; and relational prism rhythm.","games":games},indent=2)+"\n")
 sheet=Image.new("RGB",(800,352),(242,242,246));d=ImageDraw.Draw(sheet)
 for i,c in enumerate(CFG):
  im=Image.open(ROOT/"docs"/"static"/"img"/"games"/f"{c}-v1.png").resize((128,128),Image.Resampling.NEAREST);x,y=(i%5)*160+16,(i//5)*176+12;sheet.paste(im,(x,y));d.text((x,y+136),c,fill=(28,28,36))
 (ROOT/".cache").mkdir(exist_ok=True);sheet.save(ROOT/".cache"/"batch80-contact.png",optimize=True);print("9 metadata records",path)
if __name__=="__main__":main()
