"""Generate metadata, thumbnails, and the contact sheet for research Batch 60."""
import hashlib,importlib.util,json
from PIL import Image,ImageDraw
from arcengine import ActionInput,GameAction
from build_research_batch06_metadata import ROOT,SESSION,PAL
CFG={
"q539":("Strata Lesson","policy-learning-from-demonstration","conditional-policy-transfer-after-a-physical-probe-is-undone-but-its-observation-persists","A pale quarry layers fault bands beneath a demonstration, world-state, knowledge, and crawler rail."),
"q569":("Strata Counter","adaptive-adversary","legible-rival-shaping-through-reversible-probes-and-persistent-knowledge","A dark quarry aligns three fault lanes above rival, probe, and retained-knowledge bands."),
"q596":("Palimpsest Grammar","compositional-communication","one-causal-relational-symbol-isolated-from-an-overwritten-near-miss-message","A sliding archive layers four shelves beneath grouped glyph, relation, trace, and overwrite rails."),
"q626":("Palimpsest Sandbox","counterfactual-planning","failed-branch-evidence-persists-after-disposable-simulation-progress-is-reset","A split archive contrasts two miniature shelves above persistent success and failure marks."),
"q657":("Canopy Analogy","structural-analogy","seasonal-relation-transfer-through-a-hard-capacity-intermediate-seed-store","A blue terraced orchard maps four source relations to targets above seasonal store slots."),
"q686":("Palimpsest Evidence","confidence-calibration","safe-stopping-from-persistent-unequal-evidence-after-the-visible-trace-is-erased","A green evidence archive stacks three shelf samples above erased-trace and stopping bands."),
"q716":("Palimpsest Gradient","continuous-quantity-reasoning","conserved-distribution-crosses-a-threshold-identified-by-a-visible-near-miss","A red quantity archive holds three tile shelves above phase, failure-distance, and commitment rails."),
"q746":("Palimpsest Obligation","long-horizon-credit-assignment","failed-repayment-reveals-the-causal-identity-that-retains-delayed-debt","A gray creditor archive places two identity shelves above debt, reward, failure, and repayment marks."),
"q776":("Palimpsest Rhythm","temporal-abstraction","a-failed-interruption-persists-as-evidence-for-the-later-macro-window","A pink timing archive layers local and macro shelves above failure and interruption bands."),
"q476":("Palimpsest Dependency","hierarchical-goal-discovery","one-failed-prerequisite-trace-is-reused-to-repair-increasingly-many-branches","A white assembly archive grows parts from two shelves using one persistent missing-pair trace.")}
def load(c):
 p=ROOT/"docs"/"static"/"games"/"src"/f"{c}-v1"/f"{c}.py";s=importlib.util.spec_from_file_location(c,p);m=importlib.util.module_from_spec(s);s.loader.exec_module(m);return p,m
def main():
 games=[];out=ROOT/"research"/"games";out.mkdir(parents=True,exist_ok=True)
 for c,(title,axis,primary,silhouette) in CFG.items():
  p,m=load(c);h=hashlib.sha256(p.read_bytes()).hexdigest();rel=p.relative_to(ROOT).as_posix();names=[x["name"] for x in m.LEVELS];g=getattr(m,c.upper())();frame=g.perform_action(ActionInput(id=GameAction.RESET),raw=True).frame[-1];palette=sorted({int(v) for row in frame for v in row})
  meta={"schema_version":1,"game_id":c,"version":"v1","internal_title":title,"public_title":None,"author_partition":"gpt","authorship":{"model_family":"OpenAI GPT-5","model_snapshot":"current Codex task model; exact deployment id not exposed to task","session_id":SESSION,"created_at":"2026-08-30T00:00:00Z","source_lineage":[f"research/gpt-ideas-v2.tsv:{c}"],"source_commit":None},"mechanics":{"primary":primary,"secondary":[axis,"underrepresented-capability-expansion"],"novelty_claim":names[-1],"closest_prior_art":["research/coverage-gap-study-v1.md","research/flash-game-mechanics-survey.md"]},"failure_modes":["copies the near-miss sequence instead of isolating its single causal difference","erases knowledge, evidence, timing, or obligation when the visible world is reset or overwritten","fills a capacity-limited store or commits before the persistent failure trace resolves the global plan"],"interface":{"actions":[1,2,3,4,5,6],"observation":"64x64x16","deterministic":True,"seeded_stochasticity":False},"progression":[{"level":i+1,"role":["orient","discriminate","plan","compose","inhibit","synthesize"][i],"new_demand":n,"composes":list(range(1,i+1))} for i,n in enumerate(names)],"visual_identity":{"dominant_palette":palette,"silhouette_grammar":silhouette,"spatial_grammar":silhouette,"motion_grammar":primary.replace("-"," "),"hud_grammar":"Overwritten shelves, fault bands, memory tiles, erased evidence, near-miss marks, identity panes, and persistent trace rails expose state without text.","nearest_visual_games":[]},"evaluation":{"allowed_development_models":["deterministic-solvers","random-fuzzer","Qwen3.8 diagnostic only"],"held_out_evaluator":"anthropic","human_baseline_status":"not_started","held_out_status":"sealed"},"artifacts":{"source":rel,"metadata":f"research/games/{c}-v1.json","win_recording":f"research/recordings/{c}-v1-win.json","loss_recording":f"research/recordings/{c}-v1-loss.json","thumbnail":f"docs/static/img/games/{c}-v1.png","source_sha256":h},"status":"prototype"}
  (out/f"{c}-v1.json").write_text(json.dumps(meta,indent=2)+"\n");im=Image.new("RGB",(64,64));im.putdata([PAL[int(v)] for row in frame for v in row]);im.save(ROOT/"docs"/"static"/"img"/"games"/f"{c}-v1.png",optimize=True);games.append({"game_id":c,"title":title,"axis":axis,"levels":6,"source_sha256":h})
 path=ROOT/"research"/"gpt-batch60-v1.json";path.write_text(json.dumps({"schema_version":1,"batch_id":"gpt-batch60-v1","created_at":"2026-08-30T00:00:00Z","design":"Ten sliding-archive, quarry, and orchard environments use visible near misses, overwritten traces, reversible probes, and persistent evidence to distinguish causal knowledge from temporary world state.","games":games},indent=2)+"\n")
 sheet=Image.new("RGB",(800,352),(242,242,246));d=ImageDraw.Draw(sheet)
 for i,c in enumerate(CFG):
  im=Image.open(ROOT/"docs"/"static"/"img"/"games"/f"{c}-v1.png").resize((128,128),Image.Resampling.NEAREST);x,y=(i%5)*160+16,(i//5)*176+12;sheet.paste(im,(x,y));d.text((x,y+136),c,fill=(28,28,36))
 (ROOT/".cache").mkdir(exist_ok=True);sheet.save(ROOT/".cache"/"batch60-contact.png",optimize=True);print("10 metadata records",path)
if __name__=="__main__":main()
