"""Generate metadata, thumbnails, and the contact sheet for research Batch 65."""
import hashlib,importlib.util,json
from PIL import Image,ImageDraw
from arcengine import ActionInput,GameAction
from build_research_batch06_metadata import ROOT,SESSION,PAL
CFG={
"q517":("Catalyst Frame","multi-scale-reference-frames","stored-orientation-executes-after-temperature-pipe-frame-motion-changes-its-global-meaning","A white chemical refinery layers four pipe rows above local frame, memory, hidden-state, and product rails."),
"q547":("Catalyst Lesson","policy-learning-from-demonstration","conditional-demonstration-is-stored-before-context-changes-and-hidden-execution","A silver chemical refinery places a demonstration over orientation, context, memory, gesture, and result panes."),
"q577":("Catalyst Counter","adaptive-adversary","rival-state-is-shaped-observed-and-later-executed-from-stored-memory","A gray chemical refinery aligns three tactic chambers above rival, orientation, memory, and hidden-counter bands."),
"q607":("Catalyst Grammar","compositional-communication","composed-relay-code-is-stored-before-pipe-transforms-and-hidden-execution","A stone chemical refinery stacks grouped glyphs over pipe-transform, memory, and product tracks."),
"q637":("Catalyst Sandbox","counterfactual-planning","observed-simulation-orientations-persist-after-physical-copies-reset","A charcoal chemical refinery places two bright sandboxes above persistent-memory, reset, and commitment bars."),
"q667":("Catalyst Analogy","structural-analogy","source-relation-is-stored-before-surface-transforms-and-hidden-target-transfer","A black chemical gallery maps source relations to a contrasting target above memory and surface rails."),
"q727":("Catalyst Gradient","continuous-quantity-reasoning","observed-pipe-direction-later-executes-a-hidden-conserved-transfer","A pink chemical refinery holds three reactant bins above selector, memory, phase, and goal bands."),
"q757":("Catalyst Obligation","long-horizon-credit-assignment","stored-helper-identity-survives-hidden-borrowing-and-later-appearance-swaps","A rose creditor refinery places two identity panes over memory, debt, reward, and repayment rails."),
"q787":("Catalyst Rhythm","temporal-abstraction","stored-interruption-phase-survives-macro-routines-until-hidden-execution","A blue timing refinery layers alternating pulse rows above macro, memory, hidden-state, and interrupt bars."),
"q479":("Strata Dependency","hierarchical-goal-discovery","restored-physical-probes-leave-knowledge-that-unlocks-one-reusable-support-for-nested-branches","A cyan quarry layers fault bands above physical world, persistent knowledge, shared support, and branch rails.")}
def load(c):
 p=ROOT/"docs"/"static"/"games"/"src"/f"{c}-v1"/f"{c}.py";s=importlib.util.spec_from_file_location(c,p);m=importlib.util.module_from_spec(s);s.loader.exec_module(m);return p,m
def main():
 games=[];out=ROOT/"research"/"games";out.mkdir(parents=True,exist_ok=True)
 for c,(title,axis,primary,silhouette) in CFG.items():
  p,m=load(c);h=hashlib.sha256(p.read_bytes()).hexdigest();rel=p.relative_to(ROOT).as_posix();names=[x["name"] for x in m.LEVELS];g=getattr(m,c.upper())();frame=g.perform_action(ActionInput(id=GameAction.RESET),raw=True).frame[-1];palette=sorted({int(v) for row in frame for v in row})
  meta={"schema_version":1,"game_id":c,"version":"v1","internal_title":title,"public_title":None,"author_partition":"gpt","authorship":{"model_family":"OpenAI GPT-5","model_snapshot":"current Codex task model; exact deployment id not exposed to task","session_id":SESSION,"created_at":"2026-08-30T00:00:00Z","source_lineage":[f"research/gpt-ideas-v2.tsv:{c}"],"source_commit":None},"mechanics":{"primary":primary,"secondary":[axis,"underrepresented-capability-expansion"],"novelty_claim":names[-1],"closest_prior_art":["research/coverage-gap-study-v1.md","research/flash-game-mechanics-survey.md"]},"failure_modes":["uses the component's current orientation instead of the orientation written during observation","forgets that frame, relay, rival, phase, or identity state can change between memory write and hidden execution","resets persistent evidence with physical simulation state or rebuilds a shared dependency instead of reusing it"],"interface":{"actions":[1,2,3,4,5,6],"observation":"64x64x16","deterministic":True,"seeded_stochasticity":False},"progression":[{"level":i+1,"role":["orient","discriminate","plan","compose","inhibit","synthesize"][i],"new_demand":n,"composes":list(range(1,i+1))} for i,n in enumerate(names)],"visual_identity":{"dominant_palette":palette,"silhouette_grammar":silhouette,"spatial_grammar":silhouette,"motion_grammar":primary.replace("-"," "),"hud_grammar":"Temperature pipes, reactant beads, orientation rows, observation-memory bars, hidden-state panes, sandbox copies, identity chambers, fault strata, and knowledge rails expose state without text.","nearest_visual_games":[]},"evaluation":{"allowed_development_models":["deterministic-solvers","random-fuzzer","Qwen3.8 diagnostic only"],"held_out_evaluator":"anthropic","human_baseline_status":"not_started","held_out_status":"sealed"},"artifacts":{"source":rel,"metadata":f"research/games/{c}-v1.json","win_recording":f"research/recordings/{c}-v1-win.json","loss_recording":f"research/recordings/{c}-v1-loss.json","thumbnail":f"docs/static/img/games/{c}-v1.png","source_sha256":h},"status":"prototype"}
  (out/f"{c}-v1.json").write_text(json.dumps(meta,indent=2)+"\n");im=Image.new("RGB",(64,64));im.putdata([PAL[int(v)] for row in frame for v in row]);im.save(ROOT/"docs"/"static"/"img"/"games"/f"{c}-v1.png",optimize=True);games.append({"game_id":c,"title":title,"axis":axis,"levels":6,"source_sha256":h})
 path=ROOT/"research"/"gpt-batch65-v1.json";path.write_text(json.dumps({"schema_version":1,"batch_id":"gpt-batch65-v1","created_at":"2026-08-30T00:00:00Z","design":"Nine colorful chemical-refinery environments separate observation-time memory writes from later hidden execution across frames, policies, rivals, language, simulations, analogies, quantities, obligations, and rhythms; a quarry dependency task separates restored physical state from persistent knowledge.","games":games},indent=2)+"\n")
 sheet=Image.new("RGB",(800,352),(242,242,246));d=ImageDraw.Draw(sheet)
 for i,c in enumerate(CFG):
  im=Image.open(ROOT/"docs"/"static"/"img"/"games"/f"{c}-v1.png").resize((128,128),Image.Resampling.NEAREST);x,y=(i%5)*160+16,(i//5)*176+12;sheet.paste(im,(x,y));d.text((x,y+136),c,fill=(28,28,36))
 (ROOT/".cache").mkdir(exist_ok=True);sheet.save(ROOT/".cache"/"batch65-contact.png",optimize=True);print("10 metadata records",path)
if __name__=="__main__":main()
