"""Generate metadata, thumbnails, and the contact sheet for research Batch 63."""
import hashlib,importlib.util,json
from PIL import Image,ImageDraw
from arcengine import ActionInput,GameAction
from build_research_batch06_metadata import ROOT,SESSION,PAL
CFG={
"q551":("Pollen Lesson","policy-learning-from-demonstration","conditional-policy-transfer-across-a-visible-wear-triggered-rule-complement","A white alpine meadow places a bloom demonstration over context, complement, wear, and gesture rails."),
"q581":("Pollen Counter","adaptive-adversary","opponent-state-shaped-before-a-visible-wear-boundary-complements-its-update-law","A silver alpine meadow aligns three tactic beds above rival, history, wear, and exploit bands."),
"q611":("Pollen Grammar","compositional-communication","grouped-relational-message-composed-through-a-wear-complemented-relay","A gray alpine meadow stacks grouped pollen glyphs above complement and relay tracks."),
"q641":("Pollen Sandbox","counterfactual-planning","simulation-evidence-persists-while-a-reset-crosses-a-visible-rule-change","A stone alpine meadow places two bright sandboxes above persistent evidence, reset, and rule bars."),
"q671":("Pollen Analogy","structural-analogy","relational-structure-transfers-after-its-visible-mapping-becomes-the-complement","A charcoal alpine gallery maps striped source blooms to a transformed target across a wear rail."),
"q701":("Pollen Evidence","confidence-calibration","unequal-samples-support-safe-stopping-across-a-wear-triggered-evidence-inversion","A black alpine evidence garden places three sample beds over signed confidence and wear bars."),
"q731":("Pollen Gradient","continuous-quantity-reasoning","conserved-bloom-mass-is-routed-through-channels-whose-direction-inverts-at-wear","A pink alpine meadow holds three quantity beds above target, wear, and phase bands."),
"q761":("Pollen Obligation","long-horizon-credit-assignment","identity-bound-debt-survives-a-wear-triggered-exchange-of-visible-positions","A rose creditor meadow places two identity panes over delayed reward, wear, debt, and repayment bars."),
"q791":("Pollen Rhythm","temporal-abstraction","autonomous-routine-period-changes-at-wear-before-a-state-defined-interruption-window","A blue timing meadow layers striped routines above local pulse, macro, period, and wear rails."),
"q513":("Murmuration Frame","multi-scale-reference-frames","local-motion-composes-with-a-rotating-wake-frame-and-three-view-parity-audit","A cyan open aviary arranges eight wake cells above frame, audit, and majority-vote rails.")}
def load(c):
 p=ROOT/"docs"/"static"/"games"/"src"/f"{c}-v1"/f"{c}.py";s=importlib.util.spec_from_file_location(c,p);m=importlib.util.module_from_spec(s);s.loader.exec_module(m);return p,m
def main():
 games=[];out=ROOT/"research"/"games";out.mkdir(parents=True,exist_ok=True)
 for c,(title,axis,primary,silhouette) in CFG.items():
  p,m=load(c);h=hashlib.sha256(p.read_bytes()).hexdigest();rel=p.relative_to(ROOT).as_posix();names=[x["name"] for x in m.LEVELS];g=getattr(m,c.upper())();frame=g.perform_action(ActionInput(id=GameAction.RESET),raw=True).frame[-1];palette=sorted({int(v) for row in frame for v in row})
  meta={"schema_version":1,"game_id":c,"version":"v1","internal_title":title,"public_title":None,"author_partition":"gpt","authorship":{"model_family":"OpenAI GPT-5","model_snapshot":"current Codex task model; exact deployment id not exposed to task","session_id":SESSION,"created_at":"2026-08-30T00:00:00Z","source_lineage":[f"research/gpt-ideas-v2.tsv:{c}"],"source_commit":None},"mechanics":{"primary":primary,"secondary":[axis,"underrepresented-capability-expansion"],"novelty_claim":names[-1],"closest_prior_art":["research/coverage-gap-study-v1.md","research/flash-game-mechanics-survey.md"]},"failure_modes":["continues applying the original policy after the visible wear boundary complements the rule","treats reset physical state as erased evidence or assigns a delayed obligation to current appearance","trusts one misleading parity view, stops before the evidence margin is safe, or ignores the moving frame"],"interface":{"actions":[1,2,3,4,5,6],"observation":"64x64x16","deterministic":True,"seeded_stochasticity":False},"progression":[{"level":i+1,"role":["orient","discriminate","plan","compose","inhibit","synthesize"][i],"new_demand":n,"composes":list(range(1,i+1))} for i,n in enumerate(names)],"visual_identity":{"dominant_palette":palette,"silhouette_grammar":silhouette,"spatial_grammar":silhouette,"motion_grammar":primary.replace("-"," "),"hud_grammar":"Bright bloom beds, pollen glyphs, wear bars, complemented rule panes, conserved distributions, identity panes, wake cells, and parity votes expose state without text.","nearest_visual_games":[]},"evaluation":{"allowed_development_models":["deterministic-solvers","random-fuzzer","Qwen3.8 diagnostic only"],"held_out_evaluator":"anthropic","human_baseline_status":"not_started","held_out_status":"sealed"},"artifacts":{"source":rel,"metadata":f"research/games/{c}-v1.json","win_recording":f"research/recordings/{c}-v1-win.json","loss_recording":f"research/recordings/{c}-v1-loss.json","thumbnail":f"docs/static/img/games/{c}-v1.png","source_sha256":h},"status":"prototype"}
  (out/f"{c}-v1.json").write_text(json.dumps(meta,indent=2)+"\n");im=Image.new("RGB",(64,64));im.putdata([PAL[int(v)] for row in frame for v in row]);im.save(ROOT/"docs"/"static"/"img"/"games"/f"{c}-v1.png",optimize=True);games.append({"game_id":c,"title":title,"axis":axis,"levels":6,"source_sha256":h})
 path=ROOT/"research"/"gpt-batch63-v1.json";path.write_text(json.dumps({"schema_version":1,"batch_id":"gpt-batch63-v1","created_at":"2026-08-30T00:00:00Z","design":"Nine colorful alpine-meadow environments carry policy, rival, message, simulation, relation, evidence, quantity, obligation, and rhythm state across visible wear-triggered rule changes; an open aviary composes local motion with a rotating frame and redundant parity audit.","games":games},indent=2)+"\n")
 sheet=Image.new("RGB",(800,352),(242,242,246));d=ImageDraw.Draw(sheet)
 for i,c in enumerate(CFG):
  im=Image.open(ROOT/"docs"/"static"/"img"/"games"/f"{c}-v1.png").resize((128,128),Image.Resampling.NEAREST);x,y=(i%5)*160+16,(i//5)*176+12;sheet.paste(im,(x,y));d.text((x,y+136),c,fill=(28,28,36))
 (ROOT/".cache").mkdir(exist_ok=True);sheet.save(ROOT/".cache"/"batch63-contact.png",optimize=True);print("10 metadata records",path)
if __name__=="__main__":main()
