"""Generate metadata, thumbnails, and a contact sheet for research Batch 85."""
import hashlib,importlib.util,json
from PIL import Image,ImageDraw
from arcengine import ActionInput,GameAction
from build_research_batch06_metadata import ROOT,SESSION,PAL
CFG={
"a041":("Race Gate","concurrency-and-interleaving","race-condition-and-safe-event-ordering","A coral dual-track raceway exposes carrier order, shared switches, priority, and gate state."),
"a042":("Semaphore Garden","concurrency-and-interleaving","mutual-exclusion-under-variable-arrival-order","A leafy garden surrounds a single tunnel with two workers, permits, blooms, and passage history."),
"a043":("Atomic Crossing","concurrency-and-interleaving","atomic-group-commit-across-coupled-locks","A violet river bridge separates staged clamps from committed locks and cart motion."),
"a044":("Deadlock Dock","concurrency-and-interleaving","resource-ordering-and-circular-wait-avoidance","A blue harbor gives three boats, three locks, request pointers, and release history separate docks."),
"a045":("Barrier Beat","concurrency-and-interleaving","barrier-synchronization-of-unequal-agent-loops","A rhythmic stage stacks three colored loops across paired striped barriers and a pulse rail."),
"a046":("Interrupt Loom","concurrency-and-interleaving","safe-preemption-with-resumable-local-state","A woven textile field shows two automata, safe-state marks, shuttle ownership, and preserved rows."),
"a047":("Two-Phase Move","concurrency-and-interleaving","prepare-reserve-then-atomic-commit","A bright exchange floor separates tile positions, reservation shadows, phase state, and commit marks."),
"a048":("Livelock Lights","concurrency-and-interleaving","symmetry-breaking-policy-intervention","A neon corridor places mirrored robots over alternating lights with visible rule and progress panels."),
"a049":("Bottleneck Bins","queueing-and-backpressure","finite-capacity-routing-with-upstream-backpressure","A warm factory branches one source bin through two gates into unequal downstream capacities."),
"a050":("Spillback City","queueing-and-backpressure","network-spillback-and-escape-cell-preservation","A mint street grid exposes four queues, downstream vacancies, signals, and accumulating blockage."),
}
def load(c):
 p=ROOT/"docs"/"static"/"games"/"src"/f"{c}-v1"/f"{c}.py";s=importlib.util.spec_from_file_location(c,p);m=importlib.util.module_from_spec(s);s.loader.exec_module(m);return p,m
def main():
 games=[];out=ROOT/"research"/"games";out.mkdir(parents=True,exist_ok=True)
 for c,(title,axis,primary,silhouette) in CFG.items():
  p,m=load(c);h=hashlib.sha256(p.read_bytes()).hexdigest();rel=p.relative_to(ROOT).as_posix();names=[x["name"] for x in m.LEVELS];g=getattr(m,c.upper())();frame=g.perform_action(ActionInput(id=GameAction.RESET),raw=True).frame[-1];palette=sorted({int(v) for row in frame for v in row})
  meta={"schema_version":1,"game_id":c,"version":"v1","internal_title":title,"public_title":None,"author_partition":"gpt","authorship":{"model_family":"OpenAI GPT-5","model_snapshot":"current Codex task model; exact deployment id not exposed to task","session_id":SESSION,"created_at":"2026-08-31T00:00:00Z","source_lineage":[f"research/anthropic-build-ideas-v1.tsv:{c}"],"concept_lineage":"gpt-seeded-anthropic-build","intended_builder":"anthropic","implementation_author_partition":"gpt","source_commit":None},"mechanics":{"primary":primary,"secondary":[axis,"distributed-state-and-flow-control"],"novelty_claim":names[-1],"closest_prior_art":["research/anthropic-build-ideas-v1.audit.json","research/coverage-gap-study-v1.md","research/flash-game-mechanics-survey.md"]},"failure_modes":["reasons from final positions without reconstructing event order, ownership, reservation, or queue state","mistakes ongoing activity or local throughput for safe global progress","forgets a staged change, resumable state, capacity limit, waiting cohort, or downstream escape constraint"],"interface":{"actions":[1,2,3,4,5,6],"observation":"64x64x16","deterministic":True,"seeded_stochasticity":False},"progression":[{"level":i+1,"role":["orient","discriminate","plan","compose","inhibit","synthesize"][i],"new_demand":n,"composes":list(range(1,i+1))} for i,n in enumerate(names)],"visual_identity":{"dominant_palette":palette,"silhouette_grammar":silhouette,"spatial_grammar":silhouette,"motion_grammar":primary.replace("-"," "),"hud_grammar":"Tracks, tunnel permits, staged clamps, lock ownership, barrier cohorts, safe preemption marks, reservations, response rules, bin capacities, and escape cells expose concurrent state without text.","nearest_visual_games":[]},"evaluation":{"allowed_development_models":["deterministic-solvers","random-fuzzer","Qwen3.8 diagnostic only"],"held_out_evaluator":"anthropic","human_baseline_status":"not_started","held_out_status":"sealed"},"artifacts":{"source":rel,"metadata":f"research/games/{c}-v1.json","win_recording":f"research/recordings/{c}-v1-win.json","loss_recording":f"research/recordings/{c}-v1-loss.json","thumbnail":f"docs/static/img/games/{c}-v1.png","source_sha256":h},"status":"prototype"}
  (out/f"{c}-v1.json").write_text(json.dumps(meta,indent=2)+"\n");im=Image.new("RGB",(64,64));im.putdata([PAL[int(v)] for row in frame for v in row]);im.save(ROOT/"docs"/"static"/"img"/"games"/f"{c}-v1.png",optimize=True);games.append({"game_id":c,"title":title,"axis":axis,"levels":6,"source_sha256":h})
 path=ROOT/"research"/"gpt-batch85-v1.json";path.write_text(json.dumps({"schema_version":1,"batch_id":"gpt-batch85-v1","created_at":"2026-08-31T00:00:00Z","provenance":"Concepts retain gpt-seeded-anthropic-build queue lineage; implementations in this batch are authored by OpenAI GPT-5 and are not attributed to Anthropic.","design":"Ten colorful systems dioramas require reasoning about interleaving, exclusion, atomicity, deadlock, barriers, preemption, commit protocols, livelock, finite capacity, and network spillback.","games":games},indent=2)+"\n")
 sheet=Image.new("RGB",(800,352),(242,242,246));d=ImageDraw.Draw(sheet)
 for i,c in enumerate(CFG):
  im=Image.open(ROOT/"docs"/"static"/"img"/"games"/f"{c}-v1.png").resize((128,128),Image.Resampling.NEAREST);x,y=(i%5)*160+16,(i//5)*176+12;sheet.paste(im,(x,y));d.text((x,y+136),c,fill=(28,28,36))
 (ROOT/".cache").mkdir(exist_ok=True);sheet.save(ROOT/".cache"/"batch85-contact.png",optimize=True);print("10 metadata records",path)
if __name__=="__main__":main()
