"""Generate metadata, thumbnails, and the batch manifest for research Batch 04."""

from __future__ import annotations
import hashlib,importlib.util,json
from pathlib import Path
from PIL import Image,ImageDraw
from arcengine import ActionInput,GameAction

ROOT=Path(__file__).resolve().parents[1];SESSION="01a02a2e-aaf5-7e90-a559-46437ace2edb"
PALETTE=[(255,255,255),(204,204,204),(153,153,153),(102,102,102),(51,51,51),(0,0,0),(229,58,163),(255,123,204),(249,60,49),(30,147,255),(136,216,241),(255,220,0),(255,133,27),(146,18,49),(79,204,48),(163,86,214)]
ROLES=["orient","discriminate","plan","compose","inhibit","synthesize"]
CONFIG={
"q102":{"title":"Walking Room","axis":"multi-scale-reference-frames","primary":"mobile-room-local-global-navigation","secondary":["nested-position","carrier-motion","obstacle-composition"],"failures":["moves only the body","forgets carried local position","collides after translating the chamber"],"actions":[1,2,3,4,5],"palette":[0,1,3,6,8,9,10,12,14],"silhouette":"A cyan three-by-three chamber carries a magenta traveler across a pale world lattice.","spatial":"An orange world surround contains a visibly bounded moving local room.","motion":"Directional actions move within the chamber while a separate carrier action walks the whole room in the held direction.","hud":"A blue facing bead grounds the carrier's pending world direction.","progress":["Move within one stationary room.","Translate the room while preserving local position.","Compose local and carrier motion.","Avoid world walls with the room boundary.","Exploit carried position across a long translation.","Navigate a winding global route through both coordinate scales."]},
"q112":{"title":"Negative Demonstration","axis":"policy-learning-from-demonstration","primary":"success-failure-contrast-learning","secondary":["counterexample-use","shared-prefix-discrimination","sequence-transfer"],"failures":["imitates the failed trace","uses majority resemblance","misses a late discriminating action"],"actions":[1,2,3,4],"palette":[1,8,9,11,13,14,15],"silhouette":"Green success arrows and red failure arrows occupy paired rehearsal strips.","spatial":"Two pale demonstration panels sit inside a yellow teaching hall.","motion":"The player reproduces the policy distinguished by the successful trace rather than copying shared surface motion.","hud":"Violet completion tiles record transferred policy length.","progress":["Find one differing action.","Use a shared-prefix counterexample.","Reject a middle error.","Maintain a longer successful sequence.","Detect a late distinction.","Transfer a seven-action policy from nearly identical traces."]},
"q122":{"title":"Feint","axis":"adaptive-adversary","primary":"displayed-intent-execution-separation","secondary":["opponent-manipulation","two-stage-action","collision-planning"],"failures":["executes displayed intent","ignores guard adaptation","feints into a blocked follow-up"],"actions":[1,2,3,4],"palette":[0,3,7,8,9,12,13,14],"silhouette":"A blue player, red guard, and orange intent ghost occupy a white tactical grid.","spatial":"A pink arena surrounds a compact burgundy-walled pursuit board.","motion":"Every displayed direction moves the guard first; the following input executes the player's actual move.","hud":"The orange intent cell persists between the two stages of each turn.","progress":["Display one false intent.","Feint around a corner.","Manipulate a guard at a narrow gap.","Chain two bluffs.","Preserve escape space under walls.","Compose repeated intent manipulation through a constrained arena."]},
"q132":{"title":"Shape-Free Code","axis":"compositional-communication","primary":"relative-position-command-code","secondary":["geometric-grounding","message-reset","ordered-command"],"failures":["uses marker color as meaning","forgets the anchor frame","fails to reset between words"],"actions":[1,2,3,4,5],"palette":[1,6,8,9,10,12,13,14],"silhouette":"One magenta marker moves around a burgundy anchor on an unlabelled three-by-three signal pad.","spatial":"A pale geometry pad and receiver column float in a cyan communications room.","motion":"Relative displacement encodes a direction; transmission resets the marker before the next command.","hud":"Orange receiver blocks accumulate into a visible route phrase.","progress":["Ground one relative position.","Transmit two reset commands.","Compose a corner phrase.","Return across all four relations.","Maintain a five-command sentence.","Send six novel commands using geometry alone."]},
"q142":{"title":"Ghost Alternatives","axis":"counterfactual-planning","primary":"scarce-action-preview","secondary":["preview-selection","trap-avoidance","commitment"],"failures":["previews every action","confuses ghost with execution","commits through an unpreviewed trap"],"actions":[3,4,5,6],"palette":[1,3,7,8,10,11,13,14],"silhouette":"A magenta player and translucent pink ghost occupy a cyan route grid with red traps.","spatial":"A pale planning surface surrounds a compact five-by-five counterfactual board.","motion":"The selector previews one possible destination at a cost, then separately commits that alternative.","hud":"Pink preview chips and a yellow action selector expose epistemic versus physical actions.","progress":["Preview one choice.","Compare ghost destinations around hazards.","Allocate only two previews on a detour.","Delay a preview until a branch matters.","Plan with a sparse preview budget.","Cross a trap-lined board using four selected counterfactuals."]},
"q152":{"title":"Shadows to Forces","axis":"structural-analogy","primary":"offset-to-force-transfer","secondary":["cross-domain-relation","directional-invariance","sequence-transfer"],"failures":["copies object position","moves toward the visible shadow pane","fails to transfer relation order"],"actions":[1,2,3,4],"palette":[1,3,6,8,9,11,12,14,15],"silhouette":"A green object-shadow lesson sits above a magenta body in an orange invisible-force field.","spatial":"Two distinct physical domains share a blue analogy laboratory.","motion":"A geometric object-shadow offset reappears as the direction of an otherwise invisible force action.","hud":"Violet relation tiles preserve the learned transfer sequence.","progress":["Transfer one offset relation.","Apply an orthogonal relation.","Alternate three attraction directions.","Cover all four offsets.","Transfer a five-force sequence.","Compose six relations across the visual-to-physical analogy."]},
"q162":{"title":"Claim or Explore","axis":"confidence-calibration","primary":"probe-versus-progress-tradeoff","secondary":["stopping-rule","multi-step-evidence","irreversible-action"],"failures":["probes before every known step","acts with no evidence","forgets remaining clue span"],"actions":[1,2,3,4,5],"palette":[1,3,8,9,11,13,14,15],"silhouette":"A blue progress marker advances beneath yellow directional clue marks and gray unknown cells.","spatial":"A pale evidence corridor runs through a burgundy decision chamber.","motion":"Probe reveals a bounded span of policy; movement consumes that evidence and advances irreversibly.","hud":"A violet evidence bar distinguishes known from unknown action spans.","progress":["Probe before one action.","Use one clue for two steps.","Alternate exploration and execution.","Stop exploring while a three-step clue remains.","Manage sparse claims across six moves.","Finish seven actions with only three bounded probes."]},
"q172":{"title":"Fluid Blend","axis":"continuous-quantity-reasoning","primary":"two-component-conserved-mixture","secondary":["proportion-tracking","component-routing","visual-blend"],"failures":["tracks total volume only","confuses the two components","matches hue without distribution"],"actions":[3,4,5,6],"palette":[0,1,6,8,9,10,11,14,15],"silhouette":"White vessels hold separate blue and magenta fluid columns beneath paired target swatches.","spatial":"A bright blending bench sits inside a violet fluid laboratory.","motion":"Selected valves route one conserved component at a time, changing both area and perceived mixture.","hud":"Yellow valve selectors expose the currently active component transfer.","progress":["Split one fluid component.","Mix two colors equally.","Route components through three vessels.","Construct unequal blend ratios.","Preserve both components across four receivers.","Produce four exact mixtures from two conserved sources."]},
"q182":{"title":"Borrowed Floor","axis":"long-horizon-credit-assignment","primary":"cross-room-consumed-material","secondary":["resource-preservation","route-coupling","delayed-feasibility"],"failures":["uses the shortest first path","forgets consumed tile identities","preserves the wrong bridge material"],"actions":[1,2,3,4],"palette":[0,3,6,8,9,10,11,12,13,14],"silhouette":"Green present and blue future rooms share orange letterless floor materials that later turn red.","spatial":"Two stacked route boards sit within a magenta resource ledger.","motion":"Walking on a marked material in the first room removes every matching material in the later room.","hud":"The paired rooms make delayed material loss visible without numeric counters.","progress":["Preserve one future tile.","Trade a longer present route for future access.","Track two shared materials.","Maintain a three-material ledger.","Conserve the correct bridge resource.","Plan two intertwined routes across three consumable floor classes."]},
"q192":{"title":"Nested Clocks","axis":"temporal-abstraction","primary":"fast-slow-cycle-synchronization","secondary":["rollover-chunking","phase-pair-memory","multi-event-timing"],"failures":["tracks only the fast hand","counts frames without rollover","forgets the slow phase after capture"],"actions":[5,6],"palette":[1,3,8,9,11,13,14,15],"silhouette":"Blue fast tiles and violet slow tiles form two coupled physical clock rows.","spatial":"A pale clock face sits inside a red temporal editing room.","motion":"Every fast-cycle rollover advances the slow phase; capture succeeds only at the required ordered phase pair.","hud":"Yellow capture badges compress multiple raw ticks into remembered nested events.","progress":["Capture one fast phase.","Observe one slow rollover.","Track unequal nested periods.","Wait across a slow boundary.","Capture three phase pairs.","Synchronize four events on seven-by-four nested clocks."]},
}

def load_module(code):
 p=ROOT/"docs"/"static"/"games"/"src"/f"{code}-v1"/f"{code}.py";s=importlib.util.spec_from_file_location(f"{code}_meta",p);m=importlib.util.module_from_spec(s);assert s.loader;s.loader.exec_module(m);return p,m
def thumb(code,m):
 g=getattr(m,code.upper())();r=g.perform_action(ActionInput(id=GameAction.RESET),raw=True);grid=r.frame[-1];im=Image.new("RGB",(64,64));im.putdata([PALETTE[int(v)] for row in grid for v in row]);out=ROOT/"docs"/"static"/"img"/"games"/f"{code}-v1.png";out.parent.mkdir(parents=True,exist_ok=True);im.save(out,optimize=True)
def main():
 outdir=ROOT/"research"/"games";outdir.mkdir(parents=True,exist_ok=True);batch=[]
 for code,c in CONFIG.items():
  source,m=load_module(code);rel=source.relative_to(ROOT).as_posix();h=hashlib.sha256(source.read_bytes()).hexdigest();meta={"schema_version":1,"game_id":code,"version":"v1","internal_title":c["title"],"public_title":None,"author_partition":"gpt","authorship":{"model_family":"OpenAI GPT-5","model_snapshot":"current Codex task model; exact deployment id not exposed to task","session_id":SESSION,"created_at":"2026-08-30T00:00:00Z","source_lineage":[f"research/gpt-ideas-v1.tsv:{code}"],"source_commit":None},"mechanics":{"primary":c["primary"],"secondary":c["secondary"],"novelty_claim":c["progress"][-1],"closest_prior_art":["research/coverage-gap-study-v1.md","research/flash-game-mechanics-survey.md"]},"failure_modes":c["failures"],"interface":{"actions":c["actions"],"observation":"64x64x16","deterministic":True,"seeded_stochasticity":False},"progression":[{"level":i+1,"role":ROLES[i],"new_demand":d,"composes":list(range(1,i+1))} for i,d in enumerate(c["progress"])],"visual_identity":{"dominant_palette":c["palette"],"silhouette_grammar":c["silhouette"],"spatial_grammar":c["spatial"],"motion_grammar":c["motion"],"hud_grammar":c["hud"],"nearest_visual_games":[]},"evaluation":{"allowed_development_models":["deterministic-solvers","random-fuzzer","Qwen3.8 diagnostic only"],"held_out_evaluator":"anthropic","human_baseline_status":"not_started","held_out_status":"sealed"},"artifacts":{"source":rel,"metadata":f"research/games/{code}-v1.json","win_recording":f"research/recordings/{code}-v1-win.json","loss_recording":f"research/recordings/{code}-v1-loss.json","thumbnail":f"docs/static/img/games/{code}-v1.png","source_sha256":h},"status":"prototype"};(outdir/f"{code}-v1.json").write_text(json.dumps(meta,indent=2)+"\n");thumb(code,m);batch.append({"game_id":code,"title":c["title"],"axis":c["axis"],"levels":len(m.LEVELS),"source_sha256":h})
 path=ROOT/"research"/"gpt-batch04-v1.json";path.write_text(json.dumps({"schema_version":1,"batch_id":"gpt-batch04-v1","created_at":"2026-08-30T00:00:00Z","design":"Ten second-pass games across the second ten research axes, each with six progressive levels and a distinct colorful environment.","games":batch},indent=2)+"\n");sheet=Image.new("RGB",(800,352),(242,242,246));draw=ImageDraw.Draw(sheet)
 for i,code in enumerate(CONFIG):
  im=Image.open(ROOT/"docs"/"static"/"img"/"games"/f"{code}-v1.png").convert("RGB").resize((128,128),Image.Resampling.NEAREST);x,y=(i%5)*160+16,(i//5)*176+12;sheet.paste(im,(x,y));draw.text((x,y+136),code,fill=(28,28,36))
 p=ROOT/".cache"/"batch04-contact.png";p.parent.mkdir(parents=True,exist_ok=True);sheet.save(p,optimize=True);print(f"{len(batch)} metadata records -> {outdir}");print(path)
if __name__=="__main__":main()
