"""Generate metadata, thumbnails, and the contact sheet for research Batch 73."""
import hashlib,importlib.util,json
from PIL import Image,ImageDraw
from arcengine import ActionInput,GameAction
from build_research_batch06_metadata import ROOT,SESSION,PAL

CFG={
"q527":("Spectrum Frame","multi-scale-reference-frames","packet-motion-composes-across-rotating-and-translating-wavelength-splitting-reference-frames","An obsidian prism gallery separates four tall panes from a six-packet spectrum rail and split accumulator."),
"q558":("Escapement Lesson","policy-learning-from-demonstration","context-conditioned-clockwork-demonstrations-separate-effective-probes-from-a-causally-irrelevant-gesture","An ivory clock tower places four gear hypotheses above colored demonstration traces, context, and nuisance rails."),
"q590":("Workbench Counter","adaptive-adversary","a-legible-three-tactic-rival-updates-from-the-last-two-tool-treatments-before-a-fixture-is-exploited","A blue mobile workshop aligns four fixtures over a two-treatment memory, rival tactic, and tool-state rails."),
"q617":("Spectrum Grammar","compositional-communication","grouped-color-packets-compose-through-prism-relays-that-transform-the-meaning-of-later-symbols","A violet prism gallery stacks color packets above an explicit message tape, relay state, and composed spectrum rail."),
"q648":("Escapement Sandbox","counterfactual-planning","physical-clockwork-trials-reset-while-observed-fault-evidence-persists-into-an-irreversible-commitment","A green clockwork laboratory contrasts a trial chamber and reset bay above a persistent evidence notebook."),
"q678":("Escapement Analogy","structural-analogy","gear-gap-relations-transfer-to-weight-tokens-across-surface-changes-and-diagnostic-fault-rotations","A mauve clock tower presents source gears and target weights in paired panels above surface and fault rails."),
"q710":("Workbench Evidence","confidence-calibration","unequal-tool-samples-and-changing-fixtures-update-a-bounded-margin-until-further-evidence-cannot-change-the-choice","A tan workshop arrays four test fixtures over signed samples, a centered confidence margin, and sampling cost."),
"q740":("Workbench Gradient","continuous-quantity-reasoning","conserved-tool-mass-flows-through-capacity-limited-fixtures-while-phase-and-identity-bound-debt-shift","A warm workshop uses four vertical reservoirs, phase and fixture rails, and a debt-colored conserved flow."),
"q767":("Spectrum Obligation","long-horizon-credit-assignment","photon-debt-remains-attached-to-causal-identity-while-packets-exchange-position-band-and-appearance","A slate prism gallery tracks four packet identities through colored bands, swaps, rotations, and a creditor ledger."),
"q798":("Escapement Rhythm","temporal-abstraction","nested-fast-and-slow-gears-must-be-diagnosed-and-interrupted-at-a-state-defined-phase-pair","A gold clock tower arranges twelve escapement nodes above fast, slow, fault, and interruption-window rails.")}
def load(c):
 p=ROOT/"docs"/"static"/"games"/"src"/f"{c}-v1"/f"{c}.py";s=importlib.util.spec_from_file_location(c,p);m=importlib.util.module_from_spec(s);s.loader.exec_module(m);return p,m
def main():
 games=[];out=ROOT/"research"/"games";out.mkdir(parents=True,exist_ok=True)
 for c,(title,axis,primary,silhouette) in CFG.items():
  p,m=load(c);h=hashlib.sha256(p.read_bytes()).hexdigest();rel=p.relative_to(ROOT).as_posix();names=[x["name"] for x in m.LEVELS];g=getattr(m,c.upper())();frame=g.perform_action(ActionInput(id=GameAction.RESET),raw=True).frame[-1];palette=sorted({int(v) for row in frame for v in row})
  meta={"schema_version":1,"game_id":c,"version":"v1","internal_title":title,"public_title":None,"author_partition":"gpt","authorship":{"model_family":"OpenAI GPT-5","model_snapshot":"current Codex task model; exact deployment id not exposed to task","session_id":SESSION,"created_at":"2026-08-31T00:00:00Z","source_lineage":[f"research/gpt-ideas-v2.tsv:{c}"],"source_commit":None},"mechanics":{"primary":primary,"secondary":[axis,"underrepresented-capability-expansion"],"novelty_claim":names[-1],"closest_prior_art":["research/coverage-gap-study-v1.md","research/flash-game-mechanics-survey.md"]},"failure_modes":["tracks screen position while ignoring the moving prism, fixture, or gear reference frame","copies a surface sequence without inferring the context, relay transform, opponent update, or persistent evidence state","loses causal identity or conservation when packets, tools, or weights exchange visible positions"],"interface":{"actions":[1,2,3,4,5,6],"observation":"64x64x16","deterministic":True,"seeded_stochasticity":False},"progression":[{"level":i+1,"role":["orient","discriminate","plan","compose","inhibit","synthesize"][i],"new_demand":n,"composes":list(range(1,i+1))} for i,n in enumerate(names)],"visual_identity":{"dominant_palette":palette,"silhouette_grammar":silhouette,"spatial_grammar":silhouette,"motion_grammar":primary.replace("-"," "),"hud_grammar":"Prism panes, spectral packets, clock gears, weight tokens, workshop fixtures, treatment memories, evidence notebooks, confidence margins, conserved reservoirs, creditor ledgers, dual clocks, and interruption windows expose state without text.","nearest_visual_games":[]},"evaluation":{"allowed_development_models":["deterministic-solvers","random-fuzzer","Qwen3.8 diagnostic only"],"held_out_evaluator":"anthropic","human_baseline_status":"not_started","held_out_status":"sealed"},"artifacts":{"source":rel,"metadata":f"research/games/{c}-v1.json","win_recording":f"research/recordings/{c}-v1-win.json","loss_recording":f"research/recordings/{c}-v1-loss.json","thumbnail":f"docs/static/img/games/{c}-v1.png","source_sha256":h},"status":"prototype"}
  (out/f"{c}-v1.json").write_text(json.dumps(meta,indent=2)+"\n");im=Image.new("RGB",(64,64));im.putdata([PAL[int(v)] for row in frame for v in row]);im.save(ROOT/"docs"/"static"/"img"/"games"/f"{c}-v1.png",optimize=True);games.append({"game_id":c,"title":title,"axis":axis,"levels":6,"source_sha256":h})
 path=ROOT/"research"/"gpt-batch73-v1.json";path.write_text(json.dumps({"schema_version":1,"batch_id":"gpt-batch73-v1","created_at":"2026-08-31T00:00:00Z","design":"Three high-contrast visual families—prism galleries, nested clockworks, and mobile workshops—compose moving frames, demonstrations, adaptive rivals, symbolic relays, persistent experiments, analogy, calibrated sampling, conserved flow, causal obligation, and nested time.","games":games},indent=2)+"\n")
 sheet=Image.new("RGB",(800,352),(242,242,246));d=ImageDraw.Draw(sheet)
 for i,c in enumerate(CFG):
  im=Image.open(ROOT/"docs"/"static"/"img"/"games"/f"{c}-v1.png").resize((128,128),Image.Resampling.NEAREST);x,y=(i%5)*160+16,(i//5)*176+12;sheet.paste(im,(x,y));d.text((x,y+136),c,fill=(28,28,36))
 (ROOT/".cache").mkdir(exist_ok=True);sheet.save(ROOT/".cache"/"batch73-contact.png",optimize=True);print("10 metadata records",path)
if __name__=="__main__":main()
