"""Generate metadata, thumbnails, and a contact sheet for research Batch 98."""
import hashlib,importlib.util,json
from PIL import Image,ImageDraw
from arcengine import ActionInput,GameAction
from build_research_batch06_metadata import ROOT,SESSION,PAL
CFG={
"a171":("Irrelevant Paint","state-abstraction-and-equivalence","causal-feature-selection-under-salient-nuisance-churn","A navy memory chamber surrounds deterministic core relations with rapidly cycling decorative borders and a limited feature panel."),
"a172":("Minimal Memory","state-abstraction-and-equivalence","compact-sufficient-statistic-construction","A brown event stream feeds a configurable sum, parity, or last-event memory cell before a predictive gate."),
"a173":("Predictive Partition","state-abstraction-and-equivalence","all-action-future-consistent-observation-binning","A cyan observation panel groups eight surface-different configurations into bins tested by multiple future probes."),
"a174":("Bisimulation Bridge","state-abstraction-and-equivalence","reciprocal-transition-correspondence-across-worlds","A violet bridge pairs two differently rendered state columns under reciprocal action tests and route transfer."),
"a175":("Macro State","state-abstraction-and-equivalence","timescale-separated-controllable-mode-sampling","A red particle chamber cycles twelve fast microstates around slow machine modes, snapshot controls, and transition evidence."),
"a176":("Alias Breaker","state-abstraction-and-equivalence","minimal-sensor-refinement-of-history-aliases","A magenta sensor laboratory compares three aliased observation pairs under one added feature and an overfit meter."),
"a177":("Constructive Gate","proof-witness-and-counterexample","relational-property-witness-synthesis","A pale construction workbench lets the player toggle cells and relations until a new configuration visibly witnesses the demonstrated property."),
"a178":("Counterexample Garden","proof-witness-and-counterexample","minimum-edit-targeted-rule-falsification","A dark growth garden edits one leaf pattern under a small budget to contradict a previously universal plant rule."),
"a179":("Invariant Witness","proof-witness-and-counterexample","compact-parity-or-connectivity-certificate","A black transformation board selects a small colored substructure as a parity or connectivity proof of impossibility."),
"a180":("Unsat Core","proof-witness-and-counterexample","minimum-already-contradictory-constraint-subset","A cream translucent layout highlights a minimal conflicting constraint core while fading irrelevant conditions."),
}
def load(c):
 p=ROOT/"docs"/"static"/"games"/"src"/f"{c}-v1"/f"{c}.py";s=importlib.util.spec_from_file_location(c,p);m=importlib.util.module_from_spec(s);s.loader.exec_module(m);return p,m
def main():
 games=[];out=ROOT/"research"/"games";out.mkdir(parents=True,exist_ok=True)
 for c,(title,axis,primary,silhouette) in CFG.items():
  p,m=load(c);h=hashlib.sha256(p.read_bytes()).hexdigest();rel=p.relative_to(ROOT).as_posix();names=[x["name"] for x in m.LEVELS];g=getattr(m,c.upper())();frame=g.perform_action(ActionInput(id=GameAction.RESET),raw=True).frame[-1];palette=sorted({int(v) for row in frame for v in row})
  meta={"schema_version":1,"game_id":c,"version":"v1","internal_title":title,"public_title":None,"author_partition":"gpt","authorship":{"model_family":"OpenAI GPT-5","model_snapshot":"current Codex task model; exact deployment id not exposed to task","session_id":SESSION,"created_at":"2026-08-31T00:00:00Z","source_lineage":[f"research/anthropic-build-ideas-v1.tsv:{c}"],"concept_lineage":"gpt-seeded-anthropic-build","intended_builder":"anthropic","implementation_author_partition":"gpt","source_commit":None},"mechanics":{"primary":primary,"secondary":[axis,"predictive-abstraction-and-explicit-certificates"],"novelty_claim":names[-1],"closest_prior_art":["research/anthropic-build-ideas-v1.audit.json","research/coverage-gap-study-v1.md","research/flash-game-mechanics-survey.md"]},"failure_modes":["spends memory on salient nuisance state or stores raw recency instead of a sufficient statistic","clusters by appearance or one-way analogy instead of all-action prediction, reciprocal transitions, macro control, or minimal refinement","recognizes a rule or failure without constructing a witness, counterexample, invariant certificate, or minimal conflict core"],"interface":{"actions":[1,2,3,4,5,6],"observation":"64x64x16","deterministic":True,"seeded_stochasticity":False},"progression":[{"level":i+1,"role":["orient","discriminate","plan","compose","inhibit","synthesize"][i],"new_demand":n,"composes":list(range(1,i+1))} for i,n in enumerate(names)],"visual_identity":{"dominant_palette":palette,"silhouette_grammar":silhouette,"spatial_grammar":silhouette,"motion_grammar":primary.replace("-"," "),"hud_grammar":"Causal memory, statistics, predictive bins, reciprocal pairs, macro modes, alias splits, witnesses, counterexamples, certificates, and conflict cores expose abstract evidence without text.","nearest_visual_games":[]},"evaluation":{"allowed_development_models":["deterministic-solvers","random-fuzzer","Qwen3.8 diagnostic only"],"held_out_evaluator":"anthropic","human_baseline_status":"not_started","held_out_status":"sealed"},"artifacts":{"source":rel,"metadata":f"research/games/{c}-v1.json","win_recording":f"research/recordings/{c}-v1-win.json","loss_recording":f"research/recordings/{c}-v1-loss.json","thumbnail":f"docs/static/img/games/{c}-v1.png","source_sha256":h},"status":"prototype"}
  (out/f"{c}-v1.json").write_text(json.dumps(meta,indent=2)+"\n");im=Image.new("RGB",(64,64));im.putdata([PAL[int(v)] for row in frame for v in row]);im.save(ROOT/"docs"/"static"/"img"/"games"/f"{c}-v1.png",optimize=True);games.append({"game_id":c,"title":title,"axis":axis,"levels":6,"source_sha256":h})
 path=ROOT/"research"/"gpt-batch98-v1.json";path.write_text(json.dumps({"schema_version":1,"batch_id":"gpt-batch98-v1","created_at":"2026-08-31T00:00:00Z","provenance":"Concepts retain gpt-seeded-anthropic-build queue lineage; implementations in this batch are authored by OpenAI GPT-5 and are not attributed to Anthropic.","design":"Six abstraction systems reject nuisance, raw history, visual clustering, one-way analogy, microstate reaction, and wholesale deaggregation; four proof boards require constructive witnesses, minimal counterexamples, invariant certificates, and unsatisfiable cores.","games":games},indent=2)+"\n")
 sheet=Image.new("RGB",(800,352),(242,242,246));d=ImageDraw.Draw(sheet)
 for i,c in enumerate(CFG):
  im=Image.open(ROOT/"docs"/"static"/"img"/"games"/f"{c}-v1.png").resize((128,128),Image.Resampling.NEAREST);x,y=(i%5)*160+16,(i//5)*176+12;sheet.paste(im,(x,y));d.text((x,y+136),c,fill=(28,28,36))
 (ROOT/".cache").mkdir(exist_ok=True);sheet.save(ROOT/".cache"/"batch98-contact.png",optimize=True);print("10 metadata records",path)
if __name__=="__main__":main()
