"""Generate metadata and visual artifacts for research Batch 06."""
import hashlib,importlib.util,json
from pathlib import Path
from PIL import Image,ImageDraw
from arcengine import ActionInput,GameAction
ROOT=Path(__file__).resolve().parents[1];SESSION="01a02a2e-aaf5-7e90-a559-46437ace2edb"
PAL=[(255,255,255),(204,204,204),(153,153,153),(102,102,102),(51,51,51),(0,0,0),(229,58,163),(255,123,204),(249,60,49),(30,147,255),(136,216,241),(255,220,0),(255,133,27),(146,18,49),(79,204,48),(163,86,214)]
CFG={
"q103":("Nested Compass","multi-scale-reference-frames","dual-rotating-control-frames",["frame-composition","rotation-grounding"],["uses screen coordinates","tracks only one frame","forgets rotation after moving"],[1,2,3,4,5,6],"A magenta traveler crosses a pale lattice beneath two independently rotating compass marks."),
"q113":("Alternating Teacher","policy-learning-from-demonstration","context-selected-tutor-policy",["context-inference","policy-switching"],["averages tutor policies","ignores context color","copies the signal rather than response"],[1,2,3,4],"Blue and orange tutor rows demonstrate competing mappings above a mixed lesson queue."),
"q123":("Last-Move Guard","adaptive-adversary","last-successful-direction-blocking",["opponent-memory","route-variation"],["repeats a successful move","treats blocked motion as random","fails to weave around the patrol"],[1,2,3,4],"A red guard remembers the last direction while a magenta traveler weaves over a cyan board."),
"q133":("Spatial Grammar","compositional-communication","order-arrangement-joint-code",["two-dimensional-syntax","grounded-decoding"],["reads order alone","reads arrangement alone","fails to compose both dimensions"],[1,2,3,4],"Orange order marks and blue spatial offsets jointly define commands in a pink language panel."),
"q143":("Costly Preview","counterfactual-planning","selective-turn-preview",["information-allocation","commitment"],["previews every turn","commits at an uncertain fork","confuses preview with execution"],[3,4,5,6],"A yellow cursor traverses red route cards with scarce cyan previews reserved for hidden forks."),
"q153":("Braids to Signals","structural-analogy","crossing-permutation-transfer",["permutation-reasoning","temporal-transfer"],["copies strand position","ignores crossing order","fails to transfer the braid to signals"],[1,2,3,4],"Magenta braid crossings transform into blue temporal channel responses."),
"q163":("Evidence Weight","confidence-calibration","reliability-weighted-evidence-allocation",["evidence-assignment","commitment-threshold"],["counts pieces equally","places before comparing reliability","commits with missing evidence"],[1,2,3,4,6],"Differently tall evidence bars are allocated between blue and violet hypothesis platforms."),
"q173":("Density Drift","continuous-quantity-reasoning","gradient-driven-distribution-shaping",["distribution-control","conserved-particles"],["tracks individual particles","ignores gradient direction","matches total but not profile"],[3,4,5,6],"Blue particle stacks drift among pale bins toward magenta target profiles."),
"q183":("Delayed Escort","long-horizon-credit-assignment","early-help-late-policy",["delayed-effect","intermediate-distraction"],["optimizes immediate reward","overhelps every room","forgets early assistance"],[1,2,6],"A blue escort crosses gray rooms while early green help determines a later route."),
"q193":("Routine Builder","temporal-abstraction","branch-preserving-action-macro",["macro-induction","temporal-compression"],["packages the wrong span","replays through a branch","never abstracts repetition"],[1,2,3,4,5,6],"Blue action marks compress into orange routine bars before a nonrepeating suffix.")}
def load(c):
 p=ROOT/"docs"/"static"/"games"/"src"/f"{c}-v1"/f"{c}.py";s=importlib.util.spec_from_file_location(c,p);m=importlib.util.module_from_spec(s);s.loader.exec_module(m);return p,m
def main():
 games=[];out=ROOT/"research"/"games"
 for c,v in CFG.items():
  title,axis,primary,secondary,failures,actions,sil=v;p,m=load(c);h=hashlib.sha256(p.read_bytes()).hexdigest();rel=p.relative_to(ROOT).as_posix();levels=[x["name"] for x in m.LEVELS]
  meta={"schema_version":1,"game_id":c,"version":"v1","internal_title":title,"public_title":None,"author_partition":"gpt","authorship":{"model_family":"OpenAI GPT-5","model_snapshot":"current Codex task model; exact deployment id not exposed to task","session_id":SESSION,"created_at":"2026-08-30T00:00:00Z","source_lineage":[f"research/gpt-ideas-v1.tsv:{c}"],"source_commit":None},"mechanics":{"primary":primary,"secondary":secondary,"novelty_claim":levels[-1],"closest_prior_art":["research/coverage-gap-study-v1.md","research/flash-game-mechanics-survey.md"]},"failure_modes":failures,"interface":{"actions":actions,"observation":"64x64x16","deterministic":True,"seeded_stochasticity":False},"progression":[{"level":i+1,"role":["orient","discriminate","plan","compose","inhibit","synthesize"][i],"new_demand":name,"composes":list(range(1,i+1))} for i,name in enumerate(levels)],"visual_identity":{"dominant_palette":[],"silhouette_grammar":sil,"spatial_grammar":sil,"motion_grammar":primary.replace("-"," "),"hud_grammar":"Persistent color-coded state markers expose the relevant latent variable.","nearest_visual_games":[]},"evaluation":{"allowed_development_models":["deterministic-solvers","random-fuzzer","Qwen3.8 diagnostic only"],"held_out_evaluator":"anthropic","human_baseline_status":"not_started","held_out_status":"sealed"},"artifacts":{"source":rel,"metadata":f"research/games/{c}-v1.json","win_recording":f"research/recordings/{c}-v1-win.json","loss_recording":f"research/recordings/{c}-v1-loss.json","thumbnail":f"docs/static/img/games/{c}-v1.png","source_sha256":h},"status":"prototype"}
  (out/f"{c}-v1.json").write_text(json.dumps(meta,indent=2)+"\n");g=getattr(m,c.upper())();a=g.perform_action(ActionInput(id=GameAction.RESET),raw=True).frame[-1];im=Image.new("RGB",(64,64));im.putdata([PAL[int(x)] for row in a for x in row]);tp=ROOT/"docs"/"static"/"img"/"games"/f"{c}-v1.png";im.save(tp,optimize=True);games.append({"game_id":c,"title":title,"axis":axis,"levels":6,"source_sha256":h})
 path=ROOT/"research"/"gpt-batch06-v1.json";path.write_text(json.dumps({"schema_version":1,"batch_id":"gpt-batch06-v1","created_at":"2026-08-30T00:00:00Z","design":"Ten third-pass games across the second ten research axes, each with six progressive levels and a distinct colorful environment.","games":games},indent=2)+"\n")
 sheet=Image.new("RGB",(800,352),(242,242,246));d=ImageDraw.Draw(sheet)
 for i,c in enumerate(CFG):im=Image.open(ROOT/"docs"/"static"/"img"/"games"/f"{c}-v1.png").resize((128,128),Image.Resampling.NEAREST);x,y=(i%5)*160+16,(i//5)*176+12;sheet.paste(im,(x,y));d.text((x,y+136),c,fill=(28,28,36))
 sheet.save(ROOT/".cache"/"batch06-contact.png",optimize=True);print("10 metadata records",path)
if __name__=="__main__":main()
