"""Generate metadata, thumbnails, and a contact sheet for research Batch 82."""
import hashlib,importlib.util,json
from PIL import Image,ImageDraw
from arcengine import ActionInput,GameAction
from build_research_batch06_metadata import ROOT,SESSION,PAL
CFG={
"a011":("Fuse Surgeon","repair-and-maintenance-planning","two-cuts-and-one-alternate-bridge-must-contain-an-overload-without-starving-the-goal-district","A pale circuit district places seven junctions around cut, bridge, overload, and service state."),
"a012":("Maintenance Window","repair-and-maintenance-planning","preventive-service-is-scheduled-across-mutually-exclusive-rotor-windows-before-wear-deadlines","A blue factory stacks three rotating machines above service history and a phase window."),
"a013":("Cannibal Workshop","repair-and-maintenance-planning","one-device-is-sacrificed-and-interface-compatible-modules-are-redistributed-to-complete-a-required-subset","A slate workshop presents four socketed devices over a scarce module inventory."),
"a014":("Sealant Trail","repair-and-maintenance-planning","wet-repair-geometry-changes-drone-navigability-while-curing-reopens-pressure-zones","A lilac pressure chamber arranges twelve floor cells above sealant and reactivation state."),
"a015":("Calibration Crew","repair-and-maintenance-planning","two-machines-cross-measure-and-alternate-adjustments-under-a-one-turn-safe-range-tolerance","A green calibration lab pairs two dial machines above cross-measurements and tolerance debt."),
"a016":("Graceful Degradation","repair-and-maintenance-planning","power-is-rerouted-and-optional-functions-dropped-to-preserve-steering-and-braking-under-progressive-failure","A teal vehicle bay arrays five modules above damage history and travel distance."),
"a017":("Bent Compass","sensorimotor-calibration","action-outcome-pairs-reveal-a-fixed-reflection-and-rotation-before-hazard-field-navigation","A rose calibration field embeds a safe pad inside a consumable hazard grid."),
"a018":("Reversed Joint","sensorimotor-calibration","separate-reversed-joint-and-zero-offset-mappings-compose-into-an-end-effector-model","A cream manipulation cell shows a two-link arm beside narrow target sockets."),
"a019":("Sticky Controls","sensorimotor-calibration","commands-have-hysteretic-persistence-and-opposites-must-brake-early-around-moving-obstacles","A peach practice lane shows one rider, a moving obstacle, and persistence traces."),
"a020":("Mixed Axes","sensorimotor-calibration","horizontal-and-vertical-controls-factor-independently-across-colored-region-boundaries","A gold floor divides an eight-cell grid into differently remapped rolling regions.")}
def load(c):
 p=ROOT/"docs"/"static"/"games"/"src"/f"{c}-v1"/f"{c}.py";s=importlib.util.spec_from_file_location(c,p);m=importlib.util.module_from_spec(s);s.loader.exec_module(m);return p,m
def main():
 games=[];out=ROOT/"research"/"games";out.mkdir(parents=True,exist_ok=True)
 for c,(title,axis,primary,silhouette) in CFG.items():
  p,m=load(c);h=hashlib.sha256(p.read_bytes()).hexdigest();rel=p.relative_to(ROOT).as_posix();names=[x["name"] for x in m.LEVELS];g=getattr(m,c.upper())();frame=g.perform_action(ActionInput(id=GameAction.RESET),raw=True).frame[-1];palette=sorted({int(v) for row in frame for v in row})
  meta={"schema_version":1,"game_id":c,"version":"v1","internal_title":title,"public_title":None,"author_partition":"gpt","authorship":{"model_family":"OpenAI GPT-5","model_snapshot":"current Codex task model; exact deployment id not exposed to task","session_id":SESSION,"created_at":"2026-08-31T00:00:00Z","source_lineage":[f"research/anthropic-build-ideas-v1.tsv:{c}"],"concept_lineage":"gpt-seeded-anthropic-build","intended_builder":"anthropic","implementation_author_partition":"gpt","source_commit":None},"mechanics":{"primary":primary,"secondary":[axis,"safe-maintenance-and-sensorimotor-calibration"],"novelty_claim":names[-1],"closest_prior_art":["research/anthropic-build-ideas-v1.audit.json","research/coverage-gap-study-v1.md","research/flash-game-mechanics-survey.md"]},"failure_modes":["optimizes an immediate repair while destroying service continuity, future access, donor utility, or core capability","treats coupled calibration, wear windows, degradation, persistence, joint mappings, or regional axes as independent memoryless controls","copies screen-relative motion instead of learning the stable action-outcome transform"],"interface":{"actions":[1,2,3,4,5,6],"observation":"64x64x16","deterministic":True,"seeded_stochasticity":False},"progression":[{"level":i+1,"role":["orient","discriminate","plan","compose","inhibit","synthesize"][i],"new_demand":n,"composes":list(range(1,i+1))} for i,n in enumerate(names)],"visual_identity":{"dominant_palette":palette,"silhouette_grammar":silhouette,"spatial_grammar":silhouette,"motion_grammar":primary.replace("-"," "),"hud_grammar":"Circuit cuts, service windows, module sockets, wet trails, coupled dials, vehicle cores, calibration pads, arm joints, sticky traces, and region boundaries expose state without text.","nearest_visual_games":[]},"evaluation":{"allowed_development_models":["deterministic-solvers","random-fuzzer","Qwen3.8 diagnostic only"],"held_out_evaluator":"anthropic","human_baseline_status":"not_started","held_out_status":"sealed"},"artifacts":{"source":rel,"metadata":f"research/games/{c}-v1.json","win_recording":f"research/recordings/{c}-v1-win.json","loss_recording":f"research/recordings/{c}-v1-loss.json","thumbnail":f"docs/static/img/games/{c}-v1.png","source_sha256":h},"status":"prototype"}
  (out/f"{c}-v1.json").write_text(json.dumps(meta,indent=2)+"\n");im=Image.new("RGB",(64,64));im.putdata([PAL[int(v)] for row in frame for v in row]);im.save(ROOT/"docs"/"static"/"img"/"games"/f"{c}-v1.png",optimize=True);games.append({"game_id":c,"title":title,"axis":axis,"levels":6,"source_sha256":h})
 path=ROOT/"research"/"gpt-batch82-v1.json";path.write_text(json.dumps({"schema_version":1,"batch_id":"gpt-batch82-v1","created_at":"2026-08-31T00:00:00Z","provenance":"Concepts retain gpt-seeded-anthropic-build queue lineage; implementations in this batch are authored by OpenAI GPT-5 and are not attributed to Anthropic.","design":"Ten colorful systems compose safe repair order, preventive deadlines, sacrificial reconfiguration, path-dependent sealant, coupled calibration, graceful degradation, reflected controls, articulated body schema, hysteresis, and region-factored axes.","games":games},indent=2)+"\n")
 sheet=Image.new("RGB",(800,352),(242,242,246));d=ImageDraw.Draw(sheet)
 for i,c in enumerate(CFG):
  im=Image.open(ROOT/"docs"/"static"/"img"/"games"/f"{c}-v1.png").resize((128,128),Image.Resampling.NEAREST);x,y=(i%5)*160+16,(i//5)*176+12;sheet.paste(im,(x,y));d.text((x,y+136),c,fill=(28,28,36))
 (ROOT/".cache").mkdir(exist_ok=True);sheet.save(ROOT/".cache"/"batch82-contact.png",optimize=True);print("10 metadata records",path)
if __name__=="__main__":main()
