"""Generate metadata and visual artifacts for research Batch 13."""
import hashlib,importlib.util,json
from PIL import Image,ImageDraw
from arcengine import ActionInput,GameAction
from build_research_batch06_metadata import ROOT,SESSION,PAL
CFG={
"q009":("Peripheral Current","observer-dependent-dynamics","focus-radius-freezes-local-flow",["attention-boundary-control","phase-alignment"],["freezes the periphery","forgets radius changes","moves focus after pulsing"],[1,2,3,5,6],"Blue current columns flow outside a violet focus radius on an orange frame."),
"q018":("Exchange Circle","social-inference","partial-order-mutual-trade-cycle",["preference-probing","permutation-planning"],["optimizes one agent only","duplicates a bundle","confuses acceptance with mutual completion"],[1,2,3,4,5,6],"Orange agents evaluate colored bundles in a pale circular exchange hall."),
"q028":("Causal Quilt","causal-intervention","sparse-probe-law-boundaries",["region-segmentation","probe-allocation"],["marks color changes without probing","spends two probes in one region","misses a one-patch law"],[1,2,3,4,6],"Hidden quilt patches reveal blue, orange, or green causal laws beside pink seams."),
"q038":("Balance Web","conservation-law-induction","capacity-limited-network-load",["total-conservation","bottleneck-routing"],["creates load","overfills a node","moves along the shortest but blocked edge"],[1,3,4,5,6],"Orange loads redistribute among cyan nodes over a bright capacity web."),
"q048":("Reveal Paint","epistemic-resource-allocation","permanent-spatial-evidence-paint",["boundary-revelation","minimal-query-set"],["paints adjacent redundant cells","uses paint as a marker rather than evidence","claims a non-unique shape"],[1,2,3,4,5,6],"Violet paint permanently exposes green or red cells inside a pale wall."),
"q058":("Antenna","tool-construction","frequency-tuned-oriented-span",["conductive-geometry","source-selection"],["matches length but not orientation","tests an incomplete antenna","tunes to the wrong pulse"],[1,2,3,4,5,6],"Orange and blue conductive bars tune a green antenna against violet sky pulses."),
"q068":("Blind Captain","distributed-partial-observability","limited-observer-pulse-navigation",["signal-budget","instrument-memory"],["asks for every step","steers from terrain without a report","forgets repeated headings"],[1,2,3,4,5],"A green observer sends scarce orange instrument pulses to a blue captain."),
"q078":("Rotating Contract","nonstationary-rule-revision","arrangement-signaled-policy-cycle",["policy-inversion","phase-forecasting"],["uses one response map","reads command without arrangement","updates policy one turn late"],[1,2,3,4],"Cyan agents rotate height arrangements that remap orange commands on a pale plaza."),
"q088":("Mask Debt","persistent-identity","transferable-mask-identity-bound-debt",["obligation-memory","affordance-transfer"],["passes debt with the mask","repays the current wearer only","uses a mask on the wrong task"],[1,2,3,4,5,6],"Blue and orange identities pass a violet mask while red debt remains attached."),
"q098":("Rescue Order","hierarchical-goal-discovery","rescue-unlocks-action-dependency",["prerequisite-order","capability-unlocking"],["rescues the nearest agent first","treats goals as independent","misses converging prerequisites"],[3,4,5,6],"Orange captives become green capability nodes across a charcoal cave graph.")}
def load(c):
 p=ROOT/"docs"/"static"/"games"/"src"/f"{c}-v1"/f"{c}.py";s=importlib.util.spec_from_file_location(c,p);m=importlib.util.module_from_spec(s);s.loader.exec_module(m);return p,m
def main():
 games=[];out=ROOT/"research"/"games"
 for c,v in CFG.items():
  title,axis,primary,secondary,failures,actions,sil=v;p,m=load(c);h=hashlib.sha256(p.read_bytes()).hexdigest();rel=p.relative_to(ROOT).as_posix();names=[x["name"] for x in m.LEVELS]
  meta={"schema_version":1,"game_id":c,"version":"v1","internal_title":title,"public_title":None,"author_partition":"gpt","authorship":{"model_family":"OpenAI GPT-5","model_snapshot":"current Codex task model; exact deployment id not exposed to task","session_id":SESSION,"created_at":"2026-08-30T00:00:00Z","source_lineage":[f"research/gpt-ideas-v2.tsv:{c}"],"source_commit":None},"mechanics":{"primary":primary,"secondary":secondary,"novelty_claim":names[-1],"closest_prior_art":["research/coverage-gap-study-v1.md","research/flash-game-mechanics-survey.md"]},"failure_modes":failures,"interface":{"actions":actions,"observation":"64x64x16","deterministic":True,"seeded_stochasticity":False},"progression":[{"level":i+1,"role":["orient","discriminate","plan","compose","inhibit","synthesize"][i],"new_demand":n,"composes":list(range(1,i+1))} for i,n in enumerate(names)],"visual_identity":{"dominant_palette":[],"silhouette_grammar":sil,"spatial_grammar":sil,"motion_grammar":primary.replace("-"," "),"hud_grammar":"Persistent colored state markers expose the mechanic without text.","nearest_visual_games":[]},"evaluation":{"allowed_development_models":["deterministic-solvers","random-fuzzer","Qwen3.8 diagnostic only"],"held_out_evaluator":"anthropic","human_baseline_status":"not_started","held_out_status":"sealed"},"artifacts":{"source":rel,"metadata":f"research/games/{c}-v1.json","win_recording":f"research/recordings/{c}-v1-win.json","loss_recording":f"research/recordings/{c}-v1-loss.json","thumbnail":f"docs/static/img/games/{c}-v1.png","source_sha256":h},"status":"prototype"}
  (out/f"{c}-v1.json").write_text(json.dumps(meta,indent=2)+"\n");g=getattr(m,c.upper())();a=g.perform_action(ActionInput(id=GameAction.RESET),raw=True).frame[-1];im=Image.new("RGB",(64,64));im.putdata([PAL[int(x)] for row in a for x in row]);im.save(ROOT/"docs"/"static"/"img"/"games"/f"{c}-v1.png",optimize=True);games.append({"game_id":c,"title":title,"axis":axis,"levels":6,"source_sha256":h})
 path=ROOT/"research"/"gpt-batch13-v1.json";path.write_text(json.dumps({"schema_version":1,"batch_id":"gpt-batch13-v1","created_at":"2026-08-30T00:00:00Z","design":"Ten eighth-pass games across the first ten research axes, each with six progressive levels and a distinct colorful environment.","games":games},indent=2)+"\n")
 sheet=Image.new("RGB",(800,352),(242,242,246));d=ImageDraw.Draw(sheet)
 for i,c in enumerate(CFG):im=Image.open(ROOT/"docs"/"static"/"img"/"games"/f"{c}-v1.png").resize((128,128),Image.Resampling.NEAREST);x,y=(i%5)*160+16,(i//5)*176+12;sheet.paste(im,(x,y));d.text((x,y+136),c,fill=(28,28,36))
 sheet.save(ROOT/".cache"/"batch13-contact.png",optimize=True);print("10 metadata records",path)
if __name__=="__main__":main()
