"""Generate metadata and visual artifacts for research Batch 12."""
import hashlib,importlib.util,json
from PIL import Image,ImageDraw
from arcengine import ActionInput,GameAction
from build_research_batch06_metadata import ROOT,SESSION,PAL
CFG={
"q008":("Veiled Orchestra","observer-dependent-dynamics","occlusion-gated-phase-advance",["phase-alignment","selective-observation"],["pulses every mechanism","leaves advanced sections veiled","matches visible pixels instead of phase"],[1,2,3,5,6],"Colored mechanisms hold while visible and advance behind violet veils on shared pulses."),
"q017":("Mimic or Seeker","social-inference","imitation-versus-goal-motion",["behavioral-probe","latent-destination"],["classifies one motion without probing","confuses copied direction with destination","selects appearance rather than policy"],[1,2,3,4,5,6],"Ochre agents reveal either copied probes or blue goal-directed responses on an ivory field."),
"q027":("Proxy Lever","causal-intervention","slot-bound-causal-role",["identity-role-separation","object-rotation"],["tracks the first affected object","assumes causality follows color","pulls before positioning the target proxy"],[1,2,5,6],"Colored objects rotate through gray causal seats while a coral lever exposes the active proxy."),
"q037":("Hole Count","conservation-law-induction","topological-hole-invariant",["shape-transformation","topology-over-area"],["matches silhouette","counts colored pixels","forgets sealed holes change topology"],[1,2,3,4,6],"Deforming coral masses retain dark connected holes against a cream canvas."),
"q047":("Sensor Auction","epistemic-resource-allocation","costed-feature-discrimination",["minimal-evidence-set","budgeted-identification"],["buys every sensor","chooses cheap but redundant evidence","claims before the candidate is unique"],[1,2,3,4,5,6],"Distinct sensor stalls expose colored binary outcomes while a green budget bar shrinks."),
"q057":("Raft Shape","tool-construction","buoyant-footprint-construction",["cargo-support","channel-geometry"],["builds disconnected tiles","ignores footprint width","supports cargo with the wrong geometry"],[1,2,3,4,5,6],"Orange buoyant tiles form cargo-bearing silhouettes across bright blue water."),
"q067":("Map Fragments","distributed-partial-observability","rotated-fragment-registration",["overlap-alignment","global-coordinate-frame"],["keeps local north fixed","aligns one landmark only","rotates the global frame with each fragment"],[1,2,3,4,6],"Pink map cards rotate cyan landmarks above a shared golden overlap seam."),
"q077":("Aging Tools","nonstationary-rule-revision","use-count-dependent-affordance",["wear-state","future-effect-planning"],["assumes constant tool effect","uses the strongest tool first","ignores the next wear threshold"],[1,2,6],"Two colored tools accumulate visible wear while changing a modular workpiece state."),
"q087":("Body Exchange","persistent-identity","identity-bound-goals-swappable-capabilities",["capability-transfer","destination-memory"],["sends bodies to their old goals","forgets which identity is selected","swaps before finishing capability-specific motion"],[1,2,3,4,5,6],"Two colored identities ride exchangeable bodies toward separate destinations on a mint track."),
"q097":("Factory Plan","hierarchical-goal-discovery","unlabeled-production-dependency-graph",["intermediate-scheduling","shared-subassembly"],["runs unavailable machines","consumes a shared part too early","confuses machine position with output type"],[3,4,5,6],"Dark machines transform colored stock through increasingly deep dependency chains.")}
def load(c):
 p=ROOT/"docs"/"static"/"games"/"src"/f"{c}-v1"/f"{c}.py";s=importlib.util.spec_from_file_location(c,p);m=importlib.util.module_from_spec(s);s.loader.exec_module(m);return p,m
def main():
 games=[];out=ROOT/"research"/"games"
 for c,v in CFG.items():
  title,axis,primary,secondary,failures,actions,sil=v;p,m=load(c);h=hashlib.sha256(p.read_bytes()).hexdigest();rel=p.relative_to(ROOT).as_posix();names=[x["name"] for x in m.LEVELS]
  meta={"schema_version":1,"game_id":c,"version":"v1","internal_title":title,"public_title":None,"author_partition":"gpt","authorship":{"model_family":"OpenAI GPT-5","model_snapshot":"current Codex task model; exact deployment id not exposed to task","session_id":SESSION,"created_at":"2026-08-30T00:00:00Z","source_lineage":[f"research/gpt-ideas-v2.tsv:{c}"],"source_commit":None},"mechanics":{"primary":primary,"secondary":secondary,"novelty_claim":names[-1],"closest_prior_art":["research/coverage-gap-study-v1.md","research/flash-game-mechanics-survey.md"]},"failure_modes":failures,"interface":{"actions":actions,"observation":"64x64x16","deterministic":True,"seeded_stochasticity":False},"progression":[{"level":i+1,"role":["orient","discriminate","plan","compose","inhibit","synthesize"][i],"new_demand":n,"composes":list(range(1,i+1))} for i,n in enumerate(names)],"visual_identity":{"dominant_palette":[],"silhouette_grammar":sil,"spatial_grammar":sil,"motion_grammar":primary.replace("-"," "),"hud_grammar":"Persistent colored state markers expose the mechanic without text.","nearest_visual_games":[]},"evaluation":{"allowed_development_models":["deterministic-solvers","random-fuzzer","Qwen3.8 diagnostic only"],"held_out_evaluator":"anthropic","human_baseline_status":"not_started","held_out_status":"sealed"},"artifacts":{"source":rel,"metadata":f"research/games/{c}-v1.json","win_recording":f"research/recordings/{c}-v1-win.json","loss_recording":f"research/recordings/{c}-v1-loss.json","thumbnail":f"docs/static/img/games/{c}-v1.png","source_sha256":h},"status":"prototype"}
  (out/f"{c}-v1.json").write_text(json.dumps(meta,indent=2)+"\n");g=getattr(m,c.upper())();a=g.perform_action(ActionInput(id=GameAction.RESET),raw=True).frame[-1];im=Image.new("RGB",(64,64));im.putdata([PAL[int(x)] for row in a for x in row]);im.save(ROOT/"docs"/"static"/"img"/"games"/f"{c}-v1.png",optimize=True);games.append({"game_id":c,"title":title,"axis":axis,"levels":6,"source_sha256":h})
 path=ROOT/"research"/"gpt-batch12-v1.json";path.write_text(json.dumps({"schema_version":1,"batch_id":"gpt-batch12-v1","created_at":"2026-08-30T00:00:00Z","design":"Ten seventh-pass games across the first ten research axes, each with six progressive levels and a distinct colorful environment.","games":games},indent=2)+"\n")
 sheet=Image.new("RGB",(800,352),(242,242,246));d=ImageDraw.Draw(sheet)
 for i,c in enumerate(CFG):im=Image.open(ROOT/"docs"/"static"/"img"/"games"/f"{c}-v1.png").resize((128,128),Image.Resampling.NEAREST);x,y=(i%5)*160+16,(i//5)*176+12;sheet.paste(im,(x,y));d.text((x,y+136),c,fill=(28,28,36))
 sheet.save(ROOT/".cache"/"batch12-contact.png",optimize=True);print("10 metadata records",path)
if __name__=="__main__":main()
