"""Generate metadata, thumbnails, and a contact sheet for research Batch 96."""
import hashlib,importlib.util,json
from PIL import Image,ImageDraw
from arcengine import ActionInput,GameAction
from build_research_batch06_metadata import ROOT,SESSION,PAL
CFG={
"a151":("Delayed Agency","agency-and-causal-attribution","tagged-temporal-credit-across-device-delays","A steel timing laboratory aligns colored command tags, three heterogeneous queues, device effects, clock, and attribution matches."),
"a152":("Body Boundary","agency-and-causal-attribution","intervention-defined-embodiment","A green chamber surrounds a controllable core with limbs, tools, passengers, followers, probed joints, and a narrow gate."),
"a153":("Family Resemblance","concept-boundary-and-category-induction","overlapping-prototype-feature-classification","A coral sorting gallery arrays six multi-feature objects, prototype phase, routes, shared-feature score, and tempting exceptions."),
"a154":("Rule Boundary","concept-boundary-and-category-induction","active-oblique-decision-boundary-learning","A black scatter plot combines continuous spatial features, labeled examples, movable query, oblique separator, budget, and error."),
"a155":("Exception Ladder","concept-boundary-and-category-induction","specificity-ordered-hierarchical-exceptions","A gold rule ledger classifies six objects under a visible base, exception, and exception-to-exception ladder."),
"a156":("Prototype Drift","concept-boundary-and-category-induction","locally-evolving-online-prototype","A navy feature gallery plots candidate objects, moving category prototype, accepted path, stale examples, and current error."),
"a157":("Disjunctive Class","concept-boundary-and-category-induction","nonconvex-two-cluster-relational-category","A brown feature field separates two distant positive clusters from central negatives while relational membership changes."),
"a158":("Relational Category","concept-boundary-and-category-induction","context-dependent-local-minimum-membership","A cyan grouping table moves differently sized objects across a divider so smallest-in-group membership changes in place."),
"a159":("Negative Space Class","concept-boundary-and-category-induction","rotation-invariant-enclosed-hole-equivalence","A violet pairing studio presents dissimilar solids whose colored enclosed holes, not foreground contours, define equivalence."),
"a160":("Cross-Modal Category","concept-boundary-and-category-induction","motion-to-static-relational-structure-transfer","A red transfer theater switches between motion and static encodings of the same six-node relation categories."),
}
def load(c):
 p=ROOT/"docs"/"static"/"games"/"src"/f"{c}-v1"/f"{c}.py";s=importlib.util.spec_from_file_location(c,p);m=importlib.util.module_from_spec(s);s.loader.exec_module(m);return p,m
def main():
 games=[];out=ROOT/"research"/"games";out.mkdir(parents=True,exist_ok=True)
 for c,(title,axis,primary,silhouette) in CFG.items():
  p,m=load(c);h=hashlib.sha256(p.read_bytes()).hexdigest();rel=p.relative_to(ROOT).as_posix();names=[x["name"] for x in m.LEVELS];g=getattr(m,c.upper())();frame=g.perform_action(ActionInput(id=GameAction.RESET),raw=True).frame[-1];palette=sorted({int(v) for row in frame for v in row})
  meta={"schema_version":1,"game_id":c,"version":"v1","internal_title":title,"public_title":None,"author_partition":"gpt","authorship":{"model_family":"OpenAI GPT-5","model_snapshot":"current Codex task model; exact deployment id not exposed to task","session_id":SESSION,"created_at":"2026-08-31T00:00:00Z","source_lineage":[f"research/anthropic-build-ideas-v1.tsv:{c}"],"concept_lineage":"gpt-seeded-anthropic-build","intended_builder":"anthropic","implementation_author_partition":"gpt","source_commit":None},"mechanics":{"primary":primary,"secondary":[axis,"counterexample-resistant-category-updating"],"novelty_claim":names[-1],"closest_prior_art":["research/anthropic-build-ideas-v1.audit.json","research/coverage-gap-study-v1.md","research/flash-game-mechanics-survey.md"]},"failure_modes":["assigns a tagged command to the nearest effect or equates contiguous co-motion with body membership","searches for one necessary feature or one axis-aligned threshold despite prototype, oblique, hierarchical, or drifting evidence","forces one intrinsic foreground category despite disjunction, context dependence, negative space, or representation transfer"],"interface":{"actions":[1,2,3,4,5,6],"observation":"64x64x16","deterministic":True,"seeded_stochasticity":False},"progression":[{"level":i+1,"role":["orient","discriminate","plan","compose","inhibit","synthesize"][i],"new_demand":n,"composes":list(range(1,i+1))} for i,n in enumerate(names)],"visual_identity":{"dominant_palette":palette,"silhouette_grammar":silhouette,"spatial_grammar":silhouette,"motion_grammar":primary.replace("-"," "),"hud_grammar":"Delay queues, body probes, prototype overlap, oblique queries, exception depth, drift, disjunction, context minima, holes, and modality transfer expose concept boundaries without text.","nearest_visual_games":[]},"evaluation":{"allowed_development_models":["deterministic-solvers","random-fuzzer","Qwen3.8 diagnostic only"],"held_out_evaluator":"anthropic","human_baseline_status":"not_started","held_out_status":"sealed"},"artifacts":{"source":rel,"metadata":f"research/games/{c}-v1.json","win_recording":f"research/recordings/{c}-v1-win.json","loss_recording":f"research/recordings/{c}-v1-loss.json","thumbnail":f"docs/static/img/games/{c}-v1.png","source_sha256":h},"status":"prototype"}
  (out/f"{c}-v1.json").write_text(json.dumps(meta,indent=2)+"\n");im=Image.new("RGB",(64,64));im.putdata([PAL[int(v)] for row in frame for v in row]);im.save(ROOT/"docs"/"static"/"img"/"games"/f"{c}-v1.png",optimize=True);games.append({"game_id":c,"title":title,"axis":axis,"levels":6,"source_sha256":h})
 path=ROOT/"research"/"gpt-batch96-v1.json";path.write_text(json.dumps({"schema_version":1,"batch_id":"gpt-batch96-v1","created_at":"2026-08-31T00:00:00Z","provenance":"Concepts retain gpt-seeded-anthropic-build queue lineage; implementations in this batch are authored by OpenAI GPT-5 and are not attributed to Anthropic.","design":"Two agency worlds require temporal attribution and intervention-defined embodiment; eight category galleries defeat single-feature rules with prototypes, oblique boundaries, nested exceptions, drift, disjunction, context, negative space, and cross-modal structure.","games":games},indent=2)+"\n")
 sheet=Image.new("RGB",(800,352),(242,242,246));d=ImageDraw.Draw(sheet)
 for i,c in enumerate(CFG):
  im=Image.open(ROOT/"docs"/"static"/"img"/"games"/f"{c}-v1.png").resize((128,128),Image.Resampling.NEAREST);x,y=(i%5)*160+16,(i//5)*176+12;sheet.paste(im,(x,y));d.text((x,y+136),c,fill=(28,28,36))
 (ROOT/".cache").mkdir(exist_ok=True);sheet.save(ROOT/".cache"/"batch96-contact.png",optimize=True);print("10 metadata records",path)
if __name__=="__main__":main()
