"""Generate metadata, thumbnails, and a contact sheet for research Batch 90."""
import hashlib,importlib.util,json
from PIL import Image,ImageDraw
from arcengine import ActionInput,GameAction
from build_research_batch06_metadata import ROOT,SESSION,PAL
CFG={
"a091":("Pinched Tube","deformable-material-reasoning","two-way-fluid-and-tube-geometry-coupling","A violet fluid laboratory divides a bulging tube into clampable segments above two receivers and pressure."),
"a092":("Crease Memory","deformable-material-reasoning","plastic-hinge-formation-through-repeated-folds","A gold folding studio overlays a sheet grid with crease strength, selected line, shape, and autonomous sequence."),
"a093":("Viscous Block","deformable-material-reasoning","rate-dependent-impulse-versus-flow-control","A mint obstacle course carries cargo on a blob whose width and height respond differently to pushes and waits."),
"a094":("Elastic Net","deformable-material-reasoning","distributed-node-motion-and-tension-limits","A pale capture arena stretches a six-node net around a pocket, falling object, and global tension meter."),
"a095":("Plastic Trail","deformable-material-reasoning","elastic-recovery-below-a-yield-threshold","A coral roadway profiles eight deformable segments beneath selectable rollers, retained dents, and ramp evidence."),
"a096":("Shape Recovery","deformable-material-reasoning","stored-strain-actuation-under-release-order","A teal recovery chamber lines three pinned compressed shapes against constraints, sockets, strain, and jams."),
"a097":("Standing Room","wave-boundary-and-superposition","boundary-tuned-standing-wave-placement","A warm resonance room places movable walls around nodes, antinodes, receivers, fragile sites, and pulse history."),
"a098":("Boundary Echo","wave-boundary-and-superposition","phase-diagnosis-from-material-dependent-reflections","A blue echo vault arrays hidden wall materials between a probe, return ledger, cancellation, and reinforcement branches."),
"a099":("Phase Cancel","wave-boundary-and-superposition","simultaneous-destructive-and-constructive-interference","A lilac wave field opposes two phase-controlled sources across bridge and gate amplitude gauges."),
"a100":("Waveguide Switch","wave-boundary-and-superposition","transverse-mode-conversion-through-rotated-guides","A rose guide chamber segments one wide channel into rotatable mode sections before two selective branches."),
}
def load(c):
 p=ROOT/"docs"/"static"/"games"/"src"/f"{c}-v1"/f"{c}.py";s=importlib.util.spec_from_file_location(c,p);m=importlib.util.module_from_spec(s);s.loader.exec_module(m);return p,m
def main():
 games=[];out=ROOT/"research"/"games";out.mkdir(parents=True,exist_ok=True)
 for c,(title,axis,primary,silhouette) in CFG.items():
  p,m=load(c);h=hashlib.sha256(p.read_bytes()).hexdigest();rel=p.relative_to(ROOT).as_posix();names=[x["name"] for x in m.LEVELS];g=getattr(m,c.upper())();frame=g.perform_action(ActionInput(id=GameAction.RESET),raw=True).frame[-1];palette=sorted({int(v) for row in frame for v in row})
  meta={"schema_version":1,"game_id":c,"version":"v1","internal_title":title,"public_title":None,"author_partition":"gpt","authorship":{"model_family":"OpenAI GPT-5","model_snapshot":"current Codex task model; exact deployment id not exposed to task","session_id":SESSION,"created_at":"2026-08-31T00:00:00Z","source_lineage":[f"research/anthropic-build-ideas-v1.tsv:{c}"],"concept_lineage":"gpt-seeded-anthropic-build","intended_builder":"anthropic","implementation_author_partition":"gpt","source_commit":None},"mechanics":{"primary":primary,"secondary":[axis,"distributed-material-and-phase-state"],"novelty_claim":names[-1],"closest_prior_art":["research/anthropic-build-ideas-v1.audit.json","research/coverage-gap-study-v1.md","research/flash-game-mechanics-survey.md"]},"failure_modes":["treats clamps, folds, pushes, net nodes, road loads, or pin releases as static local actions without material feedback","forgets rate dependence, distributed tension, plastic yield, stored strain, or release order","routes a single ray or pipe while ignoring standing-wave boundary conditions, phase inversion, interference, or transverse mode"],"interface":{"actions":[1,2,3,4,5,6],"observation":"64x64x16","deterministic":True,"seeded_stochasticity":False},"progression":[{"level":i+1,"role":["orient","discriminate","plan","compose","inhibit","synthesize"][i],"new_demand":n,"composes":list(range(1,i+1))} for i,n in enumerate(names)],"visual_identity":{"dominant_palette":palette,"silhouette_grammar":silhouette,"spatial_grammar":silhouette,"motion_grammar":primary.replace("-"," "),"hud_grammar":"Tube width, crease strength, blob aspect, net tension, yield dents, stored strain, nodes, echoes, site amplitudes, and guide modes expose distributed state without text.","nearest_visual_games":[]},"evaluation":{"allowed_development_models":["deterministic-solvers","random-fuzzer","Qwen3.8 diagnostic only"],"held_out_evaluator":"anthropic","human_baseline_status":"not_started","held_out_status":"sealed"},"artifacts":{"source":rel,"metadata":f"research/games/{c}-v1.json","win_recording":f"research/recordings/{c}-v1-win.json","loss_recording":f"research/recordings/{c}-v1-loss.json","thumbnail":f"docs/static/img/games/{c}-v1.png","source_sha256":h},"status":"prototype"}
  (out/f"{c}-v1.json").write_text(json.dumps(meta,indent=2)+"\n");im=Image.new("RGB",(64,64));im.putdata([PAL[int(v)] for row in frame for v in row]);im.save(ROOT/"docs"/"static"/"img"/"games"/f"{c}-v1.png",optimize=True);games.append({"game_id":c,"title":title,"axis":axis,"levels":6,"source_sha256":h})
 path=ROOT/"research"/"gpt-batch90-v1.json";path.write_text(json.dumps({"schema_version":1,"batch_id":"gpt-batch90-v1","created_at":"2026-08-31T00:00:00Z","provenance":"Concepts retain gpt-seeded-anthropic-build queue lineage; implementations in this batch are authored by OpenAI GPT-5 and are not attributed to Anthropic.","design":"Six colorful deformable-material systems require fluid coupling, plastic memory, rate dependence, distributed tension, yield, and stored-strain release; four wave chambers add boundary tuning, echo phase, interference, and mode conversion.","games":games},indent=2)+"\n")
 sheet=Image.new("RGB",(800,352),(242,242,246));d=ImageDraw.Draw(sheet)
 for i,c in enumerate(CFG):
  im=Image.open(ROOT/"docs"/"static"/"img"/"games"/f"{c}-v1.png").resize((128,128),Image.Resampling.NEAREST);x,y=(i%5)*160+16,(i//5)*176+12;sheet.paste(im,(x,y));d.text((x,y+136),c,fill=(28,28,36))
 (ROOT/".cache").mkdir(exist_ok=True);sheet.save(ROOT/".cache"/"batch90-contact.png",optimize=True);print("10 metadata records",path)
if __name__=="__main__":main()
