"""Generate metadata, thumbnails, and a contact sheet for research Batch 100."""
import hashlib,importlib.util,json
from PIL import Image,ImageDraw
from arcengine import ActionInput,GameAction
from build_research_batch06_metadata import ROOT,SESSION,PAL
CFG={
"a191":("Interleaved Message","protocol-recovery-and-error-correction","pilot-phased-alternating-stream-demultiplexing","A violet multiplexing scope separates alternating pink and orange pulses into two ownership rails."),
"a192":("Self-Clocking Path","protocol-recovery-and-error-correction","transition-dense-clock-recoverable-route-encoding","An orange signal scope turns spatial bits into vertical levels whose transition ticks recover timing without a shared clock."),
"a193":("Hot Swap","modular-machines-and-reconfiguration","synchronized-live-module-replacement-with-bypass","A pale production line routes colored items between an old module, replacement module, and elevated temporary bypass."),
"a194":("Bus Backplane","modular-machines-and-reconfiguration","collision-free-shared-interface-time-slot-arbitration","A green plug-in rack maps four colored modules onto one horizontal bus and six explicit time slots."),
"a195":("Interface Adapter","modular-machines-and-reconfiguration","multidimensional-port-and-signal-conversion-chain","A yellow workbench chains differently colored geometric adapters between a sensor and actuator."),
"a196":("Module Polarity","modular-machines-and-reconfiguration","orientation-coupled-function-and-interface-validity","A gray circular assembly alternates split-polarity modules around a central transformation core."),
"a197":("Reconfigurable Cell","modular-machines-and-reconfiguration","reusable-homogeneous-multimode-processing-field","A magenta four-by-four substrate programs route, store, transform, and block modes for a sequence of inputs."),
"a198":("Shared Resource","modular-machines-and-reconfiguration","joint-layout-and-mobile-capability-scheduling","A coral workshop places six modules above a track carrying one unique mobile toolhead."),
"a199":("Capability Graph","modular-machines-and-reconfiguration","minimal-opaque-functional-dependency-composition","A dark dependency canvas joins demonstrated capability nodes into a minimal enabled graph toward a changing goal."),
"a200":("Fault-Tolerant Assembly","modular-machines-and-reconfiguration","universally-tested-single-module-failure-tolerance","A cyan factory pairs primary and backup components across five stages before disabling one chosen after construction."),
}
def load(c):
 p=ROOT/"docs"/"static"/"games"/"src"/f"{c}-v1"/f"{c}.py";s=importlib.util.spec_from_file_location(c,p);m=importlib.util.module_from_spec(s);s.loader.exec_module(m);return p,m
def main():
 games=[];out=ROOT/"research"/"games";out.mkdir(parents=True,exist_ok=True)
 for c,(title,axis,primary,silhouette) in CFG.items():
  p,m=load(c);h=hashlib.sha256(p.read_bytes()).hexdigest();rel=p.relative_to(ROOT).as_posix();names=[x["name"] for x in m.LEVELS];g=getattr(m,c.upper())();frame=g.perform_action(ActionInput(id=GameAction.RESET),raw=True).frame[-1];palette=sorted({int(v) for row in frame for v in row})
  meta={"schema_version":1,"game_id":c,"version":"v1","internal_title":title,"public_title":None,"author_partition":"gpt","authorship":{"model_family":"OpenAI GPT-5","model_snapshot":"current Codex task model; exact deployment id not exposed to task","session_id":SESSION,"created_at":"2026-08-31T00:00:00Z","source_lineage":[f"research/anthropic-build-ideas-v1.tsv:{c}"],"concept_lineage":"gpt-seeded-anthropic-build","intended_builder":"anthropic","implementation_author_partition":"gpt","source_commit":None},"mechanics":{"primary":primary,"secondary":[axis,"live-reconfiguration-and-universal-failure-tests"],"novelty_claim":names[-1],"closest_prior_art":["research/anthropic-build-ideas-v1.audit.json","research/coverage-gap-study-v1.md","research/flash-game-mechanics-survey.md"]},"failure_modes":["merges multiplexed streams or preserves content without enough transitions to recover ownership and timing","stops live flow, ignores shared-bus collisions, or matches only one interface dimension during reconfiguration","optimizes orientation, cell programming, layout, capability composition, or redundancy for one visible case instead of the full reusable or adversarial test set"],"interface":{"actions":[1,2,3,4,5,6],"observation":"64x64x16","deterministic":True,"seeded_stochasticity":False},"progression":[{"level":i+1,"role":["orient","discriminate","plan","compose","inhibit","synthesize"][i],"new_demand":n,"composes":list(range(1,i+1))} for i,n in enumerate(names)],"visual_identity":{"dominant_palette":palette,"silhouette_grammar":silhouette,"spatial_grammar":silhouette,"motion_grammar":primary.replace("-"," "),"hud_grammar":"Ownership rails, transition ticks, bypasses, time slots, adapter seams, polarity, cell modes, tool position, reachability, and per-failure robustness expose modular state without text.","nearest_visual_games":[]},"evaluation":{"allowed_development_models":["deterministic-solvers","random-fuzzer","Qwen3.8 diagnostic only"],"held_out_evaluator":"anthropic","human_baseline_status":"not_started","held_out_status":"sealed"},"artifacts":{"source":rel,"metadata":f"research/games/{c}-v1.json","win_recording":f"research/recordings/{c}-v1-win.json","loss_recording":f"research/recordings/{c}-v1-loss.json","thumbnail":f"docs/static/img/games/{c}-v1.png","source_sha256":h},"status":"prototype"}
  (out/f"{c}-v1.json").write_text(json.dumps(meta,indent=2)+"\n");im=Image.new("RGB",(64,64));im.putdata([PAL[int(v)] for row in frame for v in row]);im.save(ROOT/"docs"/"static"/"img"/"games"/f"{c}-v1.png",optimize=True);games.append({"game_id":c,"title":title,"axis":axis,"levels":6,"source_sha256":h})
 path=ROOT/"research"/"gpt-batch100-v1.json";path.write_text(json.dumps({"schema_version":1,"batch_id":"gpt-batch100-v1","created_at":"2026-08-31T00:00:00Z","provenance":"Concepts retain gpt-seeded-anthropic-build queue lineage; implementations in this batch are authored by OpenAI GPT-5 and are not attributed to Anthropic.","design":"Two communication games recover ownership and clock phase; eight modular machines demand live replacement, arbitration, conversion, polarity, reusable programming, shared capability scheduling, minimal dependency composition, and universal single-failure tolerance.","games":games},indent=2)+"\n")
 sheet=Image.new("RGB",(800,352),(242,242,246));d=ImageDraw.Draw(sheet)
 for i,c in enumerate(CFG):
  im=Image.open(ROOT/"docs"/"static"/"img"/"games"/f"{c}-v1.png").resize((128,128),Image.Resampling.NEAREST);x,y=(i%5)*160+16,(i//5)*176+12;sheet.paste(im,(x,y));d.text((x,y+136),c,fill=(28,28,36))
 (ROOT/".cache").mkdir(exist_ok=True);sheet.save(ROOT/".cache"/"batch100-contact.png",optimize=True);print("10 metadata records",path)
if __name__=="__main__":main()
