"""Generate metadata, thumbnails, and the contact sheet for research Batch 49."""
import hashlib,importlib.util,json
from PIL import Image,ImageDraw
from arcengine import ActionInput,GameAction
from build_research_batch06_metadata import ROOT,SESSION,PAL
CFG={
"q224":("Tessera Veil","observer-dependent-dynamics","attention-scheduled-mosaic-macro-with-state-window-interruption","A dark folding mosaic uses three seam wells, offset tesserae, and an interruption rail."),
"q254":("Tessera Pact","social-inference","hidden-offer-convention-coupled-to-topology-macro-interruption","A blue-violet tessera court presents three folded columns above response and phase ribbons."),
"q262":("Tide Probe","causal-intervention","budgeted-current-probes-before-one-irreversible-repair","A cobalt tidal laboratory places three shell instruments beneath a broad current band."),
"q292":("Tide Ledger","conservation-law-induction","conserved-shell-stock-through-reversing-current-and-one-way-seal","A green tidal ledger exposes three shell vaults, stock bars, and a sealing gate."),
"q322":("Tide Survey","epistemic-resource-allocation","bounded-distinct-current-samples-before-irreversible-route-commitment","A red lens basin arranges three tall sounders over evidence and cost ribbons."),
"q352":("Tide Rig","tool-construction","dual-effect-component-assembly-before-irreversible-launch","A gray-blue workshop grows colored part towers into horizontal current-spanning rigs."),
"q382":("Tide Delegation","distributed-partial-observability","alternating-disjoint-controller-marks-before-one-way-handoff","A violet basin divides two shell consoles with persistent marks and a handoff rail."),
"q412":("Tide Revision","nonstationary-rule-revision","wear-revised-current-law-with-delayed-irreversible-repair","A pink-green calibration basin couples three worn shell columns to current and delay rails."),
"q442":("Tide Lineage","persistent-identity","split-merge-appearance-ancestry-before-irreversible-gate","An orange tidal ancestry field traces shell masks above selection and target bars."),
"q506":("Palimpsest Frame","multi-scale-reference-frames","moving-archive-frame-inferred-from-near-miss-failed-examples","A red-violet archive uses three overwritten shelves and paired failed-versus-actual traces.")}
def load(c):
 p=ROOT/"docs"/"static"/"games"/"src"/f"{c}-v1"/f"{c}.py";s=importlib.util.spec_from_file_location(c,p);m=importlib.util.module_from_spec(s);s.loader.exec_module(m);return p,m
def main():
 games=[];out=ROOT/"research"/"games";out.mkdir(parents=True,exist_ok=True)
 for c,(title,axis,primary,silhouette) in CFG.items():
  p,m=load(c);h=hashlib.sha256(p.read_bytes()).hexdigest();rel=p.relative_to(ROOT).as_posix();names=[x["name"] for x in m.LEVELS];g=getattr(m,c.upper())();frame=g.perform_action(ActionInput(id=GameAction.RESET),raw=True).frame[-1];palette=sorted({int(v) for row in frame for v in row})
  meta={"schema_version":1,"game_id":c,"version":"v1","internal_title":title,"public_title":None,"author_partition":"gpt","authorship":{"model_family":"OpenAI GPT-5","model_snapshot":"current Codex task model; exact deployment id not exposed to task","session_id":SESSION,"created_at":"2026-08-30T00:00:00Z","source_lineage":[f"research/gpt-ideas-v2.tsv:{c}"],"source_commit":None},"mechanics":{"primary":primary,"secondary":[axis,"irreversible-commit-and-macro-interruption"],"novelty_claim":names[-1],"closest_prior_art":["research/coverage-gap-study-v1.md","research/flash-game-mechanics-survey.md"]},"failure_modes":["commits before evidence excludes unsafe branches","tracks appearance without conservation, identity, controller, or frame provenance","misses the state-defined macro window or spends the bounded evidence budget redundantly"],"interface":{"actions":[1,2,3,4,5,6],"observation":"64x64x16","deterministic":True,"seeded_stochasticity":False},"progression":[{"level":i+1,"role":["orient","discriminate","plan","compose","inhibit","synthesize"][i],"new_demand":n,"composes":list(range(1,i+1))} for i,n in enumerate(names)],"visual_identity":{"dominant_palette":palette,"silhouette_grammar":silhouette,"spatial_grammar":silhouette,"motion_grammar":primary.replace("-"," "),"hud_grammar":"Colored phase, current, evidence, cost, wear, controller, lineage, and failed-example rails expose state without text.","nearest_visual_games":[]},"evaluation":{"allowed_development_models":["deterministic-solvers","random-fuzzer","Qwen3.8 diagnostic only"],"held_out_evaluator":"anthropic","human_baseline_status":"not_started","held_out_status":"sealed"},"artifacts":{"source":rel,"metadata":f"research/games/{c}-v1.json","win_recording":f"research/recordings/{c}-v1-win.json","loss_recording":f"research/recordings/{c}-v1-loss.json","thumbnail":f"docs/static/img/games/{c}-v1.png","source_sha256":h},"status":"prototype"}
  (out/f"{c}-v1.json").write_text(json.dumps(meta,indent=2)+"\n");im=Image.new("RGB",(64,64));im.putdata([PAL[int(v)] for row in frame for v in row]);im.save(ROOT/"docs"/"static"/"img"/"games"/f"{c}-v1.png",optimize=True);games.append({"game_id":c,"title":title,"axis":axis,"levels":6,"source_sha256":h})
 path=ROOT/"research"/"gpt-batch49-v1.json";path.write_text(json.dumps({"schema_version":1,"batch_id":"gpt-batch49-v1","created_at":"2026-08-30T00:00:00Z","design":"Ten games contrasting state-window macro interruption with evidence-gated irreversible commitments across attention, convention, intervention, conservation, sampling, construction, delegation, revision, identity, and moving frames.","games":games},indent=2)+"\n")
 sheet=Image.new("RGB",(800,352),(242,242,246));d=ImageDraw.Draw(sheet)
 for i,c in enumerate(CFG):
  im=Image.open(ROOT/"docs"/"static"/"img"/"games"/f"{c}-v1.png").resize((128,128),Image.Resampling.NEAREST);x,y=(i%5)*160+16,(i//5)*176+12;sheet.paste(im,(x,y));d.text((x,y+136),c,fill=(28,28,36))
 (ROOT/".cache").mkdir(exist_ok=True);sheet.save(ROOT/".cache"/"batch49-contact.png",optimize=True);print("10 metadata records",path)
if __name__=="__main__":main()
