"""Generate metadata, thumbnails, and a contact sheet for research Batch 87."""
import hashlib,importlib.util,json
from PIL import Image,ImageDraw
from arcengine import ActionInput,GameAction
from build_research_batch06_metadata import ROOT,SESSION,PAL
CFG={
"a061":("Predator Valve","feedback-control-and-regulation","coupled-oscillatory-population-control","A rhythmic habitat splits prey and predator bands across two patches joined by migration valves."),
"a062":("Hysteresis House","feedback-control-and-regulation","threshold-control-with-mode-memory","A blue thermal house sequences three rooms, temperature columns, remembered door states, and a traveler."),
"a063":("Delayed Feedback","feedback-control-and-regulation","control-with-three-turn-observation-lag","A lilac greenhouse separates true bed moisture from an older display and moving irrigation head."),
"a064":("Coupled Controllers","feedback-control-and-regulation","gain-tuning-under-controller-interaction","A rose control laboratory balances two regulators around one coupled platform and settlement rail."),
"a065":("Wagon Wheel","sampling-frequency-and-aliasing","motion-inference-by-changing-sampling-rate","A warm strobe studio centers one spoke wheel above interval and apparent-direction samples."),
"a066":("Strobe Swarm","sampling-frequency-and-aliasing","multi-rate-phase-identification-with-limited-flashes","A mint night field stacks three insect tracks beneath a movable net and sparse flash ledger."),
"a067":("Nyquist Bridge","sampling-frequency-and-aliasing","structural-cycle-identification-by-probe-rate","A pale river bridge separates fast load shape, probe interval, sampled sequence, and cart risk."),
"a068":("Beat Detector","sampling-frequency-and-aliasing","coincidence-inference-from-nearby-frequencies","A violet rotor chamber pairs two phase dials over a long coincidence timeline and transfer window."),
"a069":("Sparse Tracker","sampling-frequency-and-aliasing","trajectory-estimation-from-four-chosen-observations","A teal tracking range separates hidden motion, four sight marks, bounces, catcher, and future intercept."),
"a070":("Exposure Window","sampling-frequency-and-aliasing","speed-classification-by-exposure-integration","A gold darkroom layers two motion tracks, exposure meter, smear evidence, camera, and speed gates."),
}
def load(c):
 p=ROOT/"docs"/"static"/"games"/"src"/f"{c}-v1"/f"{c}.py";s=importlib.util.spec_from_file_location(c,p);m=importlib.util.module_from_spec(s);s.loader.exec_module(m);return p,m
def main():
 games=[];out=ROOT/"research"/"games";out.mkdir(parents=True,exist_ok=True)
 for c,(title,axis,primary,silhouette) in CFG.items():
  p,m=load(c);h=hashlib.sha256(p.read_bytes()).hexdigest();rel=p.relative_to(ROOT).as_posix();names=[x["name"] for x in m.LEVELS];g=getattr(m,c.upper())();frame=g.perform_action(ActionInput(id=GameAction.RESET),raw=True).frame[-1];palette=sorted({int(v) for row in frame for v in row})
  meta={"schema_version":1,"game_id":c,"version":"v1","internal_title":title,"public_title":None,"author_partition":"gpt","authorship":{"model_family":"OpenAI GPT-5","model_snapshot":"current Codex task model; exact deployment id not exposed to task","session_id":SESSION,"created_at":"2026-08-31T00:00:00Z","source_lineage":[f"research/anthropic-build-ideas-v1.tsv:{c}"],"concept_lineage":"gpt-seeded-anthropic-build","intended_builder":"anthropic","implementation_author_partition":"gpt","source_commit":None},"mechanics":{"primary":primary,"secondary":[axis,"latent-dynamics-and-observation-design"],"novelty_claim":names[-1],"closest_prior_art":["research/anthropic-build-ideas-v1.audit.json","research/coverage-gap-study-v1.md","research/flash-game-mechanics-survey.md"]},"failure_modes":["optimizes a visible population, temperature, or controller independently while ignoring coupled state and history","treats a delayed, sparse, aliased, strobed, or integrated observation as current ground truth","infers apparent direction, slow beat, smear, or sampled cycle without changing the observation process"],"interface":{"actions":[1,2,3,4,5,6],"observation":"64x64x16","deterministic":True,"seeded_stochasticity":False},"progression":[{"level":i+1,"role":["orient","discriminate","plan","compose","inhibit","synthesize"][i],"new_demand":n,"composes":list(range(1,i+1))} for i,n in enumerate(names)],"visual_identity":{"dominant_palette":palette,"silhouette_grammar":silhouette,"spatial_grammar":silhouette,"motion_grammar":primary.replace("-"," "),"hud_grammar":"Population bands, remembered doors, lagged moisture, regulator gains, wheel samples, flash ledgers, probe intervals, beat marks, sparse sightings, and exposure smears expose temporal evidence without text.","nearest_visual_games":[]},"evaluation":{"allowed_development_models":["deterministic-solvers","random-fuzzer","Qwen3.8 diagnostic only"],"held_out_evaluator":"anthropic","human_baseline_status":"not_started","held_out_status":"sealed"},"artifacts":{"source":rel,"metadata":f"research/games/{c}-v1.json","win_recording":f"research/recordings/{c}-v1-win.json","loss_recording":f"research/recordings/{c}-v1-loss.json","thumbnail":f"docs/static/img/games/{c}-v1.png","source_sha256":h},"status":"prototype"}
  (out/f"{c}-v1.json").write_text(json.dumps(meta,indent=2)+"\n");im=Image.new("RGB",(64,64));im.putdata([PAL[int(v)] for row in frame for v in row]);im.save(ROOT/"docs"/"static"/"img"/"games"/f"{c}-v1.png",optimize=True);games.append({"game_id":c,"title":title,"axis":axis,"levels":6,"source_sha256":h})
 path=ROOT/"research"/"gpt-batch87-v1.json";path.write_text(json.dumps({"schema_version":1,"batch_id":"gpt-batch87-v1","created_at":"2026-08-31T00:00:00Z","provenance":"Concepts retain gpt-seeded-anthropic-build queue lineage; implementations in this batch are authored by OpenAI GPT-5 and are not attributed to Anthropic.","design":"Ten habitat, household, greenhouse, controller, strobe, bridge, rotor, tracking, and camera systems require state history plus deliberate choices about when and how observations are acquired.","games":games},indent=2)+"\n")
 sheet=Image.new("RGB",(800,352),(242,242,246));d=ImageDraw.Draw(sheet)
 for i,c in enumerate(CFG):
  im=Image.open(ROOT/"docs"/"static"/"img"/"games"/f"{c}-v1.png").resize((128,128),Image.Resampling.NEAREST);x,y=(i%5)*160+16,(i//5)*176+12;sheet.paste(im,(x,y));d.text((x,y+136),c,fill=(28,28,36))
 (ROOT/".cache").mkdir(exist_ok=True);sheet.save(ROOT/".cache"/"batch87-contact.png",optimize=True);print("10 metadata records",path)
if __name__=="__main__":main()
