"""Generate metadata, thumbnails, and a contact sheet for research Batch 88."""
import hashlib,importlib.util,json
from PIL import Image,ImageDraw
from arcengine import ActionInput,GameAction
from build_research_batch06_metadata import ROOT,SESSION,PAL
CFG={
"a071":("Event Sampler","sampling-frequency-and-aliasing","event-triggered-observation-under-battery-cost","A bright sensor field separates stale cell observations, peripheral change indicator, trigger state, and battery."),
"a072":("Moire Current","sampling-frequency-and-aliasing","spatial-interference-as-navigation-signal","A pale flow tank overlays two fine stripe lattices beneath coarse bands and one drifting particle."),
"a073":("Four-Bar Door","articulated-kinematics","closed-chain-latch-path-planning","A coral workshop suspends a constrained four-bar loop around an obstacle, socket, and traced latch arc."),
"a074":("Linkage Walker","articulated-kinematics","gait-generation-from-link-holes-and-phase","A blue outdoor walker exposes body travel, paired leg linkages, crank holes, foot contact, and terrain."),
"a075":("Cam Garden","articulated-kinematics","cam-profile-selection-and-temporal-phasing","A violet garden aligns three shaped cams, followers, flowers, shaft phase, and press history."),
"a076":("Scissor Lift","articulated-kinematics","coupled-height-footprint-and-actuation-geometry","A gold lift yard frames a stacked scissor silhouette between boundaries, ledge, cargo, and actuator rail."),
"a077":("Universal Joint","articulated-kinematics","bend-dependent-phase-transmission-and-yoke-alignment","A mint drivetrain bench bends input and output shafts through two yokes with phase and smoothness marks."),
"a078":("Pantograph Path","articulated-kinematics","linked-scale-reflection-and-reachability-mapping","A drafting table links cursor, movable pivot, transformed tip, obstacle, target, and remote trace."),
"a079":("Crank Slider","articulated-kinematics","nonlinear-slider-speed-from-crank-phase","A lilac machine shop joins a rotary crank to a slider, contact pad, launched objects, and speed ledger."),
"a080":("Tendon Hand","articulated-kinematics","underactuated-multi-joint-tendon-coupling","A rose worktable shows three tendon-coded fingers surrounding irregular and fragile grasp objects."),
}
def load(c):
 p=ROOT/"docs"/"static"/"games"/"src"/f"{c}-v1"/f"{c}.py";s=importlib.util.spec_from_file_location(c,p);m=importlib.util.module_from_spec(s);s.loader.exec_module(m);return p,m
def main():
 games=[];out=ROOT/"research"/"games";out.mkdir(parents=True,exist_ok=True)
 for c,(title,axis,primary,silhouette) in CFG.items():
  p,m=load(c);h=hashlib.sha256(p.read_bytes()).hexdigest();rel=p.relative_to(ROOT).as_posix();names=[x["name"] for x in m.LEVELS];g=getattr(m,c.upper())();frame=g.perform_action(ActionInput(id=GameAction.RESET),raw=True).frame[-1];palette=sorted({int(v) for row in frame for v in row})
  meta={"schema_version":1,"game_id":c,"version":"v1","internal_title":title,"public_title":None,"author_partition":"gpt","authorship":{"model_family":"OpenAI GPT-5","model_snapshot":"current Codex task model; exact deployment id not exposed to task","session_id":SESSION,"created_at":"2026-08-31T00:00:00Z","source_lineage":[f"research/anthropic-build-ideas-v1.tsv:{c}"],"concept_lineage":"gpt-seeded-anthropic-build","intended_builder":"anthropic","implementation_author_partition":"gpt","source_commit":None},"mechanics":{"primary":primary,"secondary":[axis,"mechanism-state-and-geometric-coupling"],"novelty_claim":names[-1],"closest_prior_art":["research/anthropic-build-ideas-v1.audit.json","research/coverage-gap-study-v1.md","research/flash-game-mechanics-survey.md"]},"failure_modes":["uses fixed-rate observation despite an event trigger or treats interference bands as physical objects","plans joints, tips, heights, or fingers independently despite closed-chain, scale, footprint, phase, or tendon coupling","matches a static pose or peak while ignoring the cyclic path, speed profile, transmission phase, or contact pressure"],"interface":{"actions":[1,2,3,4,5,6],"observation":"64x64x16","deterministic":True,"seeded_stochasticity":False},"progression":[{"level":i+1,"role":["orient","discriminate","plan","compose","inhibit","synthesize"][i],"new_demand":n,"composes":list(range(1,i+1))} for i,n in enumerate(names)],"visual_identity":{"dominant_palette":palette,"silhouette_grammar":silhouette,"spatial_grammar":silhouette,"motion_grammar":primary.replace("-"," "),"hud_grammar":"Event indicators, interference bands, joint paths, crank holes, cam profiles, lift footprint, yoke phase, pantograph trace, slider speed, and tendon pressure expose mechanism state without text.","nearest_visual_games":[]},"evaluation":{"allowed_development_models":["deterministic-solvers","random-fuzzer","Qwen3.8 diagnostic only"],"held_out_evaluator":"anthropic","human_baseline_status":"not_started","held_out_status":"sealed"},"artifacts":{"source":rel,"metadata":f"research/games/{c}-v1.json","win_recording":f"research/recordings/{c}-v1-win.json","loss_recording":f"research/recordings/{c}-v1-loss.json","thumbnail":f"docs/static/img/games/{c}-v1.png","source_sha256":h},"status":"prototype"}
  (out/f"{c}-v1.json").write_text(json.dumps(meta,indent=2)+"\n");im=Image.new("RGB",(64,64));im.putdata([PAL[int(v)] for row in frame for v in row]);im.save(ROOT/"docs"/"static"/"img"/"games"/f"{c}-v1.png",optimize=True);games.append({"game_id":c,"title":title,"axis":axis,"levels":6,"source_sha256":h})
 path=ROOT/"research"/"gpt-batch88-v1.json";path.write_text(json.dumps({"schema_version":1,"batch_id":"gpt-batch88-v1","created_at":"2026-08-31T00:00:00Z","provenance":"Concepts retain gpt-seeded-anthropic-build queue lineage; implementations in this batch are authored by OpenAI GPT-5 and are not attributed to Anthropic.","design":"Two event and interference samplers lead into eight colorful linkage machines that demand closed-chain reasoning, cyclic gait, motion profiles, mechanical advantage, phase transmission, geometric transforms, nonlinear speed, and underactuation.","games":games},indent=2)+"\n")
 sheet=Image.new("RGB",(800,352),(242,242,246));d=ImageDraw.Draw(sheet)
 for i,c in enumerate(CFG):
  im=Image.open(ROOT/"docs"/"static"/"img"/"games"/f"{c}-v1.png").resize((128,128),Image.Resampling.NEAREST);x,y=(i%5)*160+16,(i//5)*176+12;sheet.paste(im,(x,y));d.text((x,y+136),c,fill=(28,28,36))
 (ROOT/".cache").mkdir(exist_ok=True);sheet.save(ROOT/".cache"/"batch88-contact.png",optimize=True);print("10 metadata records",path)
if __name__=="__main__":main()
