"""Generate metadata and visual artifacts for research Batch 16."""
import hashlib,importlib.util,json
from PIL import Image,ImageDraw
from arcengine import ActionInput,GameAction
from build_research_batch06_metadata import ROOT,SESSION,PAL
CFG={
"q107":("Folding Map","multi-scale-reference-frames","hinge-folded-global-adjacency",["folded-coordinate-frame","orientation-reversal"],["treats hinges as portals","keeps global order after folding","folds around the wrong local edge"],[3,4,5,6],"Alternating blue map panels reverse around orange hinges on a pale table."),
"q116":("Counterexample Room","policy-learning-from-demonstration","counterexample-driven-rule-elimination",["minority-evidence","candidate-pruning"],["uses majority resemblance","selects redundant examples","commits before uniqueness"],[1,2,3,4,5,6],"Orange examples eliminate cyan candidate rules through green and red outcomes."),
"q126":("Copycat Trap","adaptive-adversary","one-turn-delayed-imitation-actuator",["opponent-model","remote-control"],["reacts to the rival's current action","forgets the priming move","copies the target instead of scheduling it"],[1,2,3,4],"A blue player primes an orange delayed rival that drives a remote actuator."),
"q136":("Lossy Channel","compositional-communication","predictable-drop-redundant-code",["channel-model","adaptive-redundancy"],["repeats every symbol","sends the dropped class directly","uses redundancy on reliable symbols"],[1,2,3,4],"A blue sender crosses a pale channel with violet redundant codes to a green receiver."),
"q146":("Fork Seal","counterfactual-planning","irreversible-sibling-sealing-fork",["downstream-compatibility","commitment"],["opens before previewing","optimizes one branch locally","tries to return through a sealed sibling"],[1,2,5,6],"Gray forks become cyan open paths and red sealed siblings inside a green cave."),
"q156":("Bridge Logic","structural-analogy","bridge-structure-to-boolean-activation",["and-or-transfer","embodied-logic"],["copies bridge color","confuses conjunction with sequence","fails when bridges disappear"],[1,2,3,4,6],"Orange and violet bridge supports embody Boolean gates over a cyan river."),
"q166":("Checkpoint Choice","confidence-calibration","limited-pre-risk-state-preservation",["checkpoint-placement","risk-confidence"],["saves immediately","saves after the risky step","tries to create a second checkpoint"],[1,2,5,6],"Green safe steps and red risks surround a single violet checkpoint on a pink path."),
"q176":("Heat Diffusion","continuous-quantity-reasoning","thresholded-local-heat-field",["field-prediction","material-threshold"],["tracks only the heated cell","rounds every cell independently","reacts after the threshold crossing"],[1,2,3,4,5,6],"Blue, orange, and red material columns expose a diffusing temperature field."),
"q186":("Deferred Mirror","long-horizon-credit-assignment","countdown-delayed-remote-action",["future-space","delayed-effect"],["expects an immediate mirror","fills the remote schedule too late","forgets queued actions"],[1,2,3,4,5],"Blue local actions wait in violet countdown bars before appearing in an orange room."),
"q196":("Event Order","temporal-abstraction","duration-invariant-causal-event-order",["event-boundary","temporal-transfer"],["counts animation frames","orders by duration","commits before an event boundary"],[1,2,3,4,5],"Blue events with changing orange duration bars advance only at green boundaries.")}
def load(c):
 p=ROOT/"docs"/"static"/"games"/"src"/f"{c}-v1"/f"{c}.py";s=importlib.util.spec_from_file_location(c,p);m=importlib.util.module_from_spec(s);s.loader.exec_module(m);return p,m
def main():
 games=[];out=ROOT/"research"/"games"
 for c,v in CFG.items():
  title,axis,primary,secondary,failures,actions,sil=v;p,m=load(c);h=hashlib.sha256(p.read_bytes()).hexdigest();rel=p.relative_to(ROOT).as_posix();names=[x["name"] for x in m.LEVELS]
  meta={"schema_version":1,"game_id":c,"version":"v1","internal_title":title,"public_title":None,"author_partition":"gpt","authorship":{"model_family":"OpenAI GPT-5","model_snapshot":"current Codex task model; exact deployment id not exposed to task","session_id":SESSION,"created_at":"2026-08-30T00:00:00Z","source_lineage":[f"research/gpt-ideas-v2.tsv:{c}"],"source_commit":None},"mechanics":{"primary":primary,"secondary":secondary,"novelty_claim":names[-1],"closest_prior_art":["research/coverage-gap-study-v1.md","research/flash-game-mechanics-survey.md"]},"failure_modes":failures,"interface":{"actions":actions,"observation":"64x64x16","deterministic":True,"seeded_stochasticity":False},"progression":[{"level":i+1,"role":["orient","discriminate","plan","compose","inhibit","synthesize"][i],"new_demand":n,"composes":list(range(1,i+1))} for i,n in enumerate(names)],"visual_identity":{"dominant_palette":[],"silhouette_grammar":sil,"spatial_grammar":sil,"motion_grammar":primary.replace("-"," "),"hud_grammar":"Persistent colored state markers expose the mechanic without text.","nearest_visual_games":[]},"evaluation":{"allowed_development_models":["deterministic-solvers","random-fuzzer","Qwen3.8 diagnostic only"],"held_out_evaluator":"anthropic","human_baseline_status":"not_started","held_out_status":"sealed"},"artifacts":{"source":rel,"metadata":f"research/games/{c}-v1.json","win_recording":f"research/recordings/{c}-v1-win.json","loss_recording":f"research/recordings/{c}-v1-loss.json","thumbnail":f"docs/static/img/games/{c}-v1.png","source_sha256":h},"status":"prototype"}
  (out/f"{c}-v1.json").write_text(json.dumps(meta,indent=2)+"\n");g=getattr(m,c.upper())();a=g.perform_action(ActionInput(id=GameAction.RESET),raw=True).frame[-1];im=Image.new("RGB",(64,64));im.putdata([PAL[int(x)] for row in a for x in row]);im.save(ROOT/"docs"/"static"/"img"/"games"/f"{c}-v1.png",optimize=True);games.append({"game_id":c,"title":title,"axis":axis,"levels":6,"source_sha256":h})
 path=ROOT/"research"/"gpt-batch16-v1.json";path.write_text(json.dumps({"schema_version":1,"batch_id":"gpt-batch16-v1","created_at":"2026-08-30T00:00:00Z","design":"Ten sixth-pass games across the second ten research axes, each with six progressive levels and a distinct colorful environment.","games":games},indent=2)+"\n")
 sheet=Image.new("RGB",(800,352),(242,242,246));d=ImageDraw.Draw(sheet)
 for i,c in enumerate(CFG):im=Image.open(ROOT/"docs"/"static"/"img"/"games"/f"{c}-v1.png").resize((128,128),Image.Resampling.NEAREST);x,y=(i%5)*160+16,(i//5)*176+12;sheet.paste(im,(x,y));d.text((x,y+136),c,fill=(28,28,36))
 sheet.save(ROOT/".cache"/"batch16-contact.png",optimize=True);print("10 metadata records",path)
if __name__=="__main__":main()
