"""Generate metadata, thumbnails, and a contact sheet for research Batch 97."""
import hashlib,importlib.util,json
from PIL import Image,ImageDraw
from arcengine import ActionInput,GameAction
from build_research_batch06_metadata import ROOT,SESSION,PAL
CFG={
"a161":("Frontier Marks","systematic-search-and-coverage","scarce-frontier-state-management","A magenta fading maze places three movable frontier markers among open, covered, and closed subtrees with repeat cost."),
"a162":("Survey Ribbon","systematic-search-and-coverage","cost-sensitive-irregular-boundary-coverage","A pale sea chart surrounds three irregular islands with scanned boundary segments, dock, shared battery, and retrace penalty."),
"a163":("Branch and Bound","systematic-search-and-coverage","visible-lower-bound-dominance-pruning","A dark construction tree arrays six partial branches with lower-bound bars, best complete value, expansions, and pruned nodes."),
"a164":("Bidirectional Hunt","systematic-search-and-coverage","balanced-reversible-meet-in-the-middle","A black transformation maze grows colored start and target frontiers over twelve nodes until overlap appears."),
"a165":("Landmark Search","systematic-search-and-coverage","relational-landmark-distance-navigation","A cream repetitive map anchors two unique landmarks around distance bands, traveler, hidden goal, and step budget."),
"a166":("Iterative Deepening","systematic-search-and-coverage","cost-aware-complete-depth-bounds","A steel search console stacks explicit depth layers against goal depth, exponential cost, pulses, discovery, and plan length."),
"a167":("Symmetry Pruning","systematic-search-and-coverage","one-search-representative-per-branch-orbit","A green rotational chamber surrounds eight repeated branches with class cores, representative marks, duplicates, and missing classes."),
"a168":("Dynamic Frontier","systematic-search-and-coverage","topology-updated-reachable-unknown-maintenance","A coral region grid opens and closes corridors after inspection while recomputing frontier reachability and orphaned unknowns."),
"a169":("Same Future","state-abstraction-and-equivalence","action-response-behavioral-state-merging","A black machine panel bins eight appearance-different states by probed future behavior rather than current color."),
"a170":("Quotient Rooms","state-abstraction-and-equivalence","class-based-planning-over-redundant-rooms","A gold decorated palace collapses eight concrete rooms into three transition classes for abstract navigation."),
}
def load(c):
 p=ROOT/"docs"/"static"/"games"/"src"/f"{c}-v1"/f"{c}.py";s=importlib.util.spec_from_file_location(c,p);m=importlib.util.module_from_spec(s);s.loader.exec_module(m);return p,m
def main():
 games=[];out=ROOT/"research"/"games";out.mkdir(parents=True,exist_ok=True)
 for c,(title,axis,primary,silhouette) in CFG.items():
  p,m=load(c);h=hashlib.sha256(p.read_bytes()).hexdigest();rel=p.relative_to(ROOT).as_posix();names=[x["name"] for x in m.LEVELS];g=getattr(m,c.upper())();frame=g.perform_action(ActionInput(id=GameAction.RESET),raw=True).frame[-1];palette=sorted({int(v) for row in frame for v in row})
  meta={"schema_version":1,"game_id":c,"version":"v1","internal_title":title,"public_title":None,"author_partition":"gpt","authorship":{"model_family":"OpenAI GPT-5","model_snapshot":"current Codex task model; exact deployment id not exposed to task","session_id":SESSION,"created_at":"2026-08-31T00:00:00Z","source_lineage":[f"research/anthropic-build-ideas-v1.tsv:{c}"],"concept_lineage":"gpt-seeded-anthropic-build","intended_builder":"anthropic","implementation_author_partition":"gpt","source_commit":None},"mechanics":{"primary":primary,"secondary":[axis,"explicit-search-state-and-abstraction"],"novelty_claim":names[-1],"closest_prior_art":["research/anthropic-build-ideas-v1.audit.json","research/coverage-gap-study-v1.md","research/flash-game-mechanics-survey.md"]},"failure_modes":["forgets unresolved branches, retraces expensive boundaries, or explores a dominated lower-bound branch to completion","uses one huge forward search instead of balanced frontiers, landmarks, iterative depth, symmetry classes, or dynamic frontier updates","keeps visually distinct concrete states separate despite identical future behavior or quotient transitions"],"interface":{"actions":[1,2,3,4,5,6],"observation":"64x64x16","deterministic":True,"seeded_stochasticity":False},"progression":[{"level":i+1,"role":["orient","discriminate","plan","compose","inhibit","synthesize"][i],"new_demand":n,"composes":list(range(1,i+1))} for i,n in enumerate(names)],"visual_identity":{"dominant_palette":palette,"silhouette_grammar":silhouette,"spatial_grammar":silhouette,"motion_grammar":primary.replace("-"," "),"hud_grammar":"Frontier, boundary coverage, bounds, bidirectional overlap, landmarks, depth, symmetry classes, topology, behavioral bins, and quotient paths expose search state without text.","nearest_visual_games":[]},"evaluation":{"allowed_development_models":["deterministic-solvers","random-fuzzer","Qwen3.8 diagnostic only"],"held_out_evaluator":"anthropic","human_baseline_status":"not_started","held_out_status":"sealed"},"artifacts":{"source":rel,"metadata":f"research/games/{c}-v1.json","win_recording":f"research/recordings/{c}-v1-win.json","loss_recording":f"research/recordings/{c}-v1-loss.json","thumbnail":f"docs/static/img/games/{c}-v1.png","source_sha256":h},"status":"prototype"}
  (out/f"{c}-v1.json").write_text(json.dumps(meta,indent=2)+"\n");im=Image.new("RGB",(64,64));im.putdata([PAL[int(v)] for row in frame for v in row]);im.save(ROOT/"docs"/"static"/"img"/"games"/f"{c}-v1.png",optimize=True);games.append({"game_id":c,"title":title,"axis":axis,"levels":6,"source_sha256":h})
 path=ROOT/"research"/"gpt-batch97-v1.json";path.write_text(json.dumps({"schema_version":1,"batch_id":"gpt-batch97-v1","created_at":"2026-08-31T00:00:00Z","provenance":"Concepts retain gpt-seeded-anthropic-build queue lineage; implementations in this batch are authored by OpenAI GPT-5 and are not attributed to Anthropic.","design":"Eight colorful search systems externalize frontier memory, coverage cost, lower bounds, two-sided expansion, landmark coordinates, depth limits, symmetry classes, and changing topology; two abstraction boards merge states by behavior and quotient transitions.","games":games},indent=2)+"\n")
 sheet=Image.new("RGB",(800,352),(242,242,246));d=ImageDraw.Draw(sheet)
 for i,c in enumerate(CFG):
  im=Image.open(ROOT/"docs"/"static"/"img"/"games"/f"{c}-v1.png").resize((128,128),Image.Resampling.NEAREST);x,y=(i%5)*160+16,(i//5)*176+12;sheet.paste(im,(x,y));d.text((x,y+136),c,fill=(28,28,36))
 (ROOT/".cache").mkdir(exist_ok=True);sheet.save(ROOT/".cache"/"batch97-contact.png",optimize=True);print("10 metadata records",path)
if __name__=="__main__":main()
