"""Generate metadata, thumbnails, and contact sheet for research Batch 05."""
from __future__ import annotations
import hashlib,importlib.util,json
from pathlib import Path
from PIL import Image,ImageDraw
from arcengine import ActionInput,GameAction
ROOT=Path(__file__).resolve().parents[1];SESSION="01a02a2e-aaf5-7e90-a559-46437ace2edb"
PALETTE=[(255,255,255),(204,204,204),(153,153,153),(102,102,102),(51,51,51),(0,0,0),(229,58,163),(255,123,204),(249,60,49),(30,147,255),(136,216,241),(255,220,0),(255,133,27),(146,18,49),(79,204,48),(163,86,214)]
ROLES=["orient","discriminate","plan","compose","inhibit","synthesize"]
CONFIG={
"q004":("Witness Queue","observer-dependent-dynamics","watched-commit-hidden-travel",["visibility-state","alternating-supervision","direction-memory"],["travels while watched","commits without a witness","forgets the selected branch"],[1,3,4,5,6],[1,3,4,6,8,10,11,14],"A magenta token crosses charcoal junctions beneath a yellow witness bar.","A pale queue of junction cards spans a cyan observation chamber.","Branch selection commits only under observation; transit succeeds only after the witness turns away.","The yellow/charcoal witness bar makes observation state persistent.",["Commit one watched branch.","Turn observation off before travel.","Alternate branch selection and hidden transit.","Carry direction state across four junctions.","Avoid premature travel through a longer queue.","Coordinate six supervised commitments with six unseen transitions."]),
"q013":("Signal Camp","social-inference","grounded-partner-signal-policy",["demonstration-learning","spatial-code","joint-routing"],["copies the signal instead of its response","assumes a fixed global mapping","forgets the demonstrated policy"],[1,2,3,4],[1,7,8,9,11,12,14],"Orange signal arrows map to blue partner responses above a growing green route.","Two demonstration rows occupy a warm pink camp board.","Directional action expresses the partner response inferred from the current camp's demonstrations.","Completed green waypoints externalize joint route progress.",["Ground one signal-response pair.","Use two demonstrated signs.","Transfer a reversed policy.","Maintain a four-way camp code.","Execute a six-signal silent route.","Coordinate seven responses under a novel permutation."]),
"q023":("Broken Symmetry","causal-intervention","odd-machine-identification",["active-probing","symmetry-breaking","causal-selection"],["guesses from position","selects before intervening","confuses common output with the defect"],[3,4,5,6],[0,6,8,10,11,13,14],"Gray machines reveal green or red causal responses only after a probe.","A white intervention bench floats in a magenta laboratory.","The cursor chooses a machine, probe exposes its response, and submit names the broken symmetry.","Yellow cursor caps and green probe plates separate targeting from evidence.",["Probe one asymmetric pair.","Find one defect among four twins.","Distinguish a delayed response code.","Search a five-machine wrapped bench.","Recognize a weak link among six machines.","Break symmetry when five machines share the same nonbinary response."]),
"q033":("Color Exchange","conservation-law","component-swap-bookkeeping",["global-conservation","factorized-color","operation-search"],["recolors independently","tracks only one component","submits a visually close but nonconserved arrangement"],[3,4,5,6],[1,3,6,8,9,11,12,14],"Split blue-magenta objects exchange components beneath target swatches.","A pale exchange hall rests in a green conservation field.","Selected links swap exactly one component between two objects without creating color.","Orange operation chips encode the currently selected exchange.",["Swap one component.","Exchange both factorized colors.","Bookkeep across three objects.","Search an exchange ring.","Preserve a four-object component ledger.","Compose six possible exchanges into an exact conserved target."]),
"q043":("Sampling Cart","epistemic-resource-allocation","finite-terrain-sampling",["information-budget","safe-routing","active-perception"],["drives onto unsampled ground","samples every cell","spends the last sample off-route"],[1,2,3,4,5],[3,5,6,8,9,11,12,13,14],"A blue cart reveals green soil or red rock one cell ahead.","A dark heterogeneous field sits in a burgundy sampling landscape.","Direction orients and attempts movement; sampling consumes a finite yellow resource to reveal the facing cell.","The shrinking yellow sample strip makes information cost visible.",["Sample a short route.","Probe around one blocked fork.","Allocate samples across a long diagonal.","Route through a sparse obstacle field.","Avoid wasting samples in a deceptive channel.","Reach a distant goal with only one spare observation."]),
"q053":("Bridge Loom","tool-construction","anchor-thread-bridge-building",["graph-connectivity","required-supports","construction-planning"],["submits disconnected fibers","uses a shortcut without required supports","forgets which anchor is load-bearing"],[3,4,5,6],[1,6,8,9,10,12,14],"Magenta threads join pale anchors across blue water.","A cyan basin holds an increasingly wide anchor loom.","The selector chooses structural edges; weave adds persistent thread and submit tests support plus connectivity.","Orange edge chips expose the construction palette.",["Weave one span.","Connect three anchors.","Choose the load-bearing fork.","Reject a tempting crossing shortcut.","Construct a six-anchor lower support path.","Compose four required spans through a seven-anchor loom."]),
"q063":("Two Rooms One Switch","distributed-partial-observability","remote-geometry-switch",["alternating-view","shared-causal-state","remote-planning"],["toggles from the wrong room","forgets door state after switching views","routes through the closed remote door"],[1,2,3,4,5,6],[1,3,6,8,9,10,11,12,14],"A magenta agent alternates between a pale switch room and cyan goal room.","One room at a time fills an orange shared-state console.","Movement affects only the visible room; the local switch causally opens geometry in the remote room.","A blue/orange view badge records which room is active.",["Open one remote door.","Return attention to the goal room.","Maintain switch state through a detour.","Coordinate alternating room paths.","Reach a distant local switch before remote traversal.","Solve two winding rooms around one shared causal door."]),
"q073":("Phase Change","nonstationary-rule-revision","energy-triggered-material-transition",["threshold-reasoning","rule-change","route-replanning"],["treats material as permanently solid","heats without tracking threshold","fails to replan after melting"],[1,2,3,4,5],[0,6,8,9,10,11,12,14],"Cyan barriers melt into blue traversable fluid as an orange heat bar grows.","A white material grid rests in a yellow phase laboratory.","Heat changes the collision law globally after a visible threshold; movement then crosses formerly solid cells.","The orange energy bar externalizes progress toward the phase boundary.",["Melt one gate.","Accumulate two heat units before routing.","Choose between a solid detour and melting.","Cross a diagonal phase boundary.","Track a four-unit energy ledger.","Revise the traversal model after a five-step phase transition."]),
"q083":("Unmarked Lineage","persistent-identity","ancestry-graph-selection",["identity-through-change","genealogy","unmarked-descendants"],["selects by current appearance","confuses adjacency with ancestry","loses identity through multiple generations"],[3,4,6],[1,3,5,8,10,11,12,14],"Identical cyan descendants connect by gray lineage traces to orange roots.","A pale genealogy panel floats in a red identity field.","Cursor navigation selects a present object whose identity must be reconstructed from ancestry links.","A green root cue specifies the requested lineage without marking the descendant.",["Distinguish two roots.","Follow one split.","Separate crossed families.","Trace a grandchild through two generations.","Maintain lineage across a six-object chain.","Recover identity through a seven-node unmarked genealogy."]),
"q093":("Milestone Garden","hierarchical-goal-discovery","pattern-gated-growth-operations",["subgoal-discovery","capability-unlock","nonmonotonic-planning"],["optimizes immediate coverage","misses an unlocking pattern","cannot retract a temporary milestone tile"],[3,4,5,6],[6,8,9,10,11,12,14,15],"Green growth tiles bloom in an orange soil bed around pale target cores.","A bright violet garden holds six modular planting plots.","Planting toggles selected growth; stable intermediate masks permanently unlock new operations.","Cyan, green, and orange chips distinguish locked, unlocked, and selected growth operations.",["Discover the first unlock pattern.","Use a milestone to gain a third operation.","Climb three nested subgoals.","Build a four-stage capability ladder.","Temporarily bloom an unwanted tile to unlock the final seed.","Compose five milestones into a six-plot terminal garden."])}
def load(code):
 p=ROOT/"docs"/"static"/"games"/"src"/f"{code}-v1"/f"{code}.py";s=importlib.util.spec_from_file_location(f"{code}_meta",p);m=importlib.util.module_from_spec(s);assert s.loader;s.loader.exec_module(m);return p,m
def thumb(code,m):
 g=getattr(m,code.upper())();r=g.perform_action(ActionInput(id=GameAction.RESET),raw=True);grid=r.frame[-1];im=Image.new("RGB",(64,64));im.putdata([PALETTE[int(v)] for row in grid for v in row]);out=ROOT/"docs"/"static"/"img"/"games"/f"{code}-v1.png";out.parent.mkdir(parents=True,exist_ok=True);im.save(out,optimize=True)
def main():
 outdir=ROOT/"research"/"games";outdir.mkdir(parents=True,exist_ok=True);batch=[]
 for code,v in CONFIG.items():
  title,axis,primary,secondary,failures,actions,palette,silhouette,spatial,motion,hud,progress=v;source,m=load(code);h=hashlib.sha256(source.read_bytes()).hexdigest();rel=source.relative_to(ROOT).as_posix()
  meta={"schema_version":1,"game_id":code,"version":"v1","internal_title":title,"public_title":None,"author_partition":"gpt","authorship":{"model_family":"OpenAI GPT-5","model_snapshot":"current Codex task model; exact deployment id not exposed to task","session_id":SESSION,"created_at":"2026-08-30T00:00:00Z","source_lineage":[f"research/gpt-ideas-v1.tsv:{code}"],"source_commit":None},"mechanics":{"primary":primary,"secondary":secondary,"novelty_claim":progress[-1],"closest_prior_art":["research/coverage-gap-study-v1.md","research/flash-game-mechanics-survey.md"]},"failure_modes":failures,"interface":{"actions":actions,"observation":"64x64x16","deterministic":True,"seeded_stochasticity":False},"progression":[{"level":i+1,"role":ROLES[i],"new_demand":d,"composes":list(range(1,i+1))} for i,d in enumerate(progress)],"visual_identity":{"dominant_palette":palette,"silhouette_grammar":silhouette,"spatial_grammar":spatial,"motion_grammar":motion,"hud_grammar":hud,"nearest_visual_games":[]},"evaluation":{"allowed_development_models":["deterministic-solvers","random-fuzzer","Qwen3.8 diagnostic only"],"held_out_evaluator":"anthropic","human_baseline_status":"not_started","held_out_status":"sealed"},"artifacts":{"source":rel,"metadata":f"research/games/{code}-v1.json","win_recording":f"research/recordings/{code}-v1-win.json","loss_recording":f"research/recordings/{code}-v1-loss.json","thumbnail":f"docs/static/img/games/{code}-v1.png","source_sha256":h},"status":"prototype"}
  (outdir/f"{code}-v1.json").write_text(json.dumps(meta,indent=2)+"\n");thumb(code,m);batch.append({"game_id":code,"title":title,"axis":axis,"levels":len(m.LEVELS),"source_sha256":h})
 path=ROOT/"research"/"gpt-batch05-v1.json";path.write_text(json.dumps({"schema_version":1,"batch_id":"gpt-batch05-v1","created_at":"2026-08-30T00:00:00Z","design":"Ten third-pass games across the first ten research axes, each with six progressive levels and a distinct colorful environment.","games":batch},indent=2)+"\n")
 sheet=Image.new("RGB",(800,352),(242,242,246));draw=ImageDraw.Draw(sheet)
 for i,code in enumerate(CONFIG):
  im=Image.open(ROOT/"docs"/"static"/"img"/"games"/f"{code}-v1.png").convert("RGB").resize((128,128),Image.Resampling.NEAREST);x,y=(i%5)*160+16,(i//5)*176+12;sheet.paste(im,(x,y));draw.text((x,y+136),code,fill=(28,28,36))
 p=ROOT/".cache"/"batch05-contact.png";p.parent.mkdir(parents=True,exist_ok=True);sheet.save(p,optimize=True);print(f"{len(batch)} metadata records -> {outdir}");print(path)
if __name__=="__main__":main()
