"""Generate metadata, thumbnails, and the contact sheet for research Batch 71."""
import hashlib,importlib.util,json
from PIL import Image,ImageDraw
from arcengine import ActionInput,GameAction
from build_research_batch06_metadata import ROOT,SESSION,PAL
CFG={
"q514":("Moraine Frame","multi-scale-reference-frames","local-raft-motion-composes-with-rotating-crevasse-frames-and-writes-order-sensitive-outer-tokens","A white glacier places three local enclosures above frame, completion-order, outer-token, and lock rails."),
"q544":("Moraine Lesson","policy-learning-from-demonstration","a-contextual-raft-policy-is-separated-from-empty-signals-before-writing-an-outer-dependency-token","A silver glacier lesson layers guide rafts above context, gesture, evidence, and outer-token strips."),
"q574":("Moraine Counter","adaptive-adversary","recent-raft-treatments-shape-a-three-tactic-rival-whose-state-solves-one-outer-enclosure","A gray glacier arena aligns a raft path above rival chambers, local completions, and outer tokens."),
"q619":("Monsoon Grammar","compositional-communication","grouped-rain-glyphs-can-relay-only-at-a-specific-phase-pair-of-two-unequal-clocks","A stone weather garden layers rain glyphs above storm relays, two clock bars, grouping, and code rails."),
"q634":("Moraine Sandbox","counterfactual-planning","two-miniature-glaciers-reset-physical-state-while-persistent-evidence-writes-one-outer-token","A charcoal glacier lab places twin raft systems above evidence, reset, outer-board, and commitment strips."),
"q664":("Moraine Analogy","structural-analogy","a-transformed-crevasse-route-transfers-to-rafts-and-writes-the-selected-outer-dependency-slot","A black relation glacier places source and target panes above twist, surface, outer-token, and transfer rails."),
"q694":("Moraine Evidence","confidence-calibration","decisive-unequal-local-evidence-must-be-converted-into-an-outer-token-before-final-stopping","A pink evidence glacier aligns raft samples above result tiles, a signed margin, outer board, and stop rail."),
"q724":("Moraine Gradient","continuous-quantity-reasoning","conserved-raft-flow-crosses-capacity-limited-crevasses-and-writes-phase-indexed-outer-tokens","A rose flow glacier holds three reservoirs above outer tokens, phase, completion order, and commitment bands."),
"q754":("Moraine Obligation","long-horizon-credit-assignment","identity-bound-raft-debt-repayment-writes-order-sensitive-values-into-an-outer-dependency-board","A blue creditor glacier places three raft identities above cargo, debt, outer-token, and completion-order tracks."),
"q799":("Monsoon Rhythm","temporal-abstraction","rain-macros-must-be-interrupted-at-a-state-defined-phase-pair-of-two-unequal-weather-clocks","A cyan timing garden places twelve storm nodes above two clocks, macro count, phase memory, and window rails.")}
def load(c):
 p=ROOT/"docs"/"static"/"games"/"src"/f"{c}-v1"/f"{c}.py";s=importlib.util.spec_from_file_location(c,p);m=importlib.util.module_from_spec(s);s.loader.exec_module(m);return p,m
def main():
 games=[];out=ROOT/"research"/"games";out.mkdir(parents=True,exist_ok=True)
 for c,(title,axis,primary,silhouette) in CFG.items():
  p,m=load(c);h=hashlib.sha256(p.read_bytes()).hexdigest();rel=p.relative_to(ROOT).as_posix();names=[x["name"] for x in m.LEVELS];g=getattr(m,c.upper())();frame=g.perform_action(ActionInput(id=GameAction.RESET),raw=True).frame[-1];palette=sorted({int(v) for row in frame for v in row})
  meta={"schema_version":1,"game_id":c,"version":"v1","internal_title":title,"public_title":None,"author_partition":"gpt","authorship":{"model_family":"OpenAI GPT-5","model_snapshot":"current Codex task model; exact deployment id not exposed to task","session_id":SESSION,"created_at":"2026-08-31T00:00:00Z","source_lineage":[f"research/gpt-ideas-v2.tsv:{c}"],"source_commit":None},"mechanics":{"primary":primary,"secondary":[axis,"underrepresented-capability-expansion"],"novelty_claim":names[-1],"closest_prior_art":["research/coverage-gap-study-v1.md","research/flash-game-mechanics-survey.md"]},"failure_modes":["solves a local enclosure but ignores which outer dependency token that completion writes","reorders local completions and assumes the terminal outer board will remain unchanged","counts elapsed actions instead of tracking the explicit phase pair of two unequal clocks"],"interface":{"actions":[1,2,3,4,5,6],"observation":"64x64x16","deterministic":True,"seeded_stochasticity":False},"progression":[{"level":i+1,"role":["orient","discriminate","plan","compose","inhibit","synthesize"][i],"new_demand":n,"composes":list(range(1,i+1))} for i,n in enumerate(names)],"visual_identity":{"dominant_palette":palette,"silhouette_grammar":silhouette,"spatial_grammar":silhouette,"motion_grammar":primary.replace("-"," "),"hud_grammar":"Ice enclosures, crevasse bands, stone rafts, outer dependency tokens, completion-order tiles, rain glyphs, storm relays, unequal clock bars, phase memory, and interruption windows expose state without text.","nearest_visual_games":[]},"evaluation":{"allowed_development_models":["deterministic-solvers","random-fuzzer","Qwen3.8 diagnostic only"],"held_out_evaluator":"anthropic","human_baseline_status":"not_started","held_out_status":"sealed"},"artifacts":{"source":rel,"metadata":f"research/games/{c}-v1.json","win_recording":f"research/recordings/{c}-v1-win.json","loss_recording":f"research/recordings/{c}-v1-loss.json","thumbnail":f"docs/static/img/games/{c}-v1.png","source_sha256":h},"status":"prototype"}
  (out/f"{c}-v1.json").write_text(json.dumps(meta,indent=2)+"\n");im=Image.new("RGB",(64,64));im.putdata([PAL[int(v)] for row in frame for v in row]);im.save(ROOT/"docs"/"static"/"img"/"games"/f"{c}-v1.png",optimize=True);games.append({"game_id":c,"title":title,"axis":axis,"levels":6,"source_sha256":h})
 path=ROOT/"research"/"gpt-batch71-v1.json";path.write_text(json.dumps({"schema_version":1,"batch_id":"gpt-batch71-v1","created_at":"2026-08-31T00:00:00Z","design":"Eight icy glacier environments couple local raft reasoning to order-sensitive outer dependency tokens across frames, lessons, rivals, simulations, analogies, evidence, flow, and obligations; two colorful weather gardens require phase-pair reasoning over unequal clocks for language and macro-time.","games":games},indent=2)+"\n")
 sheet=Image.new("RGB",(800,352),(242,242,246));d=ImageDraw.Draw(sheet)
 for i,c in enumerate(CFG):
  im=Image.open(ROOT/"docs"/"static"/"img"/"games"/f"{c}-v1.png").resize((128,128),Image.Resampling.NEAREST);x,y=(i%5)*160+16,(i//5)*176+12;sheet.paste(im,(x,y));d.text((x,y+136),c,fill=(28,28,36))
 (ROOT/".cache").mkdir(exist_ok=True);sheet.save(ROOT/".cache"/"batch71-contact.png",optimize=True);print("10 metadata records",path)
if __name__=="__main__":main()
