"""Generate metadata and visual artifacts for research Batch 08."""
import hashlib,importlib.util,json
from PIL import Image,ImageDraw
from arcengine import ActionInput,GameAction
from build_research_batch06_metadata import ROOT,SESSION,PAL
CFG={
"q104":("Conveyor Frame","multi-scale-reference-frames","composed-object-belt-board-velocity",["relative-motion","discrete-velocity-composition"],["tracks only input motion","ignores board drift","adds frame velocities with wrong sign"],[1,2,3,4],"A magenta payload crosses a cyan conveyor lattice while an orange board-phase marker advances."),
"q114":("Noisy Example","policy-learning-from-demonstration","causal-effect-filtered-imitation",["accident-rejection","policy-extraction"],["copies every visible action","drops a causal action","treats salience as intent"],[1,2,3,4],"Green causal gestures and red ineffective accidents occupy a pale demonstration strip."),
"q124":("Counter-Predator","adaptive-adversary","recent-distance-policy-countering",["opponent-modeling","tactic-counter"],["repeats one counter","ignores recent distance history","reacts to the predator color only"],[1,2,3,4],"A red predator reads blue distance histories before the player selects a counter tactic."),
"q134":("Relay Syntax","compositional-communication","multi-agent-local-transform-composition",["relay-composition","local-rule-grounding"],["applies only the first relay","adds transforms in the wrong order","copies the input channel"],[1,2,3,4],"Orange relay agents transform blue signals along a cyan communication channel."),
"q144":("One Reset","counterfactual-planning","evidence-preserving-progress-reset",["experiment-execution-split","single-reset-budget"],["executes before observing","resets before gathering evidence","expects physical progress to persist"],[1,2,3,4,5,6],"Hidden route cards become cyan evidence, while one orange reset clears magenta progress."),
"q154":("Reservoir Crowd","structural-analogy","capacity-constrained-population-flow",["cross-domain-conservation","room-capacity"],["creates population","overfills a room","forgets the reservoir analogy"],[3,4,5,6],"Magenta crowd particles fill pale rooms under explicit capacity and green target bars."),
"q164":("Stop Test","confidence-calibration","value-of-information-stopping",["sequential-testing","cost-aware-commitment"],["samples forever","stops before the lead is stable","chooses the latest observation"],[1,2,3,4,5],"Blue observations emerge from gray tests while a red cost bar approaches a green stopping point."),
"q174":("Resonant Steps","continuous-quantity-reasoning","phase-aligned-amplitude-accumulation",["oscillation-phase","multi-push-force"],["pushes every tick","tracks amplitude but not phase","submits after one push"],[1,2,5],"A dark body widens as correctly phased blue pushes accumulate inside a green chamber."),
"q184":("Seeded Weather","long-horizon-credit-assignment","early-placement-delayed-hazard-field",["delayed-causality","seasonal-evolution"],["places seeds after weather starts","optimizes the current field","forgets which plots influence late hazards"],[3,4,5,6],"Green seed plots evolve beneath a blue seasonal front toward an orange delayed hazard mask."),
"q194":("Interrupt Window","temporal-abstraction","state-windowed-routine-interruption",["autonomous-routine","event-timed-control"],["interrupts on elapsed time alone","misses the state window","confuses observation with interruption"],[5,6],"A cyan routine marker cycles across phase slots above ordered magenta interruption badges.")}
def load(c):
 p=ROOT/"docs"/"static"/"games"/"src"/f"{c}-v1"/f"{c}.py";s=importlib.util.spec_from_file_location(c,p);m=importlib.util.module_from_spec(s);s.loader.exec_module(m);return p,m
def main():
 games=[];out=ROOT/"research"/"games"
 for c,v in CFG.items():
  title,axis,primary,secondary,failures,actions,sil=v;p,m=load(c);h=hashlib.sha256(p.read_bytes()).hexdigest();rel=p.relative_to(ROOT).as_posix();names=[x["name"] for x in m.LEVELS]
  meta={"schema_version":1,"game_id":c,"version":"v1","internal_title":title,"public_title":None,"author_partition":"gpt","authorship":{"model_family":"OpenAI GPT-5","model_snapshot":"current Codex task model; exact deployment id not exposed to task","session_id":SESSION,"created_at":"2026-08-30T00:00:00Z","source_lineage":[f"research/gpt-ideas-v1.tsv:{c}"],"source_commit":None},"mechanics":{"primary":primary,"secondary":secondary,"novelty_claim":names[-1],"closest_prior_art":["research/coverage-gap-study-v1.md","research/flash-game-mechanics-survey.md"]},"failure_modes":failures,"interface":{"actions":actions,"observation":"64x64x16","deterministic":True,"seeded_stochasticity":False},"progression":[{"level":i+1,"role":["orient","discriminate","plan","compose","inhibit","synthesize"][i],"new_demand":n,"composes":list(range(1,i+1))} for i,n in enumerate(names)],"visual_identity":{"dominant_palette":[],"silhouette_grammar":sil,"spatial_grammar":sil,"motion_grammar":primary.replace("-"," "),"hud_grammar":"Persistent colored state markers expose the mechanic without text.","nearest_visual_games":[]},"evaluation":{"allowed_development_models":["deterministic-solvers","random-fuzzer","Qwen3.8 diagnostic only"],"held_out_evaluator":"anthropic","human_baseline_status":"not_started","held_out_status":"sealed"},"artifacts":{"source":rel,"metadata":f"research/games/{c}-v1.json","win_recording":f"research/recordings/{c}-v1-win.json","loss_recording":f"research/recordings/{c}-v1-loss.json","thumbnail":f"docs/static/img/games/{c}-v1.png","source_sha256":h},"status":"prototype"}
  (out/f"{c}-v1.json").write_text(json.dumps(meta,indent=2)+"\n");g=getattr(m,c.upper())();a=g.perform_action(ActionInput(id=GameAction.RESET),raw=True).frame[-1];im=Image.new("RGB",(64,64));im.putdata([PAL[int(x)] for row in a for x in row]);im.save(ROOT/"docs"/"static"/"img"/"games"/f"{c}-v1.png",optimize=True);games.append({"game_id":c,"title":title,"axis":axis,"levels":6,"source_sha256":h})
 path=ROOT/"research"/"gpt-batch08-v1.json";path.write_text(json.dumps({"schema_version":1,"batch_id":"gpt-batch08-v1","created_at":"2026-08-30T00:00:00Z","design":"Ten fourth-pass games across the second ten research axes, each with six progressive levels and a distinct colorful environment.","games":games},indent=2)+"\n")
 sheet=Image.new("RGB",(800,352),(242,242,246));d=ImageDraw.Draw(sheet)
 for i,c in enumerate(CFG):im=Image.open(ROOT/"docs"/"static"/"img"/"games"/f"{c}-v1.png").resize((128,128),Image.Resampling.NEAREST);x,y=(i%5)*160+16,(i//5)*176+12;sheet.paste(im,(x,y));d.text((x,y+136),c,fill=(28,28,36))
 sheet.save(ROOT/".cache"/"batch08-contact.png",optimize=True);print("10 metadata records",path)
if __name__=="__main__":main()
