"""Generate metadata, thumbnails, and the contact sheet for research Batch 61."""
import hashlib,importlib.util,json
from PIL import Image,ImageDraw
from arcengine import ActionInput,GameAction
from build_research_batch06_metadata import ROOT,SESSION,PAL
CFG={
"q538":("Breakwater Lesson","policy-learning-from-demonstration","conditional-harbor-policy-whose-first-intervention-wakes-after-two-solved-subgoals","A modular harbor places a demonstration over tide channels, dormant choice, subgoal, and affordance rails."),
"q568":("Breakwater Counter","adaptive-adversary","rival-shaped-before-the-first-treatment-activates-a-delayed-terminal-counter","A dark harbor aligns three tactic channels above rival, solved-subgoal, and latent-affordance bands."),
"q599":("Strata Grammar","compositional-communication","composed-message-decoded-from-knowledge-retained-after-physical-probe-restoration","A layered quarry stacks grouped glyphs and relations above reversible world and persistent knowledge rails."),
"q630":("Spore Sandbox","counterfactual-planning","persistent-simulation-evidence-committed-only-at-sparse-shared-events-of-unequal-clocks","A dual glass greenhouse aligns two spore simulations above unequal clock and evidence bands."),
"q658":("Breakwater Analogy","structural-analogy","latent-channel-transform-activates-after-two-branches-before-relational-transfer","A paired harbor gallery maps four source channels to targets above dormant transform and subgoal rails."),
"q688":("Breakwater Evidence","confidence-calibration","first-unequal-sample-remains-dormant-until-two-subgoals-before-safe-stopping","A bronze evidence harbor stacks three channel samples above pending and solved-subgoal tracks."),
"q717":("Canopy Gradient","continuous-quantity-reasoning","conserved-seed-distribution-routed-through-a-capacity-limited-seasonal-store","A pale terraced orchard holds three quantity bays above store, season, observation, and commitment bands."),
"q748":("Breakwater Obligation","long-horizon-credit-assignment","first-creditor-remains-dormant-across-two-subgoals-then-constrains-repayment-by-identity","A dark creditor harbor displays two identity channels above debt, reward, subgoal, and repayment rails."),
"q778":("Breakwater Rhythm","temporal-abstraction","first-timing-offset-activates-only-after-two-completed-routines-before-interruption","A bright timing harbor layers local pulses, macro routines, dormant offset, and interruption bands."),
"q478":("Breakwater Dependency","hierarchical-goal-discovery","one-dormant-key-activates-after-two-subgoals-and-governs-every-later-assembly","A blue assembly harbor grows terminal parts beneath three tide channels and a delayed key rail.")}
def load(c):
 p=ROOT/"docs"/"static"/"games"/"src"/f"{c}-v1"/f"{c}.py";s=importlib.util.spec_from_file_location(c,p);m=importlib.util.module_from_spec(s);s.loader.exec_module(m);return p,m
def main():
 games=[];out=ROOT/"research"/"games";out.mkdir(parents=True,exist_ok=True)
 for c,(title,axis,primary,silhouette) in CFG.items():
  p,m=load(c);h=hashlib.sha256(p.read_bytes()).hexdigest();rel=p.relative_to(ROOT).as_posix();names=[x["name"] for x in m.LEVELS];g=getattr(m,c.upper())();frame=g.perform_action(ActionInput(id=GameAction.RESET),raw=True).frame[-1];palette=sorted({int(v) for row in frame for v in row})
  meta={"schema_version":1,"game_id":c,"version":"v1","internal_title":title,"public_title":None,"author_partition":"gpt","authorship":{"model_family":"OpenAI GPT-5","model_snapshot":"current Codex task model; exact deployment id not exposed to task","session_id":SESSION,"created_at":"2026-08-30T00:00:00Z","source_lineage":[f"research/gpt-ideas-v2.tsv:{c}"],"source_commit":None},"mechanics":{"primary":primary,"secondary":[axis,"underrepresented-capability-expansion"],"novelty_claim":names[-1],"closest_prior_art":["research/coverage-gap-study-v1.md","research/flash-game-mechanics-survey.md"]},"failure_modes":["forgets the first intervention because its consequence remains visually dormant across solved subgoals","attributes a delayed affordance or obligation to the latest visible object instead of causal identity","commits at a local event, overfills an intermediate store, or treats temporary simulation progress as persistent evidence"],"interface":{"actions":[1,2,3,4,5,6],"observation":"64x64x16","deterministic":True,"seeded_stochasticity":False},"progression":[{"level":i+1,"role":["orient","discriminate","plan","compose","inhibit","synthesize"][i],"new_demand":n,"composes":list(range(1,i+1))} for i,n in enumerate(names)],"visual_identity":{"dominant_palette":palette,"silhouette_grammar":silhouette,"spatial_grammar":silhouette,"motion_grammar":primary.replace("-"," "),"hud_grammar":"Tide-gated channels, cargo skiffs, latent intervention bars, solved-subgoal tracks, spore clocks, seasonal stores, and terminal affordances expose state without text.","nearest_visual_games":[]},"evaluation":{"allowed_development_models":["deterministic-solvers","random-fuzzer","Qwen3.8 diagnostic only"],"held_out_evaluator":"anthropic","human_baseline_status":"not_started","held_out_status":"sealed"},"artifacts":{"source":rel,"metadata":f"research/games/{c}-v1.json","win_recording":f"research/recordings/{c}-v1-win.json","loss_recording":f"research/recordings/{c}-v1-loss.json","thumbnail":f"docs/static/img/games/{c}-v1.png","source_sha256":h},"status":"prototype"}
  (out/f"{c}-v1.json").write_text(json.dumps(meta,indent=2)+"\n");im=Image.new("RGB",(64,64));im.putdata([PAL[int(v)] for row in frame for v in row]);im.save(ROOT/"docs"/"static"/"img"/"games"/f"{c}-v1.png",optimize=True);games.append({"game_id":c,"title":title,"axis":axis,"levels":6,"source_sha256":h})
 path=ROOT/"research"/"gpt-batch61-v1.json";path.write_text(json.dumps({"schema_version":1,"batch_id":"gpt-batch61-v1","created_at":"2026-08-30T00:00:00Z","design":"Ten modular-harbor, quarry, greenhouse, and orchard environments preserve an early intervention, evidence item, clock relation, or capacity constraint across delayed activation and multiple solved subgoals.","games":games},indent=2)+"\n")
 sheet=Image.new("RGB",(800,352),(242,242,246));d=ImageDraw.Draw(sheet)
 for i,c in enumerate(CFG):
  im=Image.open(ROOT/"docs"/"static"/"img"/"games"/f"{c}-v1.png").resize((128,128),Image.Resampling.NEAREST);x,y=(i%5)*160+16,(i//5)*176+12;sheet.paste(im,(x,y));d.text((x,y+136),c,fill=(28,28,36))
 (ROOT/".cache").mkdir(exist_ok=True);sheet.save(ROOT/".cache"/"batch61-contact.png",optimize=True);print("10 metadata records",path)
if __name__=="__main__":main()
