"""Generate metadata, thumbnails, and the contact sheet for research Batch 64."""
import hashlib,importlib.util,json
from PIL import Image,ImageDraw
from arcengine import ActionInput,GameAction
from build_research_batch06_metadata import ROOT,SESSION,PAL
CFG={
"q519":("Reedbed Frame","multi-scale-reference-frames","local-controls-compose-with-a-rotating-salinity-frame-while-built-links-alter-function-and-route","A white flooded marsh arranges eight reed cells above frame, link, function, and crossing rails."),
"q549":("Reedbed Lesson","policy-learning-from-demonstration","conditional-policy-applications-also-rewire-the-route-the-policy-must-use","A silver flooded marsh places a demonstration over context, mutable-link, function, and gesture panes."),
"q579":("Reedbed Counter","adaptive-adversary","opponent-shaping-treatments-jointly-change-rival-state-function-and-connectivity","A gray flooded marsh aligns three tactic beds above rival, link, function, and exploit bars."),
"q609":("Reedbed Grammar","compositional-communication","grouped-relay-glyphs-compose-a-message-while-changing-the-relay-graph","A stone flooded marsh stacks pollen glyphs over rotating connection and decoded-code rows."),
"q639":("Reedbed Sandbox","counterfactual-planning","simulation-evidence-persists-while-temporary-functions-and-links-reset","A charcoal flooded marsh places two miniature systems above persistent evidence and reset tracks."),
"q669":("Reedbed Analogy","structural-analogy","relational-structure-transfers-through-bridges-that-change-both-function-and-connectivity","A black flooded gallery maps source links to a contrasting target above bridge and relation rails."),
"q699":("Reedbed Evidence","confidence-calibration","unequal-sensor-components-build-a-network-until-no-remaining-result-can-reverse-the-choice","A pink flooded evidence garden places three sensor beds above mutable links and signed margin bars."),
"q729":("Reedbed Gradient","continuous-quantity-reasoning","conserved-mass-crosses-capacity-changing-links-under-visible-phase-control","A rose flooded marsh holds three quantity basins above target, link-capacity, and phase tracks."),
"q789":("Reedbed Rhythm","temporal-abstraction","constructed-links-change-autonomous-period-before-a-state-defined-interruption","A blue flooded timing marsh layers alternating routines above pulse, macro, link, and period rails."),
"q477":("Canopy Dependency","hierarchical-goal-discovery","one-shared-glider-serves-nested-branches-through-a-hard-capacity-seed-store","A cyan terraced orchard grows reusable branches above store, shared-tool, season, and completion bars.")}
def load(c):
 p=ROOT/"docs"/"static"/"games"/"src"/f"{c}-v1"/f"{c}.py";s=importlib.util.spec_from_file_location(c,p);m=importlib.util.module_from_spec(s);s.loader.exec_module(m);return p,m
def main():
 games=[];out=ROOT/"research"/"games";out.mkdir(parents=True,exist_ok=True)
 for c,(title,axis,primary,silhouette) in CFG.items():
  p,m=load(c);h=hashlib.sha256(p.read_bytes()).hexdigest();rel=p.relative_to(ROOT).as_posix();names=[x["name"] for x in m.LEVELS];g=getattr(m,c.upper())();frame=g.perform_action(ActionInput(id=GameAction.RESET),raw=True).frame[-1];palette=sorted({int(v) for row in frame for v in row})
  meta={"schema_version":1,"game_id":c,"version":"v1","internal_title":title,"public_title":None,"author_partition":"gpt","authorship":{"model_family":"OpenAI GPT-5","model_snapshot":"current Codex task model; exact deployment id not exposed to task","session_id":SESSION,"created_at":"2026-08-30T00:00:00Z","source_lineage":[f"research/gpt-ideas-v2.tsv:{c}"],"source_commit":None},"mechanics":{"primary":primary,"secondary":[axis,"underrepresented-capability-expansion"],"novelty_claim":names[-1],"closest_prior_art":["research/coverage-gap-study-v1.md","research/flash-game-mechanics-survey.md"]},"failure_modes":["optimizes a component's immediate function while ignoring the route edge it creates or removes","copies local controls without composing them with the rotating frame or changed graph","overfills the intermediate store, discards persistent simulation evidence, or stops before the margin is safe"],"interface":{"actions":[1,2,3,4,5,6],"observation":"64x64x16","deterministic":True,"seeded_stochasticity":False},"progression":[{"level":i+1,"role":["orient","discriminate","plan","compose","inhibit","synthesize"][i],"new_demand":n,"composes":list(range(1,i+1))} for i,n in enumerate(names)],"visual_identity":{"dominant_palette":palette,"silhouette_grammar":silhouette,"spatial_grammar":silhouette,"motion_grammar":primary.replace("-"," "),"hud_grammar":"Flooded basins, reed cells, beetle markers, mutable link bars, function rails, sensor beds, capacity channels, terraces, and shared gliders expose state without text.","nearest_visual_games":[]},"evaluation":{"allowed_development_models":["deterministic-solvers","random-fuzzer","Qwen3.8 diagnostic only"],"held_out_evaluator":"anthropic","human_baseline_status":"not_started","held_out_status":"sealed"},"artifacts":{"source":rel,"metadata":f"research/games/{c}-v1.json","win_recording":f"research/recordings/{c}-v1-win.json","loss_recording":f"research/recordings/{c}-v1-loss.json","thumbnail":f"docs/static/img/games/{c}-v1.png","source_sha256":h},"status":"prototype"}
  (out/f"{c}-v1.json").write_text(json.dumps(meta,indent=2)+"\n");im=Image.new("RGB",(64,64));im.putdata([PAL[int(v)] for row in frame for v in row]);im.save(ROOT/"docs"/"static"/"img"/"games"/f"{c}-v1.png",optimize=True);games.append({"game_id":c,"title":title,"axis":axis,"levels":6,"source_sha256":h})
 path=ROOT/"research"/"gpt-batch64-v1.json";path.write_text(json.dumps({"schema_version":1,"batch_id":"gpt-batch64-v1","created_at":"2026-08-30T00:00:00Z","design":"Nine colorful flooded-marsh environments make every component alter both function and connectivity across frames, policies, rivals, messages, simulations, analogies, evidence, quantities, and rhythms; a terraced orchard adds reusable prerequisites under a hard store capacity.","games":games},indent=2)+"\n")
 sheet=Image.new("RGB",(800,352),(242,242,246));d=ImageDraw.Draw(sheet)
 for i,c in enumerate(CFG):
  im=Image.open(ROOT/"docs"/"static"/"img"/"games"/f"{c}-v1.png").resize((128,128),Image.Resampling.NEAREST);x,y=(i%5)*160+16,(i//5)*176+12;sheet.paste(im,(x,y));d.text((x,y+136),c,fill=(28,28,36))
 (ROOT/".cache").mkdir(exist_ok=True);sheet.save(ROOT/".cache"/"batch64-contact.png",optimize=True);print("10 metadata records",path)
if __name__=="__main__":main()
