"""Generate metadata, thumbnails, and the contact sheet for research Batch 74."""
import hashlib,importlib.util,json
from PIL import Image,ImageDraw
from arcengine import ActionInput,GameAction
from build_research_batch06_metadata import ROOT,SESSION,PAL
CFG={
"q524":("Tessera Frame","multi-scale-reference-frames","tile-motion-composes-across-rotating-mosaic-frames-while-folds-rewire-the-topology-changing-seams","A bright folding mosaic arranges nine colored tessera panels above seam, orientation, and fold rails."),
"q541":("Tapestry Lesson","policy-learning-from-demonstration","contextual-weaving-demonstrations-separate-a-null-gesture-from-the-policy-that-rewires-the-completed-loom","A pale kinetic loom suspends six shuttles above demonstration traces, weave state, and graph-rewire rails."),
"q572":("Lockwater Counter","adaptive-adversary","a-three-tactic-canal-rival-responds-to-recent-treatment-while-barges-swap-position-and-appearance-but-retain-identity","A blue stepped canal places three identity-bearing barges over a treatment memory and rival-state strip."),
"q603":("Murmuration Grammar","compositional-communication","grouped-flock-messages-compose-through-wind-relays-while-a-redundant-parity-relation-detects-a-decoy","A violet aviary layers wind glyphs, flock groups, message history, and a parity acceptance rail."),
"q632":("Lockwater Sandbox","counterfactual-planning","canal-trials-reset-barge-position-appearance-and-water-level-while-identity-indexed-wake-evidence-persists","A green canal laboratory contrasts a stepped trial basin with a reset bay and persistent evidence notebook."),
"q652":("Tide Analogy","structural-analogy","reversing-current-relations-transfer-from-geometric-source-pairs-to-shell-carriers-before-an-irreversible-gate","A yellow tidal basin presents current geometry and shell carriers in paired source and target pools."),
"q692":("Lockwater Evidence","confidence-calibration","unequal-water-gauge-samples-follow-causal-barge-identities-through-swaps-until-the-signed-margin-supports-stopping","A peach stepped canal aligns three barges over identity-indexed samples and a centered confidence rail."),
"q723":("Murmuration Gradient","continuous-quantity-reasoning","conserved-flock-mass-crosses-capacity-limited-wind-wakes-while-a-visible-parity-check-tracks-each-transfer","A rose aviary uses four vertical flock reservoirs above alternating wind, flow, phase, and parity rails."),
"q747":("Canopy Obligation","long-horizon-credit-assignment","borrowed-seed-debt-remains-attached-to-identity-through-seasonal-shade-and-a-capacity-one-intermediate-store","A slate terraced orchard places three seed identities above a narrow store, shade phase, and creditor ledger."),
"q781":("Tapestry Rhythm","temporal-abstraction","a-weaving-macro-must-be-interrupted-at-a-state-defined-dual-clock-window-after-pattern-completion-rewires-adjacency","A gold kinetic loom arranges twelve shuttle nodes above fast, slow, pattern, topology, and interruption rails.")}
def load(c):
 p=ROOT/"docs"/"static"/"games"/"src"/f"{c}-v1"/f"{c}.py";s=importlib.util.spec_from_file_location(c,p);m=importlib.util.module_from_spec(s);s.loader.exec_module(m);return p,m
def main():
 games=[];out=ROOT/"research"/"games";out.mkdir(parents=True,exist_ok=True)
 for c,(title,axis,primary,silhouette) in CFG.items():
  p,m=load(c);h=hashlib.sha256(p.read_bytes()).hexdigest();rel=p.relative_to(ROOT).as_posix();names=[x["name"] for x in m.LEVELS];g=getattr(m,c.upper())();frame=g.perform_action(ActionInput(id=GameAction.RESET),raw=True).frame[-1];palette=sorted({int(v) for row in frame for v in row})
  meta={"schema_version":1,"game_id":c,"version":"v1","internal_title":title,"public_title":None,"author_partition":"gpt","authorship":{"model_family":"OpenAI GPT-5","model_snapshot":"current Codex task model; exact deployment id not exposed to task","session_id":SESSION,"created_at":"2026-08-31T00:00:00Z","source_lineage":[f"research/gpt-ideas-v2.tsv:{c}"],"source_commit":None},"mechanics":{"primary":primary,"secondary":[axis,"underrepresented-capability-expansion"],"novelty_claim":names[-1],"closest_prior_art":["research/coverage-gap-study-v1.md","research/flash-game-mechanics-survey.md"]},"failure_modes":["uses screen coordinates while ignoring the moving mosaic, current, wind, or topology frame","copies an observed sequence without inferring context, relay composition, rival adaptation, or persistent experiment state","tracks visible appearance rather than causal identity when barges, shells, flocks, seeds, or shuttles exchange roles"],"interface":{"actions":[1,2,3,4,5,6],"observation":"64x64x16","deterministic":True,"seeded_stochasticity":False},"progression":[{"level":i+1,"role":["orient","discriminate","plan","compose","inhibit","synthesize"][i],"new_demand":n,"composes":list(range(1,i+1))} for i,n in enumerate(names)],"visual_identity":{"dominant_palette":palette,"silhouette_grammar":silhouette,"spatial_grammar":silhouette,"motion_grammar":primary.replace("-"," "),"hud_grammar":"Mosaic seams, loom shuttles, canal barges, flock wakes, experiment notebooks, tidal sources, identity samples, conserved reservoirs, narrow stores, creditor ledgers, dual clocks, and graph rewires expose state without text.","nearest_visual_games":[]},"evaluation":{"allowed_development_models":["deterministic-solvers","random-fuzzer","Qwen3.8 diagnostic only"],"held_out_evaluator":"anthropic","human_baseline_status":"not_started","held_out_status":"sealed"},"artifacts":{"source":rel,"metadata":f"research/games/{c}-v1.json","win_recording":f"research/recordings/{c}-v1-win.json","loss_recording":f"research/recordings/{c}-v1-loss.json","thumbnail":f"docs/static/img/games/{c}-v1.png","source_sha256":h},"status":"prototype"}
  (out/f"{c}-v1.json").write_text(json.dumps(meta,indent=2)+"\n");im=Image.new("RGB",(64,64));im.putdata([PAL[int(v)] for row in frame for v in row]);im.save(ROOT/"docs"/"static"/"img"/"games"/f"{c}-v1.png",optimize=True);games.append({"game_id":c,"title":title,"axis":axis,"levels":6,"source_sha256":h})
 path=ROOT/"research"/"gpt-batch74-v1.json";path.write_text(json.dumps({"schema_version":1,"batch_id":"gpt-batch74-v1","created_at":"2026-08-31T00:00:00Z","design":"Seven colorful material settings—folding mosaics, kinetic looms, stepped canals, open aviaries, a reset laboratory, a tidal basin, and a terraced orchard—compose moving frames, conditional policy, adaptive rivals, parity language, persistent evidence, analogy, calibrated sampling, conserved flow, identity obligation, and macro-time.","games":games},indent=2)+"\n")
 sheet=Image.new("RGB",(800,352),(242,242,246));d=ImageDraw.Draw(sheet)
 for i,c in enumerate(CFG):
  im=Image.open(ROOT/"docs"/"static"/"img"/"games"/f"{c}-v1.png").resize((128,128),Image.Resampling.NEAREST);x,y=(i%5)*160+16,(i//5)*176+12;sheet.paste(im,(x,y));d.text((x,y+136),c,fill=(28,28,36))
 (ROOT/".cache").mkdir(exist_ok=True);sheet.save(ROOT/".cache"/"batch74-contact.png",optimize=True);print("10 metadata records",path)
if __name__=="__main__":main()
