"""Generate metadata, thumbnails, and contact sheet for research Batch 78."""
import hashlib,importlib.util,json
from PIL import Image,ImageDraw
from arcengine import ActionInput,GameAction
from build_research_batch06_metadata import ROOT,SESSION,PAL
CFG={
"q557":("Spectrum Lesson","policy-learning-from-demonstration","contextual-packet-demonstrations-reveal-a-relational-policy-across-dissimilar-prism-surfaces","An obsidian prism gallery arrays eight packet panes above demonstration, context, and surface rails."),
"q559":("Monsoon Lesson","policy-learning-from-demonstration","contextual-weather-demonstrations-reveal-a-policy-grounded-in-unequal-fast-and-slow-phase-pairs","An ivory weather garden arranges twelve storm cells above traces and unequal clock rails."),
"q571":("Tapestry Counter","adaptive-adversary","a-three-tactic-loom-rival-updates-from-recent-treatments-while-pattern-completion-rewires-adjacency","A blue kinetic loom places eight shuttles above treatment memory, rival state, and graph rail."),
"q592":("Tide Grammar","compositional-communication","grouped-shell-messages-compose-through-current-relays-before-an-irreversible-tidal-gate","A violet tidal basin stacks six shell lanes over grouped messages, relay history, and gate state."),
"q650":("Workbench Sandbox","counterfactual-planning","tools-fixtures-and-debt-reset-physically-while-observed-toolmark-evidence-persists-across-trials","A green workshop laboratory contrasts a tool bench with a reset bay and persistent evidence."),
"q672":("Semaphore Analogy","structural-analogy","relay-gap-relations-transfer-between-dissimilar-signals-after-contrasting-miniature-policy-tests","A yellow signal yard presents paired source and target panels above miniature tests and beam state."),
"q693":("Murmuration Evidence","confidence-calibration","wind-samples-update-a-costed-margin-that-is-accepted-only-when-the-visible-parity-relation-is-consistent","A peach aviary layers eight flock cells above signed samples and a centered parity margin."),
"q734":("Tessera Gradient","continuous-quantity-reasoning","conserved-tile-mass-crosses-capacity-limited-seams-while-a-macro-must-be-interrupted-at-one-window","A rose mosaic uses four tessera reservoirs above seam flow and a macro-window rail."),
"q751":("Tapestry Obligation","long-horizon-credit-assignment","thread-debt-remains-attached-to-shuttle-identity-after-completed-patterns-rewire-the-loom-graph","A slate loom tracks three shuttle identities above graph and debt rails."),
"q792":("Semaphore Rhythm","temporal-abstraction","a-signal-macro-is-interrupted-at-a-dual-clock-phase-window-supported-by-two-miniature-tests","A gold signal yard arranges twelve flag nodes above test pulses and fast and slow clocks.")}
def load(c):
 p=ROOT/"docs"/"static"/"games"/"src"/f"{c}-v1"/f"{c}.py";s=importlib.util.spec_from_file_location(c,p);m=importlib.util.module_from_spec(s);s.loader.exec_module(m);return p,m
def main():
 games=[];out=ROOT/"research"/"games";out.mkdir(parents=True,exist_ok=True)
 for c,(title,axis,primary,silhouette) in CFG.items():
  p,m=load(c);h=hashlib.sha256(p.read_bytes()).hexdigest();rel=p.relative_to(ROOT).as_posix();names=[x["name"] for x in m.LEVELS];g=getattr(m,c.upper())();frame=g.perform_action(ActionInput(id=GameAction.RESET),raw=True).frame[-1];palette=sorted({int(v) for row in frame for v in row})
  meta={"schema_version":1,"game_id":c,"version":"v1","internal_title":title,"public_title":None,"author_partition":"gpt","authorship":{"model_family":"OpenAI GPT-5","model_snapshot":"current Codex task model; exact deployment id not exposed to task","session_id":SESSION,"created_at":"2026-08-31T00:00:00Z","source_lineage":[f"research/gpt-ideas-v2.tsv:{c}"],"source_commit":None},"mechanics":{"primary":primary,"secondary":[axis,"underrepresented-capability-expansion"],"novelty_claim":names[-1],"closest_prior_art":["research/coverage-gap-study-v1.md","research/flash-game-mechanics-survey.md"]},"failure_modes":["uses screen position while ignoring prism surface, weather phase, loom graph, current relay, fixture, beam, parity, seam, or clock state","copies surface actions without inferring demonstrations, adaptation, syntax, persistent evidence, analogy, or calibrated stopping","loses conservation or causal identity across rearrangement"],"interface":{"actions":[1,2,3,4,5,6],"observation":"64x64x16","deterministic":True,"seeded_stochasticity":False},"progression":[{"level":i+1,"role":["orient","discriminate","plan","compose","inhibit","synthesize"][i],"new_demand":n,"composes":list(range(1,i+1))} for i,n in enumerate(names)],"visual_identity":{"dominant_palette":palette,"silhouette_grammar":silhouette,"spatial_grammar":silhouette,"motion_grammar":primary.replace("-"," "),"hud_grammar":"Prism panes, storm clocks, loom graphs, shell messages, reset benches, signal tests, parity margins, tessera reservoirs, identity debt, and phase windows expose state without text.","nearest_visual_games":[]},"evaluation":{"allowed_development_models":["deterministic-solvers","random-fuzzer","Qwen3.8 diagnostic only"],"held_out_evaluator":"anthropic","human_baseline_status":"not_started","held_out_status":"sealed"},"artifacts":{"source":rel,"metadata":f"research/games/{c}-v1.json","win_recording":f"research/recordings/{c}-v1-win.json","loss_recording":f"research/recordings/{c}-v1-loss.json","thumbnail":f"docs/static/img/games/{c}-v1.png","source_sha256":h},"status":"prototype"}
  (out/f"{c}-v1.json").write_text(json.dumps(meta,indent=2)+"\n");im=Image.new("RGB",(64,64));im.putdata([PAL[int(v)] for row in frame for v in row]);im.save(ROOT/"docs"/"static"/"img"/"games"/f"{c}-v1.png",optimize=True);games.append({"game_id":c,"title":title,"axis":axis,"levels":6,"source_sha256":h})
 path=ROOT/"research"/"gpt-batch78-v1.json";path.write_text(json.dumps({"schema_version":1,"batch_id":"gpt-batch78-v1","created_at":"2026-08-31T00:00:00Z","design":"Eight colorful systems compose contextual demonstrations, adaptive topology, grouped tidal language, persistent workshop trials, tested analogy, parity-calibrated evidence, conserved mosaic flow, identity debt, and dual-clock signal interruption.","games":games},indent=2)+"\n")
 sheet=Image.new("RGB",(800,352),(242,242,246));d=ImageDraw.Draw(sheet)
 for i,c in enumerate(CFG):
  im=Image.open(ROOT/"docs"/"static"/"img"/"games"/f"{c}-v1.png").resize((128,128),Image.Resampling.NEAREST);x,y=(i%5)*160+16,(i//5)*176+12;sheet.paste(im,(x,y));d.text((x,y+136),c,fill=(28,28,36))
 (ROOT/".cache").mkdir(exist_ok=True);sheet.save(ROOT/".cache"/"batch78-contact.png",optimize=True);print("10 metadata records",path)
if __name__=="__main__":main()
