"""Generate metadata and visual artifacts for research Batch 21."""
import hashlib,importlib.util,json
from PIL import Image,ImageDraw
from arcengine import ActionInput,GameAction
from build_research_batch06_metadata import ROOT,SESSION,PAL
CFG={
"q511":("Tapestry Frame","multi-scale-reference-frames","moving-local-frame-with-pattern-rewired-adjacency",["frame-composition","graph-rewrite"],["uses screen-relative motion","misses the parity split after rewiring","forgets the frame translates every action"],[1,2,3,5,6],"A yellow shuttle moves through white local frames before a green pattern rewires the loom."),
"q542":("Lockwater Lesson","policy-learning-from-demonstration","conditional-policy-inference-with-causally-ineffective-gestures",["context-switch","noise-rejection"],["clones the failed gesture","uses one mapping across contexts","tracks barge appearance instead of identity"],[1,2,3,4,5,6],"Blue barges demonstrate conditional moves across orange coupled water levels."),
"q573":("Murmuration Counter","adaptive-adversary","shape-recent-history-to-induce-an-exploitable-tactic",["opponent-state-control","parity-validation"],["responds to the current tactic immediately","ignores the history window","accepts the misleading observation without parity"],[1,2,3,4,5],"Pink flocks reshape an orange wind history beneath a white opponent tactic marker."),
"q604":("Moraine Grammar","compositional-communication","grouped-spatial-command-composition-through-local-relays",["relay-transform","outer-dependency"],["treats primitives as global symbols","reverses group and relation","ignores the relay shift"],[1,2,3,4,5],"Yellow rafts exchange grouped orange relations through white relays in a blue glacier."),
"q635":("Waystation Sandbox","counterfactual-planning","persistent-evidence-from-reset-miniatures-before-one-main-commit",["experiment-execution-separation","model-selection"],["commits after testing one copy","forgets evidence on reset","carries simulated progress into the main system"],[1,2,3,4,5],"Two orange caravan sandboxes leave green evidence before a single dark main commitment."),
"q666":("Backstage Analogy","structural-analogy","sightline-to-actor-relational-transfer-with-quantity-threshold",["surface-invariance","accumulated-influence"],["matches actor colors","changes the relational order","ignores accumulated influence"],[1,2,3,4],"Pink sightlines and orange mask actors share one relational score on a blue stage."),
"q697":("Catalyst Evidence","confidence-calibration","reliability-weighted-stopping-when-leader-cannot-change",["value-of-information","memory-execution"],["counts samples equally","stops while remaining evidence can reverse the leader","writes the wrong candidate into memory"],[1,3,5,6],"White samples feed unequal green and pink evidence bars through a coral refinery."),
"q728":("Asterism Gradient","continuous-quantity-reasoning","conserved-phased-distribution-with-evidence-preserving-reset",["gradient-threshold","experiment-execution-separation"],["changes total influence","forgets target phase","resets before crossing the probe threshold"],[1,2,3,4,5,6],"White influence climbs pink star columns across a blue orbital chart and green phase rail."),
"q759":("Reedbed Obligation","long-horizon-credit-assignment","identity-bound-debt-through-delayed-reward-and-tool-construction",["causal-identity","connectivity-side-effect"],["repays the current appearance","forgets the early helper","builds a locally useful wrong component"],[1,2,3],"Pink beetles carry an obligation across green rewards and yellow marsh construction."),
"q790":("Vault Rhythm","temporal-abstraction","event-chunked-interrupt-with-two-conserved-shared-stores",["macro-timing","dual-conservation"],["counts frames instead of events","interrupts outside the state window","balances only one stored quantity"],[1,2,3,4,5],"Two colored stores fill beneath a white autonomous rhythm in a dark branching vault.")}
def load(c):
 p=ROOT/"docs"/"static"/"games"/"src"/f"{c}-v1"/f"{c}.py";s=importlib.util.spec_from_file_location(c,p);m=importlib.util.module_from_spec(s);s.loader.exec_module(m);return p,m
def main():
 games=[];out=ROOT/"research"/"games"
 for c,v in CFG.items():
  title,axis,primary,secondary,failures,actions,sil=v;p,m=load(c);h=hashlib.sha256(p.read_bytes()).hexdigest();rel=p.relative_to(ROOT).as_posix();names=[x["name"] for x in m.LEVELS]
  meta={"schema_version":1,"game_id":c,"version":"v1","internal_title":title,"public_title":None,"author_partition":"gpt","authorship":{"model_family":"OpenAI GPT-5","model_snapshot":"current Codex task model; exact deployment id not exposed to task","session_id":SESSION,"created_at":"2026-08-30T00:00:00Z","source_lineage":[f"research/gpt-ideas-v2.tsv:{c}"],"source_commit":None},"mechanics":{"primary":primary,"secondary":secondary,"novelty_claim":names[-1],"closest_prior_art":["research/coverage-gap-study-v1.md","research/flash-game-mechanics-survey.md"]},"failure_modes":failures,"interface":{"actions":actions,"observation":"64x64x16","deterministic":True,"seeded_stochasticity":False},"progression":[{"level":i+1,"role":["orient","discriminate","plan","compose","inhibit","synthesize"][i],"new_demand":n,"composes":list(range(1,i+1))} for i,n in enumerate(names)],"visual_identity":{"dominant_palette":[],"silhouette_grammar":sil,"spatial_grammar":sil,"motion_grammar":primary.replace("-"," "),"hud_grammar":"Persistent colored state markers expose the mechanic without text.","nearest_visual_games":[]},"evaluation":{"allowed_development_models":["deterministic-solvers","random-fuzzer","Qwen3.8 diagnostic only"],"held_out_evaluator":"anthropic","human_baseline_status":"not_started","held_out_status":"sealed"},"artifacts":{"source":rel,"metadata":f"research/games/{c}-v1.json","win_recording":f"research/recordings/{c}-v1-win.json","loss_recording":f"research/recordings/{c}-v1-loss.json","thumbnail":f"docs/static/img/games/{c}-v1.png","source_sha256":h},"status":"prototype"}
  (out/f"{c}-v1.json").write_text(json.dumps(meta,indent=2)+"\n");g=getattr(m,c.upper())();a=g.perform_action(ActionInput(id=GameAction.RESET),raw=True).frame[-1];im=Image.new("RGB",(64,64));im.putdata([PAL[int(x)] for row in a for x in row]);im.save(ROOT/"docs"/"static"/"img"/"games"/f"{c}-v1.png",optimize=True);games.append({"game_id":c,"title":title,"axis":axis,"levels":6,"source_sha256":h})
 path=ROOT/"research"/"gpt-batch21-v1.json";path.write_text(json.dumps({"schema_version":1,"batch_id":"gpt-batch21-v1","created_at":"2026-08-30T00:00:00Z","design":"Ten expanded-ledger games across the remaining capability axes and new domain offsets, each with six progressive levels and a distinct environment.","games":games},indent=2)+"\n")
 sheet=Image.new("RGB",(800,352),(242,242,246));d=ImageDraw.Draw(sheet)
 for i,c in enumerate(CFG):im=Image.open(ROOT/"docs"/"static"/"img"/"games"/f"{c}-v1.png").resize((128,128),Image.Resampling.NEAREST);x,y=(i%5)*160+16,(i//5)*176+12;sheet.paste(im,(x,y));d.text((x,y+136),c,fill=(28,28,36))
 sheet.save(ROOT/".cache"/"batch21-contact.png",optimize=True);print("10 metadata records",path)
if __name__=="__main__":main()
