"""Generate metadata, thumbnails, and a contact sheet for research Batch 94."""
import hashlib,importlib.util,json
from PIL import Image,ImageDraw
from arcengine import ActionInput,GameAction
from build_research_batch06_metadata import ROOT,SESSION,PAL
CFG={
"a131":("Symmetry Breaker","symmetry-breaking-and-canonicalization","minimal-marker-induced-complete-traversal","A magenta scanner ring surrounds eight identical machine parts with one movable marker, traversal direction, coverage, and repeats."),
"a132":("Orbit Representative","symmetry-breaking-and-canonicalization","one-selection-per-generated-symmetry-orbit","A pale four-by-four orbit board switches transformation generators while exposing selected representatives, uncovered orbits, and duplicates."),
"a133":("Anonymous Robots","symmetry-breaking-and-canonicalization","environment-grounded-robot-distinguishability","A dark four-robot chamber combines identical bodies with optional landmarks, local roles, cursor, and distinct-view count."),
"a134":("Tie Break","symmetry-breaking-and-canonicalization","shared-geometric-deterministic-choice","A black gate presents equal parallel routes, five identical arrivals, a geometric priority cue, and consensus outcome."),
"a135":("Asymmetric Seed","symmetry-breaking-and-canonicalization","symmetry-class-selected-macroscopic-growth","A cream cellular laboratory places one seed in a four-by-four symmetric field before growth, collision, and travel evaluation."),
"a136":("Normal Form","symmetry-breaking-and-canonicalization","terminating-oriented-rewrite-normalization","A steel rewrite desk arrays six reversible diagrams with selectable orientation, local rule state, normality, and cycle count."),
"a137":("Undo Group","reversible-transformation-algebra","reverse-ordered-composition-of-latent-inverses","A green machine workshop raises five scrambled objects above origins while exposing control inversion, selection, restoration, and error."),
"a138":("Commutator Lock","reversible-transformation-algebra","noncommutative-residual-isolation","A coral three-by-three lock tracks a hidden marker under A, B, inverse, and commutator traces with displacement and disturbance."),
"a139":("Inverse Pair","reversible-transformation-algebra","composition-tested-latent-inverse-matching","A black composition bench connects two columns of machines around cargo probes, restored appearance, movement, and pairing errors."),
"a140":("Conjugate Corridor","reversible-transformation-algebra","basis-transported-local-control","A gold lattice corridor wraps local movement between entry and exit basis transforms toward a global target cell."),
}
def load(c):
 p=ROOT/"docs"/"static"/"games"/"src"/f"{c}-v1"/f"{c}.py";s=importlib.util.spec_from_file_location(c,p);m=importlib.util.module_from_spec(s);s.loader.exec_module(m);return p,m
def main():
 games=[];out=ROOT/"research"/"games";out.mkdir(parents=True,exist_ok=True)
 for c,(title,axis,primary,silhouette) in CFG.items():
  p,m=load(c);h=hashlib.sha256(p.read_bytes()).hexdigest();rel=p.relative_to(ROOT).as_posix();names=[x["name"] for x in m.LEVELS];g=getattr(m,c.upper())();frame=g.perform_action(ActionInput(id=GameAction.RESET),raw=True).frame[-1];palette=sorted({int(v) for row in frame for v in row})
  meta={"schema_version":1,"game_id":c,"version":"v1","internal_title":title,"public_title":None,"author_partition":"gpt","authorship":{"model_family":"OpenAI GPT-5","model_snapshot":"current Codex task model; exact deployment id not exposed to task","session_id":SESSION,"created_at":"2026-08-31T00:00:00Z","source_lineage":[f"research/anthropic-build-ideas-v1.tsv:{c}"],"concept_lineage":"gpt-seeded-anthropic-build","intended_builder":"anthropic","implementation_author_partition":"gpt","source_commit":None},"mechanics":{"primary":primary,"secondary":[axis,"small-local-edits-with-global-algebraic-effects"],"novelty_claim":names[-1],"closest_prior_art":["research/anthropic-build-ideas-v1.audit.json","research/coverage-gap-study-v1.md","research/flash-game-mechanics-survey.md"]},"failure_modes":["breaks visual symmetry without creating process-level distinguishability, coverage, consensus, or unique growth","selects multiple members of one orbit or applies role commands before local observations differ","treats inverse order, commutators, inverse pairing, and basis conjugation as commuting surface transformations"],"interface":{"actions":[1,2,3,4,5,6],"observation":"64x64x16","deterministic":True,"seeded_stochasticity":False},"progression":[{"level":i+1,"role":["orient","discriminate","plan","compose","inhibit","synthesize"][i],"new_demand":n,"composes":list(range(1,i+1))} for i,n in enumerate(names)],"visual_identity":{"dominant_palette":palette,"silhouette_grammar":silhouette,"spatial_grammar":silhouette,"motion_grammar":primary.replace("-"," "),"hud_grammar":"Traversal, orbits, anonymity, consensus, growth, rewrite cycles, inverse error, commutator residue, composition tests, and conjugated motion expose algebraic state without text.","nearest_visual_games":[]},"evaluation":{"allowed_development_models":["deterministic-solvers","random-fuzzer","Qwen3.8 diagnostic only"],"held_out_evaluator":"anthropic","human_baseline_status":"not_started","held_out_status":"sealed"},"artifacts":{"source":rel,"metadata":f"research/games/{c}-v1.json","win_recording":f"research/recordings/{c}-v1-win.json","loss_recording":f"research/recordings/{c}-v1-loss.json","thumbnail":f"docs/static/img/games/{c}-v1.png","source_sha256":h},"status":"prototype"}
  (out/f"{c}-v1.json").write_text(json.dumps(meta,indent=2)+"\n");im=Image.new("RGB",(64,64));im.putdata([PAL[int(v)] for row in frame for v in row]);im.save(ROOT/"docs"/"static"/"img"/"games"/f"{c}-v1.png",optimize=True);games.append({"game_id":c,"title":title,"axis":axis,"levels":6,"source_sha256":h})
 path=ROOT/"research"/"gpt-batch94-v1.json";path.write_text(json.dumps({"schema_version":1,"batch_id":"gpt-batch94-v1","created_at":"2026-08-31T00:00:00Z","provenance":"Concepts retain gpt-seeded-anthropic-build queue lineage; implementations in this batch are authored by OpenAI GPT-5 and are not attributed to Anthropic.","design":"Six symmetry systems turn tiny environmental asymmetries into traversal, orbit coverage, identity, consensus, growth, and normal forms; four machine puzzles ground inverse order, commutators, inverse discovery, and conjugation.","games":games},indent=2)+"\n")
 sheet=Image.new("RGB",(800,352),(242,242,246));d=ImageDraw.Draw(sheet)
 for i,c in enumerate(CFG):
  im=Image.open(ROOT/"docs"/"static"/"img"/"games"/f"{c}-v1.png").resize((128,128),Image.Resampling.NEAREST);x,y=(i%5)*160+16,(i//5)*176+12;sheet.paste(im,(x,y));d.text((x,y+136),c,fill=(28,28,36))
 (ROOT/".cache").mkdir(exist_ok=True);sheet.save(ROOT/".cache"/"batch94-contact.png",optimize=True);print("10 metadata records",path)
if __name__=="__main__":main()
