"""Generate metadata, thumbnails, and the contact sheet for research Batch 56."""
import hashlib,importlib.util,json
from PIL import Image,ImageDraw
from arcengine import ActionInput,GameAction
from build_research_batch06_metadata import ROOT,SESSION,PAL
CFG={
"q120":("Hidden Policy Handoff","policy-learning-from-demonstration","continue-a-demonstrated-policy-from-the-tutors-latent-transfer-state","A white two-pane stage separates tutor and player traces above a latent-state rail."),
"q130":("Rhythm Rival","adaptive-adversary","cadence-adaptive-rival-opened-by-deliberate-irregular-timing","A silver timing arena places a rival pane beside colored cadence pulses."),
"q140":("Grounded Labels","compositional-communication","player-grounded-class-markers-reused-by-autonomous-workers","A gray worker yard stacks three class bays above reusable output markers."),
"q150":("Minimum Regret","counterfactual-planning","route-choice-by-minimum-worst-case-loss-and-preserved-recoverability","A charcoal route map exposes three corridors above sampled losses and fallback rails."),
"q160":("Tool Metamorphosis","structural-analogy","mechanical-part-relation-transferred-to-autonomous-agent-coordination","A red workshop transforms loose components into an agent formation above command rails."),
"q170":("Commit Threshold","confidence-calibration","decision-specific-evidence-threshold-learned-without-a-marked-target","A black evidence chamber couples an analog bar to three unlabelled decision blocks."),
"q180":("Gradient Climb","continuous-quantity-reasoning","local-delta-hill-climbing-through-smooth-fields-and-deceptive-plateaus","A magenta sampled field shows one climber and only its recent local gradient signs."),
"q190":("Lasting Shortcut","long-horizon-credit-assignment","one-global-route-change-persists-across-every-subsequent-level","A pink route network displays a persistent shortcut and changing travel direction rail."),
"q200":("Clock of Clocks","temporal-abstraction","local-period-completions-trigger-transitions-of-a-higher-level-clock","An orange clock tower stacks three local clocks above event and macro-state rails."),
"q471":("Aurora Dependency","hierarchical-goal-discovery","shared-prerequisite-reuse-through-a-visible-hysteresis-loop","A blue polar observatory grows crystal motes beneath sweeping curtains and branch rails.")}
def load(c):
 p=ROOT/"docs"/"static"/"games"/"src"/f"{c}-v1"/f"{c}.py";s=importlib.util.spec_from_file_location(c,p);m=importlib.util.module_from_spec(s);s.loader.exec_module(m);return p,m
def main():
 games=[];out=ROOT/"research"/"games";out.mkdir(parents=True,exist_ok=True)
 for c,(title,axis,primary,silhouette) in CFG.items():
  p,m=load(c);h=hashlib.sha256(p.read_bytes()).hexdigest();rel=p.relative_to(ROOT).as_posix();names=[x["name"] for x in m.LEVELS];g=getattr(m,c.upper())();frame=g.perform_action(ActionInput(id=GameAction.RESET),raw=True).frame[-1];palette=sorted({int(v) for row in frame for v in row})
  meta={"schema_version":1,"game_id":c,"version":"v1","internal_title":title,"public_title":None,"author_partition":"gpt","authorship":{"model_family":"OpenAI GPT-5","model_snapshot":"current Codex task model; exact deployment id not exposed to task","session_id":SESSION,"created_at":"2026-08-30T00:00:00Z","source_lineage":[f"research/gpt-ideas-v2.tsv:{c}"],"source_commit":None},"mechanics":{"primary":primary,"secondary":[axis,"underrepresented-capability-expansion"],"novelty_claim":names[-1],"closest_prior_art":["research/coverage-gap-study-v1.md","research/flash-game-mechanics-survey.md"]},"failure_modes":["restarts a transferred process instead of continuing its latent state","optimizes immediate or expected reward while discarding recoverability","collapses persistent, hierarchical, or macro state into the current visible frame"],"interface":{"actions":[1,2,3,4,5,6],"observation":"64x64x16","deterministic":True,"seeded_stochasticity":False},"progression":[{"level":i+1,"role":["orient","discriminate","plan","compose","inhibit","synthesize"][i],"new_demand":n,"composes":list(range(1,i+1))} for i,n in enumerate(names)],"visual_identity":{"dominant_palette":palette,"silhouette_grammar":silhouette,"spatial_grammar":silhouette,"motion_grammar":primary.replace("-"," "),"hud_grammar":"Colored tutor, cadence, label, loss, relation, evidence, gradient, shortcut, clock, and hysteresis rails expose state without text.","nearest_visual_games":[]},"evaluation":{"allowed_development_models":["deterministic-solvers","random-fuzzer","Qwen3.8 diagnostic only"],"held_out_evaluator":"anthropic","human_baseline_status":"not_started","held_out_status":"sealed"},"artifacts":{"source":rel,"metadata":f"research/games/{c}-v1.json","win_recording":f"research/recordings/{c}-v1-win.json","loss_recording":f"research/recordings/{c}-v1-loss.json","thumbnail":f"docs/static/img/games/{c}-v1.png","source_sha256":h},"status":"prototype"}
  (out/f"{c}-v1.json").write_text(json.dumps(meta,indent=2)+"\n");im=Image.new("RGB",(64,64));im.putdata([PAL[int(v)] for row in frame for v in row]);im.save(ROOT/"docs"/"static"/"img"/"games"/f"{c}-v1.png",optimize=True);games.append({"game_id":c,"title":title,"axis":axis,"levels":6,"source_sha256":h})
 path=ROOT/"research"/"gpt-batch56-v1.json";path.write_text(json.dumps({"schema_version":1,"batch_id":"gpt-batch56-v1","created_at":"2026-08-30T00:00:00Z","design":"Ten environments expanding underrepresented capability families: demonstration handoff, adaptive cadence, grounded communication, minimax recovery, structural transfer, calibration, gradients, persistent credit, temporal hierarchy, and hysteretic subgoals.","games":games},indent=2)+"\n")
 sheet=Image.new("RGB",(800,352),(242,242,246));d=ImageDraw.Draw(sheet)
 for i,c in enumerate(CFG):
  im=Image.open(ROOT/"docs"/"static"/"img"/"games"/f"{c}-v1.png").resize((128,128),Image.Resampling.NEAREST);x,y=(i%5)*160+16,(i//5)*176+12;sheet.paste(im,(x,y));d.text((x,y+136),c,fill=(28,28,36))
 (ROOT/".cache").mkdir(exist_ok=True);sheet.save(ROOT/".cache"/"batch56-contact.png",optimize=True);print("10 metadata records",path)
if __name__=="__main__":main()
