"""Generate metadata, thumbnails, and a contact sheet for research Batch 79."""
import hashlib,importlib.util,json
from PIL import Image,ImageDraw
from arcengine import ActionInput,GameAction
from build_research_batch06_metadata import ROOT,SESSION,PAL
CFG={
"q560":("Workbench Lesson","policy-learning-from-demonstration","contextual-tool-demonstrations-distinguish-null-gestures-while-helper-debt-remains-attached-to-identity","A pale mobile workshop uses three tool pedestals above demonstration, fixture, and helper-debt rails."),
"q585":("Vivarium Counter","adaptive-adversary","a-three-tactic-keeper-adapts-to-recent-fauna-treatment-and-a-visible-reciprocity-balance","An aqua stacked vivarium places three fauna columns above keeper memory, thermal strata, and fairness margin."),
"q588":("Escapement Counter","adaptive-adversary","clockwork-tactics-update-from-recent-weight-treatments-while-diagnostic-taps-separate-candidate-faults","A cobalt clock tower suspends three weights inside gear columns over diagnostic clues and phase state."),
"q602":("Lockwater Grammar","compositional-communication","grouped-barge-glyphs-compose-through-coupled-lock-relays-while-causal-identities-cross","A lilac stepped canal places two barge lanes above grouped glyphs, relay state, and identity marks."),
"q615":("Vivarium Grammar","compositional-communication","thermal-fauna-messages-compose-through-relays-whose-interpretation-depends-on-remembered-reciprocity","A moss terrarium stacks three microfauna habitats over thermal glyphs, trust, and relay rails."),
"q631":("Tapestry Sandbox","counterfactual-planning","miniature-loom-progress-resets-while-threadmark-evidence-persists-before-one-graph-rewiring-commit","A teal weaving studio contrasts a main loom and miniature copy above persistent threadmarks and graph state."),
"q642":("Semaphore Sandbox","counterfactual-planning","two-resettable-signal-copies-produce-persistent-beam-evidence-before-one-irreversible-policy-commit","A violet cliff yard presents paired miniature signal towers above persistent tests and occluded beam state."),
"q661":("Tapestry Analogy","structural-analogy","crossing-thread-relations-transfer-between-surface-dissimilar-shuttles-after-the-loom-graph-rewires","A cream tapestry studio pairs source and target looms above graph examples and a transfer rail."),
"q679":("Monsoon Analogy","structural-analogy","storm-relations-transfer-between-dissimilar-cloud-panels-only-at-inferred-fast-and-slow-phase-pairs","A peach weather garden pairs storm panels above sampled relations and unequal fast and slow clocks."),
"q702":("Semaphore Evidence","confidence-calibration","reliability-weighted-relay-samples-and-miniature-tests-support-stopping-only-at-a-decisive-visible-margin","A gold cliff yard arrays four signal towers above weighted samples, miniature outcomes, and a signed margin.")}
def load(c):
 p=ROOT/"docs"/"static"/"games"/"src"/f"{c}-v1"/f"{c}.py";s=importlib.util.spec_from_file_location(c,p);m=importlib.util.module_from_spec(s);s.loader.exec_module(m);return p,m
def main():
 games=[];out=ROOT/"research"/"games";out.mkdir(parents=True,exist_ok=True)
 for c,(title,axis,primary,silhouette) in CFG.items():
  p,m=load(c);h=hashlib.sha256(p.read_bytes()).hexdigest();rel=p.relative_to(ROOT).as_posix();names=[x["name"] for x in m.LEVELS];g=getattr(m,c.upper())();frame=g.perform_action(ActionInput(id=GameAction.RESET),raw=True).frame[-1];palette=sorted({int(v) for row in frame for v in row})
  meta={"schema_version":1,"game_id":c,"version":"v1","internal_title":title,"public_title":None,"author_partition":"gpt","authorship":{"model_family":"OpenAI GPT-5","model_snapshot":"current Codex task model; exact deployment id not exposed to task","session_id":SESSION,"created_at":"2026-08-31T00:00:00Z","source_lineage":[f"research/gpt-ideas-v2.tsv:{c}"],"source_commit":None},"mechanics":{"primary":primary,"secondary":[axis,"underrepresented-capability-expansion"],"novelty_claim":names[-1],"closest_prior_art":["research/coverage-gap-study-v1.md","research/flash-game-mechanics-survey.md"]},"failure_modes":["uses screen position while ignoring context, reciprocity, phase, causal identity, relay, persistent evidence, graph, analogy, or reliability","copies a surface sequence without inferring the demonstrated policy, opponent update, syntax, counterfactual result, relational invariant, or stopping criterion","loses causal identity or retained evidence when entities, trials, or topology rearrange"],"interface":{"actions":[1,2,3,4,5,6],"observation":"64x64x16","deterministic":True,"seeded_stochasticity":False},"progression":[{"level":i+1,"role":["orient","discriminate","plan","compose","inhibit","synthesize"][i],"new_demand":n,"composes":list(range(1,i+1))} for i,n in enumerate(names)],"visual_identity":{"dominant_palette":palette,"silhouette_grammar":silhouette,"spatial_grammar":silhouette,"motion_grammar":primary.replace("-"," "),"hud_grammar":"Tool pedestals, fauna strata, clock weights, canal lanes, thermal glyphs, miniature looms, signal copies, paired analogies, phase clocks, and reliability margins expose latent state without text.","nearest_visual_games":[]},"evaluation":{"allowed_development_models":["deterministic-solvers","random-fuzzer","Qwen3.8 diagnostic only"],"held_out_evaluator":"anthropic","human_baseline_status":"not_started","held_out_status":"sealed"},"artifacts":{"source":rel,"metadata":f"research/games/{c}-v1.json","win_recording":f"research/recordings/{c}-v1-win.json","loss_recording":f"research/recordings/{c}-v1-loss.json","thumbnail":f"docs/static/img/games/{c}-v1.png","source_sha256":h},"status":"prototype"}
  (out/f"{c}-v1.json").write_text(json.dumps(meta,indent=2)+"\n");im=Image.new("RGB",(64,64));im.putdata([PAL[int(v)] for row in frame for v in row]);im.save(ROOT/"docs"/"static"/"img"/"games"/f"{c}-v1.png",optimize=True);games.append({"game_id":c,"title":title,"axis":axis,"levels":6,"source_sha256":h})
 path=ROOT/"research"/"gpt-batch79-v1.json";path.write_text(json.dumps({"schema_version":1,"batch_id":"gpt-batch79-v1","created_at":"2026-08-31T00:00:00Z","design":"Ten colorful systems combine contextual tool lessons, adaptive vivarium and clockwork rivals, compositional canal and thermal language, persistent miniature trials, graph and weather analogies, and reliability-calibrated signal evidence.","games":games},indent=2)+"\n")
 sheet=Image.new("RGB",(800,352),(242,242,246));d=ImageDraw.Draw(sheet)
 for i,c in enumerate(CFG):
  im=Image.open(ROOT/"docs"/"static"/"img"/"games"/f"{c}-v1.png").resize((128,128),Image.Resampling.NEAREST);x,y=(i%5)*160+16,(i//5)*176+12;sheet.paste(im,(x,y));d.text((x,y+136),c,fill=(28,28,36))
 (ROOT/".cache").mkdir(exist_ok=True);sheet.save(ROOT/".cache"/"batch79-contact.png",optimize=True);print("10 metadata records",path)
if __name__=="__main__":main()
