"""Generate metadata and visual artifacts for research Batch 18."""
import hashlib,importlib.util,json
from PIL import Image,ImageDraw
from arcengine import ActionInput,GameAction
from build_research_batch06_metadata import ROOT,SESSION,PAL
CFG={
"q109":("Body-Centric Maze","multi-scale-reference-frames","body-centered-actions-under-rotating-world-frame",["frame-conversion","landmark-tracking"],["uses world commands without conversion","loses rotation count","treats the landmark as moving"],[1,2,3,4],"A pink body and gold landmark anchor a maze that rotates after every move."),
"q118":("Distributed Lesson","policy-learning-from-demonstration","compose-policy-components-from-multiple-tutors",["component-integration","delayed-demonstration"],["acts before viewing every tutor","uses only the last component","replays an intermediate policy"],[1,2,3,4,5,6],"Three pink tutors contribute blue policy components inside a coral classroom."),
"q128":("Adaptive Patrol","adaptive-adversary","route-diversity-against-recently-adapted-patrol-density",["visit-history","anti-repetition"],["repeats a recently visited region","ignores decaying density","follows a static shortest path"],[1,2,3,4],"A pink traveler crosses a coral field while red patrol density follows recent choices."),
"q138":("Command Composition","compositional-communication","concatenate-object-direction-timing-primitives",["typed-syntax","chunk-boundaries"],["permutes primitive roles","commits an incomplete command","merges adjacent commands"],[1,2,3,4,5],"Object, direction, and timing glyphs combine at a bright white command console."),
"q148":("Delayed Commit","counterfactual-planning","queue-preview-and-irreversibly-commit-whole-path",["endpoint-simulation","commitment-control"],["commits without previewing","previews a prefix only","matches the endpoint with the wrong route"],[1,2,3,4,5,6],"A queued violet route casts a green preview across a yellow planning grid."),
"q158":("Causal Rhyme","structural-analogy","transfer-cause-effect-order-across-mechanism-styles",["order-isomorphism","appearance-invariance"],["matches surface appearance","reverses a causal link","relearns each mechanism independently"],[1,2,3,4],"Changing coral mechanisms preserve one causal rhythm across pink and yellow fields."),
"q168":("Calibration Orchard","confidence-calibration","allocate-plants-by-stable-noisy-likelihood",["frequency-estimation","resource-allocation"],["treats likelihood as certainty","allocates equally despite evidence","overreacts to one observation"],[1,2,3,4,6],"Yellow plants fill coral bins according to green likelihood strips in an orchard."),
"q178":("Wave Junction","continuous-quantity-reasoning","phase-align-reflected-pulses-at-a-receiver",["modular-phase","joint-adjustment"],["matches amplitude but not phase","advances only one source","ignores shared phase motion"],[1,2,5,6],"Pink and coral sources send white waves into a green receiver over a blue lab."),
"q188":("Future Walls","long-horizon-credit-assignment","early-route-becomes-later-obstacle-memory",["phase-memory","deferred-consequence"],["forgets the early path after transition","moves before entering the future phase","confuses walls with the remembered route"],[1,2,3,4,5],"A pink early route reappears as dark walls in a later mint maze."),
"q198":("Action Chunking","temporal-abstraction","reuse-familiar-action-macro-inside-novel-plan",["macro-recognition","boundary-control"],["expands the chunk at the wrong boundary","copies a novel suffix into the macro","uses only primitive actions"],[1,2,3,4,5,6],"A yellow action routine is chunked into one move on a purple performance stage.")}
def load(c):
 p=ROOT/"docs"/"static"/"games"/"src"/f"{c}-v1"/f"{c}.py";s=importlib.util.spec_from_file_location(c,p);m=importlib.util.module_from_spec(s);s.loader.exec_module(m);return p,m
def main():
 games=[];out=ROOT/"research"/"games"
 for c,v in CFG.items():
  title,axis,primary,secondary,failures,actions,sil=v;p,m=load(c);h=hashlib.sha256(p.read_bytes()).hexdigest();rel=p.relative_to(ROOT).as_posix();names=[x["name"] for x in m.LEVELS]
  meta={"schema_version":1,"game_id":c,"version":"v1","internal_title":title,"public_title":None,"author_partition":"gpt","authorship":{"model_family":"OpenAI GPT-5","model_snapshot":"current Codex task model; exact deployment id not exposed to task","session_id":SESSION,"created_at":"2026-08-30T00:00:00Z","source_lineage":[f"research/gpt-ideas-v2.tsv:{c}"],"source_commit":None},"mechanics":{"primary":primary,"secondary":secondary,"novelty_claim":names[-1],"closest_prior_art":["research/coverage-gap-study-v1.md","research/flash-game-mechanics-survey.md"]},"failure_modes":failures,"interface":{"actions":actions,"observation":"64x64x16","deterministic":True,"seeded_stochasticity":False},"progression":[{"level":i+1,"role":["orient","discriminate","plan","compose","inhibit","synthesize"][i],"new_demand":n,"composes":list(range(1,i+1))} for i,n in enumerate(names)],"visual_identity":{"dominant_palette":[],"silhouette_grammar":sil,"spatial_grammar":sil,"motion_grammar":primary.replace("-"," "),"hud_grammar":"Persistent colored state markers expose the mechanic without text.","nearest_visual_games":[]},"evaluation":{"allowed_development_models":["deterministic-solvers","random-fuzzer","Qwen3.8 diagnostic only"],"held_out_evaluator":"anthropic","human_baseline_status":"not_started","held_out_status":"sealed"},"artifacts":{"source":rel,"metadata":f"research/games/{c}-v1.json","win_recording":f"research/recordings/{c}-v1-win.json","loss_recording":f"research/recordings/{c}-v1-loss.json","thumbnail":f"docs/static/img/games/{c}-v1.png","source_sha256":h},"status":"prototype"}
  (out/f"{c}-v1.json").write_text(json.dumps(meta,indent=2)+"\n");g=getattr(m,c.upper())();a=g.perform_action(ActionInput(id=GameAction.RESET),raw=True).frame[-1];im=Image.new("RGB",(64,64));im.putdata([PAL[int(x)] for row in a for x in row]);im.save(ROOT/"docs"/"static"/"img"/"games"/f"{c}-v1.png",optimize=True);games.append({"game_id":c,"title":title,"axis":axis,"levels":6,"source_sha256":h})
 path=ROOT/"research"/"gpt-batch18-v1.json";path.write_text(json.dumps({"schema_version":1,"batch_id":"gpt-batch18-v1","created_at":"2026-08-30T00:00:00Z","design":"Ten eighth-pass games across the second ten research axes, each with six progressive levels and a distinct colorful environment.","games":games},indent=2)+"\n")
 sheet=Image.new("RGB",(800,352),(242,242,246));d=ImageDraw.Draw(sheet)
 for i,c in enumerate(CFG):im=Image.open(ROOT/"docs"/"static"/"img"/"games"/f"{c}-v1.png").resize((128,128),Image.Resampling.NEAREST);x,y=(i%5)*160+16,(i//5)*176+12;sheet.paste(im,(x,y));d.text((x,y+136),c,fill=(28,28,36))
 sheet.save(ROOT/".cache"/"batch18-contact.png",optimize=True);print("10 metadata records",path)
if __name__=="__main__":main()
