"""Generate metadata, thumbnails, and a contact sheet for research Batch 95."""
import hashlib,importlib.util,json
from PIL import Image,ImageDraw
from arcengine import ActionInput,GameAction
from build_research_batch06_metadata import ROOT,SESSION,PAL
CFG={
"a141":("Reversible Scrambler","reversible-transformation-algebra","universally-information-preserving-gate-network","A navy token network connects four lanes through selectable swap, controlled-swap, and lossy merge gates with backward-test meters."),
"a142":("Cycle Basis","reversible-transformation-algebra","compact-generator-basis-for-permutation-cycles","A brown hexagonal permutation board highlights selected overlapping cycles, requested target, generated rank, and excess basis size."),
"a143":("Return Parity","reversible-transformation-algebra","reachability-class-invariant","A cyan sliding tray presents eight labeled pieces, selected three-cycles, two target parity classes, and reachability verdict."),
"a144":("Group Walk","reversible-transformation-algebra","transformation-word-reduction","A violet abstract pose space surrounds a central group token with a transformation word strip, goal pose, cancellations, and reduced length."),
"a145":("Self or Wind","agency-and-causal-attribution","additive-endogenous-and-exogenous-displacement","A red motion field overlays an object trace with command, periodic wind, null action, and separated displacement components."),
"a146":("Hidden Puppeteer","agency-and-causal-attribution","common-controller-under-selective-blocking","A magenta creature stage allows selective blocking while pulses reveal a shared-controller subset against local followers."),
"a147":("Common Cause","agency-and-causal-attribution","intervention-distinguished-causal-confounding","A pale causal laboratory routes three shieldable sensors toward two correlated lamps and a common-cause verdict."),
"a148":("Reactive Floor","agency-and-causal-attribution","counterfactual-stateless-reactive-field","A dark three-by-three floor changes around a relocated player while replay, fixed-rule, and goal-like scores compare explanations."),
"a149":("Controllable Object","agency-and-causal-attribution","orthogonal-intervention-controllability-identification","A black arena contains six similarly moving pieces, orthogonal command probes, one weakly steerable object, and a socket."),
"a150":("Intent Trace","agency-and-causal-attribution","environment-perturbation-goal-inference","A cream navigation world moves one obstacle before an autonomous walker replans between two candidate goals."),
}
def load(c):
 p=ROOT/"docs"/"static"/"games"/"src"/f"{c}-v1"/f"{c}.py";s=importlib.util.spec_from_file_location(c,p);m=importlib.util.module_from_spec(s);s.loader.exec_module(m);return p,m
def main():
 games=[];out=ROOT/"research"/"games";out.mkdir(parents=True,exist_ok=True)
 for c,(title,axis,primary,silhouette) in CFG.items():
  p,m=load(c);h=hashlib.sha256(p.read_bytes()).hexdigest();rel=p.relative_to(ROOT).as_posix();names=[x["name"] for x in m.LEVELS];g=getattr(m,c.upper())();frame=g.perform_action(ActionInput(id=GameAction.RESET),raw=True).frame[-1];palette=sorted({int(v) for row in frame for v in row})
  meta={"schema_version":1,"game_id":c,"version":"v1","internal_title":title,"public_title":None,"author_partition":"gpt","authorship":{"model_family":"OpenAI GPT-5","model_snapshot":"current Codex task model; exact deployment id not exposed to task","session_id":SESSION,"created_at":"2026-08-31T00:00:00Z","source_lineage":[f"research/anthropic-build-ideas-v1.tsv:{c}"],"concept_lineage":"gpt-seeded-anthropic-build","intended_builder":"anthropic","implementation_author_partition":"gpt","source_commit":None},"mechanics":{"primary":primary,"secondary":[axis,"intervention-grounded-latent-structure"],"novelty_claim":names[-1],"closest_prior_art":["research/anthropic-build-ideas-v1.audit.json","research/coverage-gap-study-v1.md","research/flash-game-mechanics-survey.md"]},"failure_modes":["uses a lossy reversible-looking shortcut or ignores generators, parity classes, and word reduction","attributes correlated or reactive motion to direct coordination or intent without an intervention","chooses visually salient motion instead of testing controllability, exogenous disturbance, common cause, or replanning"],"interface":{"actions":[1,2,3,4,5,6],"observation":"64x64x16","deterministic":True,"seeded_stochasticity":False},"progression":[{"level":i+1,"role":["orient","discriminate","plan","compose","inhibit","synthesize"][i],"new_demand":n,"composes":list(range(1,i+1))} for i,n in enumerate(names)],"visual_identity":{"dominant_palette":palette,"silhouette_grammar":silhouette,"spatial_grammar":silhouette,"motion_grammar":primary.replace("-"," "),"hud_grammar":"Information loss, generator rank, parity, word cancellation, causal components, controller evidence, confounding, reactive fit, controllability, and replanning expose latent structure without text.","nearest_visual_games":[]},"evaluation":{"allowed_development_models":["deterministic-solvers","random-fuzzer","Qwen3.8 diagnostic only"],"held_out_evaluator":"anthropic","human_baseline_status":"not_started","held_out_status":"sealed"},"artifacts":{"source":rel,"metadata":f"research/games/{c}-v1.json","win_recording":f"research/recordings/{c}-v1-win.json","loss_recording":f"research/recordings/{c}-v1-loss.json","thumbnail":f"docs/static/img/games/{c}-v1.png","source_sha256":h},"status":"prototype"}
  (out/f"{c}-v1.json").write_text(json.dumps(meta,indent=2)+"\n");im=Image.new("RGB",(64,64));im.putdata([PAL[int(v)] for row in frame for v in row]);im.save(ROOT/"docs"/"static"/"img"/"games"/f"{c}-v1.png",optimize=True);games.append({"game_id":c,"title":title,"axis":axis,"levels":6,"source_sha256":h})
 path=ROOT/"research"/"gpt-batch95-v1.json";path.write_text(json.dumps({"schema_version":1,"batch_id":"gpt-batch95-v1","created_at":"2026-08-31T00:00:00Z","provenance":"Concepts retain gpt-seeded-anthropic-build queue lineage; implementations in this batch are authored by OpenAI GPT-5 and are not attributed to Anthropic.","design":"Four reversible systems test information preservation, cycle bases, parity classes, and word reduction; six causal worlds use interventions to separate command from wind, controllers from followers, confounding from links, reaction from intent, controllability from salience, and goals from paths.","games":games},indent=2)+"\n")
 sheet=Image.new("RGB",(800,352),(242,242,246));d=ImageDraw.Draw(sheet)
 for i,c in enumerate(CFG):
  im=Image.open(ROOT/"docs"/"static"/"img"/"games"/f"{c}-v1.png").resize((128,128),Image.Resampling.NEAREST);x,y=(i%5)*160+16,(i//5)*176+12;sheet.paste(im,(x,y));d.text((x,y+136),c,fill=(28,28,36))
 (ROOT/".cache").mkdir(exist_ok=True);sheet.save(ROOT/".cache"/"batch95-contact.png",optimize=True);print("10 metadata records",path)
if __name__=="__main__":main()
