"""Generate metadata, thumbnails, and the contact sheet for research Batch 59."""
import hashlib,importlib.util,json
from PIL import Image,ImageDraw
from arcengine import ActionInput,GameAction
from build_research_batch06_metadata import ROOT,SESSION,PAL
CFG={
"q537":("Canopy Lesson","policy-learning-from-demonstration","conditional-policy-transfer-with-an-ineffective-gesture-and-capacity-sensitive-seed-ordering","A green terraced orchard places a failed demonstration above seed, shade, context, and narrow-store panes."),
"q565":("Alloy Counter","adaptive-adversary","legible-rival-shaping-when-local-tactics-map-through-a-moving-reference-frame","A steel foundry aligns three force lanes above rival, translation, and rotation rails."),
"q595":("Alloy Grammar","compositional-communication","grouped-relational-symbols-decoded-after-local-to-global-frame-transforms","A silver glyph foundry stacks three message cells above relay and moving-frame rails."),
"q627":("Canopy Sandbox","counterfactual-planning","persistent-branch-evidence-through-resets-of-a-capacity-limited-simulation-store","A split orchard contrasts two shaded sandboxes above a narrow store and persistent evidence bands."),
"q655":("Alloy Analogy","structural-analogy","source-relation-transferred-exactly-across-translation-and-rotation","A paired foundry gallery maps four source lanes to four target lanes over transform rails."),
"q685":("Alloy Evidence","confidence-calibration","unequal-causal-evidence-recovered-from-rotating-screen-slots-before-safe-stopping","A bronze evidence foundry rotates three visible lanes above sampled and frame-state bands."),
"q715":("Alloy Gradient","continuous-quantity-reasoning","conserved-billet-distribution-measured-by-a-phase-sensitive-moving-frame-gradient","A red magnetic furnace arranges four quantity lanes above force, phase, and commitment rails."),
"q745":("Alloy Obligation","long-horizon-credit-assignment","causal-identity-debt-repaid-after-object-swaps-and-reference-frame-rotation","A gray creditor foundry shows three identity lanes above debt, reward, frame, and repayment bands."),
"q775":("Alloy Rhythm","temporal-abstraction","routine-chunks-interrupted-at-macro-windows-expressed-in-a-moving-frame","A magenta timing foundry layers local pulses, macro cycles, frame rotation, and an interruption gate."),
"q475":("Alloy Dependency","hierarchical-goal-discovery","one-frame-relative-catalyst-reused-across-increasingly-nested-assemblies","A purple assembly foundry grows parts from two consumed lanes and one reusable catalyst lane.")}
def load(c):
 p=ROOT/"docs"/"static"/"games"/"src"/f"{c}-v1"/f"{c}.py";s=importlib.util.spec_from_file_location(c,p);m=importlib.util.module_from_spec(s);s.loader.exec_module(m);return p,m
def main():
 games=[];out=ROOT/"research"/"games";out.mkdir(parents=True,exist_ok=True)
 for c,(title,axis,primary,silhouette) in CFG.items():
  p,m=load(c);h=hashlib.sha256(p.read_bytes()).hexdigest();rel=p.relative_to(ROOT).as_posix();names=[x["name"] for x in m.LEVELS];g=getattr(m,c.upper())();frame=g.perform_action(ActionInput(id=GameAction.RESET),raw=True).frame[-1];palette=sorted({int(v) for row in frame for v in row})
  meta={"schema_version":1,"game_id":c,"version":"v1","internal_title":title,"public_title":None,"author_partition":"gpt","authorship":{"model_family":"OpenAI GPT-5","model_snapshot":"current Codex task model; exact deployment id not exposed to task","session_id":SESSION,"created_at":"2026-08-30T00:00:00Z","source_lineage":[f"research/gpt-ideas-v2.tsv:{c}"],"source_commit":None},"mechanics":{"primary":primary,"secondary":[axis,"underrepresented-capability-expansion"],"novelty_claim":names[-1],"closest_prior_art":["research/coverage-gap-study-v1.md","research/flash-game-mechanics-survey.md"]},"failure_modes":["treats screen coordinates as causal coordinates after the relation translates or rotates","copies a failed gesture or fills a narrow store before resolving the capacity-sensitive ordering","loses persistent evidence, causal identity, reusable catalysts, or macro state when visible objects move"],"interface":{"actions":[1,2,3,4,5,6],"observation":"64x64x16","deterministic":True,"seeded_stochasticity":False},"progression":[{"level":i+1,"role":["orient","discriminate","plan","compose","inhibit","synthesize"][i],"new_demand":n,"composes":list(range(1,i+1))} for i,n in enumerate(names)],"visual_identity":{"dominant_palette":palette,"silhouette_grammar":silhouette,"spatial_grammar":silhouette,"motion_grammar":primary.replace("-"," "),"hud_grammar":"Alternating force lanes, metal billets, orchard terraces, store slots, transform rails, evidence bars, and identity tracks expose state without text.","nearest_visual_games":[]},"evaluation":{"allowed_development_models":["deterministic-solvers","random-fuzzer","Qwen3.8 diagnostic only"],"held_out_evaluator":"anthropic","human_baseline_status":"not_started","held_out_status":"sealed"},"artifacts":{"source":rel,"metadata":f"research/games/{c}-v1.json","win_recording":f"research/recordings/{c}-v1-win.json","loss_recording":f"research/recordings/{c}-v1-loss.json","thumbnail":f"docs/static/img/games/{c}-v1.png","source_sha256":h},"status":"prototype"}
  (out/f"{c}-v1.json").write_text(json.dumps(meta,indent=2)+"\n");im=Image.new("RGB",(64,64));im.putdata([PAL[int(v)] for row in frame for v in row]);im.save(ROOT/"docs"/"static"/"img"/"games"/f"{c}-v1.png",optimize=True);games.append({"game_id":c,"title":title,"axis":axis,"levels":6,"source_sha256":h})
 path=ROOT/"research"/"gpt-batch59-v1.json";path.write_text(json.dumps({"schema_version":1,"batch_id":"gpt-batch59-v1","created_at":"2026-08-30T00:00:00Z","design":"Ten metallic foundry and terraced-orchard environments require policies, evidence, messages, quantities, identities, rhythms, and prerequisites to survive moving frames or hard intermediate-store capacity.","games":games},indent=2)+"\n")
 sheet=Image.new("RGB",(800,352),(242,242,246));d=ImageDraw.Draw(sheet)
 for i,c in enumerate(CFG):
  im=Image.open(ROOT/"docs"/"static"/"img"/"games"/f"{c}-v1.png").resize((128,128),Image.Resampling.NEAREST);x,y=(i%5)*160+16,(i//5)*176+12;sheet.paste(im,(x,y));d.text((x,y+136),c,fill=(28,28,36))
 (ROOT/".cache").mkdir(exist_ok=True);sheet.save(ROOT/".cache"/"batch59-contact.png",optimize=True);print("10 metadata records",path)
if __name__=="__main__":main()
