"""Generate metadata, thumbnails, and a contact sheet for research Batch 83."""
import hashlib,importlib.util,json
from PIL import Image,ImageDraw
from arcengine import ActionInput,GameAction
from build_research_batch06_metadata import ROOT,SESSION,PAL
CFG={
"a021":("Delayed Rudder","sensorimotor-calibration","queued-wake-marks-reveal-a-fixed-steering-delay-before-navigation-through-a-moving-channel","A pale waterway bends ten channel cells around a boat, buoys, wake observations, and a command queue."),
"a022":("Gain Garden","sensorimotor-calibration","local-soil-zones-change-action-magnitude-while-direction-remains-stable-and-fragile-seeds-forbid-overshoot","A blue garden splits twelve test plots across two gain-colored soil zones."),
"a023":("Dead Zone","sensorimotor-calibration","subthreshold-pushes-accumulate-latent-force-before-slider-motion-reveals-distinct-actuator-thresholds","A slate console stacks three sliders above hidden-force and threshold rails."),
"a024":("Crosswind Calibration","sensorimotor-calibration","sheltered-command-tests-separate-the-actuator-map-from-an-additive-field-drift","A lilac navigation field embeds one sheltered calibration strip among wind flags."),
"a025":("Which Hand","action-binding-and-control-disambiguation","neutral-probes-distinguish-a-directly-controlled-cursor-from-a-deterministic-autonomous-decoy","A green two-lane control room separates identical cursors above probe and switch history."),
"a026":("Coupled Buttons","action-binding-and-control-disambiguation","primitive-directions-gain-effects-only-in-chords-with-discoverable-button-bindings-and-forbidden-pairs","A teal floor presents four large buttons above pending primitive, chord, and forbidden state."),
"a027":("Echo Effector","action-binding-and-control-disambiguation","timing-comparisons-bind-commands-to-delayed-physical-effects-instead-of-immediate-salient-flashes","A rose effect stage pairs two physical targets above flash, queue, observation, and clock rails."),
"a028":("Shared Pedal","action-binding-and-control-disambiguation","one-stable-pedal-dynamically-targets-the-lowest-pressure-machine-after-every-use","A cream pressure plant stacks three machines above a shared pedal and recipient history."),
"a029":("Latent Cursor","action-binding-and-control-disambiguation","movement-remains-bound-to-an-invisibly-selected-object-after-highlights-disappear-and-objects-cross","A peach three-lane room tracks objects above latent selection and crossing history."),
"a030":("Ownership Flash","action-binding-and-control-disambiguation","a-three-body-control-rotation-is-propagated-between-ownership-markers-visible-only-every-fourth-turn","A gold arena stacks three body lanes above sparse ownership markers.")}
def load(c):
 p=ROOT/"docs"/"static"/"games"/"src"/f"{c}-v1"/f"{c}.py";s=importlib.util.spec_from_file_location(c,p);m=importlib.util.module_from_spec(s);s.loader.exec_module(m);return p,m
def main():
 games=[];out=ROOT/"research"/"games";out.mkdir(parents=True,exist_ok=True)
 for c,(title,axis,primary,silhouette) in CFG.items():
  p,m=load(c);h=hashlib.sha256(p.read_bytes()).hexdigest();rel=p.relative_to(ROOT).as_posix();names=[x["name"] for x in m.LEVELS];g=getattr(m,c.upper())();frame=g.perform_action(ActionInput(id=GameAction.RESET),raw=True).frame[-1];palette=sorted({int(v) for row in frame for v in row})
  meta={"schema_version":1,"game_id":c,"version":"v1","internal_title":title,"public_title":None,"author_partition":"gpt","authorship":{"model_family":"OpenAI GPT-5","model_snapshot":"current Codex task model; exact deployment id not exposed to task","session_id":SESSION,"created_at":"2026-08-31T00:00:00Z","source_lineage":[f"research/anthropic-build-ideas-v1.tsv:{c}"],"concept_lineage":"gpt-seeded-anthropic-build","intended_builder":"anthropic","implementation_author_partition":"gpt","source_commit":None},"mechanics":{"primary":primary,"secondary":[axis,"temporal-and-causal-action-binding"],"novelty_claim":names[-1],"closest_prior_art":["research/anthropic-build-ideas-v1.audit.json","research/coverage-gap-study-v1.md","research/flash-game-mechanics-survey.md"]},"failure_modes":["corrects current visible error while ignoring queued delay, latent force, zone gain, drift, hysteresis, or changing recipient","binds agency to the most salient or nearby event instead of the temporally supported causal effect","loses invisible selection or sparse ownership state when objects cross or markers disappear"],"interface":{"actions":[1,2,3,4,5,6],"observation":"64x64x16","deterministic":True,"seeded_stochasticity":False},"progression":[{"level":i+1,"role":["orient","discriminate","plan","compose","inhibit","synthesize"][i],"new_demand":n,"composes":list(range(1,i+1))} for i,n in enumerate(names)],"visual_identity":{"dominant_palette":palette,"silhouette_grammar":silhouette,"spatial_grammar":silhouette,"motion_grammar":primary.replace("-"," "),"hud_grammar":"Wake queues, gain soils, force rails, wind flags, cursor probes, chord markers, delayed effects, shared targets, hidden selections, and ownership flashes expose causal control state without text.","nearest_visual_games":[]},"evaluation":{"allowed_development_models":["deterministic-solvers","random-fuzzer","Qwen3.8 diagnostic only"],"held_out_evaluator":"anthropic","human_baseline_status":"not_started","held_out_status":"sealed"},"artifacts":{"source":rel,"metadata":f"research/games/{c}-v1.json","win_recording":f"research/recordings/{c}-v1-win.json","loss_recording":f"research/recordings/{c}-v1-loss.json","thumbnail":f"docs/static/img/games/{c}-v1.png","source_sha256":h},"status":"prototype"}
  (out/f"{c}-v1.json").write_text(json.dumps(meta,indent=2)+"\n");im=Image.new("RGB",(64,64));im.putdata([PAL[int(v)] for row in frame for v in row]);im.save(ROOT/"docs"/"static"/"img"/"games"/f"{c}-v1.png",optimize=True);games.append({"game_id":c,"title":title,"axis":axis,"levels":6,"source_sha256":h})
 path=ROOT/"research"/"gpt-batch83-v1.json";path.write_text(json.dumps({"schema_version":1,"batch_id":"gpt-batch83-v1","created_at":"2026-08-31T00:00:00Z","provenance":"Concepts retain gpt-seeded-anthropic-build queue lineage; implementations in this batch are authored by OpenAI GPT-5 and are not attributed to Anthropic.","design":"Ten colorful systems compose delayed, variable-gain, thresholded, and drifted control with agency inference, chord binding, delayed correspondence, dynamic recipients, hidden selection, and sparse ownership observation.","games":games},indent=2)+"\n")
 sheet=Image.new("RGB",(800,352),(242,242,246));d=ImageDraw.Draw(sheet)
 for i,c in enumerate(CFG):
  im=Image.open(ROOT/"docs"/"static"/"img"/"games"/f"{c}-v1.png").resize((128,128),Image.Resampling.NEAREST);x,y=(i%5)*160+16,(i//5)*176+12;sheet.paste(im,(x,y));d.text((x,y+136),c,fill=(28,28,36))
 (ROOT/".cache").mkdir(exist_ok=True);sheet.save(ROOT/".cache"/"batch83-contact.png",optimize=True);print("10 metadata records",path)
if __name__=="__main__":main()
