"""Generate metadata, thumbnails, and a contact sheet for research Batch 89."""
import hashlib,importlib.util,json
from PIL import Image,ImageDraw
from arcengine import ActionInput,GameAction
from build_research_batch06_metadata import ROOT,SESSION,PAL
CFG={
"a081":("Keystone","structural-stability-and-support","construction-sequence-and-temporary-support-removal","A slate masonry site frames a segmented arch, central wedge, temporary props, rolling load, and force rail."),
"a082":("Load Path","structural-stability-and-support","capacity-aware-force-routing-through-braces","A mint roof hall maps colored force traces through a braceable member grid toward the foundation."),
"a083":("Cantilever Cargo","structural-stability-and-support","torque-balance-with-deck-space-contention","A pale cantilever stretches over a void with distance-coded cargo, counterweight, support, and moment gauge."),
"a084":("Truss Triage","structural-stability-and-support","subtractive-redundancy-under-changing-loads","A violet tunnel fills with triangular bars, selected removal, load direction, rigidity, and vehicle clearance."),
"a085":("Buckle Line","structural-stability-and-support","orientation-and-unsupported-length-under-compression","A teal press laboratory arrays four slender columns with orientation, lateral braces, load, and buckle marks."),
"a086":("Counterbrace","structural-stability-and-support","directional-tension-bracing-under-alternating-load","A gold tower elevation exposes left and right one-way diagonals, selected bays, wind phase, and sway."),
"a087":("Archipelago Bridge","structural-stability-and-support","load-dependent-settlement-and-construction-order","A bright island chain separates pier height, placed spans, shims, settlement history, and level reference."),
"a088":("Foundation Shift","structural-stability-and-support","continuous-center-of-support-during-base-reconfiguration","A light construction yard projects a tall stack center over a moving three-tile support polygon."),
"a089":("Memory Cloth","deformable-material-reasoning","history-dependent-shape-memory-training","A coral textile frame connects six deformable pegs with pull, retained memory, crease, and fitting evidence."),
"a090":("Soft Key","deformable-material-reasoning","compression-dependent-passage-and-expanded-contact","A blue lock cross-section places one deformable key among narrow channels, side cavities, and activation pins."),
}
def load(c):
 p=ROOT/"docs"/"static"/"games"/"src"/f"{c}-v1"/f"{c}.py";s=importlib.util.spec_from_file_location(c,p);m=importlib.util.module_from_spec(s);s.loader.exec_module(m);return p,m
def main():
 games=[];out=ROOT/"research"/"games";out.mkdir(parents=True,exist_ok=True)
 for c,(title,axis,primary,silhouette) in CFG.items():
  p,m=load(c);h=hashlib.sha256(p.read_bytes()).hexdigest();rel=p.relative_to(ROOT).as_posix();names=[x["name"] for x in m.LEVELS];g=getattr(m,c.upper())();frame=g.perform_action(ActionInput(id=GameAction.RESET),raw=True).frame[-1];palette=sorted({int(v) for row in frame for v in row})
  meta={"schema_version":1,"game_id":c,"version":"v1","internal_title":title,"public_title":None,"author_partition":"gpt","authorship":{"model_family":"OpenAI GPT-5","model_snapshot":"current Codex task model; exact deployment id not exposed to task","session_id":SESSION,"created_at":"2026-08-31T00:00:00Z","source_lineage":[f"research/anthropic-build-ideas-v1.tsv:{c}"],"concept_lineage":"gpt-seeded-anthropic-build","intended_builder":"anthropic","implementation_author_partition":"gpt","source_commit":None},"mechanics":{"primary":primary,"secondary":[axis,"path-dependent-physical-state"],"novelty_claim":names[-1],"closest_prior_art":["research/anthropic-build-ideas-v1.audit.json","research/coverage-gap-study-v1.md","research/flash-game-mechanics-survey.md"]},"failure_modes":["recognizes final geometry while ignoring support removal, load path, torque arm, intermediate stability, or settlement","treats every brace or column as bidirectional and rigid despite tension, orientation, capacity, or buckling constraints","assumes a released or compressed soft body returns to one fixed shape without retained strain or cavity contact"],"interface":{"actions":[1,2,3,4,5,6],"observation":"64x64x16","deterministic":True,"seeded_stochasticity":False},"progression":[{"level":i+1,"role":["orient","discriminate","plan","compose","inhibit","synthesize"][i],"new_demand":n,"composes":list(range(1,i+1))} for i,n in enumerate(names)],"visual_identity":{"dominant_palette":palette,"silhouette_grammar":silhouette,"spatial_grammar":silhouette,"motion_grammar":primary.replace("-"," "),"hud_grammar":"Arch supports, force traces, moment gauges, removable trusses, column orientation, one-way braces, pier settlement, support polygons, retained cloth strain, and soft-key outline expose physical state without text.","nearest_visual_games":[]},"evaluation":{"allowed_development_models":["deterministic-solvers","random-fuzzer","Qwen3.8 diagnostic only"],"held_out_evaluator":"anthropic","human_baseline_status":"not_started","held_out_status":"sealed"},"artifacts":{"source":rel,"metadata":f"research/games/{c}-v1.json","win_recording":f"research/recordings/{c}-v1-win.json","loss_recording":f"research/recordings/{c}-v1-loss.json","thumbnail":f"docs/static/img/games/{c}-v1.png","source_sha256":h},"status":"prototype"}
  (out/f"{c}-v1.json").write_text(json.dumps(meta,indent=2)+"\n");im=Image.new("RGB",(64,64));im.putdata([PAL[int(v)] for row in frame for v in row]);im.save(ROOT/"docs"/"static"/"img"/"games"/f"{c}-v1.png",optimize=True);games.append({"game_id":c,"title":title,"axis":axis,"levels":6,"source_sha256":h})
 path=ROOT/"research"/"gpt-batch89-v1.json";path.write_text(json.dumps({"schema_version":1,"batch_id":"gpt-batch89-v1","created_at":"2026-08-31T00:00:00Z","provenance":"Concepts retain gpt-seeded-anthropic-build queue lineage; implementations in this batch are authored by OpenAI GPT-5 and are not attributed to Anthropic.","design":"Eight architectural systems require construction-order, load-path, torque, redundancy, buckling, directional bracing, settlement, and moving-support reasoning; two soft-body systems add persistent deformation and compression-dependent contact.","games":games},indent=2)+"\n")
 sheet=Image.new("RGB",(800,352),(242,242,246));d=ImageDraw.Draw(sheet)
 for i,c in enumerate(CFG):
  im=Image.open(ROOT/"docs"/"static"/"img"/"games"/f"{c}-v1.png").resize((128,128),Image.Resampling.NEAREST);x,y=(i%5)*160+16,(i//5)*176+12;sheet.paste(im,(x,y));d.text((x,y+136),c,fill=(28,28,36))
 (ROOT/".cache").mkdir(exist_ok=True);sheet.save(ROOT/".cache"/"batch89-contact.png",optimize=True);print("10 metadata records",path)
if __name__=="__main__":main()
