"""Generate metadata, thumbnails, and a contact sheet for research Batch 99."""
import hashlib,importlib.util,json
from PIL import Image,ImageDraw
from arcengine import ActionInput,GameAction
from build_research_batch06_metadata import ROOT,SESSION,PAL
CFG={
"a181":("Certificate Path","proof-witness-and-counterexample","sparse-independently-verifiable-reachability-checkpoints","A pale route chamber places bright certificates at one-way doors, with separate gap and excess evidence bars."),
"a182":("Minimal Obstruction","proof-witness-and-counterexample","delete-to-minimal-forbidden-obstruction","A green circular graph laboratory removes nodes until every survivor is necessary to the forbidden core."),
"a183":("Universal Tester","proof-witness-and-counterexample","compact-pairwise-hypothesis-distinguishing-suite","A yellow test matrix selects the smallest probes that separate every pair of candidate machines."),
"a184":("Proof by Tiling","proof-witness-and-counterexample","locally-verifiable-constructive-decomposition","A gray mosaic workshop rotates primitive tiles into a target whose local seams certify the construction."),
"a185":("Missing Packet","protocol-recovery-and-error-correction","cross-cycle-known-erasure-reconstruction","A magenta three-cycle packet channel exposes shifted erasures and a reconstruction rail."),
"a186":("Redundant Relay","protocol-recovery-and-error-correction","transformed-multipath-two-of-three-recovery","A coral relay field carries differently transformed message copies across three colored paths, one visibly failed."),
"a187":("Burst Error","protocol-recovery-and-error-correction","interleaving-to-disperse-contiguous-corruption","A dark two-row interleaver maps a contiguous damaged send burst into separated receive symbols."),
"a188":("Synchronization Word","protocol-recovery-and-error-correction","self-unique-cyclic-frame-delimiter","A cyan bit-stream scope repeats a delimiter across shifted frames and exposes rotational aliases."),
"a189":("Noisy Handshake","protocol-recovery-and-error-correction","feedback-retry-with-duplicate-suppression","A lime network diagram sends request and acknowledgement bands through a noisy retry channel."),
"a190":("Majority Decode","protocol-recovery-and-error-correction","two-fault-tolerant-five-voter-wiring","A blue five-sensor voting chamber routes changing faults into a central majority gate."),
}
def load(c):
 p=ROOT/"docs"/"static"/"games"/"src"/f"{c}-v1"/f"{c}.py";s=importlib.util.spec_from_file_location(c,p);m=importlib.util.module_from_spec(s);s.loader.exec_module(m);return p,m
def main():
 games=[];out=ROOT/"research"/"games";out.mkdir(parents=True,exist_ok=True)
 for c,(title,axis,primary,silhouette) in CFG.items():
  p,m=load(c);h=hashlib.sha256(p.read_bytes()).hexdigest();rel=p.relative_to(ROOT).as_posix();names=[x["name"] for x in m.LEVELS];g=getattr(m,c.upper())();frame=g.perform_action(ActionInput(id=GameAction.RESET),raw=True).frame[-1];palette=sorted({int(v) for row in frame for v in row})
  meta={"schema_version":1,"game_id":c,"version":"v1","internal_title":title,"public_title":None,"author_partition":"gpt","authorship":{"model_family":"OpenAI GPT-5","model_snapshot":"current Codex task model; exact deployment id not exposed to task","session_id":SESSION,"created_at":"2026-08-31T00:00:00Z","source_lineage":[f"research/anthropic-build-ideas-v1.tsv:{c}"],"concept_lineage":"gpt-seeded-anthropic-build","intended_builder":"anthropic","implementation_author_partition":"gpt","source_commit":None},"mechanics":{"primary":primary,"secondary":[axis,"verifiable-evidence-and-explicit-recovery-state"],"novelty_claim":names[-1],"closest_prior_art":["research/anthropic-build-ideas-v1.audit.json","research/coverage-gap-study-v1.md","research/flash-game-mechanics-survey.md"]},"failure_modes":["recognizes a property without constructing a sparse witness, minimal obstruction, universal tester, or locally checkable decomposition","reacts to a missing or corrupted symbol without using redundancy, transformation inversion, or interleaving","aligns frames by appearance or retries blindly without unique synchronization, duplicate suppression, or worst-case fault analysis"],"interface":{"actions":[1,2,3,4,5,6],"observation":"64x64x16","deterministic":True,"seeded_stochasticity":False},"progression":[{"level":i+1,"role":["orient","discriminate","plan","compose","inhibit","synthesize"][i],"new_demand":n,"composes":list(range(1,i+1))} for i,n in enumerate(names)],"visual_identity":{"dominant_palette":palette,"silhouette_grammar":silhouette,"spatial_grammar":silhouette,"motion_grammar":primary.replace("-"," "),"hud_grammar":"Certificates, obstruction cores, test coverage, tile seams, erasures, relays, dispersed damage, delimiters, acknowledgements, and voter safety expose proof or recovery state without text.","nearest_visual_games":[]},"evaluation":{"allowed_development_models":["deterministic-solvers","random-fuzzer","Qwen3.8 diagnostic only"],"held_out_evaluator":"anthropic","human_baseline_status":"not_started","held_out_status":"sealed"},"artifacts":{"source":rel,"metadata":f"research/games/{c}-v1.json","win_recording":f"research/recordings/{c}-v1-win.json","loss_recording":f"research/recordings/{c}-v1-loss.json","thumbnail":f"docs/static/img/games/{c}-v1.png","source_sha256":h},"status":"prototype"}
  (out/f"{c}-v1.json").write_text(json.dumps(meta,indent=2)+"\n");im=Image.new("RGB",(64,64));im.putdata([PAL[int(v)] for row in frame for v in row]);im.save(ROOT/"docs"/"static"/"img"/"games"/f"{c}-v1.png",optimize=True);games.append({"game_id":c,"title":title,"axis":axis,"levels":6,"source_sha256":h})
 path=ROOT/"research"/"gpt-batch99-v1.json";path.write_text(json.dumps({"schema_version":1,"batch_id":"gpt-batch99-v1","created_at":"2026-08-31T00:00:00Z","provenance":"Concepts retain gpt-seeded-anthropic-build queue lineage; implementations in this batch are authored by OpenAI GPT-5 and are not attributed to Anthropic.","design":"Four proof boards demand independently checkable certificates; six protocol boards recover from erasures, failed relays, bursts, frame shifts, noisy acknowledgements, and two simultaneous sensor faults.","games":games},indent=2)+"\n")
 sheet=Image.new("RGB",(800,352),(242,242,246));d=ImageDraw.Draw(sheet)
 for i,c in enumerate(CFG):
  im=Image.open(ROOT/"docs"/"static"/"img"/"games"/f"{c}-v1.png").resize((128,128),Image.Resampling.NEAREST);x,y=(i%5)*160+16,(i//5)*176+12;sheet.paste(im,(x,y));d.text((x,y+136),c,fill=(28,28,36))
 (ROOT/".cache").mkdir(exist_ok=True);sheet.save(ROOT/".cache"/"batch99-contact.png",optimize=True);print("10 metadata records",path)
if __name__=="__main__":main()
