"""Generate metadata and visual artifacts for research Batch 19."""
import hashlib,importlib.util,json
from PIL import Image,ImageDraw
from arcengine import ActionInput,GameAction
from build_research_batch06_metadata import ROOT,SESSION,PAL
CFG={
"q110":("Moving Portal Frame","multi-scale-reference-frames","moving-carrier-relative-portal-topology",["relative-exit","phase-tracking"],["uses the global portal position","ignores carrier velocity","waits in the wrong frame"],[1,2,5,6],"Two colored carriers move portals over a cyan sea while a green traveler tracks their relative exits."),
"q119":("Analog Lesson","policy-learning-from-demonstration","causal-policy-transfer-from-flow-to-blocks",["graph-transfer","surface-invariance"],["copies surface motion","uses the wrong block relabeling","acts before observing the complete flow"],[1,2,3,4,5,6],"Pink flows and orange blocks share one causal graph inside a blue channel."),
"q129":("Decoy Learner","adaptive-adversary","teach-false-preference-to-adaptive-guard",["opponent-modeling","strategic-deception"],["approaches the true target during teaching","commits before the guard learns","creates an unresolved attention tie"],[1,2,3,4,5],"A red guard learns from attention bars around colorful objects in a green garden."),
"q139":("Clock-Skew Messages","compositional-communication","encode-content-with-sender-and-receiver-phase",["asynchronous-cycles","temporal-addressing"],["sends correct content at the wrong phase","aligns only one clock","forgets phase persists between messages"],[1,2,3,4,5],"Blue and orange clocks frame phase-coded green messages on a dark timing board."),
"q149":("Model Tokens","counterfactual-planning","intersect-observations-until-one-world-model-survives",["hypothesis-elimination","safe-commitment"],["commits with multiple survivors","uses a redundant observation","eliminates the target model"],[1,2,3,4,5],"Green model tokens disappear under pink observation cuts on a coral table."),
"q159":("Cross-Scale Transfer","structural-analogy","repeat-causal-order-from-small-tiles-to-large-regions",["scale-invariance","relabeled-topology"],["matches spatial scale","replays local labels globally","changes causal order after scaling"],[1,2,3,4],"Small pink tiles and large orange regions share a white causal spine over blue terrain."),
"q169":("Uncertainty Routing","confidence-calibration","preserve-ambiguous-cargo-at-reversible-hub",["delayed-evidence","irreversible-routing"],["commits before evidence resolves","waits past the deadline","bypasses the required hub"],[1,2,3,4],"Orange cargo waits at a green hub before choosing yellow or white one-way branches."),
"q179":("Field Alignment","continuous-quantity-reasoning","align-local-vectors-to-control-integrated-drift",["distributed-orientation","field-realignment"],["aligns only the selected vector","uses the previous drift target","ignores post-drift local rotation"],[1,2,3,4,5],"Orange vector columns align across a purple field to produce a white global drift."),
"q189":("Inheritance","long-horizon-credit-assignment","preserve-resources-and-structure-for-successor",["intergenerational-budget","damage-repair"],["finishes current work greedily","hands off unresolved damage","salvages without accounting for repair"],[1,2,3,4,5],"Pink and orange agents share yellow resources and red structural damage on a violet site."),
"q199":("Slow Consequence","temporal-abstraction","separate-pending-causes-from-completed-effects",["concurrent-timers","completion-order"],["equates cause order with effect order","submits with pending effects","queues beyond the target prefix"],[1,2,3,5,6],"Pink causes mature through white pending columns into green effects in a blue chamber.")}
def load(c):
 p=ROOT/"docs"/"static"/"games"/"src"/f"{c}-v1"/f"{c}.py";s=importlib.util.spec_from_file_location(c,p);m=importlib.util.module_from_spec(s);s.loader.exec_module(m);return p,m
def main():
 games=[];out=ROOT/"research"/"games"
 for c,v in CFG.items():
  title,axis,primary,secondary,failures,actions,sil=v;p,m=load(c);h=hashlib.sha256(p.read_bytes()).hexdigest();rel=p.relative_to(ROOT).as_posix();names=[x["name"] for x in m.LEVELS]
  meta={"schema_version":1,"game_id":c,"version":"v1","internal_title":title,"public_title":None,"author_partition":"gpt","authorship":{"model_family":"OpenAI GPT-5","model_snapshot":"current Codex task model; exact deployment id not exposed to task","session_id":SESSION,"created_at":"2026-08-30T00:00:00Z","source_lineage":[f"research/gpt-ideas-v2.tsv:{c}"],"source_commit":None},"mechanics":{"primary":primary,"secondary":secondary,"novelty_claim":names[-1],"closest_prior_art":["research/coverage-gap-study-v1.md","research/flash-game-mechanics-survey.md"]},"failure_modes":failures,"interface":{"actions":actions,"observation":"64x64x16","deterministic":True,"seeded_stochasticity":False},"progression":[{"level":i+1,"role":["orient","discriminate","plan","compose","inhibit","synthesize"][i],"new_demand":n,"composes":list(range(1,i+1))} for i,n in enumerate(names)],"visual_identity":{"dominant_palette":[],"silhouette_grammar":sil,"spatial_grammar":sil,"motion_grammar":primary.replace("-"," "),"hud_grammar":"Persistent colored state markers expose the mechanic without text.","nearest_visual_games":[]},"evaluation":{"allowed_development_models":["deterministic-solvers","random-fuzzer","Qwen3.8 diagnostic only"],"held_out_evaluator":"anthropic","human_baseline_status":"not_started","held_out_status":"sealed"},"artifacts":{"source":rel,"metadata":f"research/games/{c}-v1.json","win_recording":f"research/recordings/{c}-v1-win.json","loss_recording":f"research/recordings/{c}-v1-loss.json","thumbnail":f"docs/static/img/games/{c}-v1.png","source_sha256":h},"status":"prototype"}
  (out/f"{c}-v1.json").write_text(json.dumps(meta,indent=2)+"\n");g=getattr(m,c.upper())();a=g.perform_action(ActionInput(id=GameAction.RESET),raw=True).frame[-1];im=Image.new("RGB",(64,64));im.putdata([PAL[int(x)] for row in a for x in row]);im.save(ROOT/"docs"/"static"/"img"/"games"/f"{c}-v1.png",optimize=True);games.append({"game_id":c,"title":title,"axis":axis,"levels":6,"source_sha256":h})
 path=ROOT/"research"/"gpt-batch19-v1.json";path.write_text(json.dumps({"schema_version":1,"batch_id":"gpt-batch19-v1","created_at":"2026-08-30T00:00:00Z","design":"Ten ninth-pass games across the second ten research axes, each with six progressive levels and a distinct colorful environment.","games":games},indent=2)+"\n")
 sheet=Image.new("RGB",(800,352),(242,242,246));d=ImageDraw.Draw(sheet)
 for i,c in enumerate(CFG):im=Image.open(ROOT/"docs"/"static"/"img"/"games"/f"{c}-v1.png").resize((128,128),Image.Resampling.NEAREST);x,y=(i%5)*160+16,(i//5)*176+12;sheet.paste(im,(x,y));d.text((x,y+136),c,fill=(28,28,36))
 sheet.save(ROOT/".cache"/"batch19-contact.png",optimize=True);print("10 metadata records",path)
if __name__=="__main__":main()
