"""Generate metadata, thumbnails, and the contact sheet for research Batch 67."""
import hashlib,importlib.util,json
from PIL import Image,ImageDraw
from arcengine import ActionInput,GameAction
from build_research_batch06_metadata import ROOT,SESSION,PAL
CFG={
"q516":("Backstage Frame","multi-scale-reference-frames","signed-stage-pressure-accumulates-through-rotating-local-sightline-frames","A white rotating theater layers curtain rows above actor, frame, signed-pressure, and goal rails."),
"q546":("Backstage Lesson","policy-learning-from-demonstration","conditional-policy-transfer-depends-on-both-threshold-distance-and-signed-direction","A silver rotating theater places a demonstration above context, threshold, gesture, and signed-result bars."),
"q576":("Backstage Counter","adaptive-adversary","rival-shaping-depends-on-signed-pressure-magnitude-and-current-direction","A gray rotating theater aligns three tactic stages above pressure, direction, rival, and exploit rails."),
"q606":("Backstage Grammar","compositional-communication","grouped-glyphs-compose-signed-pressure-through-a-direction-changing-relay","A stone rotating theater stacks grouped glyphs above signed-pressure and decoded-result bars."),
"q636":("Backstage Sandbox","counterfactual-planning","signed-simulation-evidence-persists-while-physical-stage-values-reset","A charcoal rotating theater places two miniature stages above positive, negative, reset, and commitment rails."),
"q696":("Backstage Evidence","confidence-calibration","unequal-sightline-samples-support-safe-stopping-across-a-visible-direction-turn","A black evidence theater places three sample stages above signed margin, direction, and stopping bars."),
"q726":("Backstage Gradient","continuous-quantity-reasoning","conserved-stage-mass-crosses-thresholds-under-direction-reversing-controls","A pink rotating theater holds three quantity stages above signed direction, phase, and goal rails."),
"q756":("Backstage Obligation","long-horizon-credit-assignment","signed-pressure-debts-remain-attached-to-mask-identities-after-position-swaps","A rose creditor theater places two mask panes above signed pressure, debt, and repayment rails."),
"q786":("Backstage Rhythm","temporal-abstraction","macro-routines-flip-direction-before-an-exact-signed-state-interruption-window","A blue timing theater layers alternating pulse rows above signed value, direction, window, and interrupt bars."),
"q677":("Spectrum Analogy","structural-analogy","affine-magnitude-and-direction-transfer-across-prism-and-agent-surfaces","A cyan prism gallery maps striped geometry to agent panes above direction, magnitude, surface, and transfer rails.")}
def load(c):
 p=ROOT/"docs"/"static"/"games"/"src"/f"{c}-v1"/f"{c}.py";s=importlib.util.spec_from_file_location(c,p);m=importlib.util.module_from_spec(s);s.loader.exec_module(m);return p,m
def main():
 games=[];out=ROOT/"research"/"games";out.mkdir(parents=True,exist_ok=True)
 for c,(title,axis,primary,silhouette) in CFG.items():
  p,m=load(c);h=hashlib.sha256(p.read_bytes()).hexdigest();rel=p.relative_to(ROOT).as_posix();names=[x["name"] for x in m.LEVELS];g=getattr(m,c.upper())();frame=g.perform_action(ActionInput(id=GameAction.RESET),raw=True).frame[-1];palette=sorted({int(v) for row in frame for v in row})
  meta={"schema_version":1,"game_id":c,"version":"v1","internal_title":title,"public_title":None,"author_partition":"gpt","authorship":{"model_family":"OpenAI GPT-5","model_snapshot":"current Codex task model; exact deployment id not exposed to task","session_id":SESSION,"created_at":"2026-08-30T00:00:00Z","source_lineage":[f"research/gpt-ideas-v2.tsv:{c}"],"source_commit":None},"mechanics":{"primary":primary,"secondary":[axis,"underrepresented-capability-expansion"],"novelty_claim":names[-1],"closest_prior_art":["research/coverage-gap-study-v1.md","research/flash-game-mechanics-survey.md"]},"failure_modes":["matches a threshold magnitude while ignoring its current sign or direction","treats a frame, context, or macro direction flip as decorative instead of causal","resets persistent evidence or repays pressure to a current position rather than its causal identity"],"interface":{"actions":[1,2,3,4,5,6],"observation":"64x64x16","deterministic":True,"seeded_stochasticity":False},"progression":[{"level":i+1,"role":["orient","discriminate","plan","compose","inhibit","synthesize"][i],"new_demand":n,"composes":list(range(1,i+1))} for i,n in enumerate(names)],"visual_identity":{"dominant_palette":palette,"silhouette_grammar":silhouette,"spatial_grammar":silhouette,"motion_grammar":primary.replace("-"," "),"hud_grammar":"Curtain bands, mask panes, signed pressure bars, direction indicators, threshold tracks, sample stages, conserved bins, macro windows, prisms, and affine transfer rails expose state without text.","nearest_visual_games":[]},"evaluation":{"allowed_development_models":["deterministic-solvers","random-fuzzer","Qwen3.8 diagnostic only"],"held_out_evaluator":"anthropic","human_baseline_status":"not_started","held_out_status":"sealed"},"artifacts":{"source":rel,"metadata":f"research/games/{c}-v1.json","win_recording":f"research/recordings/{c}-v1-win.json","loss_recording":f"research/recordings/{c}-v1-loss.json","thumbnail":f"docs/static/img/games/{c}-v1.png","source_sha256":h},"status":"prototype"}
  (out/f"{c}-v1.json").write_text(json.dumps(meta,indent=2)+"\n");im=Image.new("RGB",(64,64));im.putdata([PAL[int(v)] for row in frame for v in row]);im.save(ROOT/"docs"/"static"/"img"/"games"/f"{c}-v1.png",optimize=True);games.append({"game_id":c,"title":title,"axis":axis,"levels":6,"source_sha256":h})
 path=ROOT/"research"/"gpt-batch67-v1.json";path.write_text(json.dumps({"schema_version":1,"batch_id":"gpt-batch67-v1","created_at":"2026-08-30T00:00:00Z","design":"Nine colorful rotating-theater environments accumulate direction-sensitive quantities across frames, policies, rivals, language, simulations, evidence, gradients, obligations, and rhythms; a prism gallery transfers affine direction and magnitude across unlike surfaces.","games":games},indent=2)+"\n")
 sheet=Image.new("RGB",(800,352),(242,242,246));d=ImageDraw.Draw(sheet)
 for i,c in enumerate(CFG):
  im=Image.open(ROOT/"docs"/"static"/"img"/"games"/f"{c}-v1.png").resize((128,128),Image.Resampling.NEAREST);x,y=(i%5)*160+16,(i//5)*176+12;sheet.paste(im,(x,y));d.text((x,y+136),c,fill=(28,28,36))
 (ROOT/".cache").mkdir(exist_ok=True);sheet.save(ROOT/".cache"/"batch67-contact.png",optimize=True);print("10 metadata records",path)
if __name__=="__main__":main()
