"""Generate metadata, thumbnails, and a contact sheet for research Batch 91."""
import hashlib,importlib.util,json
from PIL import Image,ImageDraw
from arcengine import ActionInput,GameAction
from build_research_batch06_metadata import ROOT,SESSION,PAL
CFG={
"a101":("Diffraction Gate","wave-boundary-and-superposition","aperture-width-controlled-diffraction","An amber wave tank places a controllable aperture between striped emitters, near-field lobes, and a receiver profile."),
"a102":("Impedance Steps","wave-boundary-and-superposition","graded-impedance-transmission-matching","A cyan transmission bench stacks selectable impedance layers between a source, junction losses, and output meter."),
"a103":("Resonant Cavity","wave-boundary-and-superposition","geometry-selected-temporal-resonance","A plum resonance vault combines adjustable cavity walls, pulse rhythm, standing nodes, and accumulated energy."),
"a104":("Pulse Packet","wave-boundary-and-superposition","precompensation-for-component-dispersion","A dark-blue dispersion scope splits an input packet into frequency components, delays, and a recombined target envelope."),
"a105":("Exact Cover Mosaic","combinatorial-packing-and-covering","exact-once-coverage-with-rotation-and-anchors","A cream mosaic table overlays rotatable colored patches on nine target cells while exposing holes, overlap, and an anchor cursor."),
"a106":("Shadow Packing","combinatorial-packing-and-covering","packing-under-two-projection-constraints","A steel-blue packing studio positions four solids in depth while front and side silhouettes report complementary constraints."),
"a107":("Nesting Cargo","combinatorial-packing-and-covering","hierarchical-containment-changing-effective-items","A green cargo hold nests selectable crates and changes their effective footprint, location, balance, and root structure."),
"a108":("Guillotine Floor","combinatorial-packing-and-covering","recursive-full-cut-partition-reachability","A coral cutting floor recursively splits selected rectangles and scores target-sized pieces against unusable leftovers."),
"a109":("Hinged Packing","combinatorial-packing-and-covering","collision-free-configuration-space-folding","A magenta hinge shop folds a connected chain through discrete angles toward a bin while tracking sweep collisions and placements."),
"a110":("Mobile Cover","combinatorial-packing-and-covering","time-window-coverage-with-moving-footprints","A gold patrol field phases three mobile sentries across target cells, forbidden cells, accumulated coverage, and a timed window."),
}
def load(c):
 p=ROOT/"docs"/"static"/"games"/"src"/f"{c}-v1"/f"{c}.py";s=importlib.util.spec_from_file_location(c,p);m=importlib.util.module_from_spec(s);s.loader.exec_module(m);return p,m
def main():
 games=[];out=ROOT/"research"/"games";out.mkdir(parents=True,exist_ok=True)
 for c,(title,axis,primary,silhouette) in CFG.items():
  p,m=load(c);h=hashlib.sha256(p.read_bytes()).hexdigest();rel=p.relative_to(ROOT).as_posix();names=[x["name"] for x in m.LEVELS];g=getattr(m,c.upper())();frame=g.perform_action(ActionInput(id=GameAction.RESET),raw=True).frame[-1];palette=sorted({int(v) for row in frame for v in row})
  meta={"schema_version":1,"game_id":c,"version":"v1","internal_title":title,"public_title":None,"author_partition":"gpt","authorship":{"model_family":"OpenAI GPT-5","model_snapshot":"current Codex task model; exact deployment id not exposed to task","session_id":SESSION,"created_at":"2026-08-31T00:00:00Z","source_lineage":[f"research/anthropic-build-ideas-v1.tsv:{c}"],"concept_lineage":"gpt-seeded-anthropic-build","intended_builder":"anthropic","implementation_author_partition":"gpt","source_commit":None},"mechanics":{"primary":primary,"secondary":[axis,"latent-state-updates-and-delayed-evaluation"],"novelty_claim":names[-1],"closest_prior_art":["research/anthropic-build-ideas-v1.audit.json","research/coverage-gap-study-v1.md","research/flash-game-mechanics-survey.md"]},"failure_modes":["treats wave apertures, boundaries, impedance, resonance, or dispersion as local symbols rather than coupled systems","optimizes only one projection, footprint, cut, fold, or time step while violating another packing constraint","forgets that rotate, nest, recursive cut, hinge path, or patrol phase changes the future state space"],"interface":{"actions":[1,2,3,4,5,6],"observation":"64x64x16","deterministic":True,"seeded_stochasticity":False},"progression":[{"level":i+1,"role":["orient","discriminate","plan","compose","inhibit","synthesize"][i],"new_demand":n,"composes":list(range(1,i+1))} for i,n in enumerate(names)],"visual_identity":{"dominant_palette":palette,"silhouette_grammar":silhouette,"spatial_grammar":silhouette,"motion_grammar":primary.replace("-"," "),"hud_grammar":"Aperture, transmission, resonance, packet, coverage, projections, containment, cuts, hinge sweep, and patrol-window meters expose global state without text.","nearest_visual_games":[]},"evaluation":{"allowed_development_models":["deterministic-solvers","random-fuzzer","Qwen3.8 diagnostic only"],"held_out_evaluator":"anthropic","human_baseline_status":"not_started","held_out_status":"sealed"},"artifacts":{"source":rel,"metadata":f"research/games/{c}-v1.json","win_recording":f"research/recordings/{c}-v1-win.json","loss_recording":f"research/recordings/{c}-v1-loss.json","thumbnail":f"docs/static/img/games/{c}-v1.png","source_sha256":h},"status":"prototype"}
  (out/f"{c}-v1.json").write_text(json.dumps(meta,indent=2)+"\n");im=Image.new("RGB",(64,64));im.putdata([PAL[int(v)] for row in frame for v in row]);im.save(ROOT/"docs"/"static"/"img"/"games"/f"{c}-v1.png",optimize=True);games.append({"game_id":c,"title":title,"axis":axis,"levels":6,"source_sha256":h})
 path=ROOT/"research"/"gpt-batch91-v1.json";path.write_text(json.dumps({"schema_version":1,"batch_id":"gpt-batch91-v1","created_at":"2026-08-31T00:00:00Z","provenance":"Concepts retain gpt-seeded-anthropic-build queue lineage; implementations in this batch are authored by OpenAI GPT-5 and are not attributed to Anthropic.","design":"Four colorful wave laboratories require aperture control, impedance matching, cavity resonance, and dispersion compensation; six packing studios add exact cover, dual projections, nesting, recursive cuts, hinged paths, and timed mobile coverage.","games":games},indent=2)+"\n")
 sheet=Image.new("RGB",(800,352),(242,242,246));d=ImageDraw.Draw(sheet)
 for i,c in enumerate(CFG):
  im=Image.open(ROOT/"docs"/"static"/"img"/"games"/f"{c}-v1.png").resize((128,128),Image.Resampling.NEAREST);x,y=(i%5)*160+16,(i//5)*176+12;sheet.paste(im,(x,y));d.text((x,y+136),c,fill=(28,28,36))
 (ROOT/".cache").mkdir(exist_ok=True);sheet.save(ROOT/".cache"/"batch91-contact.png",optimize=True);print("10 metadata records",path)
if __name__=="__main__":main()
