"""Generate metadata and visual artifacts for research Batch 20."""
import hashlib,importlib.util,json
from PIL import Image,ImageDraw
from arcengine import ActionInput,GameAction
from build_research_batch06_metadata import ROOT,SESSION,PAL
CFG={
"q201":("Aurora Veil","observer-dependent-dynamics","attention-frozen-regions-with-hysteretic-hidden-updates",["coupled-occlusion","irreversible-state-loop"],["assumes returning attention restores state","updates the observed region","ignores different hidden rates"],[1,2,5,6],"Crystal columns freeze beneath a white attention curtain while hidden motes evolve over ice."),
"q232":("Tide Pact","social-inference","probe-hidden-group-convention-before-irreversible-pact",["convention-identification","delayed-commitment"],["commits before sufficient probes","confuses response with proposal","assumes one universal convention"],[1,2,3,5],"Three shell carriers answer colored offers inside a reversing blue tidal basin."),
"q263":("Ember Probe","causal-intervention","budgeted-network-diagnosis-before-irreversible-repair",["model-discrimination","shared-action-budget"],["repairs after one ambiguous probe","spends the repair budget on observation","selects adjacency as causality"],[1,2,3,4,5],"Clay vessels expose heat responses under bright probes in a coral ceramic kiln."),
"q294":("Honeycomb Ledger","conservation-law-induction","conserved-nectar-transfer-under-local-and-outer-clocks",["global-conservation","nested-time"],["matches one cell locally","forgets the outer cycle","moves nectar from an empty cell"],[1,2,3,5,6],"Yellow nectar redistributes through dark honeycomb cells beneath a green outer clock."),
"q325":("Alloy Survey","epistemic-resource-allocation","budgeted-union-of-rotating-frame-measurements",["set-coverage","reference-frame-update"],["measures the same global slice twice","exceeds the sensor budget","forgets the frame rotates after measurement"],[1,2,3,4,5,6],"Metal billets reveal green lane slices as a white measurement frame rotates across a foundry."),
"q356":("Palimpsest Rig","tool-construction","one-component-geometry-passes-two-rotated-functional-tests",["counterexample-use","reusable-geometry"],["copies the visible failed example","passes only the first test","rebuilds instead of reusing the rotated device"],[1,2,3,4,5,6],"Colored tool components overwrite pale archive slots beside a visible failed construction."),
"q387":("Canopy Delegation","distributed-partial-observability","alternate-complementary-views-through-capacity-bounded-store",["persistent-marking","transfer-order"],["acts from one projection only","overfills the intermediate store","switches controllers before leaving a mark"],[1,2,3,5,6],"Blue seed and orange shade observers exchange white marks through a green orchard store."),
"q418":("Breakwater Revision","nonstationary-rule-revision","wear-triggered-rule-shift-with-dormant-terminal-intervention",["change-point-revision","delayed-side-effect"],["keeps the pre-wear mapping","seals after the first subgoal","forgets the dormant terminal change"],[1,2,3,4,5],"A pink skiff crosses orange gates as a yellow wear band changes the harbor rule."),
"q449":("Strata Lineage","persistent-identity","causal-trail-identity-through-reversible-appearance-transforms",["ancestor-tracking","persistent-knowledge"],["selects current appearance","undoes before probing","forgets knowledge survives physical reversal"],[1,2,3,4,5,6],"Ore bodies trade places above white causal trails while a green probe records ancestry."),
"q480":("Spore Dependency","hierarchical-goal-discovery","shared-prerequisite-dag-at-sparse-two-actor-alignments",["subgoal-reuse","asynchronous-coordination"],["repeats a completed shared subgoal","acts before prerequisites","ignores the sparse joint phase"],[1,2,3,4,5,6],"Pink spore nodes unlock across an orange greenhouse when two colored actor clocks align.")}
def load(c):
 p=ROOT/"docs"/"static"/"games"/"src"/f"{c}-v1"/f"{c}.py";s=importlib.util.spec_from_file_location(c,p);m=importlib.util.module_from_spec(s);s.loader.exec_module(m);return p,m
def main():
 games=[];out=ROOT/"research"/"games"
 for c,v in CFG.items():
  title,axis,primary,secondary,failures,actions,sil=v;p,m=load(c);h=hashlib.sha256(p.read_bytes()).hexdigest();rel=p.relative_to(ROOT).as_posix();names=[x["name"] for x in m.LEVELS]
  meta={"schema_version":1,"game_id":c,"version":"v1","internal_title":title,"public_title":None,"author_partition":"gpt","authorship":{"model_family":"OpenAI GPT-5","model_snapshot":"current Codex task model; exact deployment id not exposed to task","session_id":SESSION,"created_at":"2026-08-30T00:00:00Z","source_lineage":[f"research/gpt-ideas-v2.tsv:{c}"],"source_commit":None},"mechanics":{"primary":primary,"secondary":secondary,"novelty_claim":names[-1],"closest_prior_art":["research/coverage-gap-study-v1.md","research/flash-game-mechanics-survey.md"]},"failure_modes":failures,"interface":{"actions":actions,"observation":"64x64x16","deterministic":True,"seeded_stochasticity":False},"progression":[{"level":i+1,"role":["orient","discriminate","plan","compose","inhibit","synthesize"][i],"new_demand":n,"composes":list(range(1,i+1))} for i,n in enumerate(names)],"visual_identity":{"dominant_palette":[],"silhouette_grammar":sil,"spatial_grammar":sil,"motion_grammar":primary.replace("-"," "),"hud_grammar":"Persistent colored state markers expose the mechanic without text.","nearest_visual_games":[]},"evaluation":{"allowed_development_models":["deterministic-solvers","random-fuzzer","Qwen3.8 diagnostic only"],"held_out_evaluator":"anthropic","human_baseline_status":"not_started","held_out_status":"sealed"},"artifacts":{"source":rel,"metadata":f"research/games/{c}-v1.json","win_recording":f"research/recordings/{c}-v1-win.json","loss_recording":f"research/recordings/{c}-v1-loss.json","thumbnail":f"docs/static/img/games/{c}-v1.png","source_sha256":h},"status":"prototype"}
  (out/f"{c}-v1.json").write_text(json.dumps(meta,indent=2)+"\n");g=getattr(m,c.upper())();a=g.perform_action(ActionInput(id=GameAction.RESET),raw=True).frame[-1];im=Image.new("RGB",(64,64));im.putdata([PAL[int(x)] for row in a for x in row]);im.save(ROOT/"docs"/"static"/"img"/"games"/f"{c}-v1.png",optimize=True);games.append({"game_id":c,"title":title,"axis":axis,"levels":6,"source_sha256":h})
 path=ROOT/"research"/"gpt-batch20-v1.json";path.write_text(json.dumps({"schema_version":1,"batch_id":"gpt-batch20-v1","created_at":"2026-08-30T00:00:00Z","design":"Ten expanded-ledger games staggered across capability axes and domain families, each with six progressive levels and a distinct colorful environment.","games":games},indent=2)+"\n")
 sheet=Image.new("RGB",(800,352),(242,242,246));d=ImageDraw.Draw(sheet)
 for i,c in enumerate(CFG):im=Image.open(ROOT/"docs"/"static"/"img"/"games"/f"{c}-v1.png").resize((128,128),Image.Resampling.NEAREST);x,y=(i%5)*160+16,(i//5)*176+12;sheet.paste(im,(x,y));d.text((x,y+136),c,fill=(28,28,36))
 sheet.save(ROOT/".cache"/"batch20-contact.png",optimize=True);print("10 metadata records",path)
if __name__=="__main__":main()
