"""Generate metadata, thumbnails, and the contact sheet for research Batch 76."""
import hashlib,importlib.util,json
from PIL import Image,ImageDraw
from arcengine import ActionInput,GameAction
from build_research_batch06_metadata import ROOT,SESSION,PAL
CFG={
"q528":("Escapement Frame","multi-scale-reference-frames","weight-motion-composes-through-rotating-gears-while-interventions-produce-exclusive-visible-fault-signatures","An obsidian clock tower aligns six gears above a weight track, diagnostic probes, and rotation rail."),
"q554":("Tessera Lesson","policy-learning-from-demonstration","contextual-mosaic-demonstrations-separate-a-null-gesture-and-reveal-where-a-repeated-macro-must-be-interrupted","An ivory folding mosaic places nine tesserae above demonstration traces, phase, and interruption window."),
"q589":("Monsoon Counter","adaptive-adversary","a-three-tactic-weather-rival-updates-from-recent-treatments-at-visible-unequal-clock-phase-pairs","A blue weather garden arranges storm cells above recent treatments and fast and slow phase rails."),
"q620":("Workbench Grammar","compositional-communication","grouped-tool-messages-compose-through-fixture-relays-while-the-relay-that-borrows-a-tool-writes-identity-bound-debt","A violet workshop aligns four fixtures over grouped tool messages, relay history, and obligation state."),
"q647":("Spectrum Sandbox","counterfactual-planning","prism-packet-pane-and-split-state-reset-while-wavelength-evidence-persists-across-physical-trials","A green prism laboratory contrasts a spectrum chamber with a reset bay above persistent evidence."),
"q674":("Tessera Analogy","structural-analogy","seam-gap-relations-transfer-between-dissimilar-mosaic-surfaces-and-through-a-state-defined-macro-window","A yellow folding mosaic presents geometric source and target panels above surface and window rails."),
"q689":("Strata Evidence","confidence-calibration","reversible-quarry-probes-write-persistent-fault-evidence-until-a-costed-margin-fixes-the-supported-diagnosis","A peach quarry layers five fault columns above persistent signed probes and a centered margin."),
"q739":("Monsoon Gradient","continuous-quantity-reasoning","conserved-rain-mass-crosses-capacity-limited-weather-cells-only-at-useful-fast-and-slow-phase-pairs","A rose weather garden uses four rain reservoirs above storm flow and unequal clock rails."),
"q768":("Escapement Obligation","long-horizon-credit-assignment","weight-debt-remains-attached-to-causal-identity-through-gear-rotations-and-diagnostic-fault-interventions","A slate clock tower tracks three weight identities above fault probes and an identity-bound debt ledger."),
"q795":("Vivarium Rhythm","temporal-abstraction","two-temperature-clocks-and-a-reciprocal-fairness-policy-determine-the-state-window-for-macro-interruption","A gold stacked terrarium arranges twelve fauna nodes above temperature clocks and a fairness margin.")}
def load(c):
 p=ROOT/"docs"/"static"/"games"/"src"/f"{c}-v1"/f"{c}.py";s=importlib.util.spec_from_file_location(c,p);m=importlib.util.module_from_spec(s);s.loader.exec_module(m);return p,m
def main():
 games=[];out=ROOT/"research"/"games";out.mkdir(parents=True,exist_ok=True)
 for c,(title,axis,primary,silhouette) in CFG.items():
  p,m=load(c);h=hashlib.sha256(p.read_bytes()).hexdigest();rel=p.relative_to(ROOT).as_posix();names=[x["name"] for x in m.LEVELS];g=getattr(m,c.upper())();frame=g.perform_action(ActionInput(id=GameAction.RESET),raw=True).frame[-1];palette=sorted({int(v) for row in frame for v in row})
  meta={"schema_version":1,"game_id":c,"version":"v1","internal_title":title,"public_title":None,"author_partition":"gpt","authorship":{"model_family":"OpenAI GPT-5","model_snapshot":"current Codex task model; exact deployment id not exposed to task","session_id":SESSION,"created_at":"2026-08-31T00:00:00Z","source_lineage":[f"research/gpt-ideas-v2.tsv:{c}"],"source_commit":None},"mechanics":{"primary":primary,"secondary":[axis,"underrepresented-capability-expansion"],"novelty_claim":names[-1],"closest_prior_art":["research/coverage-gap-study-v1.md","research/flash-game-mechanics-survey.md"]},"failure_modes":["uses screen coordinates while ignoring the moving gear, seam, storm, fixture, prism, or temperature frame","copies surface actions without inferring fault intervention, contextual macro timing, rival adaptation, grouped syntax, or persistent evidence","tracks visible appearance instead of conservation and causal identity across transformations"],"interface":{"actions":[1,2,3,4,5,6],"observation":"64x64x16","deterministic":True,"seeded_stochasticity":False},"progression":[{"level":i+1,"role":["orient","discriminate","plan","compose","inhibit","synthesize"][i],"new_demand":n,"composes":list(range(1,i+1))} for i,n in enumerate(names)],"visual_identity":{"dominant_palette":palette,"silhouette_grammar":silhouette,"spatial_grammar":silhouette,"motion_grammar":primary.replace("-"," "),"hud_grammar":"Gear towers, diagnostic probes, mosaic seams, macro windows, storm cells, tool relays, prism trials, evidence notebooks, quarry margins, conserved reservoirs, identity ledgers, terrarium clocks, and fairness rails expose state without text.","nearest_visual_games":[]},"evaluation":{"allowed_development_models":["deterministic-solvers","random-fuzzer","Qwen3.8 diagnostic only"],"held_out_evaluator":"anthropic","human_baseline_status":"not_started","held_out_status":"sealed"},"artifacts":{"source":rel,"metadata":f"research/games/{c}-v1.json","win_recording":f"research/recordings/{c}-v1-win.json","loss_recording":f"research/recordings/{c}-v1-loss.json","thumbnail":f"docs/static/img/games/{c}-v1.png","source_sha256":h},"status":"prototype"}
  (out/f"{c}-v1.json").write_text(json.dumps(meta,indent=2)+"\n");im=Image.new("RGB",(64,64));im.putdata([PAL[int(v)] for row in frame for v in row]);im.save(ROOT/"docs"/"static"/"img"/"games"/f"{c}-v1.png",optimize=True);games.append({"game_id":c,"title":title,"axis":axis,"levels":6,"source_sha256":h})
 path=ROOT/"research"/"gpt-batch76-v1.json";path.write_text(json.dumps({"schema_version":1,"batch_id":"gpt-batch76-v1","created_at":"2026-08-31T00:00:00Z","design":"Seven material systems—clock towers, folding mosaics, weather gardens, a mobile workshop, a prism laboratory, a deep quarry, and a stacked terrarium—compose moving frames, demonstration, adaptation, syntax, persistent experiments, analogy, calibrated diagnosis, conservation, obligation, and reciprocal time.","games":games},indent=2)+"\n")
 sheet=Image.new("RGB",(800,352),(242,242,246));d=ImageDraw.Draw(sheet)
 for i,c in enumerate(CFG):
  im=Image.open(ROOT/"docs"/"static"/"img"/"games"/f"{c}-v1.png").resize((128,128),Image.Resampling.NEAREST);x,y=(i%5)*160+16,(i//5)*176+12;sheet.paste(im,(x,y));d.text((x,y+136),c,fill=(28,28,36))
 (ROOT/".cache").mkdir(exist_ok=True);sheet.save(ROOT/".cache"/"batch76-contact.png",optimize=True);print("10 metadata records",path)
if __name__=="__main__":main()
