"""Generate metadata, thumbnails, and a contact sheet for research Batch 86."""
import hashlib,importlib.util,json
from PIL import Image,ImageDraw
from arcengine import ActionInput,GameAction
from build_research_batch06_metadata import ROOT,SESSION,PAL
CFG={
"a051":("Priority Chute","queueing-and-backpressure","priority-scheduling-with-deadlines-and-starvation","A pale sorting hall stacks three aging chutes beside one server and a bounded service history."),
"a052":("Batch Furnace","queueing-and-backpressure","deadline-aware-group-service","A rose foundry separates two cooling belts, batch selections, and a fixed-pulse furnace."),
"a053":("Service Rhythm","queueing-and-backpressure","routing-under-time-varying-service-rates","A lilac depot mirrors persistent queues around two stations and a visible capacity phase."),
"a054":("Merge Meter","queueing-and-backpressure","fair-merging-while-maintaining-throughput","A cyan mergeway funnels two colored lanes through a finite shared buffer and receiver."),
"a055":("Perishable Queue","queueing-and-backpressure","joint-queue-order-and-item-age-control","A bright market rail separates per-item freshness, queue order, siding occupancy, and disposal."),
"a056":("Pull System","queueing-and-backpressure","request-driven-production-and-circulating-inventory","A dark pull plant aligns three machines over demand sockets, inventory pipes, and jam marks."),
"a057":("Thermostat Tiles","feedback-control-and-regulation","delayed-field-regulation-with-hysteresis","A coral climate room arrays four temperature columns above heaters, a target band, and hold marks."),
"a058":("Reservoir Governor","feedback-control-and-regulation","coupled-level-control-under-intermittent-inflow","A blue reservoir field connects three level tanks with valves, safe bands, and pump phase."),
"a059":("Cruise Beetle","feedback-control-and-regulation","velocity-control-against-terrain-disturbance","A violet hillside exposes beetle position, trail-coded speed, slope, throttle, and cruise stability."),
"a060":("Balance Pole","feedback-control-and-regulation","countersteering-unstable-dynamics-while-progressing","A gold balance arena couples cart progress to an unstable pole, lean history, and center guide."),
}
def load(c):
 p=ROOT/"docs"/"static"/"games"/"src"/f"{c}-v1"/f"{c}.py";s=importlib.util.spec_from_file_location(c,p);m=importlib.util.module_from_spec(s);s.loader.exec_module(m);return p,m
def main():
 games=[];out=ROOT/"research"/"games";out.mkdir(parents=True,exist_ok=True)
 for c,(title,axis,primary,silhouette) in CFG.items():
  p,m=load(c);h=hashlib.sha256(p.read_bytes()).hexdigest();rel=p.relative_to(ROOT).as_posix();names=[x["name"] for x in m.LEVELS];g=getattr(m,c.upper())();frame=g.perform_action(ActionInput(id=GameAction.RESET),raw=True).frame[-1];palette=sorted({int(v) for row in frame for v in row})
  meta={"schema_version":1,"game_id":c,"version":"v1","internal_title":title,"public_title":None,"author_partition":"gpt","authorship":{"model_family":"OpenAI GPT-5","model_snapshot":"current Codex task model; exact deployment id not exposed to task","session_id":SESSION,"created_at":"2026-08-31T00:00:00Z","source_lineage":[f"research/anthropic-build-ideas-v1.tsv:{c}"],"concept_lineage":"gpt-seeded-anthropic-build","intended_builder":"anthropic","implementation_author_partition":"gpt","source_commit":None},"mechanics":{"primary":primary,"secondary":[axis,"dynamic-state-estimation-and-control"],"novelty_claim":names[-1],"closest_prior_art":["research/anthropic-build-ideas-v1.audit.json","research/coverage-gap-study-v1.md","research/flash-game-mechanics-survey.md"]},"failure_modes":["optimizes immediate service or position while ignoring starvation, deadlines, lag, velocity, or instability","forgets retained queue history, item age, coupled state, demand signals, or a persistent disturbance","reaches a target once without sustaining the required fairness, capacity, safety, or regulation invariant"],"interface":{"actions":[1,2,3,4,5,6],"observation":"64x64x16","deterministic":True,"seeded_stochasticity":False},"progression":[{"level":i+1,"role":["orient","discriminate","plan","compose","inhibit","synthesize"][i],"new_demand":n,"composes":list(range(1,i+1))} for i,n in enumerate(names)],"visual_identity":{"dominant_palette":palette,"silhouette_grammar":silhouette,"spatial_grammar":silhouette,"motion_grammar":primary.replace("-"," "),"hud_grammar":"Aging chutes, cooling belts, rate phases, fair buffers, freshness, demand sockets, temperature lag, coupled levels, speed trails, and pole lean expose dynamic state without text.","nearest_visual_games":[]},"evaluation":{"allowed_development_models":["deterministic-solvers","random-fuzzer","Qwen3.8 diagnostic only"],"held_out_evaluator":"anthropic","human_baseline_status":"not_started","held_out_status":"sealed"},"artifacts":{"source":rel,"metadata":f"research/games/{c}-v1.json","win_recording":f"research/recordings/{c}-v1-win.json","loss_recording":f"research/recordings/{c}-v1-loss.json","thumbnail":f"docs/static/img/games/{c}-v1.png","source_sha256":h},"status":"prototype"}
  (out/f"{c}-v1.json").write_text(json.dumps(meta,indent=2)+"\n");im=Image.new("RGB",(64,64));im.putdata([PAL[int(v)] for row in frame for v in row]);im.save(ROOT/"docs"/"static"/"img"/"games"/f"{c}-v1.png",optimize=True);games.append({"game_id":c,"title":title,"axis":axis,"levels":6,"source_sha256":h})
 path=ROOT/"research"/"gpt-batch86-v1.json";path.write_text(json.dumps({"schema_version":1,"batch_id":"gpt-batch86-v1","created_at":"2026-08-31T00:00:00Z","provenance":"Concepts retain gpt-seeded-anthropic-build queue lineage; implementations in this batch are authored by OpenAI GPT-5 and are not attributed to Anthropic.","design":"Ten industrial and environmental control boards combine deadlines, batching, changing rates, fairness, perishability, pull production, delayed thermal feedback, coupled reservoirs, velocity regulation, and unstable countersteering.","games":games},indent=2)+"\n")
 sheet=Image.new("RGB",(800,352),(242,242,246));d=ImageDraw.Draw(sheet)
 for i,c in enumerate(CFG):
  im=Image.open(ROOT/"docs"/"static"/"img"/"games"/f"{c}-v1.png").resize((128,128),Image.Resampling.NEAREST);x,y=(i%5)*160+16,(i//5)*176+12;sheet.paste(im,(x,y));d.text((x,y+136),c,fill=(28,28,36))
 (ROOT/".cache").mkdir(exist_ok=True);sheet.save(ROOT/".cache"/"batch86-contact.png",optimize=True);print("10 metadata records",path)
if __name__=="__main__":main()
