"""Generate metadata, thumbnails, and the contact sheet for research Batch 57."""
import hashlib,importlib.util,json
from PIL import Image,ImageDraw
from arcengine import ActionInput,GameAction
from build_research_batch06_metadata import ROOT,SESSION,PAL
CFG={
"q531":("Aurora Lesson","policy-learning-from-demonstration","conditional-demonstration-handoff-through-ineffective-gestures-and-hysteretic-context","A pale aurora classroom separates demonstration columns from transfer and memory rails."),
"q561":("Aurora Counter","adaptive-adversary","legible-opponent-shaping-through-hysteretic-counterplay","A navy polar arena places an adapting opponent above state and pressure rails."),
"q591":("Aurora Grammar","compositional-communication","grouped-relay-grammar-composed-under-hysteretic-channel-state","A violet relay station arranges symbol groups between luminous channel curtains."),
"q621":("Aurora Sandbox","counterfactual-planning","parallel-simulated-and-committed-copies-with-persistent-evidence","A green planning chamber aligns ghost and real routes above persistent evidence rails."),
"q651":("Aurora Analogy","structural-analogy","curtain-relation-transferred-to-a-different-mote-system","A cyan analogy gallery mirrors curtain relations into a field of independent motes."),
"q681":("Aurora Evidence","confidence-calibration","safe-stopping-under-unequal-evidence-reliability-and-hysteresis","A blue observatory stacks unequal evidence bars over context and confidence rails."),
"q712":("Tide Gradient","continuous-quantity-reasoning","conserved-influence-capacity-and-phase-before-an-irreversible-threshold","A sand-colored tidal basin exposes conserved flow, capacity, phase, and a commitment gate."),
"q741":("Aurora Obligation","long-horizon-credit-assignment","identity-bound-delayed-obligations-amid-distracting-immediate-rewards","A rose obligation hall tracks persistent identities above delayed reward chambers."),
"q771":("Aurora Rhythm","temporal-abstraction","chunked-rhythm-and-scaled-intervals-with-state-defined-interruption-windows","A warm clock arcade stacks rhythm chunks above macro-state and interruption rails."),
"q472":("Tide Dependency","hierarchical-goal-discovery","shared-prerequisite-reuse-through-reversing-current-before-irreversible-commitment","A teal tidal workshop branches shared prerequisites toward one irreversible launch gate.")}
def load(c):
 p=ROOT/"docs"/"static"/"games"/"src"/f"{c}-v1"/f"{c}.py";s=importlib.util.spec_from_file_location(c,p);m=importlib.util.module_from_spec(s);s.loader.exec_module(m);return p,m
def main():
 games=[];out=ROOT/"research"/"games";out.mkdir(parents=True,exist_ok=True)
 for c,(title,axis,primary,silhouette) in CFG.items():
  p,m=load(c);h=hashlib.sha256(p.read_bytes()).hexdigest();rel=p.relative_to(ROOT).as_posix();names=[x["name"] for x in m.LEVELS];g=getattr(m,c.upper())();frame=g.perform_action(ActionInput(id=GameAction.RESET),raw=True).frame[-1];palette=sorted({int(v) for row in frame for v in row})
  meta={"schema_version":1,"game_id":c,"version":"v1","internal_title":title,"public_title":None,"author_partition":"gpt","authorship":{"model_family":"OpenAI GPT-5","model_snapshot":"current Codex task model; exact deployment id not exposed to task","session_id":SESSION,"created_at":"2026-08-30T00:00:00Z","source_lineage":[f"research/gpt-ideas-v2.tsv:{c}"],"source_commit":None},"mechanics":{"primary":primary,"secondary":[axis,"underrepresented-capability-expansion"],"novelty_claim":names[-1],"closest_prior_art":["research/coverage-gap-study-v1.md","research/flash-game-mechanics-survey.md"]},"failure_modes":["overfits a visible action without transferring the hidden policy or relation","optimizes immediate progress while discarding evidence, prerequisites, or delayed obligations","commits before uncertainty, conserved quantity, temporal phase, or adversarial response is resolved"],"interface":{"actions":[1,2,3,4,5,6],"observation":"64x64x16","deterministic":True,"seeded_stochasticity":False},"progression":[{"level":i+1,"role":["orient","discriminate","plan","compose","inhibit","synthesize"][i],"new_demand":n,"composes":list(range(1,i+1))} for i,n in enumerate(names)],"visual_identity":{"dominant_palette":palette,"silhouette_grammar":silhouette,"spatial_grammar":silhouette,"motion_grammar":primary.replace("-"," "),"hud_grammar":"Aurora curtains, tidal channels, evidence columns, identity tracks, relay groups, and macro-state rails expose state without text.","nearest_visual_games":[]},"evaluation":{"allowed_development_models":["deterministic-solvers","random-fuzzer","Qwen3.8 diagnostic only"],"held_out_evaluator":"anthropic","human_baseline_status":"not_started","held_out_status":"sealed"},"artifacts":{"source":rel,"metadata":f"research/games/{c}-v1.json","win_recording":f"research/recordings/{c}-v1-win.json","loss_recording":f"research/recordings/{c}-v1-loss.json","thumbnail":f"docs/static/img/games/{c}-v1.png","source_sha256":h},"status":"prototype"}
  (out/f"{c}-v1.json").write_text(json.dumps(meta,indent=2)+"\n");im=Image.new("RGB",(64,64));im.putdata([PAL[int(v)] for row in frame for v in row]);im.save(ROOT/"docs"/"static"/"img"/"games"/f"{c}-v1.png",optimize=True);games.append({"game_id":c,"title":title,"axis":axis,"levels":6,"source_sha256":h})
 path=ROOT/"research"/"gpt-batch57-v1.json";path.write_text(json.dumps({"schema_version":1,"batch_id":"gpt-batch57-v1","created_at":"2026-08-30T00:00:00Z","design":"Ten environments crossing aurora observatories and tidal laboratories with demonstration transfer, adversarial shaping, relay grammar, simulation, analogy, calibration, conserved quantities, delayed obligation, temporal chunks, and hierarchical commitment.","games":games},indent=2)+"\n")
 sheet=Image.new("RGB",(800,352),(242,242,246));d=ImageDraw.Draw(sheet)
 for i,c in enumerate(CFG):
  im=Image.open(ROOT/"docs"/"static"/"img"/"games"/f"{c}-v1.png").resize((128,128),Image.Resampling.NEAREST);x,y=(i%5)*160+16,(i//5)*176+12;sheet.paste(im,(x,y));d.text((x,y+136),c,fill=(28,28,36))
 (ROOT/".cache").mkdir(exist_ok=True);sheet.save(ROOT/".cache"/"batch57-contact.png",optimize=True);print("10 metadata records",path)
if __name__=="__main__":main()
