"""Generate metadata and visual artifacts for research Batch 11."""
import hashlib,importlib.util,json
from PIL import Image,ImageDraw
from arcengine import ActionInput,GameAction
from build_research_batch06_metadata import ROOT,SESSION,PAL
CFG={
"q007":("Still Guards","observer-dependent-dynamics","watched-gate-decay-unseen-patrol",["attention-scheduling","threat-infrastructure-tradeoff"],["watches only the guard","crosses before gate decay","forgets patrol motion after looking away"],[1,2,3,4,5],"A magenta traveler crosses pale cells while red guards freeze and orange gates decay under observation."),
"q016":("Blind Guide","social-inference","movement-grounded-guide-policy",["embodied-signal","hazard-delegation"],["copies position rather than motion","ignores the guide","treats gestures as labels"],[1,2,3,4],"A green guide moves above a blue blind traveler through a warm corridor."),
"q026":("Controlled Cascade","causal-intervention","seed-barrier-exact-propagation",["cascade-control","terminal-pattern"],["maximizes spread","chooses a seed without a barrier model","accepts an approximate pattern"],[1,2,3,4,5,6],"Blue seeds and gray barriers determine a green eight-cell cascade."),
"q036":("Loop Current","conservation-law-induction","circulation-sum-conservation",["loop-flow","invisible-return"],["creates current","tracks one branch only","forgets return circulation"],[3,4,5,6],"Blue current columns circulate among gray loop vessels beneath green targets."),
"q046":("One Question","epistemic-resource-allocation","single-binary-rule-partition",["test-selection","hypothesis-identification"],["asks redundant questions","guesses before testing","confuses answer polarity"],[1,2,3,4,5,6],"Gray candidate rules sit above one orange binary test and its green or red outcome."),
"q056":("Magnet Chain","tool-construction","alternating-polar-segment-chain",["polarity","field-construction"],["uses identical poles","matches color without orientation","leaves a blank segment"],[1,2,3,4,6],"Blue and magenta polar segments assemble into a green alternating field tool."),
"q066":("Beacon Relay","distributed-partial-observability","nearest-beacon-local-direction-chain",["local-observation","global-relay"],["assumes global visibility","breaks the relay order","copies one beacon direction everywhere"],[1,2,3,4],"Orange beacons guide blue local agents through a chain of cyan signals."),
"q076":("Rule Thermostat","nonstationary-rule-revision","temperature-selected-causal-regime",["regime-control","rule-management"],["treats temperature as decoration","uses one rule at every heat level","changes state before setting regime"],[1,2,3,4,6],"Cold, warm, and hot panels select different blue state transformations toward a green target."),
"q086":("Doppel Memory","persistent-identity","permission-grounded-original-detection",["behavioral-identity","duplicate-history"],["selects by appearance","trusts copied position history","fails to test learned permissions"],[3,4,5,6],"Identical blue bodies reveal green permission behavior against copied gray trails."),
"q096":("Subgoal Cache","hierarchical-goal-discovery","reusable-subtask-boundary-cache",["subgoal-reuse","hierarchical-compression"],["rebuilds every subtask","caches the wrong boundary","reuses before first completion"],[3,4,5,6],"Gray tasks turn into reusable cyan cache blocks across repeated assemblies.")}
def load(c):
 p=ROOT/"docs"/"static"/"games"/"src"/f"{c}-v1"/f"{c}.py";s=importlib.util.spec_from_file_location(c,p);m=importlib.util.module_from_spec(s);s.loader.exec_module(m);return p,m
def main():
 games=[];out=ROOT/"research"/"games"
 for c,v in CFG.items():
  title,axis,primary,secondary,failures,actions,sil=v;p,m=load(c);h=hashlib.sha256(p.read_bytes()).hexdigest();rel=p.relative_to(ROOT).as_posix();names=[x["name"] for x in m.LEVELS]
  meta={"schema_version":1,"game_id":c,"version":"v1","internal_title":title,"public_title":None,"author_partition":"gpt","authorship":{"model_family":"OpenAI GPT-5","model_snapshot":"current Codex task model; exact deployment id not exposed to task","session_id":SESSION,"created_at":"2026-08-30T00:00:00Z","source_lineage":[f"research/gpt-ideas-v2.tsv:{c}"],"source_commit":None},"mechanics":{"primary":primary,"secondary":secondary,"novelty_claim":names[-1],"closest_prior_art":["research/coverage-gap-study-v1.md","research/flash-game-mechanics-survey.md"]},"failure_modes":failures,"interface":{"actions":actions,"observation":"64x64x16","deterministic":True,"seeded_stochasticity":False},"progression":[{"level":i+1,"role":["orient","discriminate","plan","compose","inhibit","synthesize"][i],"new_demand":n,"composes":list(range(1,i+1))} for i,n in enumerate(names)],"visual_identity":{"dominant_palette":[],"silhouette_grammar":sil,"spatial_grammar":sil,"motion_grammar":primary.replace("-"," "),"hud_grammar":"Persistent colored state markers expose the mechanic without text.","nearest_visual_games":[]},"evaluation":{"allowed_development_models":["deterministic-solvers","random-fuzzer","Qwen3.8 diagnostic only"],"held_out_evaluator":"anthropic","human_baseline_status":"not_started","held_out_status":"sealed"},"artifacts":{"source":rel,"metadata":f"research/games/{c}-v1.json","win_recording":f"research/recordings/{c}-v1-win.json","loss_recording":f"research/recordings/{c}-v1-loss.json","thumbnail":f"docs/static/img/games/{c}-v1.png","source_sha256":h},"status":"prototype"}
  (out/f"{c}-v1.json").write_text(json.dumps(meta,indent=2)+"\n");g=getattr(m,c.upper())();a=g.perform_action(ActionInput(id=GameAction.RESET),raw=True).frame[-1];im=Image.new("RGB",(64,64));im.putdata([PAL[int(x)] for row in a for x in row]);im.save(ROOT/"docs"/"static"/"img"/"games"/f"{c}-v1.png",optimize=True);games.append({"game_id":c,"title":title,"axis":axis,"levels":6,"source_sha256":h})
 path=ROOT/"research"/"gpt-batch11-v1.json";path.write_text(json.dumps({"schema_version":1,"batch_id":"gpt-batch11-v1","created_at":"2026-08-30T00:00:00Z","design":"Ten sixth-pass games across the first ten research axes, each with six progressive levels and a distinct colorful environment.","games":games},indent=2)+"\n")
 sheet=Image.new("RGB",(800,352),(242,242,246));d=ImageDraw.Draw(sheet)
 for i,c in enumerate(CFG):im=Image.open(ROOT/"docs"/"static"/"img"/"games"/f"{c}-v1.png").resize((128,128),Image.Resampling.NEAREST);x,y=(i%5)*160+16,(i//5)*176+12;sheet.paste(im,(x,y));d.text((x,y+136),c,fill=(28,28,36))
 sheet.save(ROOT/".cache"/"batch11-contact.png",optimize=True);print("10 metadata records",path)
if __name__=="__main__":main()
