"""Generate metadata, thumbnails, and the contact sheet for research Batch 62."""
import hashlib,importlib.util,json
from PIL import Image,ImageDraw
from arcengine import ActionInput,GameAction
from build_research_batch06_metadata import ROOT,SESSION,PAL
CFG={
"q540":("Spore Lesson","policy-learning-from-demonstration","conditional-policy-transfer-coordinated-at-sparse-shared-events-of-unequal-actors","A blue glass greenhouse places a demonstration over paired colony panes and two visible clocks."),
"q570":("Spore Counter","adaptive-adversary","rival-shaped-through-repeated-treatment-rounds-that-return-unequal-clocks-to-alignment","A green greenhouse aligns three tactic panes above rival, dual-clock, and shaping rails."),
"q600":("Spore Grammar","compositional-communication","grouped-relational-message-relayed-only-when-two-autonomous-schedules-align","A red glyph greenhouse stacks three message panes above unequal relay clocks."),
"q624":("Honeycomb Sandbox","counterfactual-planning","simulation-evidence-persists-across-resets-and-is-committed-at-nested-clock-boundaries","A violet split apiary places two sandboxes above evidence, local, and outer-clock bands."),
"q654":("Honeycomb Analogy","structural-analogy","source-relation-transfers-to-couriers-only-at-local-cycle-and-outer-clock-boundaries","A magenta apiary maps four source cells to target cells over nested clock rails."),
"q684":("Honeycomb Evidence","confidence-calibration","unequal-evidence-safe-stopping-is-constrained-to-visible-nested-clock-boundaries","A yellow evidence apiary stacks three sample cells above local and outer clocks."),
"q720":("Spore Gradient","continuous-quantity-reasoning","conserved-colony-distribution-crosses-a-phase-sensitive-threshold-at-unequal-clock-alignment","A warm greenhouse holds three quantity panes above humidity, phase, and dual-clock rails."),
"q750":("Spore Obligation","long-horizon-credit-assignment","identity-bound-debt-can-be-repaid-only-when-unequal-autonomous-clocks-align","A bronze creditor greenhouse shows two identity panes above debt, reward, and clock bands."),
"q779":("Strata Rhythm","temporal-abstraction","physical-timing-probe-is-undone-while-its-knowledge-guides-a-later-macro-window","A gray quarry layers fault bands above local, macro, reversible-probe, and knowledge rails."),
"q474":("Honeycomb Dependency","hierarchical-goal-discovery","shared-nectar-prerequisites-assemble-only-at-local-cycle-boundaries-of-an-outer-clock","A pale apiary grows parts beneath a field of cells and nested-clock rails.")}
def load(c):
 p=ROOT/"docs"/"static"/"games"/"src"/f"{c}-v1"/f"{c}.py";s=importlib.util.spec_from_file_location(c,p);m=importlib.util.module_from_spec(s);s.loader.exec_module(m);return p,m
def main():
 games=[];out=ROOT/"research"/"games";out.mkdir(parents=True,exist_ok=True)
 for c,(title,axis,primary,silhouette) in CFG.items():
  p,m=load(c);h=hashlib.sha256(p.read_bytes()).hexdigest();rel=p.relative_to(ROOT).as_posix();names=[x["name"] for x in m.LEVELS];g=getattr(m,c.upper())();frame=g.perform_action(ActionInput(id=GameAction.RESET),raw=True).frame[-1];palette=sorted({int(v) for row in frame for v in row})
  meta={"schema_version":1,"game_id":c,"version":"v1","internal_title":title,"public_title":None,"author_partition":"gpt","authorship":{"model_family":"OpenAI GPT-5","model_snapshot":"current Codex task model; exact deployment id not exposed to task","session_id":SESSION,"created_at":"2026-08-30T00:00:00Z","source_lineage":[f"research/gpt-ideas-v2.tsv:{c}"],"source_commit":None},"mechanics":{"primary":primary,"secondary":[axis,"underrepresented-capability-expansion"],"novelty_claim":names[-1],"closest_prior_art":["research/coverage-gap-study-v1.md","research/flash-game-mechanics-survey.md"]},"failure_modes":["coordinates one actor locally while ignoring the other actor's independently visible schedule","commits evidence, a relation, a quantity, or an obligation outside the sparse shared event","collapses local-cycle and outer-clock state or forgets persistent identity and probe knowledge"],"interface":{"actions":[1,2,3,4,5,6],"observation":"64x64x16","deterministic":True,"seeded_stochasticity":False},"progression":[{"level":i+1,"role":["orient","discriminate","plan","compose","inhibit","synthesize"][i],"new_demand":n,"composes":list(range(1,i+1))} for i,n in enumerate(names)],"visual_identity":{"dominant_palette":palette,"silhouette_grammar":silhouette,"spatial_grammar":silhouette,"motion_grammar":primary.replace("-"," "),"hud_grammar":"Glass colony panes, honeycomb cells, humidity gradients, dual clocks, outer-cycle bars, identity panes, and sparse-event gates expose state without text.","nearest_visual_games":[]},"evaluation":{"allowed_development_models":["deterministic-solvers","random-fuzzer","Qwen3.8 diagnostic only"],"held_out_evaluator":"anthropic","human_baseline_status":"not_started","held_out_status":"sealed"},"artifacts":{"source":rel,"metadata":f"research/games/{c}-v1.json","win_recording":f"research/recordings/{c}-v1-win.json","loss_recording":f"research/recordings/{c}-v1-loss.json","thumbnail":f"docs/static/img/games/{c}-v1.png","source_sha256":h},"status":"prototype"}
  (out/f"{c}-v1.json").write_text(json.dumps(meta,indent=2)+"\n");im=Image.new("RGB",(64,64));im.putdata([PAL[int(v)] for row in frame for v in row]);im.save(ROOT/"docs"/"static"/"img"/"games"/f"{c}-v1.png",optimize=True);games.append({"game_id":c,"title":title,"axis":axis,"levels":6,"source_sha256":h})
 path=ROOT/"research"/"gpt-batch62-v1.json";path.write_text(json.dumps({"schema_version":1,"batch_id":"gpt-batch62-v1","created_at":"2026-08-30T00:00:00Z","design":"Ten glass-greenhouse, honeycomb-apiary, and quarry environments coordinate policies, adversaries, messages, simulations, relations, evidence, quantities, obligations, rhythms, and dependencies across unequal visible schedules.","games":games},indent=2)+"\n")
 sheet=Image.new("RGB",(800,352),(242,242,246));d=ImageDraw.Draw(sheet)
 for i,c in enumerate(CFG):
  im=Image.open(ROOT/"docs"/"static"/"img"/"games"/f"{c}-v1.png").resize((128,128),Image.Resampling.NEAREST);x,y=(i%5)*160+16,(i//5)*176+12;sheet.paste(im,(x,y));d.text((x,y+136),c,fill=(28,28,36))
 (ROOT/".cache").mkdir(exist_ok=True);sheet.save(ROOT/".cache"/"batch62-contact.png",optimize=True);print("10 metadata records",path)
if __name__=="__main__":main()
