"""Generate metadata and visual artifacts for research Batch 17."""
import hashlib,importlib.util,json
from PIL import Image,ImageDraw
from arcengine import ActionInput,GameAction
from build_research_batch06_metadata import ROOT,SESSION,PAL
CFG={
"q108":("Camera Relative","multi-scale-reference-frames","camera-relative-controls-world-relative-dynamics",["frame-separation","view-rotation"],["rotates world drift with the camera","uses screen coordinates after rotation","forgets which frame controls motion"],[1,2,3,4,5],"A blue body follows camera-relative controls while an orange world drift leaves a trail."),
"q117":("Teach Back","policy-learning-from-demonstration","learn-then-demonstrate-transformed-policy",["rule-abstraction","student-feedback"],["copies tutor outputs directly","teaches before observing every mapping","confuses student error with noise"],[1,2,3,4,5,6],"A blue tutor's mapping becomes a green lesson for an orange student."),
"q127":("Policy Mirror","adaptive-adversary","opponent-adopts-last-winning-policy",["strategy-transfer","anti-repetition"],["repeats the winning strategy","ignores the opponent update","changes before the policy mirror"],[1,2,3,4],"An orange opponent adopts each blue winning strategy inside a pale arena."),
"q137":("Shared Convention","compositional-communication","feedback-negotiated-common-mapping",["partner-alignment","stable-convention"],["chases one partner","changes proposals before feedback settles","abandons an already aligned mapping"],[1,2,5,6],"Two colored partners converge through green feedback on one blue proposal."),
"q147":("Affordance Sketch","counterfactual-planning","outline-fit-before-construction",["structural-preview","rotation-planning"],["constructs before previewing","matches area instead of orientation","checks only one object"],[1,3,4,5,6],"Violet outlines preview blue object fit across a green drafting desk."),
"q157":("Same Graph New Bodies","structural-analogy","causal-graph-across-new-embodiments",["topology-transfer","appearance-invariance"],["matches object appearance","uses spatial proximity as causality","relearns the same graph per level"],[1,2,3,4],"Changing blue and orange bodies preserve one gray causal graph over cyan fields."),
"q167":("Probe or Act","confidence-calibration","safe-probe-before-irreversible-use",["uncertainty-reduction","commitment"],["acts on ambiguous evidence","probes after commitment","spends every available probe"],[1,2,3,4,5,6],"Orange objects sit beneath blue probes whose outcomes shrink uncertainty."),
"q177":("Pressure Web","continuous-quantity-reasoning","capacity-safe-connected-pressure-transfer",["gradient-control","rupture-avoidance"],["overfills a chamber","balances totals but not gradients","pumps against the selected membrane"],[1,2,3,4,6],"Blue pressure columns move through orange membranes inside a yellow plant."),
"q187":("Echo Cost","long-horizon-credit-assignment","use-history-dependent-later-action-effect",["repetition-cost","early-diversity"],["assumes a constant effect","repeats the locally strongest action","forgets early use counts"],[1,2,6],"Blue and orange actions accumulate red use costs before changing a later state."),
"q197":("Phase Landmark","temporal-abstraction","landmark-anchored-cycle-synchronization",["phase-reference","long-cycle-alignment"],["counts from an arbitrary frame","confuses equal-looking phases","uses one cycle's landmark for both"],[1,2,5,6],"Two colored cycles synchronize around a distinctive green landmark.")}
def load(c):
 p=ROOT/"docs"/"static"/"games"/"src"/f"{c}-v1"/f"{c}.py";s=importlib.util.spec_from_file_location(c,p);m=importlib.util.module_from_spec(s);s.loader.exec_module(m);return p,m
def main():
 games=[];out=ROOT/"research"/"games"
 for c,v in CFG.items():
  title,axis,primary,secondary,failures,actions,sil=v;p,m=load(c);h=hashlib.sha256(p.read_bytes()).hexdigest();rel=p.relative_to(ROOT).as_posix();names=[x["name"] for x in m.LEVELS]
  meta={"schema_version":1,"game_id":c,"version":"v1","internal_title":title,"public_title":None,"author_partition":"gpt","authorship":{"model_family":"OpenAI GPT-5","model_snapshot":"current Codex task model; exact deployment id not exposed to task","session_id":SESSION,"created_at":"2026-08-30T00:00:00Z","source_lineage":[f"research/gpt-ideas-v2.tsv:{c}"],"source_commit":None},"mechanics":{"primary":primary,"secondary":secondary,"novelty_claim":names[-1],"closest_prior_art":["research/coverage-gap-study-v1.md","research/flash-game-mechanics-survey.md"]},"failure_modes":failures,"interface":{"actions":actions,"observation":"64x64x16","deterministic":True,"seeded_stochasticity":False},"progression":[{"level":i+1,"role":["orient","discriminate","plan","compose","inhibit","synthesize"][i],"new_demand":n,"composes":list(range(1,i+1))} for i,n in enumerate(names)],"visual_identity":{"dominant_palette":[],"silhouette_grammar":sil,"spatial_grammar":sil,"motion_grammar":primary.replace("-"," "),"hud_grammar":"Persistent colored state markers expose the mechanic without text.","nearest_visual_games":[]},"evaluation":{"allowed_development_models":["deterministic-solvers","random-fuzzer","Qwen3.8 diagnostic only"],"held_out_evaluator":"anthropic","human_baseline_status":"not_started","held_out_status":"sealed"},"artifacts":{"source":rel,"metadata":f"research/games/{c}-v1.json","win_recording":f"research/recordings/{c}-v1-win.json","loss_recording":f"research/recordings/{c}-v1-loss.json","thumbnail":f"docs/static/img/games/{c}-v1.png","source_sha256":h},"status":"prototype"}
  (out/f"{c}-v1.json").write_text(json.dumps(meta,indent=2)+"\n");g=getattr(m,c.upper())();a=g.perform_action(ActionInput(id=GameAction.RESET),raw=True).frame[-1];im=Image.new("RGB",(64,64));im.putdata([PAL[int(x)] for row in a for x in row]);im.save(ROOT/"docs"/"static"/"img"/"games"/f"{c}-v1.png",optimize=True);games.append({"game_id":c,"title":title,"axis":axis,"levels":6,"source_sha256":h})
 path=ROOT/"research"/"gpt-batch17-v1.json";path.write_text(json.dumps({"schema_version":1,"batch_id":"gpt-batch17-v1","created_at":"2026-08-30T00:00:00Z","design":"Ten seventh-pass games across the second ten research axes, each with six progressive levels and a distinct colorful environment.","games":games},indent=2)+"\n")
 sheet=Image.new("RGB",(800,352),(242,242,246));d=ImageDraw.Draw(sheet)
 for i,c in enumerate(CFG):im=Image.open(ROOT/"docs"/"static"/"img"/"games"/f"{c}-v1.png").resize((128,128),Image.Resampling.NEAREST);x,y=(i%5)*160+16,(i//5)*176+12;sheet.paste(im,(x,y));d.text((x,y+136),c,fill=(28,28,36))
 sheet.save(ROOT/".cache"/"batch17-contact.png",optimize=True);print("10 metadata records",path)
if __name__=="__main__":main()
