"""Generate metadata, thumbnails, and the contact sheet for research Batch 68."""
import hashlib,importlib.util,json
from PIL import Image,ImageDraw
from arcengine import ActionInput,GameAction
from build_research_batch06_metadata import ROOT,SESSION,PAL
CFG={
"q518":("Asterism Frame","multi-scale-reference-frames","local-orbit-actions-compose-with-a-precessing-chart-while-observations-survive-a-physical-reset","A white observatory maps eight orbit points above phase, evidence, reset, and lock rails."),
"q548":("Asterism Lesson","policy-learning-from-demonstration","conditional-star-policies-must-be-inferred-through-context-switches-and-causally-empty-gestures","A silver observatory layers demonstration stars above context, policy, gesture, and evidence strips."),
"q578":("Asterism Counter","adaptive-adversary","a-three-tactic-rival-is-deliberately-shaped-by-recent-treatments-and-chart-precession","A gray orbital arena places a star path above three rival tactic chambers and persistent history tiles."),
"q608":("Asterism Grammar","compositional-communication","grouped-star-glyphs-are-reversed-recolored-and-rotated-by-precessing-relays-before-decoding","A stone signal observatory layers six colored glyph nodes above relay, phase, and decoded-result rails."),
"q638":("Asterism Sandbox","counterfactual-planning","two-miniature-star-systems-produce-persistent-evidence-despite-physical-reset-and-precession","A charcoal laboratory places twin star boxes above persistent evidence, phase, and commitment strips."),
"q668":("Asterism Analogy","structural-analogy","a-cyclic-star-gap-and-precession-pair-transfer-from-geometry-to-a-different-agent-surface","A black relation gallery places source and target star panes above phase, surface, and transfer rails."),
"q698":("Asterism Evidence","confidence-calibration","unequal-star-samples-support-stopping-only-when-no-unseen-sample-can-reverse-the-margin","A pink evidence observatory aligns sample slots above result tiles, a signed margin, and reset cursor."),
"q737":("Spectrum Gradient","continuous-quantity-reasoning","conserved-spectral-mass-moves-through-capacity-limited-channels-that-rotate-with-phase","A rose spectrum lab holds three colored reservoirs above goal, phase, pulse, and commitment bands."),
"q758":("Asterism Obligation","long-horizon-credit-assignment","light-debts-remain-attached-to-star-identities-across-visible-position-swaps-and-resets","A blue creditor observatory places two identity panes above light, debt, swap, and reset tracks."),
"q788":("Asterism Rhythm","temporal-abstraction","macro-orbits-change-period-and-must-be-interrupted-at-a-state-defined-window-after-resets","A cyan timing observatory places twelve orbit nodes above period, memory, and interruption tracks.")}
def load(c):
 p=ROOT/"docs"/"static"/"games"/"src"/f"{c}-v1"/f"{c}.py";s=importlib.util.spec_from_file_location(c,p);m=importlib.util.module_from_spec(s);s.loader.exec_module(m);return p,m
def main():
 games=[];out=ROOT/"research"/"games";out.mkdir(parents=True,exist_ok=True)
 for c,(title,axis,primary,silhouette) in CFG.items():
  p,m=load(c);h=hashlib.sha256(p.read_bytes()).hexdigest();rel=p.relative_to(ROOT).as_posix();names=[x["name"] for x in m.LEVELS];g=getattr(m,c.upper())();frame=g.perform_action(ActionInput(id=GameAction.RESET),raw=True).frame[-1];palette=sorted({int(v) for row in frame for v in row})
  meta={"schema_version":1,"game_id":c,"version":"v1","internal_title":title,"public_title":None,"author_partition":"gpt","authorship":{"model_family":"OpenAI GPT-5","model_snapshot":"current Codex task model; exact deployment id not exposed to task","session_id":SESSION,"created_at":"2026-08-30T00:00:00Z","source_lineage":[f"research/gpt-ideas-v2.tsv:{c}"],"source_commit":None},"mechanics":{"primary":primary,"secondary":[axis,"underrepresented-capability-expansion"],"novelty_claim":names[-1],"closest_prior_art":["research/coverage-gap-study-v1.md","research/flash-game-mechanics-survey.md"]},"failure_modes":["treats chart precession as visual motion without composing its effect into the next action","forgets persistent observations, histories, or debts when only physical orbital state resets","matches surface colors while losing a cyclic relation, conserved total, safe-stopping bound, or causal identity"],"interface":{"actions":[1,2,3,4,5,6],"observation":"64x64x16","deterministic":True,"seeded_stochasticity":False},"progression":[{"level":i+1,"role":["orient","discriminate","plan","compose","inhibit","synthesize"][i],"new_demand":n,"composes":list(range(1,i+1))} for i,n in enumerate(names)],"visual_identity":{"dominant_palette":palette,"silhouette_grammar":silhouette,"spatial_grammar":silhouette,"motion_grammar":primary.replace("-"," "),"hud_grammar":"Orbit points, star links, sample slots, glyph nodes, miniature observatories, spectral reservoirs, identity panes, phase strips, persistent evidence, and state-defined windows expose state without text.","nearest_visual_games":[]},"evaluation":{"allowed_development_models":["deterministic-solvers","random-fuzzer","Qwen3.8 diagnostic only"],"held_out_evaluator":"anthropic","human_baseline_status":"not_started","held_out_status":"sealed"},"artifacts":{"source":rel,"metadata":f"research/games/{c}-v1.json","win_recording":f"research/recordings/{c}-v1-win.json","loss_recording":f"research/recordings/{c}-v1-loss.json","thumbnail":f"docs/static/img/games/{c}-v1.png","source_sha256":h},"status":"prototype"}
  (out/f"{c}-v1.json").write_text(json.dumps(meta,indent=2)+"\n");im=Image.new("RGB",(64,64));im.putdata([PAL[int(v)] for row in frame for v in row]);im.save(ROOT/"docs"/"static"/"img"/"games"/f"{c}-v1.png",optimize=True);games.append({"game_id":c,"title":title,"axis":axis,"levels":6,"source_sha256":h})
 path=ROOT/"research"/"gpt-batch68-v1.json";path.write_text(json.dumps({"schema_version":1,"batch_id":"gpt-batch68-v1","created_at":"2026-08-30T00:00:00Z","design":"Nine bright observatory environments compose local actions with precessing star relations across frames, demonstrations, rivals, messages, simulations, analogies, evidence, obligations, and macro-time; a spectrum laboratory adds phase-rotated conserved flow.","games":games},indent=2)+"\n")
 sheet=Image.new("RGB",(800,352),(242,242,246));d=ImageDraw.Draw(sheet)
 for i,c in enumerate(CFG):
  im=Image.open(ROOT/"docs"/"static"/"img"/"games"/f"{c}-v1.png").resize((128,128),Image.Resampling.NEAREST);x,y=(i%5)*160+16,(i//5)*176+12;sheet.paste(im,(x,y));d.text((x,y+136),c,fill=(28,28,36))
 (ROOT/".cache").mkdir(exist_ok=True);sheet.save(ROOT/".cache"/"batch68-contact.png",optimize=True);print("10 metadata records",path)
if __name__=="__main__":main()
