"""Generate metadata, thumbnails, and the contact sheet for research Batch 70."""
import hashlib,importlib.util,json
from PIL import Image,ImageDraw
from arcengine import ActionInput,GameAction
from build_research_batch06_metadata import ROOT,SESSION,PAL
CFG={
"q523":("Impeller Frame","multi-scale-reference-frames","blade-motion-composes-with-counter-rotating-wake-frames-while-redundant-alignment-samples-add-cost","A white turbine chamber places two blade rings above wake, evidence, sampling-cost, and lock rails."),
"q553":("Impeller Lesson","policy-learning-from-demonstration","wake-conditioned-policy-learning-separates-empty-gestures-from-demonstrations-before-samples-become-costly","A silver instruction turbine layers demonstration blades above context, gesture, evidence, and cost strips."),
"q562":("Tide Counter","adaptive-adversary","recent-shell-treatments-shape-a-three-tactic-rival-before-an-irreversible-sluice-can-open","A gray tidal basin aligns shell tracks above rival chambers, evidence tiles, currents, and a sluice gate."),
"q613":("Impeller Grammar","compositional-communication","paired-blade-glyphs-compose-through-counter-rotating-relays-and-redundant-decoded-samples-add-cost","A stone signal turbine layers glyph pairs above relay, group, wake, sample-cost, and code rails."),
"q643":("Impeller Sandbox","counterfactual-planning","two-miniature-turbines-reset-physical-state-while-persistent-probes-grow-more-costly-after-discrimination","A charcoal turbine lab places twin blade chambers above wake, evidence, reset, cost, and commitment strips."),
"q673":("Impeller Analogy","structural-analogy","direction-and-blade-gap-transfer-from-a-wake-diagram-to-riders-on-an-unrelated-surface","A black relation turbine places source and target panes above wake, surface, sample-cost, and transfer rails."),
"q703":("Impeller Evidence","confidence-calibration","unequal-wake-probes-require-stopping-at-first-certainty-because-every-later-sample-incurs-extra-cost","A pink evidence turbine aligns blade samples above results, signed margin, wake direction, and cost tracks."),
"q733":("Impeller Gradient","continuous-quantity-reasoning","conserved-blade-mass-circulates-through-four-capacity-limited-reservoirs-as-the-wake-reverses","A rose flow turbine holds four colored reservoirs above target, phase, direction, and commitment bands."),
"q763":("Impeller Obligation","long-horizon-credit-assignment","torque-debt-remains-attached-to-three-blade-identities-across-ring-rotation-and-sampled-inspection","A blue creditor turbine places three rider panes above torque, debt, rotation, sampling, and cost rails."),
"q793":("Impeller Rhythm","temporal-abstraction","counter-rotating-macros-change-period-and-must-be-interrupted-at-a-sampled-state-window","A cyan timing turbine places twelve blade nodes above period, wake, samples, cost, and interruption tracks.")}
def load(c):
 p=ROOT/"docs"/"static"/"games"/"src"/f"{c}-v1"/f"{c}.py";s=importlib.util.spec_from_file_location(c,p);m=importlib.util.module_from_spec(s);s.loader.exec_module(m);return p,m
def main():
 games=[];out=ROOT/"research"/"games";out.mkdir(parents=True,exist_ok=True)
 for c,(title,axis,primary,silhouette) in CFG.items():
  p,m=load(c);h=hashlib.sha256(p.read_bytes()).hexdigest();rel=p.relative_to(ROOT).as_posix();names=[x["name"] for x in m.LEVELS];g=getattr(m,c.upper())();frame=g.perform_action(ActionInput(id=GameAction.RESET),raw=True).frame[-1];palette=sorted({int(v) for row in frame for v in row})
  meta={"schema_version":1,"game_id":c,"version":"v1","internal_title":title,"public_title":None,"author_partition":"gpt","authorship":{"model_family":"OpenAI GPT-5","model_snapshot":"current Codex task model; exact deployment id not exposed to task","session_id":SESSION,"created_at":"2026-08-31T00:00:00Z","source_lineage":[f"research/gpt-ideas-v2.tsv:{c}"],"source_commit":None},"mechanics":{"primary":primary,"secondary":[axis,"underrepresented-capability-expansion"],"novelty_claim":names[-1],"closest_prior_art":["research/coverage-gap-study-v1.md","research/flash-game-mechanics-survey.md"]},"failure_modes":["applies local blade motion without composing the current counter-rotating wake frame","keeps sampling after the remaining evidence can no longer change the decision and incurs disqualifying cost","opens an irreversible sluice too early or repays torque to a ring position rather than the causal rider identity"],"interface":{"actions":[1,2,3,4,5,6],"observation":"64x64x16","deterministic":True,"seeded_stochasticity":False},"progression":[{"level":i+1,"role":["orient","discriminate","plan","compose","inhibit","synthesize"][i],"new_demand":n,"composes":list(range(1,i+1))} for i,n in enumerate(names)],"visual_identity":{"dominant_palette":palette,"silhouette_grammar":silhouette,"spatial_grammar":silhouette,"motion_grammar":primary.replace("-"," "),"hud_grammar":"Blade rings, wake bars, shell tracks, sluice gates, glyph relays, miniature turbines, evidence samples, four-reservoir flows, rider identities, sampling-cost tracks, and interruption windows expose state without text.","nearest_visual_games":[]},"evaluation":{"allowed_development_models":["deterministic-solvers","random-fuzzer","Qwen3.8 diagnostic only"],"held_out_evaluator":"anthropic","human_baseline_status":"not_started","held_out_status":"sealed"},"artifacts":{"source":rel,"metadata":f"research/games/{c}-v1.json","win_recording":f"research/recordings/{c}-v1-win.json","loss_recording":f"research/recordings/{c}-v1-loss.json","thumbnail":f"docs/static/img/games/{c}-v1.png","source_sha256":h},"status":"prototype"}
  (out/f"{c}-v1.json").write_text(json.dumps(meta,indent=2)+"\n");im=Image.new("RGB",(64,64));im.putdata([PAL[int(v)] for row in frame for v in row]);im.save(ROOT/"docs"/"static"/"img"/"games"/f"{c}-v1.png",optimize=True);games.append({"game_id":c,"title":title,"axis":axis,"levels":6,"source_sha256":h})
 path=ROOT/"research"/"gpt-batch70-v1.json";path.write_text(json.dumps({"schema_version":1,"batch_id":"gpt-batch70-v1","created_at":"2026-08-31T00:00:00Z","design":"Nine industrial turbine environments compose counter-rotating wakes with frames, demonstrations, messages, simulations, analogies, evidence, conserved flow, obligations, and macro-time while making redundant samples costly; a tidal basin adds deliberately delayed irreversible commitment.","games":games},indent=2)+"\n")
 sheet=Image.new("RGB",(800,352),(242,242,246));d=ImageDraw.Draw(sheet)
 for i,c in enumerate(CFG):
  im=Image.open(ROOT/"docs"/"static"/"img"/"games"/f"{c}-v1.png").resize((128,128),Image.Resampling.NEAREST);x,y=(i%5)*160+16,(i//5)*176+12;sheet.paste(im,(x,y));d.text((x,y+136),c,fill=(28,28,36))
 (ROOT/".cache").mkdir(exist_ok=True);sheet.save(ROOT/".cache"/"batch70-contact.png",optimize=True);print("10 metadata records",path)
if __name__=="__main__":main()
