"""Generate metadata, thumbnails, and a contact sheet for research Batch 93."""
import hashlib,importlib.util,json
from PIL import Image,ImageDraw
from arcengine import ActionInput,GameAction
from build_research_batch06_metadata import ROOT,SESSION,PAL
CFG={
"a121":("All But One","relational-logic-and-quantifiers","exactly-one-relation-violation","A steel selection chamber surrounds evidence bars with six candidates whose exception count depends on the active relation phase."),
"a122":("Between Lines","relational-logic-and-quantifiers","simultaneous-ternary-betweenness","A green geometric plane crosses three endpoint pairs around a movable body, scene rotation, and ternary satisfaction meter."),
"a123":("Same Row Different Role","relational-logic-and-quantifiers","orthogonal-team-and-role-equivalence","A coral three-by-three roster encodes row teams separately from appearance-shifting behavioral roles and column duplicates."),
"a124":("Exists Exactly One","relational-logic-and-quantifiers","nested-existence-and-uniqueness","A black relation panel links green and red columns around a movable blue witness, lever cursor, and degree constraints."),
"a125":("Nested Neighborhood","relational-logic-and-quantifiers","self-referential-second-order-neighborhood","A gold octagonal room graph marks typed nodes, doors, selected room, and validity over two-hop neighborhoods."),
"a126":("Relation Closure","relational-logic-and-quantifiers","minimum-shortcuts-for-transitive-reachability","A navy directed graph separates source and target regions while distinguishing base edges, shortcuts, reachability, and missing paths."),
"a127":("Triad Ban","relational-logic-and-quantifiers","overlapping-hypergraph-nonmonochromaticity","A brown seeded grid overlays selectable three-cell constraints on binary states with valid and violated triad meters."),
"a128":("Majority Relation","relational-logic-and-quantifiers","population-changing-simultaneous-majority","A cyan divider field displays current objects above, simultaneous region-majority results below, and target match count."),
"a129":("Canonical Room","symmetry-breaking-and-canonicalization","anchor-defined-dihedral-normal-form","A violet gallery presents four rotatable and reflectable rooms whose shared normal form is selected by an external anchor."),
"a130":("Leader Tile","symmetry-breaking-and-canonicalization","landmark-grounded-local-leader-election","A red signal arena rings eight identical agents around an off-ring landmark, local pulse rules, and leader multiplicity."),
}
def load(c):
 p=ROOT/"docs"/"static"/"games"/"src"/f"{c}-v1"/f"{c}.py";s=importlib.util.spec_from_file_location(c,p);m=importlib.util.module_from_spec(s);s.loader.exec_module(m);return p,m
def main():
 games=[];out=ROOT/"research"/"games";out.mkdir(parents=True,exist_ok=True)
 for c,(title,axis,primary,silhouette) in CFG.items():
  p,m=load(c);h=hashlib.sha256(p.read_bytes()).hexdigest();rel=p.relative_to(ROOT).as_posix();names=[x["name"] for x in m.LEVELS];g=getattr(m,c.upper())();frame=g.perform_action(ActionInput(id=GameAction.RESET),raw=True).frame[-1];palette=sorted({int(v) for row in frame for v in row})
  meta={"schema_version":1,"game_id":c,"version":"v1","internal_title":title,"public_title":None,"author_partition":"gpt","authorship":{"model_family":"OpenAI GPT-5","model_snapshot":"current Codex task model; exact deployment id not exposed to task","session_id":SESSION,"created_at":"2026-08-31T00:00:00Z","source_lineage":[f"research/anthropic-build-ideas-v1.tsv:{c}"],"concept_lineage":"gpt-seeded-anthropic-build","intended_builder":"anthropic","implementation_author_partition":"gpt","source_commit":None},"mechanics":{"primary":primary,"secondary":[axis,"relation-defined-global-validity"],"novelty_claim":names[-1],"closest_prior_art":["research/anthropic-build-ideas-v1.audit.json","research/coverage-gap-study-v1.md","research/flash-game-mechanics-survey.md"]},"failure_modes":["replaces exact, ternary, nested, transitive, hypergraph, or simultaneous quantification with pairwise visual similarity","binds relational roles to color or absolute orientation despite appearance and symmetry transformations","accepts any symmetry-equivalent state instead of the anchor-defined canonical representative or unique leader"],"interface":{"actions":[1,2,3,4,5,6],"observation":"64x64x16","deterministic":True,"seeded_stochasticity":False},"progression":[{"level":i+1,"role":["orient","discriminate","plan","compose","inhibit","synthesize"][i],"new_demand":n,"composes":list(range(1,i+1))} for i,n in enumerate(names)],"visual_identity":{"dominant_palette":palette,"silhouette_grammar":silhouette,"spatial_grammar":silhouette,"motion_grammar":primary.replace("-"," "),"hud_grammar":"Exception, ternary satisfaction, role duplicates, witnesses, nested validity, reachability, triads, majority results, normal forms, and leader multiplicity expose relational state without text.","nearest_visual_games":[]},"evaluation":{"allowed_development_models":["deterministic-solvers","random-fuzzer","Qwen3.8 diagnostic only"],"held_out_evaluator":"anthropic","human_baseline_status":"not_started","held_out_status":"sealed"},"artifacts":{"source":rel,"metadata":f"research/games/{c}-v1.json","win_recording":f"research/recordings/{c}-v1-win.json","loss_recording":f"research/recordings/{c}-v1-loss.json","thumbnail":f"docs/static/img/games/{c}-v1.png","source_sha256":h},"status":"prototype"}
  (out/f"{c}-v1.json").write_text(json.dumps(meta,indent=2)+"\n");im=Image.new("RGB",(64,64));im.putdata([PAL[int(v)] for row in frame for v in row]);im.save(ROOT/"docs"/"static"/"img"/"games"/f"{c}-v1.png",optimize=True);games.append({"game_id":c,"title":title,"axis":axis,"levels":6,"source_sha256":h})
 path=ROOT/"research"/"gpt-batch93-v1.json";path.write_text(json.dumps({"schema_version":1,"batch_id":"gpt-batch93-v1","created_at":"2026-08-31T00:00:00Z","provenance":"Concepts retain gpt-seeded-anthropic-build queue lineage; implementations in this batch are authored by OpenAI GPT-5 and are not attributed to Anthropic.","design":"Eight colorful relation diagrams ground exact, ternary, orthogonal-role, nested-existential, second-order, transitive, hypergraph, and simultaneous-majority logic; two symmetry boards require an external anchor for canonical orientation and unique leadership.","games":games},indent=2)+"\n")
 sheet=Image.new("RGB",(800,352),(242,242,246));d=ImageDraw.Draw(sheet)
 for i,c in enumerate(CFG):
  im=Image.open(ROOT/"docs"/"static"/"img"/"games"/f"{c}-v1.png").resize((128,128),Image.Resampling.NEAREST);x,y=(i%5)*160+16,(i//5)*176+12;sheet.paste(im,(x,y));d.text((x,y+136),c,fill=(28,28,36))
 (ROOT/".cache").mkdir(exist_ok=True);sheet.save(ROOT/".cache"/"batch93-contact.png",optimize=True);print("10 metadata records",path)
if __name__=="__main__":main()
