"""Generate metadata, thumbnails, and the contact sheet for research Batch 72."""
import hashlib,importlib.util,json
from PIL import Image,ImageDraw
from arcengine import ActionInput,GameAction
from build_research_batch06_metadata import ROOT,SESSION,PAL
CFG={
"q526":("Crossing Frame","multi-scale-reference-frames","ferry-motion-composes-with-capacity-limited-dock-frames-across-controllers-that-require-marked-handoffs","A white ferry map places three docks above passenger, frame, load, controller-mark, and lock rails."),
"q555":("Vivarium Lesson","policy-learning-from-demonstration","temperature-conditioned-demonstrations-reveal-a-reciprocal-partner-policy-grounded-in-recent-fairness","A silver terrarium layers temperature strata above fauna, context, fairness, evidence, and policy strips."),
"q586":("Crossing Counter","adaptive-adversary","a-three-tactic-ferry-rival-is-shaped-across-controller-specific-treatments-and-persistent-handoff-marks","A gray ferry arena aligns passenger tracks above rival chambers, load, controller, and handoff marks."),
"q616":("Crossing Grammar","compositional-communication","disjoint-controller-glyph-buffers-compose-only-through-persistent-nonverbal-ferry-marks","A stone signal ferry layers colored glyphs above dock relays, controller marks, groups, and code rails."),
"q646":("Crossing Sandbox","counterfactual-planning","two-controller-ferry-simulations-reset-physical-copies-while-marked-cross-view-evidence-persists","A charcoal ferry lab places twin simulated docks above evidence, reset state, handoff marks, and commitment."),
"q675":("Vivarium Analogy","structural-analogy","temperature-and-gap-relations-transfer-to-microfauna-through-a-fairness-dependent-partner-policy","A black terrarium gallery places source and target panes above fairness, surface, relation, and transfer rails."),
"q706":("Crossing Evidence","confidence-calibration","safe-stopping-requires-combining-unequal-samples-from-two-disjoint-controller-projections","A pink evidence ferry aligns sample slots above a signed margin, controller marks, and stopping rail."),
"q736":("Crossing Gradient","continuous-quantity-reasoning","conserved-passenger-flow-crosses-controller-specific-capacity-limited-edges-through-marked-handoffs","A rose flow ferry holds three passenger reservoirs above target, phase, controller marks, and commitment."),
"q766":("Crossing Obligation","long-horizon-credit-assignment","identity-bound-fare-debt-must-be-repaid-using-disjoint-views-passed-through-persistent-marks","A blue creditor ferry stacks two passenger identities beside cargo, debt, and controller-mark ledgers."),
"q796":("Crossing Rhythm","temporal-abstraction","two-controllers-must-share-disjoint-clock-projections-before-interrupting-a-ferry-macro-at-one-phase-pair","A cyan timing ferry places twelve track nodes above two clocks, handoff marks, macro count, and window rails.")}
def load(c):
 p=ROOT/"docs"/"static"/"games"/"src"/f"{c}-v1"/f"{c}.py";s=importlib.util.spec_from_file_location(c,p);m=importlib.util.module_from_spec(s);s.loader.exec_module(m);return p,m
def main():
 games=[];out=ROOT/"research"/"games";out.mkdir(parents=True,exist_ok=True)
 for c,(title,axis,primary,silhouette) in CFG.items():
  p,m=load(c);h=hashlib.sha256(p.read_bytes()).hexdigest();rel=p.relative_to(ROOT).as_posix();names=[x["name"] for x in m.LEVELS];g=getattr(m,c.upper())();frame=g.perform_action(ActionInput(id=GameAction.RESET),raw=True).frame[-1];palette=sorted({int(v) for row in frame for v in row})
  meta={"schema_version":1,"game_id":c,"version":"v1","internal_title":title,"public_title":None,"author_partition":"gpt","authorship":{"model_family":"OpenAI GPT-5","model_snapshot":"current Codex task model; exact deployment id not exposed to task","session_id":SESSION,"created_at":"2026-08-31T00:00:00Z","source_lineage":[f"research/gpt-ideas-v2.tsv:{c}"],"source_commit":None},"mechanics":{"primary":primary,"secondary":[axis,"underrepresented-capability-expansion"],"novelty_claim":names[-1],"closest_prior_art":["research/coverage-gap-study-v1.md","research/flash-game-mechanics-survey.md"]},"failure_modes":["switches controllers without first externalizing the outgoing hidden projection in a persistent mark","treats one controller's view as complete and ignores the complementary dock, evidence, debt, or clock attribute","tracks a passenger position instead of causal identity when ferry slots swap"],"interface":{"actions":[1,2,3,4,5,6],"observation":"64x64x16","deterministic":True,"seeded_stochasticity":False},"progression":[{"level":i+1,"role":["orient","discriminate","plan","compose","inhibit","synthesize"][i],"new_demand":n,"composes":list(range(1,i+1))} for i,n in enumerate(names)],"visual_identity":{"dominant_palette":palette,"silhouette_grammar":silhouette,"spatial_grammar":silhouette,"motion_grammar":primary.replace("-"," "),"hud_grammar":"Docks, ferries, passenger tracks, controller-specific glyphs, persistent handoff marks, simulation panes, sample margins, conserved reservoirs, identity ledgers, dual clocks, and interruption windows expose state without text.","nearest_visual_games":[]},"evaluation":{"allowed_development_models":["deterministic-solvers","random-fuzzer","Qwen3.8 diagnostic only"],"held_out_evaluator":"anthropic","human_baseline_status":"not_started","held_out_status":"sealed"},"artifacts":{"source":rel,"metadata":f"research/games/{c}-v1.json","win_recording":f"research/recordings/{c}-v1-win.json","loss_recording":f"research/recordings/{c}-v1-loss.json","thumbnail":f"docs/static/img/games/{c}-v1.png","source_sha256":h},"status":"prototype"}
  (out/f"{c}-v1.json").write_text(json.dumps(meta,indent=2)+"\n");im=Image.new("RGB",(64,64));im.putdata([PAL[int(v)] for row in frame for v in row]);im.save(ROOT/"docs"/"static"/"img"/"games"/f"{c}-v1.png",optimize=True);games.append({"game_id":c,"title":title,"axis":axis,"levels":6,"source_sha256":h})
 path=ROOT/"research"/"gpt-batch72-v1.json";path.write_text(json.dumps({"schema_version":1,"batch_id":"gpt-batch72-v1","created_at":"2026-08-31T00:00:00Z","design":"Eight vivid ferry environments require alternating controllers with disjoint state projections to leave persistent nonverbal evidence across frames, rivals, messages, simulations, evidence, conserved flow, obligations, and macro-time; two stacked terrariums add fairness-conditioned policy and analogy transfer.","games":games},indent=2)+"\n")
 sheet=Image.new("RGB",(800,352),(242,242,246));d=ImageDraw.Draw(sheet)
 for i,c in enumerate(CFG):
  im=Image.open(ROOT/"docs"/"static"/"img"/"games"/f"{c}-v1.png").resize((128,128),Image.Resampling.NEAREST);x,y=(i%5)*160+16,(i//5)*176+12;sheet.paste(im,(x,y));d.text((x,y+136),c,fill=(28,28,36))
 (ROOT/".cache").mkdir(exist_ok=True);sheet.save(ROOT/".cache"/"batch72-contact.png",optimize=True);print("10 metadata records",path)
if __name__=="__main__":main()
