"""Generate metadata, thumbnails, and a contact sheet for research Batch 92."""
import hashlib,importlib.util,json
from PIL import Image,ImageDraw
from arcengine import ActionInput,GameAction
from build_research_batch06_metadata import ROOT,SESSION,PAL
CFG={
"a111":("Occlusion Cover","combinatorial-packing-and-covering","phase-dependent-visibility-coverage","A navy emitter field places vertical screens among fragile cells, solar receivers, rotating rays, and phase-sensitive violation meters."),
"a112":("Layered Bin","combinatorial-packing-and-covering","retrieval-aware-depth-layer-packing","A brown warehouse stacks colored cargo across shelves, depths, columns, and a future retrieval-order strip."),
"a113":("Stable Pairing","matching-assignment-and-exchange","blocking-pair-free-preference-matching","A cyan pairing hall links two agent columns while revealing preference rounds, blocking-pair counts, and stable edges."),
"a114":("Capacity Match","matching-assignment-and-exchange","many-to-one-capacity-and-skill-composition","A violet factory routes distinct worker skills into three machines with capacity, quota, and overload indicators."),
"a115":("Rotating Assignment","matching-assignment-and-exchange","limited-recourse-dynamic-compatibility","A red orbital work board connects inner workers to rotating outer stations while tracking phase and reassignment budget."),
"a116":("Complement Market","matching-assignment-and-exchange","bundle-complementarity-under-swap-routing","A magenta market groups three item types into stalls where pair value, swaps, and stranded singletons remain visible."),
"a117":("Fair Split","matching-assignment-and-exchange","envy-free-indivisible-allocation","A pale valuation table partitions eight patterned tiles between two owners while switching viewpoints and exposing envy."),
"a118":("Bottleneck Match","matching-assignment-and-exchange","minimax-carrier-task-assignment","A dark depot draws five carrier routes, task endpoints, travel bars, simultaneous maximum, and tie count."),
"a119":("Temporal Booking","matching-assignment-and-exchange","equipment-constrained-interval-coloring","A black calendar lays colored task intervals across equipped room lanes with cursor, conflicts, and missing-equipment meters."),
"a120":("Chain Exchange","matching-assignment-and-exchange","simultaneous-cycle-clearing","A cream exchange ring connects six agents, colored holdings, directed desires, cycle selection, satisfaction, and blocked trades."),
}
def load(c):
 p=ROOT/"docs"/"static"/"games"/"src"/f"{c}-v1"/f"{c}.py";s=importlib.util.spec_from_file_location(c,p);m=importlib.util.module_from_spec(s);s.loader.exec_module(m);return p,m
def main():
 games=[];out=ROOT/"research"/"games";out.mkdir(parents=True,exist_ok=True)
 for c,(title,axis,primary,silhouette) in CFG.items():
  p,m=load(c);h=hashlib.sha256(p.read_bytes()).hexdigest();rel=p.relative_to(ROOT).as_posix();names=[x["name"] for x in m.LEVELS];g=getattr(m,c.upper())();frame=g.perform_action(ActionInput(id=GameAction.RESET),raw=True).frame[-1];palette=sorted({int(v) for row in frame for v in row})
  meta={"schema_version":1,"game_id":c,"version":"v1","internal_title":title,"public_title":None,"author_partition":"gpt","authorship":{"model_family":"OpenAI GPT-5","model_snapshot":"current Codex task model; exact deployment id not exposed to task","session_id":SESSION,"created_at":"2026-08-31T00:00:00Z","source_lineage":[f"research/anthropic-build-ideas-v1.tsv:{c}"],"concept_lineage":"gpt-seeded-anthropic-build","intended_builder":"anthropic","implementation_author_partition":"gpt","source_commit":None},"mechanics":{"primary":primary,"secondary":[axis,"global-constraint-evaluation-after-local-edits"],"novelty_claim":names[-1],"closest_prior_art":["research/anthropic-build-ideas-v1.audit.json","research/coverage-gap-study-v1.md","research/flash-game-mechanics-survey.md"]},"failure_modes":["optimizes occupied area while ignoring phase-dependent visibility or retrieval accessibility","accepts a locally compatible assignment that violates stability, quota, recourse, bundle, fairness, minimax, interval, or cycle constraints","treats relational preferences and future phases as fixed per-object labels instead of global coupled state"],"interface":{"actions":[1,2,3,4,5,6],"observation":"64x64x16","deterministic":True,"seeded_stochasticity":False},"progression":[{"level":i+1,"role":["orient","discriminate","plan","compose","inhibit","synthesize"][i],"new_demand":n,"composes":list(range(1,i+1))} for i,n in enumerate(names)],"visual_identity":{"dominant_palette":palette,"silhouette_grammar":silhouette,"spatial_grammar":silhouette,"motion_grammar":primary.replace("-"," "),"hud_grammar":"Visibility, retrieval order, blockers, quotas, recourse, bundle value, envy, maximum time, interval conflicts, and cycle satisfaction expose relational state without text.","nearest_visual_games":[]},"evaluation":{"allowed_development_models":["deterministic-solvers","random-fuzzer","Qwen3.8 diagnostic only"],"held_out_evaluator":"anthropic","human_baseline_status":"not_started","held_out_status":"sealed"},"artifacts":{"source":rel,"metadata":f"research/games/{c}-v1.json","win_recording":f"research/recordings/{c}-v1-win.json","loss_recording":f"research/recordings/{c}-v1-loss.json","thumbnail":f"docs/static/img/games/{c}-v1.png","source_sha256":h},"status":"prototype"}
  (out/f"{c}-v1.json").write_text(json.dumps(meta,indent=2)+"\n");im=Image.new("RGB",(64,64));im.putdata([PAL[int(v)] for row in frame for v in row]);im.save(ROOT/"docs"/"static"/"img"/"games"/f"{c}-v1.png",optimize=True);games.append({"game_id":c,"title":title,"axis":axis,"levels":6,"source_sha256":h})
 path=ROOT/"research"/"gpt-batch92-v1.json";path.write_text(json.dumps({"schema_version":1,"batch_id":"gpt-batch92-v1","created_at":"2026-08-31T00:00:00Z","provenance":"Concepts retain gpt-seeded-anthropic-build queue lineage; implementations in this batch are authored by OpenAI GPT-5 and are not attributed to Anthropic.","design":"Two packing boards make coverage depend on visibility and access order; eight assignment and market systems require stability, quotas, recourse, complementarities, fairness, minimax timing, interval feasibility, and cycle clearing.","games":games},indent=2)+"\n")
 sheet=Image.new("RGB",(800,352),(242,242,246));d=ImageDraw.Draw(sheet)
 for i,c in enumerate(CFG):
  im=Image.open(ROOT/"docs"/"static"/"img"/"games"/f"{c}-v1.png").resize((128,128),Image.Resampling.NEAREST);x,y=(i%5)*160+16,(i//5)*176+12;sheet.paste(im,(x,y));d.text((x,y+136),c,fill=(28,28,36))
 (ROOT/".cache").mkdir(exist_ok=True);sheet.save(ROOT/".cache"/"batch92-contact.png",optimize=True);print("10 metadata records",path)
if __name__=="__main__":main()
