"""Generate metadata, thumbnails, and the contact sheet for research Batch 55."""
import hashlib,importlib.util,json
from PIL import Image,ImageDraw
from arcengine import ActionInput,GameAction
from build_research_batch06_metadata import ROOT,SESSION,PAL
CFG={
"q230":("Workbench Veil","observer-dependent-dynamics","attention-scheduled-tool-updates-with-helper-identity-bound-obligations","A white mobile bench uses three pegboard fixtures, moving tools, and visible debt rails."),
"q260":("Workbench Pact","social-inference","hidden-workshop-convention-with-delayed-helper-specific-reciprocity","A silver workshop court stacks three tool fixtures above reply and obligation bands."),
"q290":("Workbench Probe","causal-intervention","budgeted-fixture-diagnosis-before-repaid-helper-bound-repair","A gray diagnostic bench places three fixtures above evidence, debt, and repair rails."),
"q320":("Workbench Ledger","conservation-law-induction","conserved-tool-stock-with-temporary-helper-specific-loans","A charcoal stock bench exposes three bins with quantities and loan indicators."),
"q350":("Workbench Survey","epistemic-resource-allocation","bounded-fixture-sampling-with-identity-bound-sensor-favors","A red survey bench arranges three lenses above evidence and policy bands."),
"q380":("Workbench Rig","tool-construction","multi-part-reusable-tool-assembly-with-helper-specific-debt","A black fabrication bench grows components beneath three pegboard fixtures."),
"q410":("Workbench Delegation","distributed-partial-observability","controller-mark-integration-with-identity-bound-handoff-obligations","A magenta workshop splits complementary controller views above marks and debt rails."),
"q440":("Workbench Revision","nonstationary-rule-revision","wear-revised-fixture-law-with-helper-specific-recalibration-debt","A pink mobile bench moves three tools across wear, rule, and repair rails."),
"q448":("Breakwater Lineage","persistent-identity","split-merge-ancestry-with-a-dormant-first-intervention-across-subgoals","An orange modular harbor traces skiff ancestry above dormant and subgoal bands."),
"q512":("Lockwater Frame","multi-scale-reference-frames","local-barge-motion-with-identity-preserving-appearance-and-position-exchange","A blue stepped canal separates two barges from frame, trail, swap, and assignment rails.")}
def load(c):
 p=ROOT/"docs"/"static"/"games"/"src"/f"{c}-v1"/f"{c}.py";s=importlib.util.spec_from_file_location(c,p);m=importlib.util.module_from_spec(s);s.loader.exec_module(m);return p,m
def main():
 games=[];out=ROOT/"research"/"games";out.mkdir(parents=True,exist_ok=True)
 for c,(title,axis,primary,silhouette) in CFG.items():
  p,m=load(c);h=hashlib.sha256(p.read_bytes()).hexdigest();rel=p.relative_to(ROOT).as_posix();names=[x["name"] for x in m.LEVELS];g=getattr(m,c.upper())();frame=g.perform_action(ActionInput(id=GameAction.RESET),raw=True).frame[-1];palette=sorted({int(v) for row in frame for v in row})
  meta={"schema_version":1,"game_id":c,"version":"v1","internal_title":title,"public_title":None,"author_partition":"gpt","authorship":{"model_family":"OpenAI GPT-5","model_snapshot":"current Codex task model; exact deployment id not exposed to task","session_id":SESSION,"created_at":"2026-08-30T00:00:00Z","source_lineage":[f"research/gpt-ideas-v2.tsv:{c}"],"source_commit":None},"mechanics":{"primary":primary,"secondary":[axis,"identity-bound-obligation-and-dormant-effect-composition"],"novelty_claim":names[-1],"closest_prior_art":["research/coverage-gap-study-v1.md","research/flash-game-mechanics-survey.md"]},"failure_modes":["repays the currently held tool instead of the helper identity that supplied it","forgets an early dormant intervention after locally completing a subgoal","tracks appearance or position rather than persistent causal identity"],"interface":{"actions":[1,2,3,4,5,6],"observation":"64x64x16","deterministic":True,"seeded_stochasticity":False},"progression":[{"level":i+1,"role":["orient","discriminate","plan","compose","inhibit","synthesize"][i],"new_demand":n,"composes":list(range(1,i+1))} for i,n in enumerate(names)],"visual_identity":{"dominant_palette":palette,"silhouette_grammar":silhouette,"spatial_grammar":silhouette,"motion_grammar":primary.replace("-"," "),"hud_grammar":"Colored fixture, evidence, helper, debt, lineage, dormant, frame, swap, and assignment rails expose state without text.","nearest_visual_games":[]},"evaluation":{"allowed_development_models":["deterministic-solvers","random-fuzzer","Qwen3.8 diagnostic only"],"held_out_evaluator":"anthropic","human_baseline_status":"not_started","held_out_status":"sealed"},"artifacts":{"source":rel,"metadata":f"research/games/{c}-v1.json","win_recording":f"research/recordings/{c}-v1-win.json","loss_recording":f"research/recordings/{c}-v1-loss.json","thumbnail":f"docs/static/img/games/{c}-v1.png","source_sha256":h},"status":"prototype"}
  (out/f"{c}-v1.json").write_text(json.dumps(meta,indent=2)+"\n");im=Image.new("RGB",(64,64));im.putdata([PAL[int(v)] for row in frame for v in row]);im.save(ROOT/"docs"/"static"/"img"/"games"/f"{c}-v1.png",optimize=True);games.append({"game_id":c,"title":title,"axis":axis,"levels":6,"source_sha256":h})
 path=ROOT/"research"/"gpt-batch55-v1.json";path.write_text(json.dumps({"schema_version":1,"batch_id":"gpt-batch55-v1","created_at":"2026-08-30T00:00:00Z","design":"Ten games coupling eight workshop capabilities to delayed helper-identity obligations, then testing dormant first-intervention memory and identity through exchanged appearance, position, and reference frame.","games":games},indent=2)+"\n")
 sheet=Image.new("RGB",(800,352),(242,242,246));d=ImageDraw.Draw(sheet)
 for i,c in enumerate(CFG):
  im=Image.open(ROOT/"docs"/"static"/"img"/"games"/f"{c}-v1.png").resize((128,128),Image.Resampling.NEAREST);x,y=(i%5)*160+16,(i//5)*176+12;sheet.paste(im,(x,y));d.text((x,y+136),c,fill=(28,28,36))
 (ROOT/".cache").mkdir(exist_ok=True);sheet.save(ROOT/".cache"/"batch55-contact.png",optimize=True);print("10 metadata records",path)
if __name__=="__main__":main()
