"""Generate metadata, thumbnails, and the contact sheet for research Batch 66."""
import hashlib,importlib.util,json
from PIL import Image,ImageDraw
from arcengine import ActionInput,GameAction
from build_research_batch06_metadata import ROOT,SESSION,PAL
CFG={
"q520":("Vault Frame","multi-scale-reference-frames","two-conserved-echo-types-route-through-shared-containers-under-a-moving-local-passage-frame","A white branching vault places three echo chambers above frame, capacity, and target rails."),
"q550":("Vault Lesson","policy-learning-from-demonstration","conditional-policy-transfer-maintains-two-independent-ledgers-in-shared-containers","A silver branching vault places a demonstration above context, red-echo, blue-echo, and gesture bars."),
"q580":("Vault Counter","adaptive-adversary","rival-shaping-depends-on-the-distribution-of-two-independently-conserved-echo-types","A gray branching vault aligns three tactic chambers above dual ledgers and a rival exploit rail."),
"q610":("Vault Grammar","compositional-communication","grouped-message-operations-redistribute-two-independent-ledgers-before-decoding","A stone branching vault stacks grouped glyphs above three paired-ledger readouts."),
"q640":("Vault Sandbox","counterfactual-planning","dual-ledger-simulation-evidence-persists-while-miniature-vaults-reset","A charcoal branching vault places two miniature systems above red, blue, reset, and commitment bars."),
"q670":("Vault Analogy","structural-analogy","relational-transfer-preserves-separate-source-and-target-ledgers-across-surface-change","A black branching gallery maps paired source ledgers to a contrasting target above relation and transfer rails."),
"q700":("Vault Evidence","confidence-calibration","unequal-samples-move-two-conserved-types-until-no-remaining-result-can-reverse-the-decision","A pink evidence vault places three sample chambers above paired evidence and signed-margin bars."),
"q730":("Vault Gradient","continuous-quantity-reasoning","two-conserved-quantities-share-capacity-limited-chambers-under-phase-rotation","A rose branching vault holds three paired quantity chambers above capacity, phase, and goal rails."),
"q760":("Vault Obligation","long-horizon-credit-assignment","two-quantity-debts-remain-attached-to-causal-identities-after-visible-position-swaps","A blue creditor vault places two identity chambers above player ledgers, debt, and repayment bars."),
"q777":("Canopy Rhythm","temporal-abstraction","capacity-limited-seed-store-persists-through-macro-routines-to-an-interruption-window","A cyan terraced orchard layers seasonal bands above store, pulse, macro, and interruption rails.")}
def load(c):
 p=ROOT/"docs"/"static"/"games"/"src"/f"{c}-v1"/f"{c}.py";s=importlib.util.spec_from_file_location(c,p);m=importlib.util.module_from_spec(s);s.loader.exec_module(m);return p,m
def main():
 games=[];out=ROOT/"research"/"games";out.mkdir(parents=True,exist_ok=True)
 for c,(title,axis,primary,silhouette) in CFG.items():
  p,m=load(c);h=hashlib.sha256(p.read_bytes()).hexdigest();rel=p.relative_to(ROOT).as_posix();names=[x["name"] for x in m.LEVELS];g=getattr(m,c.upper())();frame=g.perform_action(ActionInput(id=GameAction.RESET),raw=True).frame[-1];palette=sorted({int(v) for row in frame for v in row})
  meta={"schema_version":1,"game_id":c,"version":"v1","internal_title":title,"public_title":None,"author_partition":"gpt","authorship":{"model_family":"OpenAI GPT-5","model_snapshot":"current Codex task model; exact deployment id not exposed to task","session_id":SESSION,"created_at":"2026-08-30T00:00:00Z","source_lineage":[f"research/gpt-ideas-v2.tsv:{c}"],"source_commit":None},"mechanics":{"primary":primary,"secondary":[axis,"underrepresented-capability-expansion"],"novelty_claim":names[-1],"closest_prior_art":["research/coverage-gap-study-v1.md","research/flash-game-mechanics-survey.md"]},"failure_modes":["tracks only the combined occupancy and silently converts or loses one independently conserved quantity","uses a locally valid transfer that overfills a shared destination or misreads the moving frame","forgets which causal identity owns each quantity debt or destroys persistent evidence when a simulation resets"],"interface":{"actions":[1,2,3,4,5,6],"observation":"64x64x16","deterministic":True,"seeded_stochasticity":False},"progression":[{"level":i+1,"role":["orient","discriminate","plan","compose","inhibit","synthesize"][i],"new_demand":n,"composes":list(range(1,i+1))} for i,n in enumerate(names)],"visual_identity":{"dominant_palette":palette,"silhouette_grammar":silhouette,"spatial_grammar":silhouette,"motion_grammar":primary.replace("-"," "),"hud_grammar":"Branching chambers, paired echo columns, separate ledger bars, shared-capacity tracks, identity panes, evidence reservoirs, terraced stores, and macro windows expose state without text.","nearest_visual_games":[]},"evaluation":{"allowed_development_models":["deterministic-solvers","random-fuzzer","Qwen3.8 diagnostic only"],"held_out_evaluator":"anthropic","human_baseline_status":"not_started","held_out_status":"sealed"},"artifacts":{"source":rel,"metadata":f"research/games/{c}-v1.json","win_recording":f"research/recordings/{c}-v1-win.json","loss_recording":f"research/recordings/{c}-v1-loss.json","thumbnail":f"docs/static/img/games/{c}-v1.png","source_sha256":h},"status":"prototype"}
  (out/f"{c}-v1.json").write_text(json.dumps(meta,indent=2)+"\n");im=Image.new("RGB",(64,64));im.putdata([PAL[int(v)] for row in frame for v in row]);im.save(ROOT/"docs"/"static"/"img"/"games"/f"{c}-v1.png",optimize=True);games.append({"game_id":c,"title":title,"axis":axis,"levels":6,"source_sha256":h})
 path=ROOT/"research"/"gpt-batch66-v1.json";path.write_text(json.dumps({"schema_version":1,"batch_id":"gpt-batch66-v1","created_at":"2026-08-30T00:00:00Z","design":"Nine colorful branching-vault environments require simultaneous bookkeeping of two independently conserved quantities sharing constrained containers across frames, policies, rivals, language, simulations, analogies, evidence, gradients, and obligations; a terraced orchard adds capacity-aware macro timing.","games":games},indent=2)+"\n")
 sheet=Image.new("RGB",(800,352),(242,242,246));d=ImageDraw.Draw(sheet)
 for i,c in enumerate(CFG):
  im=Image.open(ROOT/"docs"/"static"/"img"/"games"/f"{c}-v1.png").resize((128,128),Image.Resampling.NEAREST);x,y=(i%5)*160+16,(i//5)*176+12;sheet.paste(im,(x,y));d.text((x,y+136),c,fill=(28,28,36))
 (ROOT/".cache").mkdir(exist_ok=True);sheet.save(ROOT/".cache"/"batch66-contact.png",optimize=True);print("10 metadata records",path)
if __name__=="__main__":main()
