"""Generate metadata and visual artifacts for research Batch 10."""
import hashlib,importlib.util,json
from PIL import Image,ImageDraw
from arcengine import ActionInput,GameAction
from build_research_batch06_metadata import ROOT,SESSION,PAL
CFG={
"q105":("Orbiting Board","multi-scale-reference-frames","global-alignment-local-edge-exchange",["orbital-phase","board-local-transfer"],["transfers while edges are misaligned","tracks only local rotation","forgets global orbit phase"],[1,3,4,5,6],"Magenta pieces ride cyan local boards beneath a green global alignment phase."),
"q115":("Partial Demonstration","policy-learning-from-demonstration","latent-subgoal-reconstruction",["endpoint-inference","missing-trajectory"],["copies only the visible endpoint","assumes a straight interpolation","submits without a latent transition"],[1,2,3,4,6],"Blue start and green end panels surround a hidden charcoal subgoal corridor."),
"q125":("Escalation Ladder","adaptive-adversary","retreat-triggered-aggression-control",["opponent-state","controlled-alternation"],["retreats continuously","counters at the wrong aggression","ignores escalation history"],[1,2,3],"Red aggression rises beneath gray ladder stages and blue counter windows."),
"q135":("Parity Signals","compositional-communication","grouped-two-channel-parity-code",["parity","error-detecting-grouping"],["counts raw pulses","ignores grouping","reads only one channel"],[1,2,3,4],"Orange pulse pairs form grouped parity words above blue receiver tiles."),
"q145":("Parallel Sandboxes","counterfactual-planning","dual-simulation-before-irreversible-policy",["parallel-testing","policy-selection"],["tests one sandbox only","applies before comparing","confuses sandbox state with main state"],[1,2,3,4,6],"Two cyan sandboxes flank a charcoal irreversible system beneath selectable policies."),
"q155":("Mirror Roles","structural-analogy","shape-symmetry-to-social-role-transfer",["mirror-algebra","cross-domain-role-mapping"],["mirrors positions only","ignores the learned axis","copies the source role"],[1,2,3,4],"Orange shapes mirror across a gray axis into blue agent roles."),
"q165":("Hypothesis Stack","confidence-calibration","evidence-preserving-candidate-stack",["uncertainty-retention","sequential-elimination"],["discards the target early","commits with multiple candidates","ignores later recovery evidence"],[2,3,4,5,6],"Blue candidate bars survive or turn red as orange evidence plates arrive."),
"q175":("Pendulum Phase","continuous-quantity-reasoning","position-momentum-transfer-timing",["phase-state","moving-platform-transfer"],["tracks position only","transfers with wrong momentum","counts ticks without phase"],[5,6],"A blue pendulum crosses a gray arc above ordered orange platform windows."),
"q185":("Promise Tokens","long-horizon-credit-assignment","identity-bound-future-obligation",["social-debt","helper-identity"],["repays the borrowed object","forgets helper identity","accepts every temporary benefit"],[1,2,3,4,5,6],"Colored helpers issue green promise tokens that persist into a later repayment ledger."),
"q195":("Tempo Transfer","temporal-abstraction","scaled-cross-mechanism-rhythm",["tempo-scaling","rhythm-transfer"],["copies source timing directly","scales count instead of interval","loses cumulative beat phase"],[5,6],"Blue source rhythms expand into orange slow-mechanism intervals with green captures.")}
def load(c):
 p=ROOT/"docs"/"static"/"games"/"src"/f"{c}-v1"/f"{c}.py";s=importlib.util.spec_from_file_location(c,p);m=importlib.util.module_from_spec(s);s.loader.exec_module(m);return p,m
def main():
 games=[];out=ROOT/"research"/"games"
 for c,v in CFG.items():
  title,axis,primary,secondary,failures,actions,sil=v;p,m=load(c);h=hashlib.sha256(p.read_bytes()).hexdigest();rel=p.relative_to(ROOT).as_posix();names=[x["name"] for x in m.LEVELS]
  meta={"schema_version":1,"game_id":c,"version":"v1","internal_title":title,"public_title":None,"author_partition":"gpt","authorship":{"model_family":"OpenAI GPT-5","model_snapshot":"current Codex task model; exact deployment id not exposed to task","session_id":SESSION,"created_at":"2026-08-30T00:00:00Z","source_lineage":[f"research/gpt-ideas-v1.tsv:{c}"],"source_commit":None},"mechanics":{"primary":primary,"secondary":secondary,"novelty_claim":names[-1],"closest_prior_art":["research/coverage-gap-study-v1.md","research/flash-game-mechanics-survey.md"]},"failure_modes":failures,"interface":{"actions":actions,"observation":"64x64x16","deterministic":True,"seeded_stochasticity":False},"progression":[{"level":i+1,"role":["orient","discriminate","plan","compose","inhibit","synthesize"][i],"new_demand":n,"composes":list(range(1,i+1))} for i,n in enumerate(names)],"visual_identity":{"dominant_palette":[],"silhouette_grammar":sil,"spatial_grammar":sil,"motion_grammar":primary.replace("-"," "),"hud_grammar":"Persistent colored state markers expose the mechanic without text.","nearest_visual_games":[]},"evaluation":{"allowed_development_models":["deterministic-solvers","random-fuzzer","Qwen3.8 diagnostic only"],"held_out_evaluator":"anthropic","human_baseline_status":"not_started","held_out_status":"sealed"},"artifacts":{"source":rel,"metadata":f"research/games/{c}-v1.json","win_recording":f"research/recordings/{c}-v1-win.json","loss_recording":f"research/recordings/{c}-v1-loss.json","thumbnail":f"docs/static/img/games/{c}-v1.png","source_sha256":h},"status":"prototype"}
  (out/f"{c}-v1.json").write_text(json.dumps(meta,indent=2)+"\n");g=getattr(m,c.upper())();a=g.perform_action(ActionInput(id=GameAction.RESET),raw=True).frame[-1];im=Image.new("RGB",(64,64));im.putdata([PAL[int(x)] for row in a for x in row]);im.save(ROOT/"docs"/"static"/"img"/"games"/f"{c}-v1.png",optimize=True);games.append({"game_id":c,"title":title,"axis":axis,"levels":6,"source_sha256":h})
 path=ROOT/"research"/"gpt-batch10-v1.json";path.write_text(json.dumps({"schema_version":1,"batch_id":"gpt-batch10-v1","created_at":"2026-08-30T00:00:00Z","design":"Ten fifth-pass games across the second ten research axes, completing the first 101-game milestone with six progressive levels and distinct colorful environments.","games":games},indent=2)+"\n")
 sheet=Image.new("RGB",(800,352),(242,242,246));d=ImageDraw.Draw(sheet)
 for i,c in enumerate(CFG):im=Image.open(ROOT/"docs"/"static"/"img"/"games"/f"{c}-v1.png").resize((128,128),Image.Resampling.NEAREST);x,y=(i%5)*160+16,(i//5)*176+12;sheet.paste(im,(x,y));d.text((x,y+136),c,fill=(28,28,36))
 sheet.save(ROOT/".cache"/"batch10-contact.png",optimize=True);print("10 metadata records",path)
if __name__=="__main__":main()
