"""Generate metadata and visual artifacts for research Batch 14."""
import hashlib,importlib.util,json
from PIL import Image,ImageDraw
from arcengine import ActionInput,GameAction
from build_research_batch06_metadata import ROOT,SESSION,PAL
CFG={
"q010":("Shared Blindspot","observer-dependent-dynamics","two-observer-boolean-visibility",["joint-attention","visibility-trigger"],["tracks one observer","confuses either with both","pulses before positioning attention"],[1,2,3,4,5,6],"Two colored observer bands define Boolean attention states over cyan pieces."),
"q019":("Apprentice Path","social-inference","transformed-demonstration-adaptation",["imitation-model","lesson-design"],["demonstrates the desired move directly","ignores the apprentice transform","releases an incomplete lesson"],[1,2,3,4,5],"A blue teacher adapts route cards for a green apprentice in an orange school."),
"q029":("Fuse Map","causal-intervention","irreversible-downstream-cut-diagnosis",["circuit-preservation","flow-revelation"],["cuts the live branch","commits before isolating every decoy","treats revealed downstream flow as independent"],[3,4,5,6],"Gray fuses expose blue downstream flow while the orange goal circuit remains live."),
"q039":("Charge Pairs","conservation-law-induction","paired-opposite-charge-conservation",["local-net-charge","pair-annihilation"],["counts particles instead of net charge","creates a lone charge","overloads a local node"],[1,2,3,4,5,6],"Blue and orange charge bars balance across white laboratory nodes."),
"q049":("Confidence Door","epistemic-resource-allocation","sufficient-evidence-stopping",["confidence-threshold","probe-selection"],["uses every probe","opens on ambiguous evidence","selects a door before stopping"],[1,2,3,4,5,6],"Colored probes narrow a row of orange doors inside a pale violet hall."),
"q059":("Sieve","tool-construction","bidirectional-size-selective-mesh",["gap-geometry","flow-reversal"],["passes large bodies","blocks small bodies","tests only forward flow"],[1,2,3,4,5,6],"Orange mesh gaps filter blue and green bodies through a white water tank."),
"q069":("Echo Windows","distributed-partial-observability","complementary-delayed-pane-effects",["delay-alignment","view-integration"],["treats both panes as current","ignores the transform","matches the echo one step early"],[1,2,3,4],"Blue and orange panes expose present commands and violet delayed echoes."),
"q079":("Exception Signal","nonstationary-rule-revision","local-marked-rule-exception",["calibrated-revision","general-rule-retention"],["ignores the rare marker","inverts every later command","updates one action late"],[1,2,3,4],"A green general-rule road flashes marked exception bands beneath blue commands."),
"q089":("Persistent Passenger","persistent-identity","passenger-across-carrier-transfer",["carrier-change","hidden-identity-tracking"],["tracks vehicle color","forgets a transfer after rotation","delivers an empty carrier"],[1,2,3,5,6],"A violet passenger moves among colored vehicles toward a green depot gate."),
"q099":("Waypoint Memory","hierarchical-goal-discovery","reusable-waypoint-global-route",["route-abstraction","local-global-planning"],["chooses the nearest waypoint","stores waypoints out of order","forgets a reusable junction"],[1,3,4,5,6],"Orange waypoint nodes become a blue remembered route over a charcoal map.")}
def load(c):
 p=ROOT/"docs"/"static"/"games"/"src"/f"{c}-v1"/f"{c}.py";s=importlib.util.spec_from_file_location(c,p);m=importlib.util.module_from_spec(s);s.loader.exec_module(m);return p,m
def main():
 games=[];out=ROOT/"research"/"games"
 for c,v in CFG.items():
  title,axis,primary,secondary,failures,actions,sil=v;p,m=load(c);h=hashlib.sha256(p.read_bytes()).hexdigest();rel=p.relative_to(ROOT).as_posix();names=[x["name"] for x in m.LEVELS]
  meta={"schema_version":1,"game_id":c,"version":"v1","internal_title":title,"public_title":None,"author_partition":"gpt","authorship":{"model_family":"OpenAI GPT-5","model_snapshot":"current Codex task model; exact deployment id not exposed to task","session_id":SESSION,"created_at":"2026-08-30T00:00:00Z","source_lineage":[f"research/gpt-ideas-v2.tsv:{c}"],"source_commit":None},"mechanics":{"primary":primary,"secondary":secondary,"novelty_claim":names[-1],"closest_prior_art":["research/coverage-gap-study-v1.md","research/flash-game-mechanics-survey.md"]},"failure_modes":failures,"interface":{"actions":actions,"observation":"64x64x16","deterministic":True,"seeded_stochasticity":False},"progression":[{"level":i+1,"role":["orient","discriminate","plan","compose","inhibit","synthesize"][i],"new_demand":n,"composes":list(range(1,i+1))} for i,n in enumerate(names)],"visual_identity":{"dominant_palette":[],"silhouette_grammar":sil,"spatial_grammar":sil,"motion_grammar":primary.replace("-"," "),"hud_grammar":"Persistent colored state markers expose the mechanic without text.","nearest_visual_games":[]},"evaluation":{"allowed_development_models":["deterministic-solvers","random-fuzzer","Qwen3.8 diagnostic only"],"held_out_evaluator":"anthropic","human_baseline_status":"not_started","held_out_status":"sealed"},"artifacts":{"source":rel,"metadata":f"research/games/{c}-v1.json","win_recording":f"research/recordings/{c}-v1-win.json","loss_recording":f"research/recordings/{c}-v1-loss.json","thumbnail":f"docs/static/img/games/{c}-v1.png","source_sha256":h},"status":"prototype"}
  (out/f"{c}-v1.json").write_text(json.dumps(meta,indent=2)+"\n");g=getattr(m,c.upper())();a=g.perform_action(ActionInput(id=GameAction.RESET),raw=True).frame[-1];im=Image.new("RGB",(64,64));im.putdata([PAL[int(x)] for row in a for x in row]);im.save(ROOT/"docs"/"static"/"img"/"games"/f"{c}-v1.png",optimize=True);games.append({"game_id":c,"title":title,"axis":axis,"levels":6,"source_sha256":h})
 path=ROOT/"research"/"gpt-batch14-v1.json";path.write_text(json.dumps({"schema_version":1,"batch_id":"gpt-batch14-v1","created_at":"2026-08-30T00:00:00Z","design":"Ten ninth-pass games across the first ten research axes, each with six progressive levels and a distinct colorful environment.","games":games},indent=2)+"\n")
 sheet=Image.new("RGB",(800,352),(242,242,246));d=ImageDraw.Draw(sheet)
 for i,c in enumerate(CFG):im=Image.open(ROOT/"docs"/"static"/"img"/"games"/f"{c}-v1.png").resize((128,128),Image.Resampling.NEAREST);x,y=(i%5)*160+16,(i//5)*176+12;sheet.paste(im,(x,y));d.text((x,y+136),c,fill=(28,28,36))
 sheet.save(ROOT/".cache"/"batch14-contact.png",optimize=True);print("10 metadata records",path)
if __name__=="__main__":main()
