"""Generate metadata, thumbnails, and the contact sheet for research Batch 77."""
import hashlib,importlib.util,json
from PIL import Image,ImageDraw
from arcengine import ActionInput,GameAction
from build_research_batch06_metadata import ROOT,SESSION,PAL
CFG={
"q530":("Workbench Frame","multi-scale-reference-frames","tool-motion-composes-across-rotating-reconfigurable-fixtures-while-borrowing-writes-a-visible-frame-bound-obligation","An obsidian workshop aligns four fixtures above a tool track, debt rail, and rotation lock."),
"q543":("Murmuration Lesson","policy-learning-from-demonstration","contextual-flock-demonstrations-contain-one-parity-detectable-decoy-and-reveal-a-wind-conditioned-policy","An ivory aviary arranges twelve flock cells above demonstration traces, wind context, and parity."),
"q584":("Tessera Counter","adaptive-adversary","a-three-tactic-mosaic-rival-updates-from-recent-treatments-before-a-repeated-fold-macro-is-interrupted","A blue folding mosaic places nine tessera panels above treatment memory, rival tactic, and macro window."),
"q601":("Tapestry Grammar","compositional-communication","grouped-shuttle-messages-compose-through-relays-while-completed-patterns-rewire-the-graph-for-later-phrases","A violet kinetic loom stacks thread rails over grouped messages, relay history, and graph state."),
"q633":("Murmuration Sandbox","counterfactual-planning","flock-wind-and-parity-reset-physically-while-observed-wake-evidence-persists-across-trials","A green aviary laboratory contrasts a flock chamber with a reset bay above persistent parity evidence."),
"q662":("Lockwater Analogy","structural-analogy","coupled-water-level-relations-transfer-between-dissimilar-views-while-barge-identity-exchanges-appearance","A yellow stepped canal presents source water geometry and target barges above identity and level rails."),
"q705":("Vivarium Evidence","confidence-calibration","temperature-samples-update-a-signed-margin-under-a-partner-policy-that-changes-with-recent-fairness","A peach terrarium layers six fauna strata above signed samples, fairness, and confidence margin."),
"q719":("Strata Gradient","continuous-quantity-reasoning","conserved-ore-crosses-capacity-limited-fault-edges-while-reversible-probes-write-persistent-knowledge","A rose quarry uses four ore reservoirs above fault flow and a persistent evidence notebook."),
"q744":("Honeycomb Obligation","long-horizon-credit-assignment","nectar-debt-remains-attached-to-courier-identity-while-local-and-colony-clocks-advance-at-different-rates","A slate apiary tracks three courier identities above local clock, colony clock, and debt rails."),
"q782":("Lockwater Rhythm","temporal-abstraction","coupled-water-clocks-define-the-macro-interruption-window-while-barges-exchange-position-and-appearance-but-retain-identity","A gold stepped canal aligns three identity-bearing barges above fast and slow water-clock rails.")}
def load(c):
 p=ROOT/"docs"/"static"/"games"/"src"/f"{c}-v1"/f"{c}.py";s=importlib.util.spec_from_file_location(c,p);m=importlib.util.module_from_spec(s);s.loader.exec_module(m);return p,m
def main():
 games=[];out=ROOT/"research"/"games";out.mkdir(parents=True,exist_ok=True)
 for c,(title,axis,primary,silhouette) in CFG.items():
  p,m=load(c);h=hashlib.sha256(p.read_bytes()).hexdigest();rel=p.relative_to(ROOT).as_posix();names=[x["name"] for x in m.LEVELS];g=getattr(m,c.upper())();frame=g.perform_action(ActionInput(id=GameAction.RESET),raw=True).frame[-1];palette=sorted({int(v) for row in frame for v in row})
  meta={"schema_version":1,"game_id":c,"version":"v1","internal_title":title,"public_title":None,"author_partition":"gpt","authorship":{"model_family":"OpenAI GPT-5","model_snapshot":"current Codex task model; exact deployment id not exposed to task","session_id":SESSION,"created_at":"2026-08-31T00:00:00Z","source_lineage":[f"research/gpt-ideas-v2.tsv:{c}"],"source_commit":None},"mechanics":{"primary":primary,"secondary":[axis,"underrepresented-capability-expansion"],"novelty_claim":names[-1],"closest_prior_art":["research/coverage-gap-study-v1.md","research/flash-game-mechanics-survey.md"]},"failure_modes":["uses screen coordinates while ignoring the fixture, wind, seam, graph, water, temperature, fault, or clock frame","copies surface actions without inferring parity, opponent adaptation, syntax, reset-persistent evidence, reciprocal policy, or identity","fails to preserve conservation or causal identity when objects exchange positions and appearance"],"interface":{"actions":[1,2,3,4,5,6],"observation":"64x64x16","deterministic":True,"seeded_stochasticity":False},"progression":[{"level":i+1,"role":["orient","discriminate","plan","compose","inhibit","synthesize"][i],"new_demand":n,"composes":list(range(1,i+1))} for i,n in enumerate(names)],"visual_identity":{"dominant_palette":palette,"silhouette_grammar":silhouette,"spatial_grammar":silhouette,"motion_grammar":primary.replace("-"," "),"hud_grammar":"Workshop fixtures, flock wakes, mosaic seams, loom messages, reset laboratories, canal sources, fauna samples, ore reservoirs, evidence notebooks, courier clocks, debt rails, barge identities, and rhythm windows expose state without text.","nearest_visual_games":[]},"evaluation":{"allowed_development_models":["deterministic-solvers","random-fuzzer","Qwen3.8 diagnostic only"],"held_out_evaluator":"anthropic","human_baseline_status":"not_started","held_out_status":"sealed"},"artifacts":{"source":rel,"metadata":f"research/games/{c}-v1.json","win_recording":f"research/recordings/{c}-v1-win.json","loss_recording":f"research/recordings/{c}-v1-loss.json","thumbnail":f"docs/static/img/games/{c}-v1.png","source_sha256":h},"status":"prototype"}
  (out/f"{c}-v1.json").write_text(json.dumps(meta,indent=2)+"\n");im=Image.new("RGB",(64,64));im.putdata([PAL[int(v)] for row in frame for v in row]);im.save(ROOT/"docs"/"static"/"img"/"games"/f"{c}-v1.png",optimize=True);games.append({"game_id":c,"title":title,"axis":axis,"levels":6,"source_sha256":h})
 path=ROOT/"research"/"gpt-batch77-v1.json";path.write_text(json.dumps({"schema_version":1,"batch_id":"gpt-batch77-v1","created_at":"2026-08-31T00:00:00Z","design":"Eight material systems—workshop, aviary, mosaic, loom, laboratory, canal, terrarium, quarry, apiary, and water clocks—compose moving frames, demonstration, adaptation, syntax, persistent trials, analogy, calibrated reciprocity, conservation, obligation, and temporal identity.","games":games},indent=2)+"\n")
 sheet=Image.new("RGB",(800,352),(242,242,246));d=ImageDraw.Draw(sheet)
 for i,c in enumerate(CFG):
  im=Image.open(ROOT/"docs"/"static"/"img"/"games"/f"{c}-v1.png").resize((128,128),Image.Resampling.NEAREST);x,y=(i%5)*160+16,(i//5)*176+12;sheet.paste(im,(x,y));d.text((x,y+136),c,fill=(28,28,36))
 (ROOT/".cache").mkdir(exist_ok=True);sheet.save(ROOT/".cache"/"batch77-contact.png",optimize=True);print("10 metadata records",path)
if __name__=="__main__":main()
