"""Generate metadata, thumbnails, and a contact sheet for research Batch 84."""
import hashlib,importlib.util,json
from PIL import Image,ImageDraw
from arcengine import ActionInput,GameAction
from build_research_batch06_metadata import ROOT,SESSION,PAL
CFG={
"a031":("Branching Actuator","action-binding-and-control-disambiguation","hidden-lever-mode-and-changing-branch-geometry-must-be-inferred-jointly-from-consequences","A pale branch works splits a central lever into near and far geometry with mode evidence."),
"a032":("Command Arbitration","action-binding-and-control-disambiguation","a-stable-priority-rule-resolves-player-and-two-automatic-commands-while-low-priority-actions-can-block","A blue control platform places three command panels above a shared rail and blocker history."),
"a033":("Twin Stacks","algorithmic-container-manipulation","two-top-only-wells-provide-lifo-temporary-storage-for-a-buried-output-order","A slate vault presents two tall wells above source depth and output sockets."),
"a034":("Queue Garden","algorithmic-container-manipulation","three-fifo-seed-channels-combine-insertion-order-with-distinct-visible-latencies","A lilac irrigation garden stacks three channels above shared beds and a delay clock."),
"a035":("Ring Buffer","algorithmic-container-manipulation","a-six-slot-circular-buffer-overwrites-the-oldest-tile-while-rotation-selects-the-output-gate","A green circular rack surrounds six bounded slots above output and eviction traces."),
"a036":("Stable Sorter","algorithmic-container-manipulation","pairwise-size-comparators-must-preserve-arrival-order-among-equal-size-crates","A teal depot arrays five height-coded crates above comparator and revealed-arrival state."),
"a037":("Heap Orchard","algorithmic-container-manipulation","parent-child-swaps-maintain-a-max-heap-through-repeated-root-harvests","A rose orchard arranges seven area-coded fruit nodes in a binary tree."),
"a038":("Deque Ferry","algorithmic-container-manipulation","front-and-back-loading-and-unloading-serve-spatial-requests-with-an-inaccessible-interior","A cream harbor places a narrow ferry between request and service rails."),
"a039":("Register Swap","algorithmic-container-manipulation","one-short-sequence-of-adjacent-swaps-and-three-rotations-must-generalize-across-register-inputs","A peach console arrays four shape registers above swap focus and an operation program."),
"a040":("Tape Head","algorithmic-container-manipulation","a-geometric-finite-state-transition-table-controls-read-write-state-and-head-motion-separately-from-tape-state","A gold laboratory places an eight-cell tape under a head and two transition rows.")}
def load(c):
 p=ROOT/"docs"/"static"/"games"/"src"/f"{c}-v1"/f"{c}.py";s=importlib.util.spec_from_file_location(c,p);m=importlib.util.module_from_spec(s);s.loader.exec_module(m);return p,m
def main():
 games=[];out=ROOT/"research"/"games";out.mkdir(parents=True,exist_ok=True)
 for c,(title,axis,primary,silhouette) in CFG.items():
  p,m=load(c);h=hashlib.sha256(p.read_bytes()).hexdigest();rel=p.relative_to(ROOT).as_posix();names=[x["name"] for x in m.LEVELS];g=getattr(m,c.upper())();frame=g.perform_action(ActionInput(id=GameAction.RESET),raw=True).frame[-1];palette=sorted({int(v) for row in frame for v in row})
  meta={"schema_version":1,"game_id":c,"version":"v1","internal_title":title,"public_title":None,"author_partition":"gpt","authorship":{"model_family":"OpenAI GPT-5","model_snapshot":"current Codex task model; exact deployment id not exposed to task","session_id":SESSION,"created_at":"2026-08-31T00:00:00Z","source_lineage":[f"research/anthropic-build-ideas-v1.tsv:{c}"],"concept_lineage":"gpt-seeded-anthropic-build","intended_builder":"anthropic","implementation_author_partition":"gpt","source_commit":None},"mechanics":{"primary":primary,"secondary":[axis,"data-structure-and-program-state"],"novelty_claim":names[-1],"closest_prior_art":["research/anthropic-build-ideas-v1.audit.json","research/coverage-gap-study-v1.md","research/flash-game-mechanics-survey.md"]},"failure_modes":["attributes a resolved effect to one command without inferring actuator mode or arbitration","forgets buried, queued, overwritten, tie-order, heap, deque, register-program, or tape-control state","solves one extraction or input while breaking the invariant or reusable program required by later states"],"interface":{"actions":[1,2,3,4,5,6],"observation":"64x64x16","deterministic":True,"seeded_stochasticity":False},"progression":[{"level":i+1,"role":["orient","discriminate","plan","compose","inhibit","synthesize"][i],"new_demand":n,"composes":list(range(1,i+1))} for i,n in enumerate(names)],"visual_identity":{"dominant_palette":palette,"silhouette_grammar":silhouette,"spatial_grammar":silhouette,"motion_grammar":primary.replace("-"," "),"hud_grammar":"Branch geometry, arbitration panels, stack wells, queue channels, ring slots, stable crates, heap nodes, ferry ends, register programs, and tape transitions expose algorithmic state without text.","nearest_visual_games":[]},"evaluation":{"allowed_development_models":["deterministic-solvers","random-fuzzer","Qwen3.8 diagnostic only"],"held_out_evaluator":"anthropic","human_baseline_status":"not_started","held_out_status":"sealed"},"artifacts":{"source":rel,"metadata":f"research/games/{c}-v1.json","win_recording":f"research/recordings/{c}-v1-win.json","loss_recording":f"research/recordings/{c}-v1-loss.json","thumbnail":f"docs/static/img/games/{c}-v1.png","source_sha256":h},"status":"prototype"}
  (out/f"{c}-v1.json").write_text(json.dumps(meta,indent=2)+"\n");im=Image.new("RGB",(64,64));im.putdata([PAL[int(v)] for row in frame for v in row]);im.save(ROOT/"docs"/"static"/"img"/"games"/f"{c}-v1.png",optimize=True);games.append({"game_id":c,"title":title,"axis":axis,"levels":6,"source_sha256":h})
 path=ROOT/"research"/"gpt-batch84-v1.json";path.write_text(json.dumps({"schema_version":1,"batch_id":"gpt-batch84-v1","created_at":"2026-08-31T00:00:00Z","provenance":"Concepts retain gpt-seeded-anthropic-build queue lineage; implementations in this batch are authored by OpenAI GPT-5 and are not attributed to Anthropic.","design":"Ten colorful systems combine latent command resolution with explicit stack, queue, bounded buffer, stable-sort, heap, deque, permutation-program, and finite-state tape semantics.","games":games},indent=2)+"\n")
 sheet=Image.new("RGB",(800,352),(242,242,246));d=ImageDraw.Draw(sheet)
 for i,c in enumerate(CFG):
  im=Image.open(ROOT/"docs"/"static"/"img"/"games"/f"{c}-v1.png").resize((128,128),Image.Resampling.NEAREST);x,y=(i%5)*160+16,(i//5)*176+12;sheet.paste(im,(x,y));d.text((x,y+136),c,fill=(28,28,36))
 (ROOT/".cache").mkdir(exist_ok=True);sheet.save(ROOT/".cache"/"batch84-contact.png",optimize=True);print("10 metadata records",path)
if __name__=="__main__":main()
