"""Generate metadata and visual artifacts for research Batch 09."""
import hashlib,importlib.util,json
from PIL import Image,ImageDraw
from arcengine import ActionInput,GameAction
from build_research_batch06_metadata import ROOT,SESSION,PAL
CFG={
"q006":("Shadow Cargo","observer-dependent-dynamics","unobserved-endpoint-cargo-transfer",["observation-locking","temporary-storage"],["moves cargo through watched pockets","tracks total only","forgets endpoint visibility"],[1,2,3,4,5,6],"Green cargo moves among gray pockets beneath yellow watch locks."),
"q015":("Reciprocal Hands","social-inference","short-memory-reciprocity-policy",["helper-memory","reciprocal-response"],["assumes unconditional help","forgets recent obstruction","uses total history under a last-action policy"],[1,2],"Green assistance and red obstruction histories predict a blue helper reply."),
"q025":("Latent Gearbox","causal-intervention","hidden-clutch-transmission-network",["active-intervention","distant-coupling"],["trusts visual contact","turns gears independently","fails to infer distant transmission"],[3,4,5,6],"Pale gears turn blue through hidden clutches beneath green target states."),
"q035":("Momentum Bank","conservation-law-induction","collision-based-momentum-redistribution",["stored-motion","heavy-body-transfer"],["creates momentum","moves each body independently","spends stored motion too early"],[3,4,5,6],"Gray bodies exchange blue motion quantities against green conserved targets."),
"q045":("Scout Drones","epistemic-resource-allocation","disposable-ray-map-revelation",["launch-selection","persistent-map-evidence"],["launches every scout","duplicates revealed corridors","submits an incomplete map"],[3,4,5,6],"Blue disposable drones reveal cyan corridor strips from a dark map."),
"q055":("Funnel Forge","tool-construction","segment-built-particle-sorter",["wall-assembly","emergent-sorting"],["builds every segment","matches a silhouette instead of function","omits a momentum guide"],[3,4,5,6],"Cyan wall segments assemble around blue particles and a green sorting exit."),
"q065":("Asymmetric Twins","distributed-partial-observability","alternating-color-shape-evidence",["complementary-observers","joint-classification"],["classifies from one view","confuses controller with evidence","fails to alternate observers"],[1,2,5],"Blue twins reveal either color or shape before a joint object decision."),
"q075":("Betrayal Gate","nonstationary-rule-revision","wear-triggered-complement-rule",["visible-change-point","rule-inversion"],["keeps the original rule","switches before wear","forgets the complement relation"],[1,2],"Cyan gate cues invert after a red wear band becomes visible."),
"q085":("Identity Trail","persistent-identity","footprint-grounded-entity-assignment",["route-history","identity-after-convergence"],["selects by current appearance","follows the nearest trail","loses identity at crossings"],[3,4,6],"Identical blue bodies sit beneath gray footprints that preserve lineage identity."),
"q095":("Closure Graph","hierarchical-goal-discovery","nested-cycle-closure",["cycle-subgoals","closure-composition"],["targets the outer cycle directly","leaves a small cycle open","confuses adjacency with closure"],[3,4,5,6],"Gray graph nodes and blue cycle bars turn green through nested closure.")}
def load(c):
 p=ROOT/"docs"/"static"/"games"/"src"/f"{c}-v1"/f"{c}.py";s=importlib.util.spec_from_file_location(c,p);m=importlib.util.module_from_spec(s);s.loader.exec_module(m);return p,m
def main():
 games=[];out=ROOT/"research"/"games"
 for c,v in CFG.items():
  title,axis,primary,secondary,failures,actions,sil=v;p,m=load(c);h=hashlib.sha256(p.read_bytes()).hexdigest();rel=p.relative_to(ROOT).as_posix();names=[x["name"] for x in m.LEVELS]
  meta={"schema_version":1,"game_id":c,"version":"v1","internal_title":title,"public_title":None,"author_partition":"gpt","authorship":{"model_family":"OpenAI GPT-5","model_snapshot":"current Codex task model; exact deployment id not exposed to task","session_id":SESSION,"created_at":"2026-08-30T00:00:00Z","source_lineage":[f"research/gpt-ideas-v1.tsv:{c}"],"source_commit":None},"mechanics":{"primary":primary,"secondary":secondary,"novelty_claim":names[-1],"closest_prior_art":["research/coverage-gap-study-v1.md","research/flash-game-mechanics-survey.md"]},"failure_modes":failures,"interface":{"actions":actions,"observation":"64x64x16","deterministic":True,"seeded_stochasticity":False},"progression":[{"level":i+1,"role":["orient","discriminate","plan","compose","inhibit","synthesize"][i],"new_demand":n,"composes":list(range(1,i+1))} for i,n in enumerate(names)],"visual_identity":{"dominant_palette":[],"silhouette_grammar":sil,"spatial_grammar":sil,"motion_grammar":primary.replace("-"," "),"hud_grammar":"Persistent colored state markers expose the mechanic without text.","nearest_visual_games":[]},"evaluation":{"allowed_development_models":["deterministic-solvers","random-fuzzer","Qwen3.8 diagnostic only"],"held_out_evaluator":"anthropic","human_baseline_status":"not_started","held_out_status":"sealed"},"artifacts":{"source":rel,"metadata":f"research/games/{c}-v1.json","win_recording":f"research/recordings/{c}-v1-win.json","loss_recording":f"research/recordings/{c}-v1-loss.json","thumbnail":f"docs/static/img/games/{c}-v1.png","source_sha256":h},"status":"prototype"}
  (out/f"{c}-v1.json").write_text(json.dumps(meta,indent=2)+"\n");g=getattr(m,c.upper())();a=g.perform_action(ActionInput(id=GameAction.RESET),raw=True).frame[-1];im=Image.new("RGB",(64,64));im.putdata([PAL[int(x)] for row in a for x in row]);im.save(ROOT/"docs"/"static"/"img"/"games"/f"{c}-v1.png",optimize=True);games.append({"game_id":c,"title":title,"axis":axis,"levels":6,"source_sha256":h})
 path=ROOT/"research"/"gpt-batch09-v1.json";path.write_text(json.dumps({"schema_version":1,"batch_id":"gpt-batch09-v1","created_at":"2026-08-30T00:00:00Z","design":"Ten fifth-pass games across the first ten research axes, each with six progressive levels and a distinct colorful environment.","games":games},indent=2)+"\n")
 sheet=Image.new("RGB",(800,352),(242,242,246));d=ImageDraw.Draw(sheet)
 for i,c in enumerate(CFG):im=Image.open(ROOT/"docs"/"static"/"img"/"games"/f"{c}-v1.png").resize((128,128),Image.Resampling.NEAREST);x,y=(i%5)*160+16,(i//5)*176+12;sheet.paste(im,(x,y));d.text((x,y+136),c,fill=(28,28,36))
 sheet.save(ROOT/".cache"/"batch09-contact.png",optimize=True);print("10 metadata records",path)
if __name__=="__main__":main()
