"""Generate metadata, thumbnails, and the batch manifest for research Batch 03."""

from __future__ import annotations
import hashlib
import importlib.util
import json
from pathlib import Path
from PIL import Image, ImageDraw
from arcengine import ActionInput, GameAction

ROOT = Path(__file__).resolve().parents[1]
SESSION = "01a02a2e-aaf5-7e90-a559-46437ace2edb"
PALETTE = [(255,255,255),(204,204,204),(153,153,153),(102,102,102),(51,51,51),(0,0,0),(229,58,163),(255,123,204),(249,60,49),(30,147,255),(136,216,241),(255,220,0),(255,133,27),(146,18,49),(79,204,48),(163,86,214)]
ROLES = ["orient", "discriminate", "plan", "compose", "inhibit", "synthesize"]
CONFIG = {
    "q003": {"title":"Blind Growth","axis":"observer-dependent-dynamics","primary":"gaze-opposed-growth","secondary":["observation-as-control","self-avoiding-growth","occluded-route-planning"],"failures":["grows toward the gaze","forgets held orientation","traps the branch against prior growth"],"actions":[1,2,3,4,5],"palette":[0,3,6,8,9,10,11,12,13,14],"silhouette":"A cyan branching organism grows through an orange-soil lattice beneath a blue eye.","spatial":"A green biological surround frames a compact burgundy growth bed.","motion":"The active tip advances opposite the observer's held gaze and cannot cross its own trail.","hud":"A directional eye externalizes the otherwise causal observation state.","progress":["Grow one straight segment away from observation.","Turn the gaze to shape a corner.","Route around a pruning wall.","Hold and revise gaze through a corridor.","Avoid trapping a long self-grown branch.","Compose gaze, obstacles, and self-avoidance across the full bed."]},
    "q012": {"title":"Private Appetites","axis":"social-inference","primary":"preference-grounded-allocation","secondary":["choice-observation","elimination","one-to-one-fairness"],"failures":["matches by agent color","reuses a consumed resource","ignores unshown preferences"],"actions":[1,2,3,4,5],"palette":[0,1,3,6,7,8,9,10,11,12,13,14,15],"silhouette":"Tall colorful diners face a row of uniquely colored resource blocks and choice-history samples.","spatial":"A pale allocation table fills a cyan social hall.","motion":"Assignments lock one agent and consume one resource, making preference inference globally coupled.","hud":"Gray sample plaques distinguish demonstrated tastes from preferences inferred by elimination.","progress":["Allocate one demonstrated favorite.","Separate two visible appetites.","Use a complete choice history.","Infer one missing preference by elimination.","Preserve fairness with two missing demonstrations.","Allocate six unique resources from a sparse preference history."]},
    "q022": {"title":"Counterweight Lab","axis":"causal-intervention","primary":"coupled-platform-ratio-control","secondary":["signed-causal-effects","ratio-induction","multi-platform-balancing"],"failures":["assumes one-to-one levers","ignores signed coupling","overshoots a constrained platform"],"actions":[3,4,5,6],"palette":[0,3,8,9,11,12,14,15],"silhouette":"Orange weights hang above gray platforms with green target height marks.","spatial":"A white pulley laboratory sits inside a violet chamber.","motion":"Each selected counterweight changes several platform heights with a stable signed ratio.","hud":"Yellow energy capsules and blue selector blocks show remaining trials and active rig.","progress":["Learn one opposed cable.","Discover a shared positive cable.","Infer unequal three-platform effects.","Compose crossed signed couplings.","Balance two ratio banks together.","Reach four exact heights through overlapping counterweights."]},
    "q032": {"title":"Parity Forge","axis":"conservation-law-induction","primary":"pairwise-parity-preserving-transformation","secondary":["invariant-recognition","graph-toggle-planning","exact-pattern-control"],"failures":["tries to toggle one bit","ignores global parity","repeats a locally useful strike"],"actions":[3,4,5,6],"palette":[0,3,6,7,8,9,11,12,13,14,15],"silhouette":"Binary metal billets sit above paired forge-strike links and a green target row.","spatial":"An orange forge is embedded in a burgundy foundry wall.","motion":"Every strike toggles exactly two linked billets, preserving the global parity class.","hud":"Blue selection and colored endpoint studs expose the active pair without symbols.","progress":["Toggle one forced pair.","Move a spark along a chain.","Recognize an even parity class.","Plan toggles around a ring.","Route parity through a crossed graph.","Synthesize an exact six-billet pattern without violating the invariant."]},
    "q042": {"title":"Sonar Pips","axis":"epistemic-resource-allocation","primary":"scarce-distance-only-localization","secondary":["triangulation","probe-placement","commitment"],"failures":["treats distance as direction","spends all pings locally","commits to a symmetric alternative"],"actions":[1,2,3,4,5,6],"palette":[0,8,9,10,11,12,14,15],"silhouette":"Violet sonar buoys carry orange distance pips on a cyan ocean grid.","spatial":"A blue sea surrounds a clean six-by-six ranging field.","motion":"Coordinate pings reveal Manhattan distance only; the cursor later commits to one hidden beacon cell.","hud":"Violet probe bars show the scarce sensing budget.","progress":["Interpret one unambiguous range.","Combine two bearings.","Resolve an edge reflection.","Place sparse pings across a wide field.","Reject ring-symmetric candidates.","Triangulate a corner beacon under a three-ping budget."]},
    "q052": {"title":"Lens Bench","axis":"tool-construction","primary":"orientation-composed-optical-tool","secondary":["signed-refraction","fixed-parts","functional-geometry"],"failures":["matches fragment appearance","rotates fixed glass","ignores cumulative refraction"],"actions":[1,2,3,4,5],"palette":[0,1,3,7,8,10,11,12,14],"silhouette":"Tall cyan lens shards intersect one orange beam and a green receiver.","spatial":"A pale optics bench sits in a pink fabrication studio.","motion":"Rotating fragments changes the cumulative signed exit direction of the assembled beam tool.","hud":"Yellow selection and gray fixed panes expose manipulable versus structural glass.","progress":["Orient one lens fragment.","Compose two refracting surfaces.","Handle opposed curvature signs.","Work around a fixed pane.","Assemble a four-part compound lens.","Align five fragments with two immutable surfaces."]},
    "q062": {"title":"Relay Shadows","axis":"distributed-partial-observability","primary":"body-shadow-representation-alignment","secondary":["cross-pane-integration","light-direction","identity-ordering"],"failures":["sorts bodies by color","ignores light direction","confuses overlapping silhouettes"],"actions":[3,4,5,6],"palette":[0,1,3,6,7,8,9,10,11,12,13,14,15],"silhouette":"Colorful vertical bodies occupy a blue sky while gray shadows lie in a separate pale ground pane.","spatial":"Two complementary observation bands share an orange relay surround.","motion":"Adjacent body swaps must reproduce the role order encoded only by shadow geometry and sun direction.","hud":"A white cursor rail and burgundy correctness sockets separate action from evidence.","progress":["Align two body-shadow roles.","Order three silhouette lengths.","Account for stronger light scaling.","Reverse the sun's direction.","Disentangle six overlapping shadows.","Integrate reverse light and six identities in one relay."]},
    "q072": {"title":"Honest Liar","axis":"nonstationary-rule-revision","primary":"state-conditioned-signal-inversion","secondary":["visible-regime-cue","opposite-direction-decoding","sequence-memory"],"failures":["always follows the guide","always opposes the guide","misses mid-route state changes"],"actions":[1,2,3,4],"palette":[1,6,8,9,11,13,14,15],"silhouette":"A violet guide emits block arrows beside green honest or red liar state cards.","spatial":"A pale route theater sits inside a magenta signal room.","motion":"The correct route is signaled directly in one visible state and by its opposite in the other.","hud":"Yellow progress tablets preserve how much of the decoded route is complete.","progress":["Follow an honest two-step signal.","Invert one visibly lying signal.","Alternate honest and opposing policies.","Persist through two consecutive lies.","Decode a longer nonperiodic state pattern.","Execute seven directions under rapidly changing guide states."]},
    "q082": {"title":"Borrowed Color","axis":"persistent-identity","primary":"role-under-container-recoloring","secondary":["appearance-decoupling","event-sequence-memory","adjacent-reordering"],"failures":["sorts by borrowed color","acts before recoloring ends","forgets original role order"],"actions":[1,3,4,5,6],"palette":[0,3,6,7,8,9,10,11,12,13,14,15],"silhouette":"Hollow multicolor pieces stand above identity sockets while recoloring events pass overhead.","spatial":"A cyan display shelf fills a yellow wardrobe room.","motion":"Containers repeatedly recolor shells without changing their persistent socket roles, followed by constrained reordering.","hud":"Burgundy event tokens record the required observation phase before manipulation.","progress":["Track two roles through one recoloring.","Preserve three identities through two containers.","Remember four roles across repeated borrowing.","Reject a color-matched false arrangement.","Track six pieces through four appearance events.","Reconstruct six persistent roles after five recolorings."]},
    "q092": {"title":"Nesting Rooms","axis":"hierarchical-goal-discovery","primary":"inner-solution-transforms-outer-state","secondary":["nested-boundaries","subgoal-order","carried-state"],"failures":["edits the outer room first","forgets the carried rotation","seals an unsolved inner boundary"],"actions":[1,2,5],"palette":[0,3,6,7,8,10,11,12,13,14,15],"silhouette":"Concentric colored room boundaries surround a magenta core and green target tabs.","spatial":"Nested rectangles occupy a red architectural field with no flat tile grid.","motion":"Sealing a solved inner room rotates the next enclosing boundary before it becomes active.","hud":"White active tabs, gray sealed walls, and a compact action strip expose hierarchy and progress.","progress":["Solve and seal one inner room.","Carry one rotation into its container.","Propagate state across three boundaries.","Handle an inverse carried rotation.","Compose five nested subgoals with mixed influences.","Solve a five-room hierarchy whose inner closures transform every outer target."]},
}


def load_module(code):
    source = ROOT / "docs" / "static" / "games" / "src" / f"{code}-v1" / f"{code}.py"; spec = importlib.util.spec_from_file_location(f"{code}_metadata", source); module = importlib.util.module_from_spec(spec); assert spec.loader is not None; spec.loader.exec_module(module); return source, module


def render_thumbnail(code, module):
    game = getattr(module, code.upper())(); result = game.perform_action(ActionInput(id=GameAction.RESET), raw=True); grid = result.frame[-1]; image = Image.new("RGB", (64,64)); image.putdata([PALETTE[int(value)] for row in grid for value in row]); out = ROOT / "docs" / "static" / "img" / "games" / f"{code}-v1.png"; out.parent.mkdir(parents=True, exist_ok=True); image.save(out, optimize=True)


def main():
    out_dir = ROOT / "research" / "games"; out_dir.mkdir(parents=True, exist_ok=True); batch = []
    for code, cfg in CONFIG.items():
        source, module = load_module(code); source_rel = source.relative_to(ROOT).as_posix(); digest = hashlib.sha256(source.read_bytes()).hexdigest()
        meta = {"schema_version":1,"game_id":code,"version":"v1","internal_title":cfg["title"],"public_title":None,"author_partition":"gpt","authorship":{"model_family":"OpenAI GPT-5","model_snapshot":"current Codex task model; exact deployment id not exposed to task","session_id":SESSION,"created_at":"2026-08-30T00:00:00Z","source_lineage":[f"research/gpt-ideas-v1.tsv:{code}"],"source_commit":None},"mechanics":{"primary":cfg["primary"],"secondary":cfg["secondary"],"novelty_claim":cfg["progress"][-1],"closest_prior_art":["research/coverage-gap-study-v1.md","research/flash-game-mechanics-survey.md"]},"failure_modes":cfg["failures"],"interface":{"actions":cfg["actions"],"observation":"64x64x16","deterministic":True,"seeded_stochasticity":False},"progression":[{"level":i+1,"role":ROLES[i],"new_demand":demand,"composes":list(range(1,i+1))} for i,demand in enumerate(cfg["progress"])],"visual_identity":{"dominant_palette":cfg["palette"],"silhouette_grammar":cfg["silhouette"],"spatial_grammar":cfg["spatial"],"motion_grammar":cfg["motion"],"hud_grammar":cfg["hud"],"nearest_visual_games":[]},"evaluation":{"allowed_development_models":["deterministic-solvers","random-fuzzer","Qwen3.8 diagnostic only"],"held_out_evaluator":"anthropic","human_baseline_status":"not_started","held_out_status":"sealed"},"artifacts":{"source":source_rel,"metadata":f"research/games/{code}-v1.json","win_recording":f"research/recordings/{code}-v1-win.json","loss_recording":f"research/recordings/{code}-v1-loss.json","thumbnail":f"docs/static/img/games/{code}-v1.png","source_sha256":digest},"status":"prototype"}
        (out_dir / f"{code}-v1.json").write_text(json.dumps(meta,indent=2)+"\n",encoding="utf-8"); render_thumbnail(code,module); batch.append({"game_id":code,"title":cfg["title"],"axis":cfg["axis"],"levels":len(module.LEVELS),"source_sha256":digest})
    manifest={"schema_version":1,"batch_id":"gpt-batch03-v1","created_at":"2026-08-30T00:00:00Z","design":"Ten second-pass cross-family games; each has six causal-progression levels and a distinct colorful environment.","games":batch}; path=ROOT/"research"/"gpt-batch03-v1.json"; path.write_text(json.dumps(manifest,indent=2)+"\n",encoding="utf-8")
    sheet=Image.new("RGB",(800,352),(242,242,246)); draw=ImageDraw.Draw(sheet)
    for index,code in enumerate(CONFIG):
        thumb=Image.open(ROOT/"docs"/"static"/"img"/"games"/f"{code}-v1.png").convert("RGB").resize((128,128),Image.Resampling.NEAREST); x,y=(index%5)*160+16,(index//5)*176+12; sheet.paste(thumb,(x,y)); draw.text((x,y+136),code,fill=(28,28,36))
    out=ROOT/".cache"/"batch03-contact.png"; out.parent.mkdir(parents=True,exist_ok=True); sheet.save(out,optimize=True); print(f"{len(batch)} metadata records -> {out_dir}"); print(path)


if __name__ == "__main__": main()
