"""Generate metadata, thumbnails, and the contact sheet for research Batch 75."""
import hashlib,importlib.util,json
from PIL import Image,ImageDraw
from arcengine import ActionInput,GameAction
from build_research_batch06_metadata import ROOT,SESSION,PAL
CFG={
"q522":("Semaphore Frame","multi-scale-reference-frames","flag-motion-composes-across-rotating-and-translating-occluded-relay-frames-while-miniature-tests-ground-the-policy","An obsidian cliff signal yard aligns five relay towers above a flag track, miniature tests, and frame rail."),
"q534":("Honeycomb Lesson","policy-learning-from-demonstration","contextual-courier-demonstrations-separate-a-null-dance-from-a-policy-governed-by-local-and-enclosing-clocks","An ivory layered apiary arrays twelve nectar cells above demonstration, local-clock, and colony-clock rails."),
"q582":("Semaphore Counter","adaptive-adversary","a-three-tactic-signal-rival-updates-from-recent-treatments-and-two-visible-miniature-policy-testbeds","A blue cliff yard contrasts twin test systems above recent treatments, a rival tactic, and flag state."),
"q612":("Semaphore Grammar","compositional-communication","grouped-flag-messages-compose-through-transforming-relays-before-two-miniature-policy-tests-support-commitment","A violet signal yard stacks five relay towers over grouped messages, test events, and relay state."),
"q622":("Tide Sandbox","counterfactual-planning","physical-shell-current-and-phase-reset-while-observed-wake-evidence-persists-across-tidal-trials","A green tidal laboratory contrasts a shell basin with a reset bay above a persistent wake notebook."),
"q663":("Murmuration Analogy","structural-analogy","geometric-gap-relations-transfer-to-flock-agents-under-changing-wind-and-a-redundant-parity-constraint","A yellow aviary presents source geometry and target flocks in paired panels above wind and parity rails."),
"q682":("Tide Evidence","confidence-calibration","unequal-current-samples-update-a-costed-signed-margin-before-an-irreversible-tidal-decision","A peach tidal basin layers six shell lanes above signed samples, a bounded confidence margin, and cost."),
"q714":("Honeycomb Gradient","continuous-quantity-reasoning","conserved-nectar-crosses-capacity-limited-scent-edges-while-local-and-colony-clocks-update-at-different-rates","A rose apiary uses four vertical nectar cells above scent flow, local clock, and colony clock rails."),
"q762":("Semaphore Obligation","long-horizon-credit-assignment","signal-debt-remains-attached-to-flag-agent-identity-through-relay-rotations-and-two-miniature-policy-tests","A slate signal yard tracks three flag identities above twin testbeds and an identity-bound debt ledger."),
"q772":("Tide Rhythm","temporal-abstraction","a-reversing-current-macro-must-be-interrupted-at-a-state-defined-dual-clock-window-after-safe-evidence","A gold tidal basin arranges twelve shell nodes above evidence pulses, fast and slow clocks, and a gate.")}
def load(c):
 p=ROOT/"docs"/"static"/"games"/"src"/f"{c}-v1"/f"{c}.py";s=importlib.util.spec_from_file_location(c,p);m=importlib.util.module_from_spec(s);s.loader.exec_module(m);return p,m
def main():
 games=[];out=ROOT/"research"/"games";out.mkdir(parents=True,exist_ok=True)
 for c,(title,axis,primary,silhouette) in CFG.items():
  p,m=load(c);h=hashlib.sha256(p.read_bytes()).hexdigest();rel=p.relative_to(ROOT).as_posix();names=[x["name"] for x in m.LEVELS];g=getattr(m,c.upper())();frame=g.perform_action(ActionInput(id=GameAction.RESET),raw=True).frame[-1];palette=sorted({int(v) for row in frame for v in row})
  meta={"schema_version":1,"game_id":c,"version":"v1","internal_title":title,"public_title":None,"author_partition":"gpt","authorship":{"model_family":"OpenAI GPT-5","model_snapshot":"current Codex task model; exact deployment id not exposed to task","session_id":SESSION,"created_at":"2026-08-31T00:00:00Z","source_lineage":[f"research/gpt-ideas-v2.tsv:{c}"],"source_commit":None},"mechanics":{"primary":primary,"secondary":[axis,"underrepresented-capability-expansion"],"novelty_claim":names[-1],"closest_prior_art":["research/coverage-gap-study-v1.md","research/flash-game-mechanics-survey.md"]},"failure_modes":["uses screen position while ignoring the moving relay, wind, scent, current, or clock frame","copies visible actions without inferring context, grouped syntax, rival adaptation, experiment persistence, or stopping evidence","tracks visible signal or shell appearance instead of conserved quantity and causal identity"],"interface":{"actions":[1,2,3,4,5,6],"observation":"64x64x16","deterministic":True,"seeded_stochasticity":False},"progression":[{"level":i+1,"role":["orient","discriminate","plan","compose","inhibit","synthesize"][i],"new_demand":n,"composes":list(range(1,i+1))} for i,n in enumerate(names)],"visual_identity":{"dominant_palette":palette,"silhouette_grammar":silhouette,"spatial_grammar":silhouette,"motion_grammar":primary.replace("-"," "),"hud_grammar":"Relay towers, flag tracks, miniature testbeds, honeycomb cells, courier traces, tidal basins, shell wakes, flock panels, parity rails, nectar reservoirs, identity ledgers, dual clocks, and interruption gates expose state without text.","nearest_visual_games":[]},"evaluation":{"allowed_development_models":["deterministic-solvers","random-fuzzer","Qwen3.8 diagnostic only"],"held_out_evaluator":"anthropic","human_baseline_status":"not_started","held_out_status":"sealed"},"artifacts":{"source":rel,"metadata":f"research/games/{c}-v1.json","win_recording":f"research/recordings/{c}-v1-win.json","loss_recording":f"research/recordings/{c}-v1-loss.json","thumbnail":f"docs/static/img/games/{c}-v1.png","source_sha256":h},"status":"prototype"}
  (out/f"{c}-v1.json").write_text(json.dumps(meta,indent=2)+"\n");im=Image.new("RGB",(64,64));im.putdata([PAL[int(v)] for row in frame for v in row]);im.save(ROOT/"docs"/"static"/"img"/"games"/f"{c}-v1.png",optimize=True);games.append({"game_id":c,"title":title,"axis":axis,"levels":6,"source_sha256":h})
 path=ROOT/"research"/"gpt-batch75-v1.json";path.write_text(json.dumps({"schema_version":1,"batch_id":"gpt-batch75-v1","created_at":"2026-08-31T00:00:00Z","design":"Four distinct material systems—cliff semaphore yards, layered honeycomb apiaries, reversing tidal basins, and an open aviary—compose moving frames, two-clock demonstrations, adaptive rivals, grouped syntax, persistent trials, analogy, calibrated evidence, conserved flow, identity debt, and macro interruption.","games":games},indent=2)+"\n")
 sheet=Image.new("RGB",(800,352),(242,242,246));d=ImageDraw.Draw(sheet)
 for i,c in enumerate(CFG):
  im=Image.open(ROOT/"docs"/"static"/"img"/"games"/f"{c}-v1.png").resize((128,128),Image.Resampling.NEAREST);x,y=(i%5)*160+16,(i//5)*176+12;sheet.paste(im,(x,y));d.text((x,y+136),c,fill=(28,28,36))
 (ROOT/".cache").mkdir(exist_ok=True);sheet.save(ROOT/".cache"/"batch75-contact.png",optimize=True);print("10 metadata records",path)
if __name__=="__main__":main()
