"""Generate metadata and visual artifacts for research Batch 07."""
import hashlib,importlib.util,json
from PIL import Image,ImageDraw
from arcengine import ActionInput,GameAction
from build_research_batch06_metadata import ROOT,SESSION,PAL
CFG={
"q005":("Lantern Census","observer-dependent-dynamics","illumination-conditioned-population-dynamics",["hidden-growth","visible-merging"],["assumes light is cosmetic","tracks total but not distribution","forgets concurrent enclosure updates"],[1,3,4,5,6],"Green creatures grow in dark pens and merge beneath selected yellow lanterns."),
"q014":("Flock Vote","social-inference","latent-gesture-aggregation-rule",["group-policy","rule-inference"],["follows one bird under majority","assumes every flock uses one rule","ignores gesture order"],[1,2,3,4],"Blue birds cast orange gestures above collective corridor decisions."),
"q024":("Last Probe","causal-intervention","finite-experiment-bank-before-commit",["probe-selection","irreversible-choice"],["probes redundant machines","commits without required evidence","confuses observation with hypothesis"],[1,2,3,4,5,6],"Four pale hypotheses sit above a finite row of blue intervention plates."),
"q034":("Area Keeper","conservation-law-induction","silhouette-invariant-filled-area",["shape-transformation","area-conservation"],["matches width","matches silhouette","forgets area under folding"],[3,4,5,6],"Magenta shapes repeatedly change silhouette beneath a fixed green area socket."),
"q044":("Memory Camera","epistemic-resource-allocation","selective-region-snapshot-memory",["future-relevance","ordered-recall"],["photographs every region","stores the most salient rather than useful region","recalls snapshots out of order"],[3,4,5,6],"Blue scene regions vanish behind a charcoal plate while saved green evidence answers later queries."),
"q054":("Gear Teeth","tool-construction","finite-tooth-ratio-construction",["resource-allocation","mechanical-synchronization"],["adds teeth greedily","leaves unused material","matches one gear but not the train"],[3,4,5,6],"Blue blank gears receive finite magenta teeth against green ratio bars."),
"q064":("Scout Gestures","distributed-partial-observability","grounded-scout-motion-reports",["remote-observation","gesture-decoding"],["copies the gesture","assumes branch identity is visible","forgets the learned report code"],[1,2,3,4],"Returning blue scouts communicate hidden cyan branches through orange motion marks."),
"q074":("Drift Law","nonstationary-rule-revision","rotating-action-transformation",["calibration","mapping-expiry"],["reuses the old mapping","acts before calibration","rotates in the wrong direction"],[1,2,3,4,5],"A cyan calibration mark reveals the rotation applied to a blue route sequence."),
"q084":("Control Transfer","persistent-identity","contact-driven-controller-transfer",["body-goal-binding","controller-identity"],["moves the wrong body after contact","attaches the goal to control","cannot stage contact at a solved position"],[1,2,3,4,6],"Magenta and cyan bodies retain separate colored goals while contact transfers a yellow controller."),
"q094":("Delivery Tree","hierarchical-goal-discovery","dependency-revealing-delivery-network",["upstream-subgoals","topological-planning"],["serves the final request first","misses a shared dependency","repeats completed deliveries"],[3,4,5,6],"Gray dependency nodes turn cyan then green as upstream deliveries unlock a magenta request.")}
def load(c):
 p=ROOT/"docs"/"static"/"games"/"src"/f"{c}-v1"/f"{c}.py";s=importlib.util.spec_from_file_location(c,p);m=importlib.util.module_from_spec(s);s.loader.exec_module(m);return p,m
def main():
 games=[];out=ROOT/"research"/"games"
 for c,v in CFG.items():
  title,axis,primary,secondary,failures,actions,sil=v;p,m=load(c);h=hashlib.sha256(p.read_bytes()).hexdigest();rel=p.relative_to(ROOT).as_posix();names=[x["name"] for x in m.LEVELS]
  meta={"schema_version":1,"game_id":c,"version":"v1","internal_title":title,"public_title":None,"author_partition":"gpt","authorship":{"model_family":"OpenAI GPT-5","model_snapshot":"current Codex task model; exact deployment id not exposed to task","session_id":SESSION,"created_at":"2026-08-30T00:00:00Z","source_lineage":[f"research/gpt-ideas-v1.tsv:{c}"],"source_commit":None},"mechanics":{"primary":primary,"secondary":secondary,"novelty_claim":names[-1],"closest_prior_art":["research/coverage-gap-study-v1.md","research/flash-game-mechanics-survey.md"]},"failure_modes":failures,"interface":{"actions":actions,"observation":"64x64x16","deterministic":True,"seeded_stochasticity":False},"progression":[{"level":i+1,"role":["orient","discriminate","plan","compose","inhibit","synthesize"][i],"new_demand":n,"composes":list(range(1,i+1))} for i,n in enumerate(names)],"visual_identity":{"dominant_palette":[],"silhouette_grammar":sil,"spatial_grammar":sil,"motion_grammar":primary.replace("-"," "),"hud_grammar":"Persistent colored state markers expose the mechanic without text.","nearest_visual_games":[]},"evaluation":{"allowed_development_models":["deterministic-solvers","random-fuzzer","Qwen3.8 diagnostic only"],"held_out_evaluator":"anthropic","human_baseline_status":"not_started","held_out_status":"sealed"},"artifacts":{"source":rel,"metadata":f"research/games/{c}-v1.json","win_recording":f"research/recordings/{c}-v1-win.json","loss_recording":f"research/recordings/{c}-v1-loss.json","thumbnail":f"docs/static/img/games/{c}-v1.png","source_sha256":h},"status":"prototype"}
  (out/f"{c}-v1.json").write_text(json.dumps(meta,indent=2)+"\n");g=getattr(m,c.upper())();a=g.perform_action(ActionInput(id=GameAction.RESET),raw=True).frame[-1];im=Image.new("RGB",(64,64));im.putdata([PAL[int(x)] for row in a for x in row]);im.save(ROOT/"docs"/"static"/"img"/"games"/f"{c}-v1.png",optimize=True);games.append({"game_id":c,"title":title,"axis":axis,"levels":6,"source_sha256":h})
 path=ROOT/"research"/"gpt-batch07-v1.json";path.write_text(json.dumps({"schema_version":1,"batch_id":"gpt-batch07-v1","created_at":"2026-08-30T00:00:00Z","design":"Ten fourth-pass games across the first ten research axes, each with six progressive levels and a distinct colorful environment.","games":games},indent=2)+"\n")
 sheet=Image.new("RGB",(800,352),(242,242,246));d=ImageDraw.Draw(sheet)
 for i,c in enumerate(CFG):im=Image.open(ROOT/"docs"/"static"/"img"/"games"/f"{c}-v1.png").resize((128,128),Image.Resampling.NEAREST);x,y=(i%5)*160+16,(i//5)*176+12;sheet.paste(im,(x,y));d.text((x,y+136),c,fill=(28,28,36))
 sheet.save(ROOT/".cache"/"batch07-contact.png",optimize=True);print("10 metadata records",path)
if __name__=="__main__":main()
