"""Generate metadata, thumbnails, and the contact sheet for research Batch 53."""
import hashlib,importlib.util,json
from PIL import Image,ImageDraw
from arcengine import ActionInput,GameAction
from build_research_batch06_metadata import ROOT,SESSION,PAL
CFG={
"q228":("Escapement Veil","observer-dependent-dynamics","attention-scheduled-hidden-weight-dynamics-with-a-fault-separating-intervention","A white clock tower uses three tall gear wells, occluded weights, and diagnostic rails."),
"q258":("Escapement Pact","social-inference","stable-group-convention-inference-under-a-shared-clockwork-fault","A silver clock court stacks three weighted gears above offer, reply, and choice rails."),
"q288":("Escapement Probe","causal-intervention","budgeted-model-discrimination-before-irreversible-fault-repair","A gray clock laboratory places three gear chambers above evidence and repair bands."),
"q318":("Escapement Ledger","conservation-law-induction","conserved-weight-transfer-through-an-intervention-selected-fault","A charcoal clock ledger exposes three weight stocks, phase bars, and a diagnostic seal."),
"q348":("Escapement Survey","epistemic-resource-allocation","budgeted-evidence-collection-around-mutually-exclusive-fault-probes","A red clock survey arranges three brass lenses above evidence and policy rails."),
"q378":("Escapement Rig","tool-construction","multi-part-instrument-assembly-for-fault-specific-clockwork-diagnosis","A black clock workshop grows colored components inside three brass gear wells."),
"q386":("Palimpsest Delegation","distributed-partial-observability","controller-specific-marks-integrated-through-a-visible-near-miss-example","A magenta archive splits two reader shelves above marks, an erratum, and an integration seal."),
"q416":("Palimpsest Revision","nonstationary-rule-revision","drifting-archive-rule-repaired-from-explicit-failed-examples","A pink archive moves three rewritten tiles across wear, delay, and erratum rails."),
"q446":("Palimpsest Lineage","persistent-identity","ancestry-recovery-through-split-merge-appearance-changes-and-failed-exemplars","An orange archive traces split and merged tile lineages above selection and exemplar bands."),
"q510":("Spore Frame","multi-scale-reference-frames","moving-greenhouse-control-at-progressively-sparse-dual-schedule-confluences","A blue greenhouse aligns two spore colonies against independent phase and frame rails.")}
def load(c):
 p=ROOT/"docs"/"static"/"games"/"src"/f"{c}-v1"/f"{c}.py";s=importlib.util.spec_from_file_location(c,p);m=importlib.util.module_from_spec(s);s.loader.exec_module(m);return p,m
def main():
 games=[];out=ROOT/"research"/"games";out.mkdir(parents=True,exist_ok=True)
 for c,(title,axis,primary,silhouette) in CFG.items():
  p,m=load(c);h=hashlib.sha256(p.read_bytes()).hexdigest();rel=p.relative_to(ROOT).as_posix();names=[x["name"] for x in m.LEVELS];g=getattr(m,c.upper())();frame=g.perform_action(ActionInput(id=GameAction.RESET),raw=True).frame[-1];palette=sorted({int(v) for row in frame for v in row})
  meta={"schema_version":1,"game_id":c,"version":"v1","internal_title":title,"public_title":None,"author_partition":"gpt","authorship":{"model_family":"OpenAI GPT-5","model_snapshot":"current Codex task model; exact deployment id not exposed to task","session_id":SESSION,"created_at":"2026-08-30T00:00:00Z","source_lineage":[f"research/gpt-ideas-v2.tsv:{c}"],"source_commit":None},"mechanics":{"primary":primary,"secondary":[axis,"fault-intervention-and-failed-example-composition"],"novelty_claim":names[-1],"closest_prior_art":["research/coverage-gap-study-v1.md","research/flash-game-mechanics-survey.md"]},"failure_modes":["copies visible colors instead of inferring the latent mechanism","commits before the intervention or failed example separates alternatives","ignores phase, controller, or reference-frame state after it changes"],"interface":{"actions":[1,2,3,4,5,6],"observation":"64x64x16","deterministic":True,"seeded_stochasticity":False},"progression":[{"level":i+1,"role":["orient","discriminate","plan","compose","inhibit","synthesize"][i],"new_demand":n,"composes":list(range(1,i+1))} for i,n in enumerate(names)],"visual_identity":{"dominant_palette":palette,"silhouette_grammar":silhouette,"spatial_grammar":silhouette,"motion_grammar":primary.replace("-"," "),"hud_grammar":"Colored phase, controller, evidence, diagnostic, repair, lineage, and schedule rails expose state without text.","nearest_visual_games":[]},"evaluation":{"allowed_development_models":["deterministic-solvers","random-fuzzer","Qwen3.8 diagnostic only"],"held_out_evaluator":"anthropic","human_baseline_status":"not_started","held_out_status":"sealed"},"artifacts":{"source":rel,"metadata":f"research/games/{c}-v1.json","win_recording":f"research/recordings/{c}-v1-win.json","loss_recording":f"research/recordings/{c}-v1-loss.json","thumbnail":f"docs/static/img/games/{c}-v1.png","source_sha256":h},"status":"prototype"}
  (out/f"{c}-v1.json").write_text(json.dumps(meta,indent=2)+"\n");im=Image.new("RGB",(64,64));im.putdata([PAL[int(v)] for row in frame for v in row]);im.save(ROOT/"docs"/"static"/"img"/"games"/f"{c}-v1.png",optimize=True);games.append({"game_id":c,"title":title,"axis":axis,"levels":6,"source_sha256":h})
 path=ROOT/"research"/"gpt-batch53-v1.json";path.write_text(json.dumps({"schema_version":1,"batch_id":"gpt-batch53-v1","created_at":"2026-08-30T00:00:00Z","design":"Ten games combining fault-separating interventions, visible failed examples, and sparse joint schedules with attention, convention, causality, conservation, evidence allocation, tool building, delegation, revision, identity, and reference-frame reasoning.","games":games},indent=2)+"\n")
 sheet=Image.new("RGB",(800,352),(242,242,246));d=ImageDraw.Draw(sheet)
 for i,c in enumerate(CFG):
  im=Image.open(ROOT/"docs"/"static"/"img"/"games"/f"{c}-v1.png").resize((128,128),Image.Resampling.NEAREST);x,y=(i%5)*160+16,(i//5)*176+12;sheet.paste(im,(x,y));d.text((x,y+136),c,fill=(28,28,36))
 (ROOT/".cache").mkdir(exist_ok=True);sheet.save(ROOT/".cache"/"batch53-contact.png",optimize=True);print("10 metadata records",path)
if __name__=="__main__":main()
