"""Generate metadata, thumbnails, and a contact sheet for research Batch 81."""
import hashlib,importlib.util,json
from PIL import Image,ImageDraw
from arcengine import ActionInput,GameAction
from build_research_batch06_metadata import ROOT,SESSION,PAL
CFG={
"a001":("Dead Bulb Atlas","diagnostic-fault-localization","branching-circuit-faults-are-localized-by-discriminating-junction-pulses-rather-than-nearest-dark-lamps","A pale lamp wall arranges three junctions over six downstream bulbs and a pulse-evidence rail."),
"a002":("Crosstalk Cart","diagnostic-fault-localization","a-shared-control-line-appears-only-during-simultaneous-cart-motion-and-must-be-isolated-before-cargo-transit","A blue rail yard separates two cargo tracks above overlap tests and calibration marks."),
"a003":("False Floor Clinic","diagnostic-fault-localization","weighted-probes-produce-spatial-deformation-fields-that-localize-a-support-rather-than-the-largest-visible-sag","A slate floor clinic arrays nine support tiles above active-probe evidence."),
"a004":("Stuck Gear Census","diagnostic-fault-localization","multiple-input-comparisons-separate-a-jammed-axle-from-directional-backlash-and-passive-nonmovement","A lilac clockwork wall arranges six gear branches above input and backlash traces."),
"a005":("Leaking Loop","diagnostic-fault-localization","two-movable-gauges-and-valve-contrasts-triangulate-a-leak-from-global-conservation-residuals","A green pipe plant wraps a closed fluid loop around gauge and residual records."),
"a006":("One-Sided Hinge","diagnostic-fault-localization","opposed-marble-launches-reveal-a-direction-specific-hinge-fault-that-one-way-testing-cannot-detect","A teal kinetic sculpture presents six hinged petals above directional marble trails."),
"a007":("Phantom Load","diagnostic-fault-localization","a-known-movable-weight-reveals-one-hidden-beam-attachment-through-changes-in-the-coupled-sag-field","A rose load laboratory arrays six platforms above controlled weight trials."),
"a008":("Cascade Autopsy","diagnostic-fault-localization","freeze-per-replay-evidence-separates-an-early-causal-deviation-from-later-visible-alarms","A cream replay theater arranges ten event cells above freeze marks and replay speed."),
"a009":("Patch Cable","repair-and-maintenance-planning","a-temporary-bypass-must-precede-removal-of-a-broken-articulation-edge-to-preserve-live-service","A peach powered network shows two sinks, a broken articulation, bypass, and service bar."),
"a010":("Spare Path","repair-and-maintenance-planning","one-reusable-track-tile-is-moved-only-during-stops-to-schedule-preventive-maintenance-across-three-quotas","A gold depot stacks three degrading machines above spare placement and quota history.")}
def load(c):
 p=ROOT/"docs"/"static"/"games"/"src"/f"{c}-v1"/f"{c}.py";s=importlib.util.spec_from_file_location(c,p);m=importlib.util.module_from_spec(s);s.loader.exec_module(m);return p,m
def main():
 games=[];out=ROOT/"research"/"games";out.mkdir(parents=True,exist_ok=True)
 for c,(title,axis,primary,silhouette) in CFG.items():
  p,m=load(c);h=hashlib.sha256(p.read_bytes()).hexdigest();rel=p.relative_to(ROOT).as_posix();names=[x["name"] for x in m.LEVELS];g=getattr(m,c.upper())();frame=g.perform_action(ActionInput(id=GameAction.RESET),raw=True).frame[-1];palette=sorted({int(v) for row in frame for v in row})
  meta={"schema_version":1,"game_id":c,"version":"v1","internal_title":title,"public_title":None,"author_partition":"gpt","authorship":{"model_family":"OpenAI GPT-5","model_snapshot":"current Codex task model; exact deployment id not exposed to task","session_id":SESSION,"created_at":"2026-08-31T00:00:00Z","source_lineage":[f"research/anthropic-build-ideas-v1.tsv:{c}"],"concept_lineage":"gpt-seeded-anthropic-build","intended_builder":"anthropic","implementation_author_partition":"gpt","source_commit":None},"mechanics":{"primary":primary,"secondary":[axis,"active-diagnosis-and-safe-repair"],"novelty_claim":names[-1],"closest_prior_art":["research/anthropic-build-ideas-v1.audit.json","research/coverage-gap-study-v1.md","research/flash-game-mechanics-survey.md"]},"failure_modes":["repairs the nearest visible symptom instead of localizing the latent fault from contrasting interventions","uses a single passive observation where direction, overlap, load, valve, replay, bypass, or schedule comparisons are required","performs the correct repair in an unsafe order that loses service continuity or reusable capacity"],"interface":{"actions":[1,2,3,4,5,6],"observation":"64x64x16","deterministic":True,"seeded_stochasticity":False},"progression":[{"level":i+1,"role":["orient","discriminate","plan","compose","inhibit","synthesize"][i],"new_demand":n,"composes":list(range(1,i+1))} for i,n in enumerate(names)],"visual_identity":{"dominant_palette":palette,"silhouette_grammar":silhouette,"spatial_grammar":silhouette,"motion_grammar":primary.replace("-"," "),"hud_grammar":"Lamp pulses, rail overlaps, deformation fields, backlash traces, gauge residuals, marble directions, load coupling, replay freezes, bypass service, and spare schedules expose causal evidence without text.","nearest_visual_games":[]},"evaluation":{"allowed_development_models":["deterministic-solvers","random-fuzzer","Qwen3.8 diagnostic only"],"held_out_evaluator":"anthropic","human_baseline_status":"not_started","held_out_status":"sealed"},"artifacts":{"source":rel,"metadata":f"research/games/{c}-v1.json","win_recording":f"research/recordings/{c}-v1-win.json","loss_recording":f"research/recordings/{c}-v1-loss.json","thumbnail":f"docs/static/img/games/{c}-v1.png","source_sha256":h},"status":"prototype"}
  (out/f"{c}-v1.json").write_text(json.dumps(meta,indent=2)+"\n");im=Image.new("RGB",(64,64));im.putdata([PAL[int(v)] for row in frame for v in row]);im.save(ROOT/"docs"/"static"/"img"/"games"/f"{c}-v1.png",optimize=True);games.append({"game_id":c,"title":title,"axis":axis,"levels":6,"source_sha256":h})
 path=ROOT/"research"/"gpt-batch81-v1.json";path.write_text(json.dumps({"schema_version":1,"batch_id":"gpt-batch81-v1","created_at":"2026-08-31T00:00:00Z","provenance":"Concepts retain gpt-seeded-anthropic-build queue lineage; implementations in this batch are authored by OpenAI GPT-5 and are not attributed to Anthropic.","design":"Ten colorful systems emphasize active fault localization, direction and interaction tests, causal event order, service-preserving repair, and preventive maintenance scheduling.","games":games},indent=2)+"\n")
 sheet=Image.new("RGB",(800,352),(242,242,246));d=ImageDraw.Draw(sheet)
 for i,c in enumerate(CFG):
  im=Image.open(ROOT/"docs"/"static"/"img"/"games"/f"{c}-v1.png").resize((128,128),Image.Resampling.NEAREST);x,y=(i%5)*160+16,(i//5)*176+12;sheet.paste(im,(x,y));d.text((x,y+136),c,fill=(28,28,36))
 (ROOT/".cache").mkdir(exist_ok=True);sheet.save(ROOT/".cache"/"batch81-contact.png",optimize=True);print("10 metadata records",path)
if __name__=="__main__":main()
